### ISSUE TITLE
CKEditor removes an inline image when removing the text after it in the same paragraph

### ISSUE THREAD

**Issue by MarcelSalla** [ckeditor/ckeditor4#1006]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Open http://ckeditor.com/ and scroll to "Article Editor" example
2. Open the image properties with double click and make the image "non-captioned" and "not aligned".
3. Write some text before and after the inline image.
4. Remove all the text written after the inline image using the backspace key.

### Expected result

The image should still be there.

### Actual result

The image is removed when you delete the last character of the text after the image.

## Other details

* Browser: MS Edge
* OS: Windows 10 x64
* Installed CKEditor plugins: image2

**Comment by msamsel** [comment]
I was able to reproduce the issue on Edge 15 an Edge 16.

**Comment by beatadelura** [comment]
This bug is not reproducible on older version Edge 14.

**Comment by MarcelSalla** [comment]
When you remove the text after the image you should remove it using the backspace key, if you select the text and the use delete the image is not removed.

**Comment by Dumluregn** [comment]
This issue is no longer reproducible in the latest Edge browser version.
