### ISSUE TITLE
CKEditor loses the text when you drag and drop a text selection after an image

### ISSUE THREAD

**Issue by MarcelSalla** [ckeditor/ckeditor4#1007]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Open http://ckeditor.com/ and scroll to "Article Editor" example
2. Open the image properties and make the image "non-captioned" and "not aligned"
3. Select some text inside CkEditor and drag the text selection after the image.

### Expected result

The text is dragged after the image

### Actual result

The text is lost

## Other details

* Browser: MS Edge
* OS: Windows 10 x64
* Installed CKEditor plugins: image2

**Comment by lateklmast** [comment]
The problem in MS Edge is more general: if I select e. g. a word in editor on https://ckeditor.com/ckeditor-4/ and try to move it with mouse, it disappears when dropped.

**Comment by sorabht** [comment]
I'm facing this issue on IE and Chrome as well. Any update on this issue?

**Comment by mlewand** [comment]
@lateklmast issue that you're referring to is more generic, and we're tracking it in #1832. Unfortunately there were multiple bugs introduced in MS Edge recently related to DnD

**Comment by sorabht** [comment]
Thanks @lateklmast for quick update.

**Comment by Dumluregn** [comment]
This issue is no longer reproducible in the latest Edge browser version.
