### ISSUE TITLE
Selection is incorrect after deleting empty table rows

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor4#1161]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Insert empty 2x2 table.
2. Select the first row and press <kbd>Delete</kbd>.
3. Repeat step 2 for the last row.
4. Type something.

### Expected result

Text should appear next to the caret.

### Actual result

The caret moves downwards, but text appears above.

### GIF
![bug_cke4](https://user-images.githubusercontent.com/20988892/32783217-41f69bce-c94b-11e7-927e-d45b9de2d775.gif)

## Other details

* Browser: Edge 16
* OS: Windows 10
* CKEditor version: 4.7.3
* Installed CKEditor plugins: `full-all`

This bug is reproducible only in `Edge 16`.

**Comment by msamsel** [comment]
I just add label `status:confirmed` to easily filter out this issue.

**Comment by Dumluregn** [comment]
This issue is no longer reproducible in the latest Edge browser version.
