### ISSUE TITLE
Undoing the widget paste scrolls the editor to the beginning

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor4#1163]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Go to http://localhost:1030/tests/plugins/clipboard/manual/draganddrop
2. Select first widget from the first editor.
3. Copy it.
4. Scroll down.
5. Paste the widget.
6. Undo.

### Expected result

Scroll position remains unchanged.

### Actual result

Editor scrolls to the beginning.

### GIF
![bug_cke4](https://user-images.githubusercontent.com/20988892/32785035-bf1baf0e-c950-11e7-815a-ebe3763e7aaa.gif)

## Other details

* Browser: Edge 15, Edge 16
* OS: Windows 10
* CKEditor version: 4.7.3
* Installed CKEditor plugins: full-all

**Comment by f1ames** [comment]
@Mgsy if you will have a minute, could you check if it was fixed by #1170 (should work on 4.8.0 and latest `major`)?

**Comment by f1ames** [comment]
Related to #1160.

**Comment by Mgsy** [comment]
> @Mgsy if you will have a minute, could you check if it was fixed by #1170 (should work on 4.8.0 and latest major)?

Unfortunately, this bug still occurs in 4.8.0. It scrolls to the beginning of the document, but selection is correct.

**Comment by msamsel** [comment]
I just add label `status:confirmed` to easily filter out this issue.

**Comment by Dumluregn** [comment]
This issue is no longer reproducible in the latest Edge browser version.
