### ISSUE TITLE
Exception thrown after dropping table in an empty area in Edge

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor4#1189]
## Are you reporting a feature request or a bug?

Bug

 ## Provide detailed reproduction steps (if any)

1. Go to http://tests.ckeditor.test:1030/tests/plugins/clipboard/manual/draganddrop.
2. Remove whole content from the first editor.
3. Create new 2x2 table.
4. Fill the first row with some characters.
5. Select whole table starting from the last cell (it's important).
6. Drag it and drop at the end of the editor (you should drop it on the blank space).

 ### Expected result

No exception is thrown.

 ### Actual result

Exception is thrown: `Unable to get property scrollIntoView of undefined or null reference`.

 ## Other details

Note it happens only on major, I could not reproduce it with 4.7.3.

* Browser: Edge 16
* OS: Windows 10
* CKEditor version: CKE 4.8.0 (major)

**Comment by mlewand** [comment]
Note, it's not about `tableselection` plugin, as this manual test has table selection plugin disabled.

**Comment by Dumluregn** [comment]
This issue is no longer reproducible in the latest Edge browser version.
