### ISSUE TITLE
Exception after pasting the empty widget

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor4#1300]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Go to http://localhost:1030/tests/plugins/clipboard/manual/datatransferfallback#child.
2. Start the selection in the first paragraph and move it to the widget (image and caption should be selected).
3. Type some character, i.e. a.
4. Drag & drop the widget.

### Expected result

Only caption should be removed after step 3 and the widget shouldn't be empty. There should be no error in the console.

### Actual result

Widget becomes empty after step 3. There is the exception after step 4.

## Other details

**Error**
```
SCRIPT5007: Unable to get property 'getAttribute' of undefined or null reference
```

It occurs also in CKEditor 4.7.3

* Browser: Edge
* OS: Windows 10
* CKEditor version: 4.8.0

**Comment by Dumluregn** [comment]
This issue is no longer reproducible in the latest Edge browser version.
