### ISSUE TITLE
docprops plugin does not read meta information 

### ISSUE THREAD

**Issue by Offerel** [ckeditor/ckeditor4#1442]
If the html code contains meta-tags like keywords: `<meta name="keywords" content="Google, Bing, Search, Maps, Internet, Windows" />` the docprops plugin seems to ignore this data. If i open docprops for such a html code, the fields are empty.

However, when i enter new values in to the keyword field in docprops and save the html, the new meta tag is written correctly.

I'm not sure, if keywords is the only field where this issue occurs, since i need only this field. At least the title tag is saved and read correctly.

Tested browser is Firefox 57.x

_Additional notes:_
Reproduction steps:
1. Open: https://cdn.ckeditor.com/4.8.0/full-all/samples/old/docprops/docprops.html
2. Add in docprops in "Meta tags" -> "keywords" some keyword: e.g. `Google, Bing, Search, Maps, Internet, Windows`
3. Close dialog
4. Re-open docprops. ( Meta tags are still in document )
5. Get data from editor: `CKEDITOR.instances.editor1.getData()` ( Meta tags are still in document )
6. Change to `Sourcemode` and back to `wysiwygarea`
7. Open docprops. ( **Meta tags are missing** )
8. Get data from editor ( Meta tags are in output data )

**Comment by msamsel** [comment]
I was able to confirm the issue. I also add better description with reproduction steps to issue description.
