### ISSUE TITLE
Pasting easy image widget at the beginning of the content breaks it

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor4#1537]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Open CKEditor instance with Easy Image, e.g. our [Easy Image feature preview](https://ckeditor4-preview.ckeditor.com/t/932-2961/plugins/easyimage/samples/easyimage.html).
2. Focus the editor.
1. Just cut and paste easy image widget (full height) to the beginning of content

### Expected result

Image is not being stripped.

### Actual result

Only caption is preserved, image is removed.

![image](https://user-images.githubusercontent.com/5353898/35616108-877b80c2-0674-11e8-9089-c01e3bd71aeb.png)

## Other details

* Browser: Edge 16
* OS: Win 10

**Comment by Comandeer** [comment]
It seems that in Edge 41.16299.15.0 it does not matter where the widget is pasted – it's always destroyed.

**Comment by Dumluregn** [comment]
This issue is no longer reproducible in the latest Edge browser version.
