### ISSUE TITLE
Easy Image button state after applying the style is not refreshed on IE/Edge in inline editors

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor4#1580]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Open <http://tests.ckeditor.test:1030/tests/plugins/easyimage/manual/balloontoolbar/balloontoolbar> manual test.
2. Use the "Divarea editor".
3. Focus the image.
1. Change type to a "Full Size Image".

### Expected result

"Full Size Image" button in the Balloon Toolbar gets activated, formerly selected side image button is no longer active.

### Actual result

Side image button remains active, full size image is not marked as active.

Widget itself is transformed as expected though.

## Other details

Same thing happens for the "Inline editor". It's not reproducible with "Classic editor" though.

It does look as if our [`forceSelectionCheck` trick](https://github.com/ckeditor/ckeditor-dev/blob/a458f76801f2644497b8aa8e3890281a6deaefa1/plugins/easyimage/plugin.js#L46-L47) was not working.

* Browser: Edge, IE11
* OS: Windows 10
* CKEditor version: 4.8.0

**Comment by Comandeer** [comment]
On Edge is also not possible to click on non-refreshed button:

1. Open http://tests.ckeditor.dev:1030/tests/plugins/easyimage/manual/balloontoolbar/balloontoolbar
2. Click on Easy Image widget.
3. Click "Full Size Image" button.
4. Click "Side Image".

**Expected:**

Widget is back to side image.

**Unexpected:**

Widget is still full size.

It works only after blurring and refocusing widget.

**Comment by Comandeer** [comment]
Additionally, it's not possible to apply styles from different styles groups.

1. Open http://tests.ckeditor.dev:1030/tests/plugins/easyimage/manual/customgroups
2. Click on Easy Image widget.
3. Try to apply "Side Image" style and one of the border styles.

**Expected:**

Both styles are applied.

**Unexpected:**

Only first style is applied.

**Comment by Dumluregn** [comment]
This issue is no longer reproducible in the latest Edge browser version.
