### ISSUE TITLE
Image changes its size after pasting it to the editor

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor4#1603]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Open the Easy Image sample.
2. Focus the first image (CKEditor 4 logo) and transform it into the `side image`.
3. Focus the second image.
4. Cut it.
5. Paste it at the end of the first paragraph.

### Expected result

Image is pasted with normal size.

### Actual result

Image inside the widget changes its size.

## Other details

**GIF**

![bug_cke4](https://user-images.githubusercontent.com/20988892/35922072-dd61a82e-0c1c-11e8-874c-a9fa388b0151.gif)

* Browser: Edge 16
* OS: Windows 10

**Comment by jacekbogdanski** [comment]
I spend some time on this issue and it looks like a `cut` event is not called for an image if you change it's position by balloon toolbar (it's fine with context menu). In the result an image isn't cached by clipboard and native selection is used with all styles junk.

**Comment by Dumluregn** [comment]
This issue is no longer reproducible in the latest Edge browser version.
