### ISSUE TITLE
Test plugins/magicline/magicline fails on some screen resolutions

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor4#1636]
## Are you reporting a feature request or a bug?

Failing test

## Provide detailed reproduction steps (if any)

This issue happens on Firefox only.

Test http://tests.ckeditor.test:1030/tests/plugins/magicline/magicline#tests%2Fplugins%2Fmagicline%2Fmagicline%20get%20size fails for me on the following setups:

* 3840x2160 (2.5 pixel density ratio)
* 2560x2336 (1.0 pixel density ratio) - weird resolution, as it is from a vbox guest on a 2560x1440 screen

It produces errors like that:

```
tests/plugins/magicline/magicline get size

Values should be equal.
Expected: 9 (number)
Actual:   8 (number)
```

**Comment by jacekbogdanski** [comment]
Also fails on Android 9 (Chrome).

**Comment by jacekbogdanski** [comment]
Closing as it's not reproducible recently.
