### ISSUE TITLE
Failing test: /tests/plugins/widget/manual/outline#child

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor4#1641]
## Are you reporting a feature request or a bug?

Bug: failing test

## Provide detailed reproduction steps (if any)

1. `/tests/plugins/widget/manual/outline#child` - **inline editor** inside this test case doesn't embed widget properly. Widgets in other iniline editors (e.g. http://10.0.2.2:10490/tests/plugins/widget/manual/block ) are working fine. Problem is possible to reproduce on dev version.
![screen shot 2018-02-09 at 17 00 33](https://user-images.githubusercontent.com/9017322/36036697-cf1f2d46-0dba-11e8-9204-316b27c5db52.png)

### Expected result

test suit will have properly upcast widget inside inline editor

### Actual result

Widget inside inline editor is not appear. Error is thrown in console.

## Other details

* Browser: IE8
* OS: Win7
* CKEditor version: 4.9.0
* Installed CKEditor plugins: full-all

**Comment by jacekbogdanski** [comment]
Closed via #1820
