### ISSUE TITLE
Fake selection error when trying to delete widget in read-only mode

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor4#1651]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Open http://tests.ckeditor.test:1030/tests/core/selection/manual/readonly
2. Open console.
3. Follow test instructions and use `Delete` key in the last step.

### Expected result

There is no error in the console.

### Actual result

There is warning in the console:
> [CKEDITOR] Error code: selection-fake-reset.

Additionally, selection is lost.

## Other details

* Browser: Edge 16
* CKEditor version: 4.9.0

May be connected with #1575.

**Comment by Comandeer** [comment]
The same happens after pressing <kbd>Ctrl</kbd>.

**Comment by Dumluregn** [comment]
This issue is no longer reproducible in the latest Edge browser version.
