### ISSUE TITLE
Balloontolbar in divarea doesn't react on scrollbar movement

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor4#1653]
## Are you reporting a feature request or a bug?

bug

## Provide detailed reproduction steps (if any)

1. Open test: `/tests/plugins/easyimage/manual/customstyleicons`
2. Click into image to show balloontoolbar
3. Move scrollbar of editable in divarea editor
![screen shot 2018-02-12 at 14 28 55](https://user-images.githubusercontent.com/9017322/36099113-c9812580-1001-11e8-8369-2789fed1f239.png)

### Expected result

ballontoolabr should be repositioned simmilar to classic editor

### Actual result

ballontolbar is not moved

## Other details

* Browser: Safari, Chrome
* OS: MacOS
* CKEditor version: 4.9.0
* Installed CKEditor plugins: full-all

**Comment by jacekbogdanski** [comment]
Closed via #3562
