### ISSUE TITLE
Preserving custom colors feature

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor4#1795]
## Are you reporting a feature request or a bug?

Feature request

## Provide detailed reproduction steps (if any)

1. Open [Sample](https://sdk.ckeditor.com/samples/colorbutton.html).
1. Click `Text Color` button.
1. When dialog show up click  `More colors`.
1. Select custom color and click `Ok`. 
1. Click `Text Color` button again.

### Expected result

New color should be added to color palette inside `colorbutton` dialog.

![screen shot 2018-03-14 at 12 20 54](https://user-images.githubusercontent.com/10279586/37399558-428d2ce8-2782-11e8-9ca9-f7781d70e73d.png)

### Actual result

User is not able to get back to previous selected color from `colorbutton` dialog.

![screen shot 2018-03-14 at 12 22 15](https://user-images.githubusercontent.com/10279586/37399605-61944b94-2782-11e8-8634-13def26b2b9c.png)

## Other details

We had some brain storm with @mlewand how to implement this feature and we find out with some idea:

1. Scan editor content for elements containing color information on dialog open. It could be defined be default as `span[color]` or configured by user e.g. [colorButton_backStyle](https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_config.html#cfg-colorButton_backStyle), [colorButton_foreStyle](https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_config.html#cfg-colorButton_foreStyle). We should find out the most performant way to scan editor content by keeping CSS selectors precise.
1. Filter out default colors. We don't want to duplicate already  #defined default colors.
1. Sort colors by occurrence so we will be able to choose the most frequent ones.
1. Limit custom colors to some value, 12 should be fine (two rows). With this limitation we will keep dialog relatively small so it won't grow too big if a user used many different colors inside editor.
1. Append custom colors to dialog. A user will be able to reapply previously selected color without the need to memorise or use [Copy Formatting](https://sdk.ckeditor.com/samples/copyformatting.html) feature.

**Comment by Dumluregn** [comment]
Some further specs:
1. Custom colors will be displayed between default palette and `More colors` button to avoid confusion (some padding should help in it too).
1. Text and background colors should be handled separately.
1. We want to track both colors used in document and those picked from `colordialog`. The latter have priority: they should be displayed first. After them if we didn't reach the limit (which will probably be set to 2 full rows) we also display colors from the document.
1. Document colors should be updated on each panel show. This way we are able to catch custom colors in content pasted from Word etc.
1. Colors from `colordialog` should be ordered from the most recently picked. Colors found in content should be ordered by number of occurrences, counted in `<span>` elements.
1. For now we don't include config options to change the way of searching for colors in document.
1. Feature should work both with and without `colordialog`. In the second version it should just collect colors from document.
1. If color was added to custom palette, it shouldn't disappear even if it is no longer used. The only case we stop displaying it is if we have too many colors that are have higher priority (according to sorting rules described above).

**Comment by Dumluregn** [comment]
As the feature for finding colors in the editor contents is basically a separate feature, I created a separate issue for it.
