### ISSUE TITLE
Drop in Egde doesn't work everytime

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor4#1832]
## Are you reporting a feature request or a bug?
Bug

## Provide detailed reproduction steps (if any)

1. Go to https://sdk.ckeditor.com/samples/draganddrop.html
2. Clear editor contents and make the editing space bigger by pressing enter few times
3. Start Dragging & Dropping contact into editor content area (Please see the attached gif if you have any doubts)

### Expected result

Contact should always be dropped just like it is happening in Firefox, Chrome or even IE11.

### Actual result

At certain point dropping stops and you need to either drop the same contact at least 5 times or hold it for a few seconds to pin point the exact location where contact can be dropped.

## Other details

Contact gets copied to `dataTransfer` object while dragging starts and the HTML contains necessary information before dropping. Only the drop doesn't occur. 

I have also checked classic editor and native `contenteditable`.  Classic editor worked the same while native element allowed only for D&D of images from contacts but it has worked every time.

* Browser: Edge
* OS: Win10
* CKEditor version: 4.9.0
* Installed CKEditor plugins: widget

![drag_drop_feature_inedge](https://user-images.githubusercontent.com/5314687/37763930-b645fb94-2dc0-11e8-8979-27b73121e14b.gif)

**Comment by mlewand** [comment]
I feel that it might have something to do with dynamically created editor. You can see that UI is blinking, and something weird is going on under the surface - so there's a chance it's a race condition.

**Comment by Dumluregn** [comment]
This issue is no longer reproducible in the latest Edge browser version.
