### ISSUE TITLE
Typing after autolink in Edge

### ISSUE THREAD

**Issue by StuartSilvester** [ckeditor/ckeditor4#1873]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Go to https://ckeditor.com/ckeditor-4/#document (the autoembed plugin in the article example works around this)
2. Paste an URL from your clipboard
3. Type some text

### Expected result

The text typed after pasting the URL should not be in the anchor

### Actual result

The actual result is that the text typed after pasting the link is included in the anchor and it's difficult to break out of it. I can reproduce this on multiple systems.

https://www.screencast.com/t/bHUkhY4U (sorry that it's flash based!)

## Other details

* Browser: Edge 42.17133.1.0
* OS: Windows 10 1803
* CKEditor version: CKE Demo
* Installed CKEditor plugins: See CKE Demo

**Comment by engineering-this** [comment]
I have reproduced this on Edge. After pasting link collapsed selection stays inside `<a>` tag, while on Chrome selection is outside. All browsers should have same behaviour.

However about:
>... it's difficult to break out of it. 

I could do it just by pressing `right arrow` key.

**Comment by stoo2000** [comment]
> I could do it just by pressing right arrow key.
Yes, you're right although that isn't totally ideal, the cursor moves into the next paragraph.

This issue also appears to be reproduceable in FireFox 59.0.2

**Comment by Dumluregn** [comment]
This issue is no longer reproducible in the latest Edge browser version.
