### ISSUE TITLE
editor.resize() doesn't work with CSS units

### ISSUE THREAD

**Issue by engineering-this** [ckeditor/ckeditor4#1883]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Open sample CKEditor.
2. Open console, and type `CKEDITOR.instances[ 'your-instance-name' ].resize( '500em', '500em' )`

### Expected result

Editor is resized.

### Actual result

Nothing happens

## Other details

According to [docs](https://docs.ckeditor.com/ckeditor4/latest/api/CKEDITOR_editor.html#method-resize) you should be able to pass
> a CSS size value with unit as an argument.

Note: None of other CSS are working.

* Browser: Any
* OS: Any
* CKEditor version: 4.9.2
* Installed CKEditor plugins: resize

**Comment by jacekbogdanski** [comment]
@ashrafsabrym we fixed the issue but note that this method is supposed to only work with absolute CSS units. Docs have been also updated as they could give incorrect information about this feature.

Closed in #4010
