### ISSUE TITLE
range.getClientRects doesn't work correctly on IE9-IE10 with collapsed selection at the end of line

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor4#1925]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Open CKEditor sample.
1. Open console.
1. Put cursor inside editor at the end of line e.g. `Hello world!^`
1. Type inside console: 
```javascript
var editor = CKEDITOR.instances.editor;
var range = editor.getSelection().getRanges()[ 0 ];
console.log( range.getClientRects()[ 0 ] );
```

### Expected result

Single DOMRect object.

### Actual result

For IE10 it gives empty array.
For IE9 it gives DOMRect with invalid position.

The issue is probably related to #1895.

## Other details

It works fine if you put selection inside or at the beginning of an element. 

* Browser: IE9, IE10
* OS: Windows
* CKEditor version: 4.10.0
* Installed CKEditor plugins: any

**Comment by mlewand** [comment]
@engineering-this could you check whether this is an upstream issue? Even if it is, could we try to apply our `span` injection workaround to mitigate this case? (in which case this issue would be a feature request)
