### ISSUE TITLE
Cannot remove <video> tag

### ISSUE THREAD

**Issue by tberne** [ckeditor/ckeditor4#1937]
## Are you reporting a feature request or a bug?
Bug

## Provide detailed reproduction steps (if any)
1. Change sample JS of `4.9.2` standard distribution to add `CKEDITOR.config.allowedContent = true;` in `samples/js/sample.js`.
2. Open `samples/index.html`.
3. Go to code view, remove all current content and paste the following code:

`<p><video controls="controls" src="https://www.sample-videos.com/video/mp4/240/big_buck_bunny_240p_1mb.mp4">&nbsp;</video></p>`

4. Go to wysiwyg.
5. Try to delete the video.

### Expected result
The video could be removed.

### Actual result
The video can't be removed.

* Browser: Chrome / FF (in IE and Edge it seems to be working)
* OS: Windows 10
* CKEditor version: I first saw the problem in `4.5.7`, but I could reproduce in `4.9.2`.
* Installed CKEditor plugins: none

**Comment by engineering-this** [comment]
CKEditor isn't handling `<video>` tag in any special way, and as you can see you can't even put it inside editor without setting `allowedContent = true`.
I can reproduce it in textarea without CKEditor and it behaves in same way.

As this is default behaviour this issue is feature request.

**Comment by mypetertw** [comment]
After added `allowedContent = true` still can't remove <video> tag.
