### ISSUE TITLE
When D&D in new Edge42, dropped content dissapears.

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor4#1943]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Open editor sample like replacebycode.html
2. Select link text or image or some portion of plain text and try to drag and drop it to some other place in text.
Edit: **Same thing will happen when you select plain text, image etc. and try to D&D it.**

### Expected result

The link or other selected content should be moved from one place to another just like in case of native `contenteditable` element.

### Actual result

The dropped link or other selected content disappears.

## Other details

* Browser: Edge 42
* OS: Win10
* CKEditor version: 4.8.0+ (in works fine in older versions, just like in native `contenteditable`)
* Installed CKEditor plugins: N/A

Please see attached images:

**Native Contenteditable:**
![contenteditable-drag](https://user-images.githubusercontent.com/5314687/39530155-a98c93da-4e28-11e8-9bed-11cda7a41396.png)
![contenteditable-drop](https://user-images.githubusercontent.com/5314687/39530157-abe944de-4e28-11e8-8f0e-10b12b49ffb9.png)

**CKEditor:**
![ckeditor-drag](https://user-images.githubusercontent.com/5314687/39530190-b9910fae-4e28-11e8-9d58-1e050aafa16b.png)
![ckeditor-drop](https://user-images.githubusercontent.com/5314687/39530192-bb80fc70-4e28-11e8-9f9f-21cf3223de60.png)

**Comment by mlewand** [comment]
I can't reproduce it with Edge 41. It's interesting that it is reproducible since CKE 4.8.0 🤔

**Comment by jswiderski** [comment]
Please also note that drag and dropping text between two editor results in droped content not being dropped into target editor. This problem can also be reproduced from CKEditor 4.8.0 in MS Edge 42.

**Comment by engineering-this** [comment]
Related to: https://github.com/ckeditor/ckeditor-dev/pull/1850#pullrequestreview-119836678
But I guess it should be in separate ticket.

**Comment by engineering-this** [comment]
After testing on Edge 42 it looks like this problem is not existing on branch `t/1832` from PR #1850. However there is another problem with Edge dnd, when widgets dragged into the editor are changed into plain text.

**Comment by mlewand** [comment]
Let's target this into minor for the time being. However there's a good chance it's going to be a significant change in the clipboard API. In this case it will require us to move the fix to next major release, as it will need to get solid manual testing before releasing.

**Comment by mlewand** [comment]
I still have a feeling that this is an upstream issue. @engineering-this once you're back please, confirm that this is not an upstream issue.

**Comment by Dumluregn** [comment]
This issue is no longer reproducible in the latest Edge browser version.
