### ISSUE TITLE
TableResize plugin stops working in Maximized mode when used with Divarea plugin

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor4#1959]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Open this online same - https://codepen.io/j_swiderski/pen/XqVRxG
2. Try maximizing the editor and then resizing the table column

### Expected result

It should be possible to resize table columns.

### Actual result

Resizing table columns won't work.

## Other details

* Browser: any
* OS: Any
* CKEditor version: 4.0+
* Installed CKEditor plugins: tableresize,maximize,divarea.

**Comment by f1ames** [comment]
Fixed in e3be5c1.
