### ISSUE TITLE
Invalid display name for links with mailto href

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor4#2027]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open CKEditor sample with `link` plugin.
1. Add a link with display name `@foo` and href `foo@example.com`.
1. Click on the added link to open dialog.
1. Close dialog by clicking `ok` button.

![linkmail](https://user-images.githubusercontent.com/10279586/40655583-0c43ee8c-6342-11e8-8039-3316253e11c5.gif)

### Expected result

Link shouldn't change its display name.

### Actual result

Link has href as a display name.

## Other details

* Browser: Any
* OS: Any
* CKEditor version: 4.9.2
* Installed CKEditor plugins: link

**Comment by f1ames** [comment]
Fixed in https://github.com/ckeditor/ckeditor4/commit/d4617d14bb0960fdb6a3476730e6ab31cd23f5de.
