### ISSUE TITLE
Low contrast in default High Contrast Mode theme

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor4#2073]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Switch on High Contrast Mode in Windows.
2. Open https://sdk.ckeditor.com/samples/classic.html
3. Look at editor's toolbar.

### Expected result

There is at least 4.5:1 contrast radio for buttons and other elements of toolbars.

### Actual result

Buttons are nearly invisible:

<img width="1060" alt="screen shot 2018-06-11 at 13 36 14" src="https://user-images.githubusercontent.com/1078728/41233643-583b5a4e-6d8a-11e8-9e16-787a696f71fe.png">

The same issue is visible for links in the editor's content.

## Other details

* Browser: Firefox
* OS: Windows 10
* CKEditor version: 4.9.2
* Installed CKEditor plugins: standard preset

It could be an unsolvable upstream issue, as Firefox styles all the links in HCM the same way and it's possible that it restricts the styling.

**Comment by engineering-this** [comment]
The problem with Firefox in HCM is that it uses all system colours except for `hyperlink`. Switching to various HCM presets changes all the colours except for link. Only solution I could find so far is to change link colour in Firefox settings.

For IE and Edge it is possible to change styling in HCM via
```@media screen and (-ms-high-contrast: active)```
But it wont work in FF.

Issue in bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=697836

**Comment by f1ames** [comment]
The upstream issue is fixed so we should verify if this issue is fixed too.

**Comment by KarolDawidziuk** [comment]
Problem has been fixed and is no longer occurred since version 70.x.
