### ISSUE TITLE
Can't type with styling at the beginning of a block after activating style while autocomplete dropdown is visible

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor4#2150]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open a sample with the emoji/mentions plugin, i.e. `tests/plugins/emoji/manual/emoji`.
1. Create new paragraph.
1. Type `:bu`.
1. Press <kbd>Ctrl</kbd> + <kbd>B</kbd>.
1. Press <kbd>Backspace</kbd> three times.
1. Pres <kbd>Ctrl</kbd> + <kbd>B</kbd>.
1. Type something. 

### Expected result

The text is bolded.

### Actual result

The text isn't bolded.

## Other details
**GIF**

![bug_cke4](https://user-images.githubusercontent.com/20988892/41838565-080cff46-7861-11e8-87ba-4d041654de9f.gif)

* Browser: Edge
* OS: Windows 10
* CKEditor version: 4.10.0

**Comment by Dumluregn** [comment]
This issue is no longer reproducible in the latest Edge browser version.
