### ISSUE TITLE
Use "https" as default protocol for links

### ISSUE THREAD

**Issue by seeallie** [ckeditor/ckeditor4#2227]
## Type of report

Feature request

## Provide description of the new feature

Change the default protocol for links to "https" from "http".  https://github.com/ckeditor/ckeditor-dev/blob/master/plugins/link/dialogs/link.js line 268

**Comment by mlewand** [comment]
@Comandeer @seeallie Firstly I can see it as an opt-in feature rather than rolling out `https` as a default protocol. That way the editor does not break installations that use plain http, yet is a config switch allowing to conveniently define the default protocol.

**Comment by mlewand** [comment]
Somewhat related issue; #2277.

**Comment by seeallie** [comment]
My organization recently went through a process of replacing http with https in our web system ( includes several web platforms) whenever possible. If this is a current web best practice, it would make sense for this library to set it as the default protocol while allowing other options. In addition, as @wwalc pointed out, technically it involves "a few lines of code".

**Comment by mlewand** [comment]
@seeallie the works on the proposal continue, and we have a preview, where one of examples I used is `https` protocol for the dialog. If you'd like to share the feedback, please check the "Preview available" section in #2277. Thanks!

**Comment by seeallie** [comment]
@mlewand I tested out the "https" behavior in the codepen for preview: it worked as expected & thanks!

**Comment by mlewand** [comment]
@seeallie note that it's still a subject of discussion, we faced [some challenges during the implementations](https://github.com/ckeditor/ckeditor-dev/issues/2277#issuecomment-422031074) that we need to solve before merging this feature. So make sure to keep an eye on that.

**Comment by mohitnegi724** [comment]
Hi,
Can I Add more protocols in CK Editors. I want to add "mailto:" and "tel:" in Protocol Dropdown. Is it Possible to do that?
I am using React.js.

**Comment by f1ames** [comment]
@mohitnegi724 it's not possible at the moment, as [documentation](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-linkDefaultProtocol) says:

> Default URL protocol used for the Link dialog.
>
> Available values are:
> 
> 'http://'
> 'https://'
> 'ftp://'
> 'news://'
> '' — An empty string for the <other> option.

You may report a separate feature request issue for this one.

**Comment by kiknadze** [comment]
I set link default values this way:
```
CKEDITOR.on('dialogDefinition', (ev) => {
        if (ev.data.name == 'link') {
          ev.data.definition.getContents('target').get('linkTargetType')['default']='_blank';
          ev.data.definition.getContents('info').get('protocol')['default']='https://';
        }
      });
```
