### ISSUE TITLE
[Edge] Pasting text reflects lazily on certain condition

### ISSUE THREAD

**Issue by jamadam** [ckeditor/ckeditor4#2245]
## Type of report

Text pasting is reflected lazily on certain condition.

## Provide detailed reproduction steps (if any)

1. Open https://ckeditor.com/ckeditor-4/#document or https://cdn.ckeditor.com/4.10.0/full-all/samples/
2. Empty wysiwyg area.
3. Type FOO
4. Select FOO with keyboard by holding shift and hitting left key 3 times.
5. Hit ctrl+c, hit ctrl+v, hit ctrl+v.

### Expected result

FOOFOO is left.

### Actual result

Only FOO is left. After random operation, second FOO is lazily appears.

## Other details

* Browser: Microsoft Edge 42.17134.1.0 (distributed from ModernIE)
* OS: Windows 10 Enterprize evalutation 1803 (build 17134.48)
* CKEditor version: 4.8.0+
* Installed CKEditor plugins: This reproduces on demo site but seems full distribution

**Comment by msamsel** [comment]
I've update a little bit your description.
It appears that bug exists since 4.8.0 in 4.7.3 I cannot observe such behaviour (https://cdn.ckeditor.com/4.7.3/full-all/samples/).

**Comment by Dumluregn** [comment]
This issue is no longer reproducible in the latest Edge browser version.
