### ISSUE TITLE
Links are pasted with selection inside them and it is not possible to leave a link using space key 

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor4#2321]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open any sample with CKEditor, clear its contents and paste this link - https://ckeditor.com/ckeditor-5.
2. The cursor is blinking next to the link and as you can see based on element's path it is inside it. At this point is obvious that if you start typing, text will get linked so try pressing the space key to leave it and start typing.

### Expected result

The link should be pasted with selection outside of it. Since the visual cursor at the end of the link, it is natural for user to try pressing the `Space` to enter regular text after the link. If selection inside the link is an ok result, then pressing space should allow leaving its boundaries.

### Actual result

Selection is inside a link and it is not possible to leave it using Space key. 

*What is the actual result of the above steps?*

## Other details

* Browser: Edge
* OS: Win10
* CKEditor version: 4.0.+
* Installed CKEditor plugins: N/A

Problem can be worked around by pressing `End`, `Enter` or `Right Arrow` keys and then typing. Please note however this is not intuitive.

Problem can't be reproduced in native editable element as browser paste a link with a selection outside of it. Please see attached screen casts.

[Egde editable iframe.zip](https://github.com/ckeditor/ckeditor-dev/files/2297271/Egde.editable.iframe.zip)
[Edge editor.zip](https://github.com/ckeditor/ckeditor-dev/files/2297272/Edge.editor.zip)

**NOTE:** Similar problem can be observed in IE11. The selection there is also being placed inside a link however during native tests I have noticed that browser actually requires one of keys (`Space`, `End`, `Enter` or `Right Arrow`) being pressed as otherwise it will link the text anyway.

**Comment by Dumluregn** [comment]
This issue is no longer reproducible in the latest Edge browser version.
