### ISSUE TITLE
The Find/Replace plugin can't find text with multiple spaces

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor4#2322]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open editor instance with Find plugin attached
2. Enter the following text `test[space][space][space][space]test` where `[space]` represents Space Key press
3. Open Find plugin and type the same text in the search box. 
4. Press the Find button.

### Expected result

Text is found.

### Actual result

Text is not found.

## Other details

* Browser: Any
* OS: Any
* CKEditor version: 4.0+
* Installed CKEditor plugins: Find/Replace

**Comment by kapilgupta77** [comment]
Any update on this issue? It is preventing users from finding and removing erroneously added double spaces in the editor

**Comment by csalvaneschi** [comment]
We need a fix for this as well. Any update?

**Comment by jacekbogdanski** [comment]
Fixed in [4.17.2](https://github.com/ckeditor/ckeditor4/blob/master/CHANGES.md#ckeditor-4172)
