### ISSUE TITLE
API to get dialog's subject of change / model

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor4#2423]
## Are you reporting a feature request or a bug?

Feature request

## Provide detailed reproduction steps (if any)

Currently there's no common way to access a subject of change for a dialog, instead each dialog implements this in a custom way.

Having this unified would allow us to add a method like `dialog.isEditing()` that tells whether a new entity is currently created or an existing one is created. We often need this kind of information.

Note that since the dialogs are static, `isEditing` method would need to accept `editor` instance as an argument.

### Proposal

Add a new interface that _might_ be implemented in dialogDefinition, let's call it `ModeledDialog`.

It features a single method:

* `getModel( editor ) : [Object/null]`
	* For the most plugins like `table` / `link` it would simply return a [`CKEDITOR.dom.element`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_dom_element.html) if there's a related element to it. For widget plugins (`image2`, `placeholder`) it would return widget instance that is a subject of this dialog.
	* Returns `null` if there's no related model (`about`, `help` dialogs).

If the dialog does not implement `getModel()` it is assumed to be always in editing mode (backward compatible).

### Compatibility

Compatibility is a priority here. In case we have some workarounds in published plugins, like:

* [Adding a widget to dialog event in image2 plugin](https://github.com/ckeditor/ckeditor-dev/blob/6b32b1b109d85ff998df79861f59e78c0add17aa/plugins/image2/plugin.js#L455-L459)
* [Passing widget instance as a first argument](https://github.com/ckeditor/ckeditor-dev/blob/6b32b1b109d85ff998df79861f59e78c0add17aa/plugins/widget/plugin.js#L1162) to `CKEDITOR.dialog.definition.uiElement#setup()` method.

**Comment by mlewand** [comment]
Let's start the discussion first to understand what's the best direction here.

**Comment by jacekbogdanski** [comment]
I'm wondering if we need a function returning model. Could't be just `isEditing` function returning `true` as a default to overwrite?

However, we already have a request for putting a widget into dialog events (#1044) so it looks like this feature may not be redundant.

It may play nice with #2277 where the new feature will be enabled if plugin or widget is adapted to it, ie. implements `getModel` function.

Can we assume that model existence is synonymous with `isEditing` mode? I don't see a problem with our plugins / widgets, but maybe there are cases where this mode should be set explicitly?

**Comment by mlewand** [comment]
The function for returning the model is needed anyway so it make sense to add it. What's more is that if you implement `getModel` you don't have to implement `isEditing` function anymore (as long as generic implementation covers handling of common types, such as DOM elements, widgets etc.).
