### ISSUE TITLE
Error during test: /tests/plugins/balloonpanel/manual/selectionpositioning

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor4#2534]
## Type of report

Failing test 

## Provide detailed reproduction steps (if any)

1. Open test `/tests/plugins/balloonpanel/manual/selectionpositioning`
2. Add few empty paragraphs
3. Make selection from bottom end in empty paragraph

![oct-30-2018 12-44-14](https://user-images.githubusercontent.com/9017322/47715993-a724ec80-dc41-11e8-811d-a088bed0d761.gif)

### Expected result

No error in console

### Actual result

Error in console - wrong position of balloonpanel

## Other details

* Browser: IE10
* OS: Win7
* CKEditor version: 4.11.0
* Installed CKEditor plugins: …

**Comment by mlewand** [comment]
Low prio issue.
