### ISSUE TITLE
Emoji tooltip should show a human friendly label

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor4#2583]
The current way of presenting smileys looks pretty ugly:

<img width="260" alt="screen shot 2018-11-07 at 09 07 04" src="https://user-images.githubusercontent.com/545175/48118490-ace78700-e26c-11e8-9a99-33f295d9a5c9.png">

**Comment by jacekbogdanski** [comment]
An implementation may require changes on the `autocomplete` side, at the current time it supports only changing list item template. We may use `:before` CSS for it, but I think that additional way to style autocomplete dropdown would be nice.
