### ISSUE TITLE
tests/plugins/pastefromword/generated failing on high resolution display

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor4#2736]
## Type of report

Failing tests.

## Provide detailed reproduction steps (if any)

1. Open following tests:
`/tests/plugins/pastefromword/generated/config`
`/tests/plugins/pastefromword/generated/generic_strict`
`/tests/plugins/pastefromword/generated/paragraph_indentation`
`/tests/plugins/pastefromword/generated/tickets1`
`/tests/plugins/pastefromword/generated/tickets5`

### Expected result

All tests pass.

### Actual result

There are some failing tests.

## Other details
It looks like the result depends on the screen size.

* Browser: Chrome
* OS: Any

**Comment by mlewand** [comment]
Tested on notebook with 4k display and android tablet @Mgsy what exactly model was that?

**Comment by Mgsy** [comment]
>@Mgsy what exactly model was that?

It was tested on Huawei MediaPad M5 with Android 8.0.

**Comment by jacekbogdanski** [comment]
I'm also able to reproduce failing tests for PFW in `/tests/plugins/pastefromword/generated/tickets1` using Google Pixel 3 Android 9.

**Comment by Dumluregn** [comment]
`4.14.0` built version, Xiaomi Redmi 7:
`pastefromword/generated/verticalmargin`
`pastefromword/generated/table`
`pastefromword/generated/list_indentation`
are failing.

**Comment by KarolDawidziuk** [comment]
Problem is not occurred because all these tests are skipped on mobile devices.
