### ISSUE TITLE
Edge: Removing list item is problematic due to broken selection

### ISSUE THREAD

**Issue by engineering-this** [ckeditor/ckeditor4#2737]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open CKEditor sample with Edge eg. http://cdn.ckeditor.com/4.11.1/full-all/samples/
2. Paste following into source:
```
<ol>
	<li>Test
	<ol>
		<li>$
		<ol>
			<li>a</li>
			<li>b</li>
			<li>c</li>
		</ol>
		</li>
	</ol>
	</li>
</ol>
```
3. Place caret after `$`.
4. Press backspace.

### Expected result

- Selection stays behind `3`.

### Actual result

- Selection is moved to next list item.

## Other details

Note. This is likely to be an upstream issue. If so than this ticket should be relabelled as `feature`.  In that case workaround would be to act as whole list item was removed - this is what happens in IE.

* Browser: Edge
* OS: Windows 10
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by Dumluregn** [comment]
This issue is no longer reproducible in the latest Edge browser version.
