### ISSUE TITLE
Consider renaming everything to ckeditor4

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor4#2793]
This ticket is about renaming repositories:

 * ckeditor-dev -> ckeditor4
 * ckeditor-presets -> ckeditor4-presets

and so on.

Looks like a huge task as it touches not only GitHub, an incredible amount of the documentation, but also places such as npm, nuget etc.

In short: `ckeditor-dev` says nothing to a new user. Is it CKEditor 4, CKEditor 5? We have same problems with repos such as https://github.com/ckeditor/ckeditor-docs-samples, which include samples only for CKEditor 4 but the name does not reflect this.

**Comment by jacekbogdanski** [comment]
How about user submodules etc? Do you consider keeping `ckeditor-dev` alongside for compatibility or just renaming current repository?

**Comment by jacekbogdanski** [comment]
Sorry, now I see that GH keeps the old endpoint after renaming so above comment is invalid. Also this discussion may be helpful: https://github.community/t5/How-to-use-Git-and-GitHub/How-long-does-github-forward-renamed-moved-repos/td-p/3256

**Comment by mlewand** [comment]
Not something that we want to do ASAP, but definitely will be useful.

**Comment by wwalc** [comment]
The repositories have been renamed. What has left:

 - [ ] Make sure that our docs work fine & can be deployed.
 - [ ] "Rename" npm packages (deprecate old name and during the next occasion - a new release, publish the package under a new name). Make sure our documentation will mention the new package name as npm does not handle redirects as nicely as GitHub.
 - [ ] Update links to GitHub in our documentation (`ckeditor-dev`, `ckeditor-releases`, `ckeditor-presets`, `ckeditor4-docs`, `ckeditor4-docs-samples` etc.).

**Comment by f1ames** [comment]
If you find that anything stopped working please add it to this list so we can track what to fix:

- [ ] Travis integration script (see https://travis-ci.org/ckeditor/ckeditor4/jobs/583657798)

**Comment by msamsel** [comment]
> Make sure that our docs work fine & can be deployed

When I recently build a docs. I noticed that there might be an issue with links `see source` which points directly to github repository.

**Comment by f1ames** [comment]
Moving to next milestone since we probably have some leftovers here and there.

**Comment by f1ames** [comment]
Fixed in #3518.
