### ISSUE TITLE
Travis instability

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor4#2818]
## Type of report

Task

## Provide description of the task

It seems that Travis is unstable from time to time. I'll create this umbrella issue where we'll report problems noticed with it.

**Comment by mlewand** [comment]
The Firefox launcher got a timeout for a community PR: https://travis-ci.org/ckeditor/ckeditor-dev/jobs/494345870

In turn it failed the build status.

**Comment by mlewand** [comment]
Another failing build, where supposedly things should pass: https://travis-ci.org/ckeditor/ckeditor-dev/jobs/494900973

```
info: Testing complete: 7507 total, 7053 passed, 2 failed, 452 ignored in 12m 59s 476ms
error: 1) tests/plugins/easyimage/uploadintegrations - Values should be the same.
Expected: <figure class="easyimage easyimage-full">
	<img alt="" src="/jobs/nUtWYVaz2NR5JlNB/tests/tests/_assets/logo.png" width="163" />
	<figcaption></figcaption>
</figure>
<p>&nbsp;</p>
 (string)
Actual:   <figure class="easyimage easyimage-full">
	<img alt="" src="/jobs/nUtWYVaz2NR5JlNB/tests/tests/_assets/logo.png" />
	<figcaption></figcaption>
</figure>
<p>&nbsp;</p>
 (string)
error: 2) tests/plugins/easyimage/uploadintegrations - Widget#0 src
Expected: /jobs/nUtWYVaz2NR5JlNB/tests/tests//_assets/logo.png (string)
Actual:   blob:http://localhost:1030/32646ad2-a1d9-4006-a0cd-fdca18511089 (string)
```

**Comment by msamsel** [comment]
I don't know why this is wasn't merged automatically as it was merged in Feb. :(
