### ISSUE TITLE
[Table Resize]Connot drag the last column border in IE when border is collapse

### ISSUE THREAD

**Issue by woody-li** [ckeditor/ckeditor4#2823]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Set Table border-collapse as collapse.
2. Insert a table in IE.
3. Try to resize the last column right border.

### Expected result

It can resize, and drag to change the last column width.

### Actual result

Can't show the drag element by mouseover.

## Other details

* Browser: IE11 (may also happen in older IEs)
* CKEditor version: 4.11.2
* Installed CKEditor plugins: Table Resize

**Comment by woody-li** [comment]
What‘s more, the drag element becomes abnormal after any cell split.

**Comment by msamsel** [comment]
Tested on:
http://cdn.ckeditor.com/4.11.2/full-all/samples/old/tableresize/tableresize.html
with `style="border-collapse:collapse;"`.
Table resize sometimes is not displayed at the end of table, so it's not possible to resize the table.

**Comment by lumills** [comment]
Is there any update/eta on this fix? Continuing to see it as of today

**Comment by f1ames** [comment]
Hello @lumills,
no ETA for now since we have other priorities. Please upvote the issue (by adding :+1: to initial report) if you would like to see the fix so we can see what's the interest for it na prioritize.

**Comment by f1ames** [comment]
Fixed in e45cf79.
