### ISSUE TITLE
Improve embed based manual tests with correct test URLs

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor4#2849]
## Type of report

Task

## Provide description of the task

Some of the embed/autoembed tests contain incorrect test URLs. It would be nice to replace them among tests and check if the issue is not caused by any bug. Invalid URLs:

```
https://www.google.dk/maps/place/Zygmunta+S%C5%82omi%C5%84skiego+15,+Warszawa
http://tellto.tumblr.com/post/112160646328
https://open.spotify.com/track/2XsTC2dPbmWREu5RQ1mQC0
```

manual tests requiring improvement:

```
tests/plugins/embed/manual/embed
tests/plugins/embedsemantic/manual/embedsemantic
tests/plugins/autoembed/manual/autoembed
```

**Comment by f1ames** [comment]
Related to #2836.
