### ISSUE TITLE
Vue integration

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor4#2861]
## Type of report

Feature request

## Provide description of the new feature

It would be nice to have an actively maintained Vue integration for CKE4.

Naturally it will land in a separate repository, I'm just adding the issue here so we can track it here.

**Comment by nehadhiman6** [comment]
Image upload is not working

**Comment by f1ames** [comment]
@nehadhiman6 The Vue integration is not yet available, so I assume your issue relates to CKEditor 4, if so please report as separate issue - https://github.com/ckeditor/ckeditor4/issues/new/choose.

**Comment by f1ames** [comment]
Covered in https://github.com/ckeditor/ckeditor4-vue/pull/1 🎉

Now we are working on docs (#3774) and we should be ready to launch soon - see [0.1.0 milestone](https://github.com/ckeditor/ckeditor4-vue/milestone/1).
