### ISSUE TITLE
"Report an Issue" link in docs should point to `ckeditor-dev` instead of `ckeditor-docs` repo

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4#2928]
Since we are migrating all issues from `ckeditor-docs` to `ckeditor-dev` repo, the "Report an Issue" link in docs should be updated to point to https://github.com/ckeditor/ckeditor-dev/issues/new/choose or even https://github.com/ckeditor/ckeditor-dev/issues/new?template=docs-issue.md (after it will be added in https://github.com/ckeditor/ckeditor-dev/issues/2901).

Mentioned "Report an Issue" link is an ❗️ icon in the right top corner:

![image](https://user-images.githubusercontent.com/1061942/53806626-b7c9d400-3f4d-11e9-81c3-c646403115d3.png)

**Comment by msamsel** [comment]
It's worth to test if just creating/updating entry in `umberto.json` will be enough.
search [here](https://github.com/cksource/umberto) for:
```
"github": {
    "url": "url/to/github/repo"
  },
```

**Comment by f1ames** [comment]
See https://github.com/ckeditor/ckeditor-docs/pull/239#issuecomment-494322924.

**Comment by f1ames** [comment]
Moving to the next iteration since Umberto fix is not released yet.

**Comment by msamsel** [comment]
The feature, unfortunately, doesn't work as it should.

Case1:
- "contributeUrl": "https://github.com/ckeditor/ckeditor-docs"
- "issueUrl": "https://github.com/ckeditor/ckeditor4"

Problem: Contribute URL is fixed, so there is missing feature, where now there is direct path to a specific file on GH repository

Case2:
- "url": "https://github.com/ckeditor/ckeditor-docs"
- "issueUrl": "https://github.com/ckeditor/ckeditor4"

Problem: Now contribute URL has nicely calculated paths, however, all links with `see source on github` in API docs gets `url` value so points to `ckeditor-docs`

Case3:
- "url": "https://github.com/ckeditor/ckeditor4"
- "contributeUrl": "https://github.com/ckeditor/ckeditor-docs"
- "issueUrl": "https://github.com/ckeditor/ckeditor4"

Problem: It's the same situation as in case 1.

**Comment by msamsel** [comment]
Right now I remain with option:
```
"url": "https://github.com/ckeditor/ckeditor-dev",
"contributeUrl": "https://github.com/ckeditor/ckeditor-docs",
"issueUrl": "https://github.com/ckeditor/ckeditor4"
```

**Comment by msamsel** [comment]
I've updated branch and solution. Right now links are correctly created.
Please remember to reinstall dependencies when PR will be tested.

**Comment by f1ames** [comment]
Fixed in https://github.com/ckeditor/ckeditor4-docs/commit/ae0dd5626346971b17cd886a4291195808845814.
