### ISSUE TITLE
Auto embed doesn't work with bottom toolbar

### ISSUE THREAD

**Issue by nuljon** [ckeditor/ckeditor4#3000]
## Type of report

Bug

## Provide detailed reproduction steps (if any)
1. install auto embed plugin using media embed tool (not semantic) 
2. config toolbar location bottom
2. run editor in classic mode with firefox browser
3. paste a url for a youtube video from the share link on youtube
4. see ckeditor output 'trying to embed video url ...."
5. f12 to see error in console of firefox debug:
   "type error f is null' (line is 670 position 86 in my custom build)

### Expected result

placement of embedded video

### Actual result

4. see ckeditor output 'trying to embed video url ...."
5. f12 to see error in console of firefox debug:
   "type error f is null' (line is 670 position 86 in my custom build)

## Other details

* CKEditor version: at least 4.10.0

FOR PROOF OF CAUSE IN THE MY TROUBLESHOOTING EFFORT I FIXED THIS SIMPLY BY EDITING LINE 670 TO READ  
c.toolbar&&(f=c.ui.space("bottom")
INSTEAD OF 
c.toolbar&&(f=c.ui.space("top")

**Comment by jacekbogdanski** [comment]
Full error message:
![image](https://user-images.githubusercontent.com/10279586/56411652-bba58180-6281-11e9-902c-6b84bf554cb3.png)

**Comment by f1ames** [comment]
Fixed with c29775a.
