### ISSUE TITLE
Firefox 66.0.2 most of tests randomly fails

### ISSUE THREAD

**Issue by engineering-this** [ckeditor/ckeditor4#3003]
## Type of report

Failing test

## Other details

🚨 When running tests on Firefox 66.0.2 they fail, when running tests with devtools opened browser freezes.

* Browser: Firefox 66.0.2
* OS: macOS/Windows
* CKEditor version: Found in 4.11.4 developement

**Comment by f1ames** [comment]
There is some old issue in FF repository - https://github.com/firefox-devtools/debugger/issues/3736. It's already closed but I can see two [fresh](https://github.com/firefox-devtools/debugger/issues/3736#issuecomment-474869259) [comments](https://github.com/firefox-devtools/debugger/issues/3736#issuecomment-474940482) there regarding similar issue. Maybe it's worth to keep an eye on it.

**Comment by KarolDawidziuk** [comment]
Problem no longer occurs on the latest versions of FF and issue mentioned above in `firefox-debugger` repo is already closed.
