### ISSUE TITLE
[Edge]: opening dialogs results in error `permission denied`

### ISSUE THREAD

**Issue by engineering-this** [ckeditor/ckeditor4#3029]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open sample https://cdn.ckeditor.com/4.11.3/full-all/samples/
2. Open console.
3. Press one of buttons: link, flash or image.

### Expected result

No errors thrown.

### Actual result

`Permission denied` is thrown

## Other details

* Browser: Edge
* OS: Microsoft
* CKEditor version: Found in 4.11.3
* Installed CKEditor plugins: full-all

**Comment by engineering-this** [comment]
According to comment https://github.com/ckeditor/ckeditor-dev/issues/2035#issuecomment-419446612 Edge throws `permission denied` when iframe element has `src` attribute with js code inside.

Apparently we use method [`CKEDITOR.tools.fixDomain`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_tools.html#method-fixDomain) for IE, however some conditions haven't been updated to not execute in Edge. Docs on this method states it's required only for IE.

Proposed solution: https://github.com/ckeditor/ckeditor-dev/commit/2a7506577eac74cd8b820b9f026f65ce35724f05

**Comment by Dumluregn** [comment]
This issue is no longer reproducible in the latest Edge browser version.
