### ISSUE TITLE
Spread the news about the official integrations

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor4#3085]
E.g.

https://github.com/JefMari/awesome-wysiwyg

For the full list of ideas check: https://github.com/ckeditor/ckeditor5/issues/1344

**Comment by jacekbogdanski** [comment]
Copying the list from https://github.com/ckeditor/ckeditor5/issues/1344 as a reference:

## Generic

* [ ] https://github.com/JefMari/awesome-wysiwyg

## Angular

* [ ] https://github.com/gdi2290/awesome-angular
* [ ] https://github.com/brillout/awesome-angular-components
* [ ] https://github.com/Angular-RU/angular-awesome-list

## React

* [ ] https://react.parts/
* [ ] https://github.com/enaqx/awesome-react
* [ ] https://github.com/brillout/awesome-react-components

## [Vue](https://github.com/ckeditor/ckeditor5-vue/issues/4)

* [ ] https://github.com/vuejs/awesome-vue#rich-text-editing
* [ ] https://github.com/JefMari/awesome-wysiwyg

**Comment by jacekbogdanski** [comment]
Ok, so it seems like all listed repositories are covered (or have pending PRs). Only  https://github.com/brillout/awesome-angular-components left but it doesn't seem to be maintained - I'm unable to visit the website used to add new integrations. Seems we can close it for now and revisit if needed.
