### ISSUE TITLE
Integration link leads to easyimage

### ISSUE THREAD

**Issue by engineering-this** [ckeditor/ckeditor4#3092]
## Type of report

Docs

## Provide a description of requested docs changes

https://ckeditor.com/docs/ckeditor4/latest/guide/index.html
![Screenshot 2019-05-09 at 15 45 33](https://user-images.githubusercontent.com/23366849/57458421-9c42b880-7271-11e9-8fa6-1f3865f5626e.png)
`Integration` link leads to https://ckeditor.com/docs/ckeditor4/latest/guide/dev_easyimage_integration.html which is quite inconvienient as this is group for unrelated topics it can't lead to just one of them. Especially when we add framework integrations than there is high chance user wanting to find out about integrations would end up in easyimage article.

**Comment by f1ames** [comment]
@AnnaTomanek maybe you have any ideas on this one?

We were thinking about extracting integrations to separate section (like `CKEditor 4 Plugin SDK`), but then it will be inconsistent with the rest of the page.

The other idea was to make `Integration` title not clickable and just turn parts of the description (mentioning particular items) links. But again it will be inconsistent with the rest of the page.

Finally, the 3rd idea was to make some introduction page in the Integration docs section which can be linked here. However, such page will probably only duplicate content which we have here and in other integration subsections which is just making a mess.

**Comment by Dumluregn** [comment]
I think that the 3rd idea makes most sense, we could just create a page being mainly table of contents like [here](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_advanced_installation.html) and mention there that we provide integration with popular JS frameworks (maybe Angular, React and Vue should be together in a subfolder?) and other stuff.

**Comment by AnnaTomanek** [comment]
I can create a simple landing page for integrations that will resemble what we have for CKEditor 5: https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/overview.html. It will be needed for the CKEditor 4 integrations section on the product page anyway.
