### ISSUE TITLE
Docs on NPM should mentioned how to install other CKEditor presets via NPM

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4#3103]
## Type of report

Docs

## Provide a description of requested docs changes

Extracted from #2053.

The `ckeditor` npm package contains `standard-all` build only. There is no obvious way to install other builds via npm. However, as @msamsel pointed out in https://github.com/ckeditor/ckeditor-dev/issues/2053#issuecomment-394617895, this can be done by installing builds directly from Github.

This information should be include in our docs on npm https://ckeditor.com/docs/ckeditor4/latest/guide/dev_package_managers.html#npm.

**Comment by jacekbogdanski** [comment]
Closed via https://github.com/ckeditor/ckeditor4-docs/pull/280
