### ISSUE TITLE
Failing test 'tests/plugins/imagebase/features/link'

### ISSUE THREAD

**Issue by engineering-this** [ckeditor/ckeditor4#3147]
## Type of report

Failing test

## Details

`major` branch: various tests in `tests/plugins/imagebase/features/link` fails randomly.
Additionally there are some typeerrors, although they don't break tests.
![Screenshot 2019-05-31 at 14 29 19](https://user-images.githubusercontent.com/23366849/58705948-f508fb00-83b0-11e9-97c3-37af15d7a8d5.png)
![Screenshot 2019-05-31 at 14 29 24](https://user-images.githubusercontent.com/23366849/58705947-f508fb00-83b0-11e9-858f-84494cf78ccb.png)

* Browser: IE11
* OS: Windows 10
* CKEditor version: 4.12.0 development

**Comment by Dumluregn** [comment]
Works fine in 4.13.1 release version.

**Comment by f1ames** [comment]
Still failing in 4.13.1 development version, passes on release version.

**Comment by sculpt0r** [comment]
Already ignored:
https://github.com/ckeditor/ckeditor4/blob/70649e5cd8b1afedba2aeb18017aed4e6227c911/tests/plugins/imagebase/features/link.js#L272-L274
