### ISSUE TITLE
It is not possible to set autolink_urlRegex and autolink_emailRegex properties of autolink plugin

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor4#3156]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Download CKEditor with autolink plugin.
2. Use one of below code versions to configure CKEditor:
```
CKEDITOR.config.autolink_urlRegex = /^(https?|ftp|file):\/\/(-\.)?([^\s\/?\.#]+\.?)+(\/[^\s]*)?[^\s\.,]$/i;
var editor = CKEDITOR.replace( 'editor1', {extraPlugins : 'autolink'});
```
```
var editor = CKEDITOR.replace( 'editor1', {
    extraPlugins : 'autolink',
    autolink_urlRegex : /^(https?|ftp|file):\/\/(-\.)?([^\s\/?\.#]+\.?)+(\/[^\s]*)?[^\s\.,]$/i
});
```
2. Load CKEditor and type e.g.  `file://C:/test/`  and press space
(I know the URL is invalid and the regex should be changed becaue it match `file:///C:/test/` but this is just for simplicity of testing)

### Expected result

Text should get linked.

### Actual result

Text doesn't get linked

## Other details

This is happening because plugin code uses e.g. `CKEDITOR.config.autolink_emailRegex` instead of `editor.config.autolink_emailRegex`:
https://github.com/ckeditor/ckeditor-dev/blob/master/plugins/autolink/plugin.js#L128
https://github.com/ckeditor/ckeditor-dev/blob/master/plugins/autolink/plugin.js#L103
https://github.com/ckeditor/ckeditor-dev/blob/master/plugins/autolink/plugin.js#L127
what makes impossible to overwrite values for these properties.

* Browser: Any
* OS: Any
* CKEditor version: 4.11.0+
* Installed CKEditor plugins: autolink

**Comment by jacekbogdanski** [comment]
Fixed in https://github.com/ckeditor/ckeditor4/pull/3930
