### ISSUE TITLE
Right clicking toolbar buttons clears selection

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor4#3170]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open CKEditor 4 sample, e.g. https://ckeditor.com/docs/ckeditor4/latest/examples/classic.html
2. Select some text.
3. Right click any button inside the toolbar.

### Expected result

Selection inside the editor becomes inactive (changes color to gray).

### Actual result

Selection disappears.

## Other details

* Browser: Edge

It happens only when we right click right after selecting anything. If we click first anywhere outside the editable and then right click toolbar's button, it works as expected.

**Comment by Dumluregn** [comment]
This issue is no longer reproducible in the latest Edge browser version.
