### ISSUE TITLE
Unstable test in tests/plugins/font/font

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor4#3180]
## Type of report

Failing test

## Provide detailed reproduction steps (if any)

1. Open http://tests.ckeditor.test:1030/tests/plugins/font/font#tests%2Fplugins%2Ffont%2Ffont%20test%20apply%20font%20size%20(collapsed%20selection)

### Expected result

Test always passes.

### Actual result

Test often fails.

## Other details

* Browser: IE9
* Installed CKEditor plugins: font

**Comment by sculpt0r** [comment]
Already ignored on IE9 - I'm closing this one.
