### ISSUE TITLE
Unstable tests in /tests/tickets/10448/1

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor4#3186]
## Type of report

Failing test

![image](https://user-images.githubusercontent.com/10279586/59697101-8cfa4780-91ed-11e9-9cf8-7d5c7846d33e.png)

## Other details

Tests seem to be unstable on Edge:

![image](https://user-images.githubusercontent.com/10279586/59697060-7c49d180-91ed-11e9-9bf0-9f804c15a121.png)

* Browser: Edge
* CKEditor version: 4.12.0 built

**Also fails on `4.11.4` version which means it is probably caused by Edge update (from version `17` to `18`)**.

**Comment by Dumluregn** [comment]
As this test was not reported to fail in the last couple testing phases, I'm closing this issue.
