### ISSUE TITLE
Unstable eventBuffer tests in tests/core/tools

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor4#3187]
## Type of report

Failing test

![image](https://user-images.githubusercontent.com/10279586/59698586-4b1ed080-91f0-11e9-9115-62665f4bc86a.png)

Tests are failing randomly.

## Other details

* Browser: Edge
* CKEditor version: 4.12.0 built

**Comment by f1ames** [comment]
I checked on `4.11.4` build but wasn't able to make it red. Then tried `4.12.0` and the test was all green. It seems it's a little unstable and may be hard to reproduce.

**Comment by Dumluregn** [comment]
As this test was not reported to fail in the last couple testing phases, I'm closing this issue.

**Comment by Dumluregn** [comment]
This issue is no longer reproducible in the latest Edge browser version.
