### ISSUE TITLE
Failing test in tests/plugins/pastefromword/manual/listindentation

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor4#3195]
## Type of report

Failing test

`tests/plugins/pastefromword/manual/listindentation`

Pasting from example docx seems to correctly preserve indentation, although hovering gives some weird results - in most cases, there is no provided `margin-left` or it has a different value than expected.

Looks like it's the issue with the test itself, not feature.

## Other details

* Browser: Edge
* CKEditor version: 4.12.0 built

**Comment by Dumluregn** [comment]
As this test was not reported to fail in the last couple testing phases, I'm closing this issue.
