### ISSUE TITLE
Add `Default` or `Normal` option to `Styles` dropdown

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor4#3207]
## Type of report

Feature request

## Provide description of the new feature

If user changes block style using combo:
<img width="175" alt="Screenshot 2019-06-24 at 12 40 36" src="https://user-images.githubusercontent.com/10883184/60013110-ec3cd980-967d-11e9-8c64-87a57d081493.png">
and wants to return to default one, he/she needs to click the style again (like with format buttons - `B`, `I` etc.). I think more intuitive would be to add the option `Default` or `Normal` removing formatting on block level. Such an approach is used for Font dropdown:
<img width="182" alt="Screenshot 2019-06-24 at 12 47 02" src="https://user-images.githubusercontent.com/10883184/60013238-3faf2780-967e-11e9-953b-0f4abb56f1e3.png">

**Comment by engineering-this** [comment]
I wonder if we really need such feature. You can remove styling with `remove format` button. Also the difference between **Styles Combo** and **Format Combo** (or other combos which work like Format) is that you can mix few options from the first one, but you can't have two headings applied on same content. In other words Styles works like checkboxes, but Format and others work like radio inputs.

Another thing is that Styles Combo is a tool that should be configured for users need, predefined styles are more like a suggestion of what can be done with this plugin. While Paragraph Format and other combos contains styles that are used in most of documents.

Also there might be some tricky cases, eg. we have style `Italic Title` which applies `h2{font-style:italic}`. If I have just `h2` from **Format**, should the default **Styles** remove the `h2` or do it only when it has inline style property mentioned earlier?

**Comment by Dumluregn** [comment]
> you can mix few options from the first one, but you can't have two headings applied on same content.

This is true for inline styles, but you can't set two block styles, so in this group it still works as radio button. And you don't 'unmark' radio button by clicking it second time.

> If I have just h2 from Format, should the default Styles remove the h2 or do it only when it has inline style property mentioned earlier?

This problem is already solved, because this scenario applies when you click on currently used block style again. And it removes `h2` tag changing text into `p` indeed.

**Comment by jacekbogdanski** [comment]
After the #4181 fix, we can get this behavior by just using paragraph format + removing inline styles, which should be enough to close this issue.
