### ISSUE TITLE
It should be possible to use mask only on a widget part

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4#3240]
## Type of report

Feature request

## Provide description of the new feature

The [widget `mask` property](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_plugins_widget.html#property-mask) works in a way that it covers entire widget. There are cases where it could be useful to define only a [part](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_plugins_widget.html#property-parts) of a widget which will be masked.

This is real use case encountered during [Drupal `embed-entity` plugin](https://www.drupal.org/project/entity_embed) development, where there is an captionable media embed. The media itself should have interaction blocked while the caption should be editable in place (and the mask covers entire widget blocking caption editing).

The proposal is to make `mask` property accept string too which will be the name of the widget part which should be masked.

**Comment by wimleers** [comment]
Corresponding issue on `drupal.org`: https://www.drupal.org/project/entity_embed/issues/3064572
