### ISSUE TITLE
Make applyStyle and removeStyle hookable

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4#3306]
## Type of report

Feature request

## Provide description of the new feature

Some of the features use [`commands`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_command.html) (e.g. bold, italics, alignment, etc) which makes it easy to hook into with [`beforeCommandExec`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#event-beforeCommandExec) and [`afterCommandExec`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#event-afterCommandExec).

However, others use [`applyStyle`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#method-applyStyle) and [`removeStyle`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#method-removeStyle) (e.g. font, stylescombo, colorbutton, colordialog) which makes it impossible to hook into as there are no events or any other forms of intercepting the flow (apart from hacky methods proxying). This makes it quite difficult to integrate with other features.

So the idea is to make `applyStyle` and `removeStyle` methods hookable. We were thinking about refactoring using commands however it requires quite significant amount of work and may be problematic. So we decided to go with events which will be fired before/after styles applying/removing.

I'm just wondering if one event will be enough - something like `beforeApplyStyle`/`removeApplyStyle` (which will also allow canceling styles applying) or we could also add `afterApplyStyle`/`afterApplyStyle`? cc @jacekbogdanski

**Comment by jacekbogdanski** [comment]
Fortunately, these methods don't return anything, so probably canceling them shouldn't cause side effects. Yeah, I think that additional events instead of dedicated methods will be much easier to implement (single place) with the same profit.

Just don't forget about passing style object into an event, otherwise, it will be useless.

`before` events looks redundant for me as if I'm correct styles method are called synchronously, so you can always attach a listener at the end of the event queue. In that case, maybe let's simplify naming into `applyStyle/removeStyle` event?

**Comment by Comandeer** [comment]
You can look into `copyformatting` plugin. We made there commands and events around applying styles. Maybe similar strategy can be used also for styles core?

**Comment by f1ames** [comment]
After some testing (@jacekbogdanski 👍) we decided to go with commands (but in simplified version). Since few plugins overuse `apply/removeStyle()` methods (for example calling both methods on a single styles application) firing event will not be reliable.

So the idea is to provide commands which will be wrapping current code which applies styles for a given plugin (so it's kind of implementation/refactor per plugin basis). We do not want to try with any generic solution since it will require huge amount of work.

Each style should have own command, for example the `font` plugin which adds `Font` and `FontSize` combos, should have `font` and `fontSize` commands, which will be fired on style application (so probably [somewhere there](https://github.com/ckeditor/ckeditor-dev/blob/major/plugins/font/plugin.js#L106-L182)). If the same style is applied 2nd time, command should not be fired (since styles are not toggleable).

The command data object should contain applied style (if style is removed, it should be `null` or something similar).

Let's start with covering:
1. `font` plugin
2. `colorbutton` plugin

Depending on how it goes we may think of supporting `format` and `stylescombo` to have all "combo-like" plugins covered.

**Comment by jacekbogdanski** [comment]
Extracted commands for colorbutton and font plugins separately, see https://github.com/ckeditor/ckeditor4/issues/3727
https://github.com/ckeditor/ckeditor4/issues/3728

Although, implementation details are still relevant.
