### ISSUE TITLE
Paste image randomly not working

### ISSUE THREAD

**Issue by bdelvauxevscom** [ckeditor/ckeditor4#3323]
Hi,

We are using CKEditor 4.12.1 in a Dynamics 365 environment as a webresource (in an iframe), and the Upload Image plugin to copy/paste or drap/drop images into the editor.
It works perfectly well most of the times, but sometimes for some reasons we get nothing when pasting the image: the data.dataValue property stays empty in the paste event.
Chrome is our main browser for testing the application.
Does anyone know how to fix this?

Thanks!

## Detailed steps

1. Paste an image in CKE
2. go to browser dev tools
3. Check data.dataValue

### Expected result

data.dataValue must contain a tag img containing base64 string in src attribute

### Actual result

data.dataValue contains an empty string

## Other details

* Browser: Chrome latest version
* OS: Windows 10 1903
* CKEditor version: 4.12.1
* Installed CKEditor plugins: 

Auto Grow
Color Button
Enhanced Image
Basic Styles
Clipboard
Context Menu
Editor Resize
Editor Toolbar
Enter key
Escape HTML Entities
File Browser
Floating Space
Format
Horizontal Rule
HTML Output Writer
IFrame Editing Area
Indent List
Link
List
Magic Line
Paste As Plain Text
Paste From Word
Remove Format
Show Table Borders
Styles Combo
Tab Key Handling
Table
Table Selection
Table Tools
Undo
Upload Image
Dialog
Dialog User Interface
Fake Object
File Tools
Floating Panel
Indent / Outdent
Line Utilities
List Block
Menu
Notification
Notification Aggregator
Panel
Panel Button
Popup
Rich Combo
UI Button
Upload Widget
Widget
Widget Selection

**Comment by Comandeer** [comment]
Can you provide some more info how exactly you paste the image? There are some known issues with pasting in Chrome, e.g. #2675.

**Comment by bdelvauxevscom** [comment]
Hello Tomasz,

Thanks for the prompt reply, we basically paste it from windows clipboard with an screenshot captured via Greenshot.

We think we found a workaround by systematically checking in the paste event whether there is a copied or a dropped image in evt.data.dataTransfer._.files.
If there is one, we replace evt.data.dataValue by a new img tag with the image data.

editor.on('paste', function (evt) {
    var copiedImage = evt.data.dataTransfer._.files[0] || null;

    if (copiedImage && copiedImage.type.search('image/') > -1) {
        // We have an image in the clipboard, we paste it or drop it.
        var reader = new FileReader();

        reader.addEventListener('load', function () {
            evt.data.dataValue = '<img src="' + reader.result + '" data-cke-upload-id="0" data-widget="uploadimage" />';
        }, false);

        reader.readAsDataURL(copiedImage);
    }
});

We’ll monitor the behavior in the next few days in order to confirm that this resolved the issue.

Best regards,

Benoit DELVAUX – IT Business Analyst
T. +32 4 361.89.93 b.delvaux@evs.com<mailto://b.delvaux@evs.com>
EVS Broadcast Equipment - 13 Rue Bois St Jean - 4102 Seraing - BELGIUM


Quicklinks:   Latest News<http://www.evs.com/news>   Next Events<http://www.evs.com/events>   Contacts<http://www.evs.com/contact>
Community:   Facebook<http://www.facebook.com/home.php#!/pages/EVS-Broadcast-Equipment/262186759015?ref=ts>   Twitter<http://twitter.com/EVSEquipment>    LinkedIn<https://www.linkedin.com/company/evs-broadcast-equipment>  Youtube<http://www.youtube.com/user/EVSBroadcast>   Instagram<http://instagram.com/evsequipment>   MyEVS<http://www.evs.com/myevs>   RSS<http://www.evs.com/rss/news>

[cid:evs_40525554-59bc-4de5-afaf-e8cc5cecc82a.jpg]<http://www.evs.com/>

www.evs.com<http://www.evs.com>


EVS Broadcast Equipment is a commercial name which is used for all legal entities of our group<https://evs.com/sites/default/files/evs_broadcast_equipment_addresses.pdf>.

At EVS we give utmost importance to your data's privacy. If you wish to know more on how we manage your data and on your rights, please consult our Privacy Statement<https://evs.com/en/privacystatement>.

This message may contain confidential information and is intended solely for the use of the addressee. Please do not use or publish the contained information without the agreement of the sender. If you are not the intended recipient of this message, please notify the sender and do not disclose, use, disseminate or copy this message.

Please consider the environment before printing this email.

**Comment by Comandeer** [comment]
@bdelvauxevscom, can you confirm that the workaround fixed the issue? 

If yes, it can probably be replaced by solution suggested in https://github.com/ckeditor/ckeditor-dev/issues/2675#issuecomment-515750101, which doesn't involve regular polling the clipboard.

**Comment by Dumluregn** [comment]
Hi @bdelvauxevscom, it's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Comment by bdelvauxevscom** [comment]
Hello Dariusz,

Sorry for the delay and thanks for the follow up.

I'll check with our dev and come back to you.

Thanks,

Get Outlook for Android<https://aka.ms/ghei36>

Benoit DELVAUX – IT Business Analyst
T. +32 4 361.89.93 b.delvaux@evs.com<mailto://b.delvaux@evs.com>
EVS Broadcast Equipment - 13 Rue Bois St Jean - 4102 Seraing - BELGIUM


Quicklinks:   Latest News<http://www.evs.com/news>   Next Events<http://www.evs.com/events>   Contacts<http://www.evs.com/contact>
Community:   Facebook<http://www.facebook.com/home.php#!/pages/EVS-Broadcast-Equipment/262186759015?ref=ts>   Twitter<http://twitter.com/EVSEquipment>    LinkedIn<https://www.linkedin.com/company/evs-broadcast-equipment>  Youtube<http://www.youtube.com/user/EVSBroadcast>   Instagram<http://instagram.com/evsequipment>   MyEVS<http://www.evs.com/myevs>   RSS<http://www.evs.com/rss/news>

[cid:evs_40525554-59bc-4de5-afaf-e8cc5cecc82a.jpg]<http://www.evs.com/>

www.evs.com<http://www.evs.com>


EVS Broadcast Equipment is a commercial name which is used for all legal entities of our group<https://evs.com/sites/default/files/evs_broadcast_equipment_addresses.pdf>.

At EVS we give utmost importance to your data's privacy. If you wish to know more on how we manage your data and on your rights, please consult our Privacy Statement<https://evs.com/en/privacystatement>.

This message may contain confidential information and is intended solely for the use of the addressee. Please do not use or publish the contained information without the agreement of the sender. If you are not the intended recipient of this message, please notify the sender and do not disclose, use, disseminate or copy this message.

Please consider the environment before printing this email.


________________________________
