### ISSUE TITLE
Make getClipboard utility configurable

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor4#3329]
## Type of report

Task

## Provide description of the task

Currently `dev/pastefromword/getclipboard.html` is very inflexible: it has one, hardcoded configuration. However now we're extending our paste handling with `pastetools` and `pastefromgdocs`. It would be nice to make this utility more flexible:

* choose which paste plugin to use;
* choose which plugins to load;
* provide additional config (e.g. `allowedContent`/`extraAllowedContent`).

## Other details

* Installed CKEditor plugins: pastefromword, pastetools, pastefromgdocs

**Comment by jacekbogdanski** [comment]
Closed in https://github.com/ckeditor/ckeditor4/pull/3907
