### ISSUE TITLE
Update standard and full presets

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor4#3349]
## Type of report

Task

## Provide description of the task

As of 4.13.0 we should extend our standard and full presets to also include `pastetools` and `pastefromgdocs` plugins, introduced by #835 and #3258. Probably we should also update `config.js` in this repo.

## Other details

* CKEditor version: 4.13.0
* Installed CKEditor plugins: pastetools, pastefromgdocs

**Comment by f1ames** [comment]
Fixed in https://github.com/ckeditor/ckeditor4/commit/23582c4754d2ff933b2c3359ac5e064077502872 and https://github.com/ckeditor/ckeditor4-presets/commit/af3de0013942121e8b5afe0995b098e94bdd92eb.
