### ISSUE TITLE
Can't get selected widgets during copy/cut after selecting all content

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor4#3352]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open https://jsfiddle.net/Comandeer/ab3dsngr/
2. Open console.
3. Select all content inside the editor using <kbd>Ctrl</kbd>/<kbd>Cmd</kbd> + <kbd>A</kbd>
4. Copy/cut content

### Expected result

The array of two selected widgets should be logged into the console.

### Actual result

An empty array is logged.

## Other details

Strangely enough, adding `selectall` plugin seems to fix the issue 🤔 

* CKEditor version: 4.5.0+
* Installed CKEditor plugins: widget

**Comment by f1ames** [comment]
@Comandeer I see it works fine on Chrome (tested on provided JSFiddle). but fails on Firefox, which means it is browser specific issue. Can you confirm? (Chrome - `76.0.3809.132 `, FF - `69.0`).

**Comment by f1ames** [comment]
It's a little more complex - select all + copy works as expected on Chrome. But selecting widget then cutting it and then select all + copy returns empty widgets array 🤔 So on FF it simply fails for every copy while on Chrome it starts to fail after cutting widget 🤔

**Comment by Comandeer** [comment]
It's even more complex: it sometimes Just Works™ 😂 The behaviour seems to be totally random.

**Comment by Comandeer** [comment]
OK, I discovered the pattern: selection is refreshed after releasing keys, so pressing <kbd>Cmd/Ctrl</kbd>+<kbd>A</kbd> and then immediately (without releasing <kbd>Cmd/Ctrl</kbd> key) <kbd>Cmd/Ctrl</kbd>+<kbd>C</kbd>/<kbd>X</kbd> shows 0 widgets. Also holding <kbd>Cmd/Ctrl</kbd>+<kbd>A</kbd> shows 0 until keys are released. It seems like more fundamental issue with refreshing selection in the editor/widget plugin.

**Comment by Comandeer** [comment]
The very naive solution would be to fire `selectionCheck` also on `keydown`/`key` event: https://github.com/ckeditor/ckeditor4/blob/5fa2a5b5f5b06d139ecaf8d47f5444734244e5b9/core/selection.js#L934-L940

However it seems to fix the issue only in Firefox, Chrome and Safari still incorrectly show the amount of selected widgets. I'm also not sure if such approach won't break anything inside the editor.

For now I can think only of more dirty solution: force widget repository to check if widgets are selected also on `key` event.

**Comment by f1ames** [comment]
Fixed in https://github.com/ckeditor/ckeditor4/commit/6000049574d4835bf11cc2f51582d01a589ed712.
