### ISSUE TITLE
The tests/plugins/clipboard/drop fails on Firefox on Windows

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4#3353]
## Type of report

Task

## Provide description of the task

![image](https://user-images.githubusercontent.com/1061942/63684888-50a32300-c7fe-11e9-8837-5dcfc720c824.png)

## Other details

* Browser: Firefox `68.0.2 (64-bit)`
* OS: Windows 10 (Passes on Linux and macOS)
* CKEditor version: 4.12
* Installed CKEditor plugins: -

**Comment by sculpt0r** [comment]
It is no longer reproducible (dev 4.16.3 & build 4.16.3). Tested on Windows 10 & macOS.
