### ISSUE TITLE
Failing test /tests/plugins/justify/justify

### ISSUE THREAD

**Issue by engineering-this** [ckeditor/ckeditor4#3364]
## Type of report

Failing test

## Provide detailed reproduction steps (if any)

Run test `/tests/plugins/justify/justify` in Firefox. They randomly fail.

## Other details

![Screenshot 2019-08-29 at 12 02 14](https://user-images.githubusercontent.com/23366849/63931085-dddfb500-ca54-11e9-897d-363bc96dc47b.png)

* Browser: Firefox 68.0.2 (64 bit)
* OS: macOS 10.14.6
* CKEditor version: 4.13.0 development
* Installed CKEditor plugins: …

**Comment by FilipTokarski** [comment]
Failing on 4.14.0, Firefox version 73.0

```
test alignment commands in div mode and with justifyClasses

leftCmd.state
Expected: 2 (number)
Actual:   1 (number)
```

**Comment by Dumluregn** [comment]
Still randomly failing in CKE 4.14.1 (both dev and build versions).

**Comment by sculpt0r** [comment]
Already ignored.
