### ISSUE TITLE
Bump umberto version

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor4#3390]
## Type of report

Task

## Provide description of the task

* update umberto version in ckeditor-docs repository

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by f1ames** [comment]
Fixed in https://github.com/ckeditor/ckeditor4-docs/commit/a3719787ffbeec2901b5899eff19b26246cb9ad7.
