### ISSUE TITLE
CKEDITOR.editor#setData() docs are incorrect

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor4#3417]
## Type of report

Docs

## Provide a description of requested docs changes

`CKEDITOR.editor#setData()` has incorrect API docs. They are not consistent with method's signature: https://github.com/ckeditor/ckeditor4/blob/52ec0b185b005611368b3eccd59275ba4294526a/core/editor.js#L1111-L1118

**Comment by f1ames** [comment]
Fixed in 5e37e65.
