### ISSUE TITLE
Provide support for building docs from ckeditor4 folder

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor4#3422]
## Type of report

Docs

## Provide a description of requested docs changes

Currently, docs search for `ckeditor-dev` folder during building.  It could be nice to support `ckeditor4` folder as well.

Related to change: #2793

**Comment by f1ames** [comment]
Fixed in https://github.com/ckeditor/ckeditor4-docs/commit/c3e8f03e888ccfbc1315499d92b10fb2cbc413a1.
