### ISSUE TITLE
Find a way to destroy editor when iframe is loaded on Safari

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor4#3426]
## Type of report

Task

## Provide a description of the task

Currently, there are ignored tests on safari which destroys editor after iframe load. What is strange, that tests are passing when debugging console is turned on.
There might be some sort of optimization in Safari which loads this iframe more secure or somehow independently, what results in failing test.
It could be nice to find another way, which would allow on destroying the editor in that specific moment.

https://github.com/ckeditor/ckeditor4/blob/major/tests/core/editor/detaching.js (link will be working after merge of #3128)

I tried to overwrite the original prototype method in `CKEDITOR.editor.prototype.addMode`, however, it doesn't work for me.

![image](https://user-images.githubusercontent.com/1061942/65044843-f9f0bb00-d95d-11e9-8f07-edeefae8c529.png)

**Comment by jacekbogdanski** [comment]
Dup of https://github.com/ckeditor/ckeditor4/issues/5191
