### ISSUE TITLE
Italic-Title

### ISSUE THREAD

**Issue by Tejatr** [ckeditor/ckeditor4#3431]
Styles

If we select Italic title it will change to heading 2 and font style italic  and at styles it will show Italic title .   but if we edit heading to any like heading 1 or 3 it wont show as Italic title in styles 
but till sentences are in italic style  at least Italic title should high let to know the user as font is in italic format 

## Provide detailed reproduction steps (if any)

1. write some thing in ck editor in any header or footer
2. select and apply italic title
3 now change heading it will change but in styles user need to understand it is italic title but it not showing

### Expected result

In styles Italic title must beat top after changes

### Actual result

showing only styles after changes

## Other details

* Browser; chrome
* OS: windows 7
* CKEditor version:4.11

**Comment by Dumluregn** [comment]
Hello, the predefined styles work as a whole set of styling applied to selection (or, in this case, block), i.e. heading level, bold etc. If you change any of those, the style is no longer identical as the predefined `Italic Title`, so it wouldn't be true to show it is.
