### ISSUE TITLE
Anchor with text is not in editing mode

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor4#3437]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open `/tests/plugins/link/manual/editingmode`
2. Type some text in editor
3. Select it
4. Apply anchor to it and accept
5. Double click on anchor

### Expected result

Dialog is in editing mode

### Actual result

Dialog is in creation mode

## Other details
![Screenshot 2019-09-18 at 15 24 37](https://user-images.githubusercontent.com/9017322/65152958-32a99680-da29-11e9-8b78-a280345b9a8b.png)

* Browser: Safari
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by Comandeer** [comment]
It is more general issue, connected with the fact that `getSelectedAnchor` private function in `anchor` dialog can't get `a` element, when selection is inside text.

**Comment by Comandeer** [comment]
The same issue is present in IE8.
