### ISSUE TITLE
Color Dialog is without editing mode

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor4#3438]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open one of the manual tests for editing mode.
2. Type something in the editor and select it.
3. Use color dialog to apply background for this text.
4. Reopen dialog

### Expected result

Color dialog should be in editing mode

### Actual result

Color dialog is in creation mode.

*What is the actual result of the above steps?*
![Screenshot 2019-09-18 at 15 34 17](https://user-images.githubusercontent.com/9017322/65153542-3a1d6f80-da2a-11e9-9fe9-5a26bf9ab051.png)

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by Comandeer** [comment]
Actually `colordialog` does not operate on element, but directly on color, passed as a part of `show` event. This way `colordialog` can be used also in context, where there is no element and only colorpicker is needed.
