### ISSUE TITLE
Multiple widgets drag&drop with specific selection doesn't work well

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor4#3441]
## Type of report

Feature request

## Provide detailed reproduction steps (if any)

1. Open `/tests/plugins/widget/manual/clipboardhtml` test.
2. Make selection containing a few widgets, but starting and ending with text.
3. Drag&drop.

### Expected result

Widgets content should change as described in test scenario.

### Actual result

Widgets content doesn't change.

## Other details

* Browser: Firefox
* OS: macOS
* CKEditor version: 4.13
* Installed CKEditor plugins: widget

**Comment by Comandeer** [comment]
It's more of a feature request, because current implementation is built around modifying copied content, not altering pasted one. Because of that, handling d&d will require altering the whole d&d logic to introduce new serializing behaviour to it.

**Comment by f1ames** [comment]
@Dumluregn @Comandeer how did it worked before the recent changes in clipboard? From what I understand it works as before the change:

> Widgets content doesn't change.

So we are missing the part for handling d'n'd (with selection containing widgets)? If so we can handle it as a follow-up.

**Comment by Comandeer** [comment]
It is supported only on d&d of one widget – as it was the only case supported by the previous implementation. I didn't extend `drag` handler, only `copy` one.
