### ISSUE TITLE
Update dev dependencies 

### ISSUE THREAD

**Issue by Colinax** [ckeditor/ckeditor4#3446]
## Type of report

Task

## Provide description of the task

Some of the CKEditor development dependencies are out of date:

 benderjs-yui ^0.3.2  →   ^0.3.4
 grunt ^1.0.1  →   ^1.0.4
 grunt-contrib-concat ^1.0.0  →   ^1.0.1
 grunt-contrib-imagemin  ^2.0.1  →   ^3.1.0
 grunt-contrib-jshint ^1.0.0  →   ^2.1.0
 grunt-contrib-watch ^1.0.0  →   ^1.1.0
 less ^3.8.0  →  ^3.10.3
 shelljs ^0.8.2  →   ^0.8.3

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by jacekbogdanski** [comment]
It may also help https://david-dm.org/ckeditor/ckeditor4?type=dev
