### ISSUE TITLE
Ignore mobile tests

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor4#3454]
## Type of report

Task

## Provide description of the task

`tests/core/dom/range/manual/followingfcs` - no way to create soft enter
`tests/core/dom/range/manual/gettableelement` - not able to create such selection with touch devices
`tests/core/editable/manual/insertgetdata` - dnd not supported on mobile
`tests/plugins/panel/manual/keydown` - keyboard is hidden when context menu open
`tests/plugins/pastetools/manual/loadingfilters` - no console support
`tests/plugins/widget/manual/clipboardhtml` - clipboard support by dialog, no dnd, should be enabled again after fixing https://github.com/ckeditor/ckeditor4/issues/3463
`tests/plugins/widget/manual/clipboardhtmlselectall` - no console support
`tests/plugins/widget/manual/draghandlerreadonly` - no dnd support

all `pastefromgdocs` tests due to https://github.com/ckeditor/ckeditor4/issues/3451

**Comment by f1ames** [comment]
Fixed in a3a8560.
