### ISSUE TITLE
failing test - tests/core/htmldataprocessor/htmldataprocessor

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor4#3483]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. run `tests/core/htmldataprocessor/htmldataprocessor` on iOS13 with Safari

### Expected result

passing test

### Actual result

failing test

## Other details

![IMG_0005](https://user-images.githubusercontent.com/9017322/65498463-3a02f100-debc-11e9-84df-f2db92371a24.PNG)

* Browser: Safari
* OS: iOS 13 (iPhone 11)
* CKEditor version: adcefdd71 (4.13.0)
* Installed CKEditor plugins: …

**Comment by Dumluregn** [comment]
Fails also on the newest Safari for macOS (right now 13.0.3).

**Comment by Dumluregn** [comment]
Seems like Safari went the same way as Chrome (#1070) and Opera (#1291) before and changed the way it handles excessive preceding spaces in attribute values, so the test should be adjusted.

**Comment by f1ames** [comment]
Fixed in 25c7006.
