### ISSUE TITLE
Randomly failing test - tests/plugins/image2/editing

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor4#3484]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. run test "tests/plugins/image2/editing" on iOS 13 Safari
2. Sometimes earlier tests fails, sometimes everything pass.

### Expected result

passing test

### Actual result

failing test

## Other details
![IMG_0007](https://user-images.githubusercontent.com/9017322/65498704-a847b380-debc-11e9-94fc-b0dffa114352.PNG)

* Browser: Safari (605)
* OS: iOS 13
* CKEditor version: adcefdd71 (4.13.0)
* Installed CKEditor plugins: …

**Comment by f1ames** [comment]
Verified with Safari Mobile on iOS (`14.5.1`) with `4.16.1` pre-release version and tests are green.
