### ISSUE TITLE
Randomly failing test - tests/plugins/emoji/basic

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor4#3485]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Run test "tests/plugins/emoji/basic" on iOS13 Safari
2. Test sometimes pass (usually when data are cached in browser). That's why it is highly recommended to attach a debugger and prevent reading data from the cache.

### Expected result

passing test

### Actual result

failing test

## Other details
![IMG_0006](https://user-images.githubusercontent.com/9017322/65500690-f5795480-debf-11e9-8554-835b21499a92.PNG)

* Browser: Safari ( 605 )
* OS: iOS 13
* CKEditor version: adcefdd71 (4.13.0)
* Installed CKEditor plugins: …

**Comment by f1ames** [comment]
Verified with Safari Mobile on iOS (`14.5.1`) with `4.16.1` pre-release version and tests are green.
