### ISSUE TITLE
Randomly failing test - tests/plugins/balloontoolbar/cssdefault

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor4#3486]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. It's really important to clear a cache or connect to bender with fresh domain/port! Bug appears only when the test is loaded first time. However not always.
2. Open test: "tests/plugins/balloontoolbar/cssdefault"

### Expected result

passing test

### Actual result

failing test

## Other details
![IMG_0004](https://user-images.githubusercontent.com/9017322/65505576-d089df00-dec9-11e9-9c43-e111020f4b4b.PNG)
![IMG_0008](https://user-images.githubusercontent.com/9017322/65505588-d7b0ed00-dec9-11e9-803e-96d8d8155c01.PNG)

* Browser: Safari (605)
* OS: iOS 13
* CKEditor version: adcefdd71 (4.13.0)
* Installed CKEditor plugins: …

**Comment by f1ames** [comment]
Verified with Safari Mobile on iOS (`14.5.1`) with `4.16.1` pre-release version and tests are green.
