### ISSUE TITLE
Add ACF section on PFW and PfGD fonts filtering

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4#3505]
## Type of report

Docs

## Provide a description of requested docs changes

Extracted from https://github.com/ckeditor/ckeditor4/issues/3502#issuecomment-535716735.

We advice in API docs to use ACF instead of [`pasteTools_keepZeroMargins`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-pasteTools_keepZeroMargins) (and of [`pasteFromWordRemoveFontStyles`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-pasteFromWordRemoveFontStyles) before deprecation), however there is no section in ACF docs on this (or similar topic). Since ACF is quite complex mechanism we should provide short section on how it can be achieved.

**Comment by jacekbogdanski** [comment]
Should [pasteTools_keepZeroMargins](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-pasteTools_keepZeroMargins) be a part of this docs changes? I didn't find out recommendation about using ACF instead and it looks like it won't have any effect as it trims down zero margins if the setting is not set:

https://github.com/ckeditor/ckeditor4/blob/16c60f9c79c0658f37480377f9ba91d0aec5c69a/plugins/pastetools/filter/common.js#L292-L297

**Comment by f1ames** [comment]
Fixed in https://github.com/ckeditor/ckeditor4-docs/commit/32d8604fed1b74c3a3ba54617e74f6265591e418.
