### ISSUE TITLE
Missing plugin causes content to not be rendered

### ISSUE THREAD

**Issue by JamoCA** [ckeditor/ckeditor4#3508]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1.  I manually included `pastefromgdocs` as a extraPlugins, but didn't have the supporting sub-directory in the plugins directory
2. I opened the webpage & the textarea field was hidden and the editor didn't render. An error message was in the developer console.

### Expected result

I assumed that, in the absense of a plugin, that CKEditor would try/catch and silently fail while the editor would continue to work normally or fallback to a TEXTAREA field; the missing plugin would still be reported in the developer console.  (Is there an CKEditor option to report loading fails vs abort? A visual alert would be preferable to displaying nothing.)

### Actual result

A large empty space where the TEXTAREA field or CKEditor widget would normally be displayed.  An error in the developer console states:

    Resource name "pastefromgdocs" was not found at 
    "http://mywebsite.com/CKEditor/plugins/pastefromgdocs/plugin.js?t=J5S8".
        at CKEDITOR.resourceManager.<anonymous> (ckeditor.js:268)
        at e (ckeditor.js:263)
        at Array.x (ckeditor.js:263)
        at t (ckeditor.js:263)
        at ckeditor.js:264

## Other details

* Browser: Chrome 77.0.3865.90
* OS: Windows 10
* CKEditor version: 4.12.1  (We rolled-back from 4.13 while we upgrade deprecated pastefromword options to use ACF so we can evaluate having separate rules for Word vs GoogleDocs.)
* Installed CKEditor plugins: `pastefromgdocs` was specifically enabled, but no plugin sub-directory existed.

**Comment by f1ames** [comment]
Hi @JamoCA!
This is an intended behaviour and it works like this by-design. It prevents from situations like misspelling plugin names (because error will always be thrown for non-existent plugin resources no matter if plugin with such name exists or not) or missing the fact that even though you have configured editor to use the plugin, it wasn't loaded.
Also it may protect from situations when plugin file hadn't loaded due to some server error and one was using not fully featured editor instance which resulted in e.g. malfroming user content (it's an edge case though).

Of course both approaches (throwing error or failing silently) have it's pros and cons, but the current approach is more suitable from what we have seen so far, covering various cases.

**Comment by JamoCA** [comment]
In the case where the HTML was updated & libraries rolled back, I guess I wasn't expecting it to hard fail and only display the message in the developer console.  Most end users don't know to look there for problems when reporting issues.

Since this is intentional & by design, how about adding a configurable option to allow either not hard failing and/or displaying a friendly in-your-face message to the novice, non-developer end users that are attempting to edit the content?  Without displaying something UI-wise, the user may not notice that there was editable content on the webpage.

Side note: I intentionally add try/catch to all implementations of Google Analytics client-side scripting so that ad blockers don't encounter show-stopping errors that prevent other scripts from functioning.

**Comment by f1ames** [comment]
> In the case where the HTML was updated & libraries rolled back, I guess I wasn't expecting it to hard fail and only display the message in the developer console.

Totally understand this or the situation when one may simply forget to roll back the config. From the other hand, Paste from Google Docs was introduced in `4.13` so downgrading to previous version should somehow remind of the fact that this plugin was not available earlier.

> Most end users don't know to look there for problems when reporting issues.

> how about adding a configurable option to allow either not hard failing and/or displaying a friendly in-your-face message to the novice, non-developer end users that are attempting to edit the content?

Correct editor configuration is not end user job usually, but the developer who integrates it, so he/she should make sure that everything works fine.
