### ISSUE TITLE
Failing drop test

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor4#3517]
## Type of report

Failing test

## Provide detailed reproduction steps (if any)

1. Open http://tests.ckeditor.test:1030/tests/plugins/clipboard/drop

### Expected result

All tests passes.

### Actual result

Tests from `test internal drag and drop on editors margin` group fail.

## Other details

* Browser: Firefox 69.0.1
* OS: Windows (not reproducible on other OS)
* CKEditor version: `master`

**Comment by f1ames** [comment]
Fixed in https://github.com/ckeditor/ckeditor4/commit/a9c85ea12468a5e2ddf0c8471b3814187cb15459.
