### ISSUE TITLE
Easy Image plugin conflicts with MathType

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor4#3524]
If both plugins (easyimage and wiris) are enabled, copy and paste a  MathType formula throws an error.

Reviewing the easyimage plugin we noticed that the paste event handle base64 images
and only base64 images

However, the condition easyimageplugin have to detect base64 images is the following

```
if ( !evt.data.dataValue.match( /<img[\s\S]+data:/i ) ) {
               return;
           }
```
easyimageplugin assumes that all images with a data uri scheme are a base64 images, which is not totally correct. Our images have a data uri schema, but they aren't encoded in base64, 
`data:image/svg+xml;` is ours.
I think the easyimageplugin should handle only images with the following schema  data:`[<media type>];base64`.

**Comment by f1ames** [comment]
Fixed in https://github.com/ckeditor/ckeditor4/commit/74a699f424f285543facd74a922af899278a6a36.

**Comment by LonHon** [comment]
@wwalc hello,
  I have the same use case as you, now my project can't add easyimage plugin, page reports error: "Uncaught TypeError: Cannot read property 'icons' of null"
  Could you please give me a copy of dmeo or what the following code needs to be modified, thanks.
Best wishes.

main code: 
1. download imagebase & easyimage  from this page
2. addExternal
```
  window.CKEDITOR.plugins.addExternal('imagebase', '/static/ckeditor/plugin/imagebase/', 'plugin.js');
  window.CKEDITOR.plugins.addExternal('easyimage', '/static/ckeditor/plugin/easyimage/', 'plugin.js');
```
3. 
```
CKEDITOR.editorConfig = function( config ) {
  // ... other code
  config.extraPlugins = 'imagebase, easyimage';
}
```

then i got this error: 
![image](https://user-images.githubusercontent.com/19330620/69860769-e0f77500-12d1-11ea-8dfb-384152407b3a.png)
