### ISSUE TITLE
Failing tests - tests/plugins/link/link

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4#3527]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

4 tests in `tests/plugins/link/link` fails on IE8:

![image](https://user-images.githubusercontent.com/1061942/66048817-84264b00-e52a-11e9-9f58-d78ced7a7d26.png)

Checked current `master` and `major` and tests fails on both. Not sure what we missed, but these tests were green during recent testing phase.

## Other details

* Browser: IE8
* OS: Windows 7
* CKEditor version: 4.13.0
* Installed CKEditor plugins: `link`

**Comment by f1ames** [comment]
Most probably caused by https://github.com/ckeditor/ckeditor4/commit/4b25e68d2d1ee737a3b8ae4c26044504de25fbc3 change, same as #3700.

**Comment by sculpt0r** [comment]
Already ignored. I'm closing this issue.
