### ISSUE TITLE
Img tag blacked by firewall

### ISSUE THREAD

**Issue by sujith857** [ckeditor/ckeditor4#3532]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. …img tag in ckediter used by hackers to hack on websites
2. …need to consider remove img tag or convert ckediter output to be possible to pass through post request
3. …

### Expected result

*What is the expected result of the above steps?*
Need to change img tag into any other existing format ,
### Actual result

*What is the actual result of the above steps?*
Need to change img tag into any other existing format ,
# Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by jacekbogdanski** [comment]
You can use [`editor.filter.addTransformations`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_filter.html#method-addTransformations) feature to update img tag during content filtering (e.g. when using `editor.getData`). 

If you struggle with some security issue, 

⚠️ Please **DO NOT report security issues here**, use the contact form at https://ckeditor.com/contact/ instead. ⚠️

**Comment by sujith857** [comment]
thank you
