### ISSUE TITLE
Sample page is missing meta description tag

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4#3538]
## Type of report

Task

## Provide description of the task

Since CKEditor 4 sample page is also available from our official website (https://ckeditor.com/latest/samples/index.html), it needs proper `meta` tagging. ATM meta description tag is missing, let's add it:

> Try the latest sample of CKEditor 4 and learn more about customizing your WYSIWYG editor with endless possibilities.

**Comment by msamsel** [comment]
@nzaridze
1. Should we also add meta tags related to: "open graph", "twitter", "Dublin core"?
2. Should we also add meta tags to pages located here: https://ckeditor.com/latest/samples/old/ Honestly, I'm not sure if those are indexed at all.

// cc @f1ames

**Comment by AnnaTomanek** [comment]
Ad 2: Yes, old samples should be updated, too.

**Comment by nzaridze** [comment]
@msamsel

1. Not really, in this case, our goal isn't to rank, but to optimize to show bots that the site is doing is okay.
2. Yep, we should. (It's indexed and actually it's in my seo fix list)

@f1ames 

Just ``` meta description tag ``` will be fine.

There are more links to fix. I'll create issues today.

**Comment by f1ames** [comment]
Fixed in https://github.com/ckeditor/ckeditor4/commit/44e418685bffe00fa63efa047fa777c36928e2ca.
