### ISSUE TITLE
Special Character dialog has empty elements which confuses screen readers

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4#3544]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

Screen reader should be used during below steps, however the issue is also visible without it.

1. Go to https://ckeditor.com/docs/ckeditor4/latest/examples/fullpreset.html.
2. Open "Select Special Character" dialog.
3. Navigate the screen using <kbd>Caps</kbd> + <kbd>Arrows</kbd> (screen reader virtual cursor traversing accessibility tree).

![image](https://user-images.githubusercontent.com/1061942/66294785-1a22f280-e8ea-11e9-959e-00cbcab9dee1.png)

### Expected result
​
Screen reader should navigate to the disabled text. Or empty `td` should not be there to not confuse screen readers.

### Actual result

Unable to navigate to next item using <kbd>Caps</kbd> + <kbd>Arrows</kbd> after the end of visible special character. On screen next item is disabled text on which the screen reader focus is not moving.

## Other details

The possible solution is to add `role="presentation"` attribute to empty `td` elements or just remove them.

* Browser: Checked on Chrome.
* OS: 4.5+
* CKEditor version: `full preset`
* Installed CKEditor plugins: `special character`

**Comment by Comandeer** [comment]
Fix was merged into `master` and will be released in 4.13.1.
