### ISSUE TITLE
ck editor tool bar options replaced by original text 

### ISSUE THREAD

**Issue by Crakesh19** [ckeditor/ckeditor4#3556]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. …once a new EAR is build and login to application to view ck editor , it displays as shown in image below

### Expected result :'
text should be replaced by icons

## Other details
:please find the image Url below
![Capture](https://user-images.githubusercontent.com/54285964/66428731-9b5eb000-e9e4-11e9-8892-a6627c27d046.PNG)

* Browser: … IE and Chrome
* CKEditor version: …4.12

**Comment by Crakesh19** [comment]
@engineering-this Please do help me in fixing this issue .

Thank you in advance

Regards,
Rakesh Ch

**Comment by Crakesh19** [comment]
This is not only happening with new EAR but also while using application once in a while in between.

**Comment by jacekbogdanski** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
