### ISSUE TITLE
Colordialog is incorrectly positioned when used with another dialog

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor4#3559]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open CKEditor4 sample.
2. Open color dialog using colorbutton plugin and change its position.
3. Close color dialog.
4. Add a new table to the editor.
5. Open color dialog again from cell properties dialog.

### Expected result

The color dialog is responsive, correctly positioned and overflow table properties dialog. See 4.12.1 how it worked.

### Actual result

The color dialog is hidden under the table properties dialog. The table dialog is not dimmed. The color dialog is not responsive at all.

![colorbutton](https://user-images.githubusercontent.com/10279586/66466037-483b3a80-ea82-11e9-80b7-a7e3bddd46ee.gif)

## Other details

* CKEditor version: regression provided with 4.13.0

**Comment by Dumluregn** [comment]
For the record - regression has been introduced in #2413.

**Comment by jacekbogdanski** [comment]
Closed via #3572
