### ISSUE TITLE
Empty paragraph added above the table while selecting table content using shift + arrow

### ISSUE THREAD

**Issue by mathan05** [ckeditor/ckeditor4#3560]
## Type of report

We have downloaded CKeditor and open in sample index.html. Insert the 1 row and 4 columns. While selecting from last cell to first cell using shift + arrow and cut then empty paragraph added above the table.

## Provide detailed reproduction steps (if any)

1. Insert table inside Editor with 1 row and 4 columns
2. Enter the content for all columns
3. Select the whole content from last cell to first cell with table also like long press for shift, using shift + arrow
4. Cut using Ctrl + x

### Expected result

Whole content and table should be Deleted

### Actual result

Content only Deleted and empty paragraph added above the table

## Other details

* Browser: Chrome
* OS: Windows 7
* CKEditor version: 4.11.4

**Comment by mathan05** [comment]
Anyone can please any solution regarding that issue?

**Comment by Comandeer** [comment]
I was able to reproduce the issue on 4.11.4-4.12.1 versions, however it is no longer reproducible on 4.13.0. Upgrading to the newest version of CKEditor 4 should resolve the issue.
