### ISSUE TITLE
&quot; in source text breaks browser

### ISSUE THREAD

**Issue by aimeos** [ckeditor/ckeditor4#3565]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Use source code view and enter `&quot;`
2. Save that text to the database
3. Initialize CKEditor with that text (`&quot;`) though `initialData` property

### Expected result

`"` is shown

### Actual result

Browser freezes due to high CPU load

## Other details

* Browser: Chrome, Firefox
* OS: Linux, Windows
* CKEditor version: 14.13.0 and before
* Installed CKEditor plugins: divarea, but happens also without
* Configuration:
```
this.instance = CKEDITOR.replace(1, {
	extraPlugins: 'divarea',
	initialData: '&quot;',
	autoParagraph: false,
	entities: false
});
```

**Comment by Comandeer** [comment]
Can you provide some minimal demo of the issue? I can't reproduce it: https://jsfiddle.net/Comandeer/tgbnp5ey/

Can you also show what exactly does `initialData` option do? It's not an official option.

**Comment by aimeos** [comment]
Problem wasn't CKEditor but an invalid encoding of `&quot;` in JSON data e.g.
`{"key": "&quot;"}` became `{&quot;key&quot;: &quot;&quot;&quot;}` in HTML attribute which can't parsed correctly and depending on the JS parser, this resulted in a high CPU load
