### ISSUE TITLE
Safari hangs with CKEditor 4.12.1 plugin button press

### ISSUE THREAD

**Issue by epchristi** [ckeditor/ckeditor4#3570]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

Add custom command, add a button for command, and in the _onclick handler call e.openDialog('dialogName')

var cmd = editor.addCommand('dialogCommand', {
                canUndo: true,
                modes: {
                    wysiwyg: 1,
                    source: 1
                },
                exec: customDialog_onclick
            });

            editor.ui.addButton('dialogName', {
                title: "title",
                label: "label",
                command: 'dialogCommand'
            });

### Expected result

Dialog will open

### Actual result

On Safari (only) - it hangs and the console emits 2 errors:
Only one instance of babel-polyfill is allowed
(same for WebViewJavascriptBridgeAdapter)

## Other details

Browser hangs

* Browser: … Safari
* OS: … Mac OS
* CKEditor version: … 4.12.1
* Installed CKEditor plugins: … dozens

This only manifests itself on Safari. Chrome, Edge and Firefox all work as expected.

**Comment by Comandeer** [comment]
Can you provide some more info or live demo of the issue?

CKEditor 4 does not include `babel-polyfill` by default, so it's possible that the issue is connected with some third-party plugin.

**Comment by epchristi** [comment]
I believe I tracked this down to the codemirror plugin.
