### ISSUE TITLE
Enter key example doesn't start - looks broken

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor4#3575]
## Type of report

Docs

## Provide a description of requested docs changes

Open page: https://ckeditor.com/docs/ckeditor4/latest/examples/enterkey.html
The editor should be visible on the page instead there is only a textarea element.
The editor appears when the new type of enter mode is selected.

**Comment by f1ames** [comment]
Fixed in https://github.com/ckeditor/ckeditor4-docs/commit/bc8b4c1ab6178e521cebfe5c72baa2d0b4936674.
