### ISSUE TITLE
Extra <span>'s injected on existing source mode (4.12.1)

### ISSUE THREAD

**Issue by epchristi** [ckeditor/ckeditor4#3576]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. …
Enter content as follows:
![image](https://user-images.githubusercontent.com/16124617/66799136-2c45f780-eecd-11e9-80d6-e863b542c157.png)

2. …
Then exist source mode

3. …
Then enter source mode again:
![image](https://user-images.githubusercontent.com/16124617/66799195-5f888680-eecd-11e9-9eb0-2d8b23967a17.png)

### Expected result
No extra <span>'s entered where _ is

### Actual result

We see additional spans injected where the underscore _ character is. (As per screen shot)

## Other details

* Browser: … Chrome
* OS: … Windows or Linux
* CKEditor version: … 4.12.1

**Comment by Dumluregn** [comment]
Hello! I can't reproduce this error using our [CDN](http://cdn.ckeditor.com/4.12.1/full-all/samples/). Could you share some details about your config? It seems that [Advanced Content Filter](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_advanced_content_filter.html) is heavily customised here and probably is the reason why `<span>`s appear.

**Comment by epchristi** [comment]
We do specify extraPlugins, they vary to some degree across different instances, depending on the use case.  We also set:
```
allowedContent = {  
      $1: {
           elements: CKEDITOR.dtd,
           attributes: true,
           styles: true,
           classes: true
     }
}; 

```

**Comment by epchristi** [comment]
I also tried it again with removing both of those settings and setting allowedContent = true, and it still reproduces for me.

**Comment by epchristi** [comment]
After lots of debugging tonight, I found the issue. 
`scayt_autoStartup: true
`
Feel free to close this defect. Sorry for the trouble.
