### ISSUE TITLE
When the editor has an invalid DOM id (example has ":

### ISSUE THREAD

**Issue by saw** [ckeditor/ckeditor4#3578]
## Type of report

Bug

## Provide detailed reproduction steps (if any)
In IE 11

1. Give an editor a DOM id of "foo:bar"
2. Select text
3. Attempt to insert a link

### Expected result

Text becomes a link

### Actual result

Nothing happens, "Syntax Error" appears in console

## Other details

* Browser: IE 11
* OS: Windows
* CKEditor version:  4.5.10+
* Installed CKEditor plugins: N/A

Issue is caused by removing escapeCss here: 4b6704860431d4a5b98333e494c0a838c37117b0

**Comment by jacekbogdanski** [comment]
I'm not able to reproduce the issue with the latest `4.13.0` version. As I understand, you mean use case where CKEditor target has `foo:bar` ID? As an example:

```html
<div id="foo:bar">Hello world!</div>
<script>
CKEDITOR.replace( 'foo:bar' );
</script>
```
?

**Comment by saw** [comment]
Let me try and get a full repro for you, might be in a few days

**Comment by jacekbogdanski** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
