### ISSUE TITLE
Paste from Excel in FF embeds image instead of table

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor4#3585]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open firefox
2. Copy-paste table from this excel [simple_styles.xlsx](https://github.com/ckeditor/ckeditor4/files/3738318/simple_styles.xlsx)

### Expected result

The table is copied with appropriate styles to the editor.

### Actual result

The table is copied as an image.

## Other details

The issue is not present in 4.12.1.

* Browser: Firefox
* OS: Windows10
* CKEditor version: 4.13.0
* Installed CKEditor plugins: …

**Comment by f1ames** [comment]
Fixed in https://github.com/ckeditor/ckeditor4/commit/fa31eed746af0c30d1288ed36a19284cb2cb4acc.
