### ISSUE TITLE
CKEditor 4.8 IE 11 Chinese character input: Does not detect changes until enter is pressed 

### ISSUE THREAD

**Issue by JohnCSMoodys** [ckeditor/ckeditor4#3590]
## Type of report

Bug
CKEditor 4.0 IE 11 Chinese character input: Does not detect changes until enter key is pressed 
## Provide detailed reproduction steps (if any)

IE 11 Chinese Character Input
Enter a chinese word (do not press enter)

### Expected result

*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps? The chinese character input should trigger change event in IE even without pressing the Enter key

## Other details

Browser: IE11
OS: Windows 10
CKEditor version: 4.8
Installed CKEditor plugins: Refer http://ckeditor.com/builder/2bdfbacce18d569288d65af80dfeb520

**Comment by JohnCSMoodys** [comment]
![image](https://user-images.githubusercontent.com/36516764/67239873-d7970500-f415-11e9-8048-9ddf060f5d35.png)
![image](https://user-images.githubusercontent.com/36516764/67239886-dcf44f80-f415-11e9-8618-dca9a02bbb7a.png)

**Comment by JohnCSMoodys** [comment]
Let me know if we can have a quick webex to demo the issue.

**Comment by f1ames** [comment]
Hello @JohnCSMoodys,
this is a known issue we are aware for some time. Please see the original issue report - #676. There is also a workaround provided so you may give it a try - https://github.com/ckeditor/ckeditor4/issues/676#issuecomment-510845175.

Closing this one as a duplicate.
