### ISSUE TITLE
Error when filter changes element node to text node

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor4#3593]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

https://github.com/ckeditor/ckeditor4/blob/5fa2a5b5f5b06d139ecaf8d47f5444734244e5b9/core/htmlparser/filter.js#L221-L223
`onText` and `onComment` methods requires 3 arguments to work correctly, which are not passed to the method call

### Expected result

There is no error when the filter changes the element node to the text node or the comment node.

### Actual result

Error

## Other details

* Browser: All
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by Comandeer** [comment]
Merged into 4.13.1.
