### ISSUE TITLE
Move selected text inside Source Dialog

### ISSUE THREAD

**Issue by pan1982** [ckeditor/ckeditor4#3595]
I cant drag selected text in the opened Source dialog. Why so?
You can check on this page 
https://ckeditor.com/docs/ckeditor4/latest/examples/inline.html

**Comment by msamsel** [comment]
We would like to help solve your issue but it seems you have missed our [template for bug reports](https://github.com/ckeditor/ckeditor4/blob/major/.github/ISSUE_TEMPLATE/1-bug-report.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_issues_readme.html#avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.
