### ISSUE TITLE
Uncaught TypeError: Cannot read property gwfInjected of undefined

### ISSUE THREAD

**Issue by epchristi** [ckeditor/ckeditor4#3602]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

While using CKEditor I opened an editor instance that caused a console error:
ckeditor.js?D202:813 Uncaught TypeError: Cannot read property 'gwfInjected' of undefined
 at Object.<anonymous> (ckeditor.js?D202:813)
    at Object.l (ckeditor.js?D202:10)
    at Object.fire (ckeditor.js?D202:12)
    at a.<anonymous> (ckeditor.js?D202:365)
    at a.l (ckeditor.js?D202:10)
    at a.<anonymous> (ckeditor.js?D202:12)
    at a.CKEDITOR.editor.CKEDITOR.editor.fire (ckeditor.js?D202:13)
    at a.fireOnce (ckeditor.js?D202:12)
    at a.CKEDITOR.editor.CKEDITOR.editor.fireOnce (ckeditor.js?D202:13)
    at Object.<anonymous> (ckeditor.js?D202:287)

### Expected result

No Errors

### Actual result

Error above ^^^

## Other details

* Browser: … Chrome
* OS: … Windows 10
* CKEditor version: … 4.13
* Installed CKEditor plugins: … 
panel,floatpanel,listblock,button,richcombo,a11yfirsthelp,menu,menubutton,a11yheading,dialogui,dialog,a11yhelp,fakeobjects,a11ylink,removeformat,a11ystylescombo,about,textwatcher,autocomplete,autogrow,basicstyles,bidi,blockquote,ckeditor-gwf-plugin,ckeditorfa,notification,toolbar,clipboard,codemirror,xml,ajax,lineutils,widgetselection,widget,codesnippet,codesnippetgeshi,panelbutton,colorbutton,colordialog,contextmenu,copyformatting,devtools,dialogadvtab,div,wysiwygarea,docprops,elementspath,enterkey,entities,popup,filetools,filebrowser,find,flash,floatingspace,font,format,horizontalrule,htmlwriter,iframe,indent,indentblock,indentlist,justify,language,lineheight,link,list,liststyle,magicline,maximize,pastefromexcel,pastetools,pastefromgdocs,pastefromword,pastetext,placeholder,preview,resize,scayt,selectall,showblocks,showborders,simplebutton,smiley,sourcearea,sourcedialog,specialchar,stylescombo,stylesheetparser,tab,table,tabletools,tableresize,tableselection,templates,uicolor,undo,wsc,dropdownmenumanager,notificationaggregator,uploadwidget,symbol,textselection

**Comment by epchristi** [comment]
* (3) https://ckeditor.com/cke4/builder/download/824434181c9c782e8fd8fe5a7c255d60

**Comment by epchristi** [comment]
CKEDITOR.plugins.add("ckeditor-gwf-plugin", {
        popup: null,
        fontLabel: null,
        init: function(a) {
            a.config.gwfplugin = a.config.gwfplugin || {
                font: {},
                cancel: {},
                ok: {},
                message: {}
            };
            a.config.gwfplugin.font = a.config.gwfplugin.font || {};
            a.config.gwfplugin.cancel = a.config.gwfplugin.cancel || {};
            a.config.gwfplugin.ok = a.config.gwfplugin.ok || {};
            a.config.gwfplugin.message = a.config.gwfplugin.message || {};
            this.fontLabel = a.config.gwfplugin.font.label || "GoogleWebFonts";
            this.popup = this.popUp(a.config);
            var b = this;
            CKEDITOR.on("instanceReady", function(c) {
                if (!c.editor.ui.instances.Font.gwfInjected) {

**Comment by msamsel** [comment]
The plugin you are referring to is a third-party one, and it is not maintained by CKSource. Since we cannot fix issues with the code that does not belong to us, we are unable to help solve your issue. Please redirect your question to the plugin’s author who should be able to review the problem and suggest a solution.

If, however, after contacting the plugin’s maintainer you find out the issue lies on the editor’s side, and you can provide a test case file showing the problem, we will be happy to have a look at it.
