### ISSUE TITLE
[SEO] CKE4 Docs pages have wrong canonical points

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor4#3603]
Wrong: https://ckeditor.com/docs/examples/latest/examples/fileupload.html
Correct: https://ckeditor.com/docs/ckeditor4/latest/examples/fileupload.html

There are more CKEditor 4 pages with a similar issue (at least all examples).

**Comment by msamsel** [comment]
Canonical paths are created by Umberto automatically. That's why we won't be able to make anything to fix it on our side.

**Comment by f1ames** [comment]
Closing as it needs to be fixed in Umberto as mentioned in previous comment.

**Comment by f1ames** [comment]
Reopening so we have an eye on this issue.

**Comment by f1ames** [comment]
Issue in Umberto was fixed, we just need to wait for new Umberto version release and check if it works as intended.

**Comment by f1ames** [comment]
Docs with updated Umberto version already deployed.
