### ISSUE TITLE
Plugin downloads sporadically failing when IPv6 is not supported

### ISSUE THREAD

**Issue by rjgwiz** [ckeditor/ckeditor4#3605]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

This may not necessarily be a bug -- I wanted to report this issue in case others are experiencing the same problem.

When downloading ckeditor plugins, as opposed to an entire [ckeditor4 release](https://github.com/ckeditor/ckeditor4/releases), I have been seeing sporadic download timeouts errors over the past week (beginning on 10/21).

I am experiencing this issue primarily in Travis CI, with Ubuntu Linux, because [Travis does not support IPv6](https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system).

This is similar to #1294, but without timeout errors instead of `Content-Length mismatch` errors.

I think the sporadic nature is downloads work over IPv4 and fail on IPv6 though I'm not sure what dictates which version is used.

I believe I verified IPv6 usage via command `$ host ckeditor.com`

### Expected result

Dependencies are downloaded from https://download.ckeditor.com/.

### Actual result

Download times out, times out again on retry, then fails.

I've experienced the issue with bower and separately with composer.

bower results:

> [16:26:42] bower retry Download of https://download.ckeditor.com/autogrow/releases/autogrow_4.7.2.zip failed with ETIMEDOUT, retrying in 15.3s
> [16:27:27] bower error ETIMEDOUT

composer results (via [drupal/webform](https://www.drupal.org/docs/8/modules/webform/webform-frequently-asked-questions/how-to-use-composer-to-install-libraries)'s `composer.libraries.json`):
>   [Composer\Downloader\TransportException]                                     
>  The "https://download.ckeditor.com/autogrow/releases/autogrow_4.11.4.zip" file could not be downloaded: failed to open stream: Connection timed out     

## Other details

- Travis virtualization environment used: https://docs.travis-ci.com/user/reference/xenial/
- Travis CI IPv6 related issue: https://github.com/travis-ci/travis-ci/issues/8361 (several related issues listed in comments)
- Potential work around:
  - Disable IPv6 in `.travis.yml`: https://github.com/travis-ci/travis-ci/issues/8361#issuecomment-350497804

**Comment by jacekbogdanski** [comment]
@vokiel could you take a look?

**Comment by rjgwiz** [comment]
In `.travis.yml`, adding this command under `before_install` to disable IPv6 seems to reliably prevent the timeout errors:

```
sudo sh -c 'echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6'
```

My other branches without the above are still failing today, and my dev branch with the above hasn't failed once in ~7 days

**Comment by jacekbogdanski** [comment]
@rjgwiz thank you for your research. I believe it may be very useful for everyone experiencing the issue with Travis timeouts.

As far as I know, we didn't notice such timeouts using Travis during our normal workflow, so I would be rather skeptical about disabling IPv6 in Travis by default - but if the issue shows up in the future, it may be a good option to consider.

As for now, as I understand you solved the issue on your side, so I'm closing the ticket. However, if you consider it as a CKEditor4 testing environment bug, please share your thoughts so we can reopen this ticket again.
