### ISSUE TITLE
Links pasted to ckeditor table cell (copied from excel) adds new row to table and link not opening in new tab/window

### ISSUE THREAD

**Issue by Vivek2393** [ckeditor/ckeditor4#3618]
## When user creates table in ckeditor and paste link from excel to table cell. A new Row is added in table and link is not pasted with target="_blank"

Bug

## Provide detailed reproduction steps (if any)

1. User creates new table in ckeditor.
2. User copy link from excel and paste it to ckeditor table cell.

### Expected result

*Pasted link should open in new window/tab i.e. target="_blank" & new row should not get added to table. *

### Actual result

*A new row gets added to table and link is pasted without target="_blank" attribute.

## Other details

* Browser: Chrome, I.E, FF
* OS: Windows 8/10
* CKEditor version: 4.11.4
* Installed CKEditor plugins: …

**Comment by Comandeer** [comment]
The content pasted from Excel is inside table and it causes to be treated as every other pasted table when Table Selection plugin is enabled: it inserts all rows from pasted table into the existing one. This behaviour can be disabled by disabling Table Selection plugin.

Additionally Excel does not pass any information about how the link should be opened, so such information is not inserted by CKEditor 4.

**Comment by Vivek2393** [comment]
Hello  @Comandeer,
 But it gets pasted differently when same content pasted from Excel to ckeditor table cell (1*1) and different for (1*2). And it goes on alternatively.

![ckeditorLink](https://user-images.githubusercontent.com/34581373/68672818-695ae380-0578-11ea-9ec0-9332c249f3f1.gif)

How can we prevent creation of new row below on paste of link?

**Comment by Comandeer** [comment]
The only way for disabling such behaviour is to disable Table Selection plugin.

**Comment by Vivek2393** [comment]
Hello @Comandeer Table Selection plugin is already not used.
And issue is still reproduced.

**Comment by Vivek2393** [comment]
@Comandeer can you please assist more on this. 
We are not using Table Selection plugin.
How can we get rid of this issue?

**Comment by Comandeer** [comment]
Table Selection plugin seems to be present in the editor from the screenshot, as the table cell is selected in a specific way (with dark blue background). You can use [`removePlugins` config option](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-removePlugins) to force disabling it. Without Table Selection plugin I can't reproduce the issue.
