### ISSUE TITLE
cursor stops blinking after drag and drop

### ISSUE THREAD

**Issue by adriancioclei** [ckeditor/ckeditor4#3619]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open in Chrome: https://ckeditor.com/ckeditor-4/demo/#inline
2. Drag and drop any text from inside or outside the editor area (from the current page)

Variant:
1. Open in Chrome: https://ckeditor.com/ckeditor-4/demo/#document
2. Drag and drop any text from outside the editor area (from the current page)

### Expected result

After paste the cursor should blink.

### Actual result

The cursor doesn't blink.

## Other details

* Browser: Chrome
* OS: Windows
* CKEditor version: v4.13.0
* Installed CKEditor plugins: default

**Comment by Comandeer** [comment]
This is confirmed bug in Blink: https://bugs.chromium.org/p/chromium/issues/874830
