### ISSUE TITLE
Content pasted from PowerPoint is converted to image

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor4#3625]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Create some PowerPoint document.
2. Copy text from one of the slides.
3. Paste into CKEditor 4.

### Expected result

Content is pasted as a text.

### Actual result

The image of the copied content is pasted.

## Other details

The issue is probably connected with the fact that Office applications attaches screenshot of copied content to the clipboard data.

* Browser: Firefox
* CKEditor version: 4.13.0
* Installed CKEditor plugins: clipboard

**Comment by msamsel** [comment]
probably related to #3585

**Comment by f1ames** [comment]
Fixed in https://github.com/ckeditor/ckeditor4/commit/fa31eed746af0c30d1288ed36a19284cb2cb4acc.
