### ISSUE TITLE
Add more features to the spreadsheest sample

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor4#3628]
https://ckeditor.com/docs/ckeditor4/latest/examples/spreadsheets.html

use reasonably a similar setup to the one in https://ckeditor.com/ckeditor-4/spreadsheets/
(e.g. use two lines toolbar)
 
Make sure the following features are available, among many other:
 - paste from word/excel with formatting
 - tables
 - magicline

**Comment by Comandeer** [comment]
Closed in ckeditor/ckeditor4-docs#268.
