### ISSUE TITLE
Failing test - tests/core/editable/misc (since FF 70)

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor4#3633]
## Type of report

Failing test

## Provide detailed reproduction steps (if any)

1. Run test `tests/core/editable/misc`.

### Expected result

Test passes.

### Actual result

3rd and 4th test cases fail:

<img width="580" alt="Screenshot 2019-11-07 at 16 04 30" src="https://user-images.githubusercontent.com/10883184/68400458-6034d580-0178-11ea-8d32-f430797c2140.png">

## Other details

The issue was introduced in FF 70.

* Browser: Firefox 70
* OS: macOS
* CKEditor version: `4.13.0`

**Comment by jacekbogdanski** [comment]
Closed via #3643
