### ISSUE TITLE
Add CKEDITOR.plugins.clipboard.dataTransfer#getTypes method

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor4#3634]
## Type of report

Task

## Provide description of the task

There are sometimes need to check what types are actually inside pasted data. `CKEDITOR.plugins.clipboard.dataTransfer#getTypes` will do exactly that: return the array of pasted types!

**Comment by f1ames** [comment]
Fixed in https://github.com/ckeditor/ckeditor4/commit/fa31eed746af0c30d1288ed36a19284cb2cb4acc.
