### ISSUE TITLE
Trying to open the dialog for the second time when it's already opened causes dialog cover to stay after dialog closing

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor4#3638]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Go to [CDN](http://cdn.ckeditor.com/4.13.0/full-all/samples/)
2. Execute `CKEDITOR.instances.editor.execCommand( 'link' )` twice 
3. Close the dialog

### Expected result

Dialog is closed and editor is available

### Actual result

Dialog cover stays after closing dialog, editor is unavailable

## Other details

This behaviour was introduced in #2413. Before it was also broken, but in different way - after calling dialog for the second time it has been hiding behind cover.

* Browser: all
* OS: macOS
* CKEditor version: `4.13.0`
* Installed CKEditor plugins: `dialog`

**Comment by Comandeer** [comment]
The behaviour is back to the old way of being broken – after opening dialog for the second time, it hides under the overlay. It seems that c612866 reintroduced it.

**Comment by Dumluregn** [comment]
Closed with https://github.com/ckeditor/ckeditor4/pull/4688.
