### ISSUE TITLE
Find And Replace dialog does not search content if Match Cyclic checkbox is unchecked

### ISSUE THREAD

**Issue by kapilgupta77** [ckeditor/ckeditor4#3651]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open any CKEditor sample, say https://ckeditor.com/docs/ckeditor4/latest/examples/fullpreset.html
2. Place cursor at start of content and open find dialog
3. Uncheck match cyclic checkbox and search for a word which is not in the document, say Apollo123
4. Dialog will throw message that specified text was not found
5. Now search for text Apollo which is in the document
### Expected result
 The word Apollo should be selected in editor
*What is the expected result of the above steps?*

### Actual result
Message is shown that specified text was not found
*What is the actual result of the above steps?*

## Other details

* Browser: Chrome
* OS: Windows
* CKEditor version:4.13.x
* Installed CKEditor plugins: Full preset sample

**Comment by Dumluregn** [comment]
Hello,
despite this behaviour is a little bit archaic, in fact it's correct. That's because if you deselect `match cyclic`, after the first search there is no more content in editor to search, so any search will show nothing. Still, we could change it to avoid such an awkward situations.
