### ISSUE TITLE
MS Edge (Chromium based) support

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4#3655]
## Type of report

Task

## Provide description of the task

Borrowed part of the description from https://github.com/ckeditor/ckeditor5/issues/5739 (thx @mlewand !) since it's the same issue.

---

Now that MS Edge Chromium is in release candidate phase, and the [official release date has been set to the 15th of January](https://blogs.windows.com/msedgedev/2019/11/04/edge-chromium-release-candidate-get-ready/#SERvfCOZorrWXtWx.97), we can start thinking about the support strategy for Edge.

It make sense to make some sort of compatibility testing. I believe it will act pretty much like Chrome, so it should work well with CKEditor 4. There is also [beta available for download](https://www.microsoftedgeinsider.com/pl-pl/download). 

Surely we'll have to update [browser support](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_browsers.html#officially-supported-browsers) docs accordingly. Since for mobiles we support "official/bundled" browsers (Chrome on Android, Safari on iOS) there is no need to change mobile section.

I believe Edge (Chromium) and old Edge (IE-based) can exist side by side. Also Edge (Chromium) will provide IE Compatibility Mode which should be taken into consideration too. It's unclear what will be the default browser in Win10 - so we should check that too. Knowing that we might determine our support strategy for Edge (IE).

After that we should review existing edge issues and re-triage these accordingly.

**Comment by Dumluregn** [comment]
During testing phase there was indeed no difference between new Edge and Chrome (I conducted unit tests on both dev and built version and manuals on all presets). Can we consider it done then?

**Comment by f1ames** [comment]
Good job @Dumluregn :+1: I wonder if we should adjust our [Browser Compatibility docs](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_browsers.html#officially-supported-browsers) somehow. 

Now it says, latest Edge which make sense meaning that we can slowly move away from edgeHTML based Edge versiosn. OTOH edgeHTML based Edge is also supported so we could mention that too :thinking: 

@Dumluregn I suggest to close this issue as done and extract the docs follow-up, WDYT?

**Comment by Dumluregn** [comment]
Sounds right 👍 I'll create an issue.
