### ISSUE TITLE
Uncaught TypeError: CKEDITOR.tools.throttle is not a function     at new TextWatcher (plugin.js?t=FB9E:157)

### ISSUE THREAD

**Issue by Tectract** [ckeditor/ckeditor4#3658]
## Type of report

Bug

CKEDITOR.tools.throttle is not a function, error kicking up from textwatcher / autocomplete / emoji plugins. I'm trying to get the emoji plugin working, which relies on autocomplete, which relies on textwatcher...

## Provide detailed reproduction steps (if any)

using textwatcher plugin, seems that ckeditor.tools.throttle is throwing a halting error

### Expected result

no error

### Actual result

error

## Other details

* Browser: …
* OS: …
* CKEditor version: 4.11-4.13
* Installed CKEditor plugins: html5video,widget,widgetselection,clipboard,lineutils,dialog,dialogui,notification,toolbar,button,textmatch,textwatcher,xml,panel,autocomplete,ajax,panelbutton,floatpanel,emoji

**Comment by msamsel** [comment]
Hi,

I cannot reproduce the error. Please take a look at samples:
http://cdn.ckeditor.com/4.13.0/full-all/samples/old/emoji/emoji.html
You can type in browser's console `CKEDITOR.tools.throttle` and you'll see the function is available.

Please provide extender reproduction steps or some demo website.

**Comment by Tectract** [comment]
oops this ticket was supposed to be in the ckeditor-rails repo...

**Comment by msamsel** [comment]
@Tectract no problem. I've closed it in such case :)

**Comment by kruzalmighty** [comment]
Change ckeditor.js version
<script src="http://cdn.ckeditor.com/4.13.0/full-all/ckeditor.js"></script>
