### ISSUE TITLE
Unable to paste image to ckeditor. Issue specific to Chrome. 

### ISSUE THREAD

**Issue by Vivek2393** [ckeditor/ckeditor4#3659]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Right click on any image and select copy.
2. Open ckeditor in chrome.
3. Right click and paste  to ckeditor.

### Expected result

Image should get pasted in ckeditor

### Actual result

Nothing happens

## Other details

* Browser: CHROME
* OS: Win 10/8
* CKEditor version: 4.11.4
* Installed CKEditor plugins:

**Comment by Comandeer** [comment]
It's an upstream issue: https://bugs.chromium.org/p/chromium/issues/detail?id=316472
