### ISSUE TITLE
How to prevent CKEditor from stripping < and > (greater-than/less-than) symbol

### ISSUE THREAD

**Issue by vilassagar26** [ckeditor/ckeditor4#3674]
Object Descriptions with ">" or "<" causes "Random" Text

Expected result is I can use < or > symbol in my editor .

My config Setting is

CKEDITOR.editorConfig = function (config) {
// Define changes to default configuration here.
// For complete reference see:
// http://docs.ckeditor.com/#!/api/CKEDITOR.config

config.htmlEncodeOutput = true;
}

**Comment by msamsel** [comment]
duplicate #3673
