### ISSUE TITLE
Automatic addition of <div id="i4c-dialogs-container">&nbsp;</div> in the CKEditor upon clicking "Source" everytime in latest Chrome (Version 78.0.3904.108). Please help

### ISSUE THREAD

**Issue by jeyanthit** [ckeditor/ckeditor4#3683]
## Provide detailed reproduction steps (if any)

1. …
2. …
3. …

### Expected result

*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by jeyanthit** [comment]
![CKEditor](https://user-images.githubusercontent.com/33976344/69612296-84067f80-1083-11ea-9bbe-de5d90ebce24.jpg)

**Comment by jacekbogdanski** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.
