### ISSUE TITLE
Can't change dialog tabs with arrows after focusing with mouse

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor4#3689]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open dialog with some navigation tabs, for example link dialog here: https://ckeditor.com/latest/samples/index.html
2. Use mouse click to focus one of the navigation tabs
3. Try to use left and right arrows to switch navigation tabs.
4. Start pressing TAB button to move focus to navigation tab
5. When focus reach the navigation tab, try to use left and right arrows to switch navigation tab

### Expected result

Focusing navigation tab by mouse click and by tab key, should allow on switching tab with arrow keys.

### Actual result

Only focusing on navigation tabs by keyboard allows on switching navigation tab with left and right arrow.

## Other details

* Browser: All
* OS: MacOS
* CKEditor version: 4.13.0
* Installed CKEditor plugins: …

**Comment by f1ames** [comment]
Fixed with https://github.com/ckeditor/ckeditor4/commit/1ff8ee2f5401424a59c87840e201842df111399e.
