### ISSUE TITLE
Memory leak after having multiple inline editor instances of ckeditor

### ISSUE THREAD

**Issue by RubyGeorge** [ckeditor/ckeditor4#3690]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Created a standalone page 
2. Multiple instances of inline editors were created (15 in this case)
3. Destroy all the instances

### Expected result

The memory usage remains the same as when the page was loaded

### Actual result

There is an increase in memory usage
![image](https://user-images.githubusercontent.com/13714665/69794599-8e925780-11f0-11ea-9e81-da02bd88fc38.png)
Not sure if ticket #1770 is connected to this.
Could note that several instances of CKEDITOR.filter, ui, commands were deattached but retrieved in the page.

## Other details

* Browser: Chrome 78.0
* OS: Windows 10
* CKEditor version: 4.13
* Installed CKEditor plugins: none

**Comment by f1ames** [comment]
Hello @RubyGeorge,
as you mentioned we have covered memory leaks issues in #1770 and #2969 (more generic fix here). AFAIR editor instance initially takes some resources which are not freed after destroying all instances - this is mentioned in https://github.com/ckeditor/ckeditor4/pull/2969#pullrequestreview-217354643: 

> > First editor takes plenty of memory which is not released, but most of it is reused by next editors.
>
> I think it is caused by some shared resources and additional scripts which are loaded on editor creation. This resources are reused so we shouldn't try to remove them on destroying editors (because they will need to be loaded again which slows down significantly editor creation).

So I think that might be the case here. If you create X inline editor instances then destroy them and check heap snapshot and do the same again - both heap snapshots after destroying editors should be of very similar size (this way you can check for memory leaks apart from some initial resources which were loaded). Please also keep in mind that GC is non-deterministic so the best way to test it is to force it manually via browser dev console.

**Comment by Dumluregn** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
