### ISSUE TITLE
Emoji plugin jumps like monkeys on mobile 

### ISSUE THREAD

**Issue by teddydoors** [ckeditor/ckeditor4#3695]
* Browser: Google chrome
* OS: Android (Sony XA Ultra)
* CKEditor version: 4.13 
* Installed CKEditor plugins: Emoji 4.13

**Comment by Comandeer** [comment]
Can you provide some more info? Because for now it sounds intriguing, but there aren't enough details…

**Comment by Dumluregn** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
