### ISSUE TITLE
Outdated "npm install --save ckeditor" after NPM package renaming

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4#3697]
## Type of report

Docs

## Provide a description of requested docs changes

Should be

```
npm install --save ckeditor4
```

Quick start guide is outdated (https://ckeditor.com/docs/ckeditor4/latest/guide/dev_installation.html) and Package Managers guide (https://ckeditor.com/docs/ckeditor4/latest/guide/dev_package_managers.html). We should scan entire docs to check if there are no more outdated places and fix them.

**Comment by Dumluregn** [comment]
[ckeditor4-docs#277](https://github.com/ckeditor/ckeditor4-docs/pull/277)

**Comment by f1ames** [comment]
Fixed in https://github.com/ckeditor/ckeditor4-docs/commit/05cb4b780758fa4379cc65cbfcaac2f2041b72e8.
