### ISSUE TITLE
Some of "plugins/forms" unit tests fails on IE8

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4#3700]
## Type of report

Failing tests

## Provide description of the task

![image](https://user-images.githubusercontent.com/1061942/70036109-60c45e80-15b4-11ea-9705-fb389f070fae.png)

The error is `'type' is null or not an object`, the same as in #3527 so it might be related (the cause might be the same).

## Other details

* Browser: IE8
* OS: Windows 7
* CKEditor version: `4.13`
* Installed CKEditor plugins: -

**Comment by Comandeer** [comment]
Seems like https://github.com/ckeditor/ckeditor4/commit/4b25e68d2d1ee737a3b8ae4c26044504de25fbc3 is guilty.

**Comment by f1ames** [comment]
Probably the same fix could be applied to #3257 as it seems like the same issue.

**Comment by f1ames** [comment]
Also `tests/plugins/placeholder/dialog` fails with the same error (and same cause most probably).

**Comment by sculpt0r** [comment]
I've rerun this one a few times and everything is fine. Looking at the numbers and those tests code - they are already ignored. So, currently, we can close this issue.
