### ISSUE TITLE
Typing in source area throws error

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor4#3704]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open sample with source area plugin.
2. Open dev console.
3. Click the source area button.
4. Start typing.

### Expected result

Error is thrown inside the console:
![image](https://user-images.githubusercontent.com/10279586/70064343-a9e2d580-15e9-11ea-97cf-ec26a423cafe.png)

### Actual result

No console errors.

## Other details

Invalid commit caused regression: https://github.com/ckeditor/ckeditor4/commit/d633573567628308391da5a5f29e1a35e55b9b33

* CKEditor version: 4.13.1

**Comment by f1ames** [comment]
Fixed with https://github.com/ckeditor/ckeditor4/commit/e9c2070c8d3ae68e662159fc83abd965c765b5c1.
