### ISSUE TITLE
Safari incorrectly removes blocks after selecting all

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor4#3705]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open https://jsfiddle.net/Comandeer/jnf5at6z/
2. Open console.
3. Click "Extract HTML" button.

### Expected result

`<p><br></p>` is logged.

### Actual result

`<div><br></div><p><br></p>` is logged.

## Other details

It seems that Safari, instead of just deleting both blocks, removes their content and preserves blocks.

* Browser: Safar
* OS: macOS
* CKEditor version: 4.13.0

**Comment by f1ames** [comment]
Breaking commit https://github.com/ckeditor/ckeditor4/commit/06b94a64713e34ae8cb41196f2ce00618468a76a.

**Comment by f1ames** [comment]
It looks like (from review) that this change could be only applied to FF browser - https://github.com/ckeditor/ckeditor4/pull/3213#issuecomment-524658321:

> ## Firefox cases
>
> It looks like adding `skipBogus = true` to call on [range.shrink](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_dom_range.html#method-shrink) solved the issue.

However, it should be carefully investigated.
