### ISSUE TITLE
The alignment of images affects the layout of the page

### ISSUE THREAD

**Issue by 99Kies** [ckeditor/ckeditor4#3708]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. edit (left justifying, And this is also true of right alignment) 
![edit](https://user-images.githubusercontent.com/45918704/70111230-8de44000-168c-11ea-8695-05be65723b6a.png)

2. done
![done_1](https://user-images.githubusercontent.com/45918704/70111316-c84ddd00-168c-11ea-8677-cc9c9f81de2f.png)
![done2](https://user-images.githubusercontent.com/45918704/70111321-ca17a080-168c-11ea-93ac-4101917d09e4.png)

### Expected result

*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: Chrome
* OS: Windows10/Ubuntu16.04
* CKEditor version: 0.4.3
* Installed CKEditor plugins: from pip install

**Comment by Comandeer** [comment]
By default images are aligned using `float` inline style. If you use Enhanced Image (`image2`) plugin, you can [switch to using classes](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-image2_alignClasses) instead.
