### ISSUE TITLE
Performance Bug with scayt_autoStartup​ and pastebase64

### ISSUE THREAD

**Issue by lfoster-pcg** [ckeditor/ckeditor4#3711]
Bug

We are using integration with CKEditor 4.13 and our own spellex server.  We are implementing new functionality that allows a user to drag / drop or paste an image into the CKEditor field and are encountering a performance issue.  CKEditor is being started with the scayt_autoStartup​: true and grayt_autoStartup: true parameters.  ​The CKEditor field attempts to send the contents of the content editable div to the grammar check server to be checked, which is very slow as it's sending several KB of base 64 encoded image data when an image is pasted.  We've tried using the scayt_elementsToIgnore ​option to skip img tags, but that appears to pass a parameter to the Spellex server for what words to ignore but still send the full contents of the content editable div to be spelling / grammar checked.  Is there a way to specify elements within the content editable div that should not be sent to the spell check / grammar check server at all?  ​

### Expected result

Ignored elements do not get forwarded to the spelling / grammar check server at all.

### Actual result

Base64 encoded image data is sent to the spelling / grammar check server along with a parameter that img text should be ignored.

## Other details

* Browser: Any
* OS: Any
* CKEditor version: 4.13
* Installed CKEditor plugins: pastebase64, scayt

**Comment by Comandeer** [comment]
Both SCAYT and WSC are third party plugins developed by the [WebSpellChecker](https://github.com/webspellchecker) organization.

Please report ticket directly in [SCAYT](https://github.com/WebSpellChecker/ckeditor-plugin-scayt) or [WSC](https://github.com/WebSpellChecker/ckeditor-plugin-wsc) repositories.
