### ISSUE TITLE
The Package ckeditor didnt work on laravel 6

### ISSUE THREAD

**Issue by amrullahdev** [ckeditor/ckeditor4#3712]
## Type of report
 The Package ckeditor didnt work on laravel 6
Task
  please make it posible for package to install on laravel 6
## Provide description of the task

*What steps should be taken to fulfil the task?*

## Other details

* Browser: ...
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by f1ames** [comment]
Hello @amrullahdev,
do you use official Composer package - https://packagist.org/packages/ckeditor/ckeditor or some different way to add CKEditor 4 to your Laravel 6 project? What is the exact issue?

**Comment by jacekbogdanski** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
