### ISSUE TITLE
Failing tests /tests/plugins/pastetools/filter/parsestyles

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor4#3713]
## Type of report

Failing test

The whole test suite is failing `/tests/plugins/pastetools/filter/parsestyles`.

Also, see https://github.com/ckeditor/ckeditor4/issues/3424

* Browser: Edge
* CKEditor version: 4.13.1

**Comment by Dumluregn** [comment]
This issue is no longer reproducible in the latest Edge browser version.
