### ISSUE TITLE
Randomly failed test - /tests/plugins/image2/link

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor4#3716]
## Type of report

Failing tests (build version)

## Provide detailed reproduction steps (if any)

tests randomly failes under IE9
* `/tests/plugins/image2/link#tests%2Fplugins%2Fimage2%2Flink%20test%20link%20in%20figcaption`
* `/tests/plugins/image2/link#tests%2Fplugins%2Fimage2%2Flink%20test%20link%20bare%20widget%20(link%20dialog)%3A%20inline%2C%20none`

![Screenshot 2019-12-05 at 12 56 32](https://user-images.githubusercontent.com/9017322/70236255-e129c180-1764-11ea-9fab-38f738096f56.png)
![Screenshot 2019-12-05 at 12 56 11](https://user-images.githubusercontent.com/9017322/70236258-e1c25800-1764-11ea-8bdf-cd6abba25dd1.png)

### Expected result

passing tests

### Actual result

Failing tests

## Other details

* Browser: IE9
* OS: Windows7
* CKEditor version: 4.13.1
* Installed CKEditor plugins: …

**Comment by Dumluregn** [comment]
As this test wasn't reported to fail in the two last testing phases, I'm closing this issue.
