### ISSUE TITLE
Failing tests on CI tests/plugins/emoji/dropdown

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor4#3744]
## Type of report

Failing test

## Provide description

Tests from `tests/plugins/emoji/dropdown` are failing regularly. They seem to pass when run outside Travis CI. See also https://github.com/ckeditor/ckeditor4/issues/3407 for some hints.

![image](https://user-images.githubusercontent.com/10279586/71104805-b0ae4280-21bc-11ea-9264-a2ad9a695ba8.png)
![image](https://user-images.githubusercontent.com/10279586/71104836-bb68d780-21bc-11ea-84ab-03385040b684.png)

https://travis-ci.org/ckeditor/ckeditor4/jobs/625681191?utm_medium=notification&utm_source=github_status

## Other details

* Browser: Chrome
* OS: Travis CI
* CKEditor version: 4.14.0 built

**Comment by msamsel** [comment]
I just remain the note to not forget. Error related to `'getSelectedElement'` are not related to emoji test fail.
Those errors look that is thrown from other test suites which pass.

**Comment by msamsel** [comment]
It seems that mouse cursor on CI triggered mousemove event 😱.
After adding an overlay to this test case, which hides emoji dropdown underneath, the tests start to work.
