### ISSUE TITLE
Copy Format is not working as expected

### ISSUE THREAD

**Issue by peorth80** [ckeditor/ckeditor4#3756]
Bug

We found a bug on the Copy Format functionality

## Provide detailed reproduction steps (if any)

1. Go to the demo page https://ckeditor.com/ckeditor-4/demo/#document
2. Add Bold and Italic to one of the words
3. Click on Copy Format on that word
4. Click on another unformatted word to paste the format

![CKEditor_bug](https://user-images.githubusercontent.com/16003799/71728833-fa359900-2e1c-11ea-8518-ffaaf9b313a5.gif)

### Expected result

The format is pasted correctly, without the white space on the left

### Actual result

The pasted format is not correct, it shows an extra space to the left. See attached GIF file.

## Other details

* Browser: Chrome, Firefox, Edge (all of them)
* OS: Windows
* CKEditor version: Last version 
* Installed CKEditor plugins: Whatever is loaded on the DEMO page at https://ckeditor.com/ckeditor-4/demo/#document

**Comment by jacekbogdanski** [comment]
I tried to reproduce the issue on Chrome, Firefox, and Edge both Windows 10 and Linux Fedora 31 with no success. Are there some additional steps that could cause the issue? Are you able to reproduce the issue outside https://ckeditor.com/ckeditor-4/demo/#document demo?

![copyformat](https://user-images.githubusercontent.com/10279586/71962489-d34edc80-31f9-11ea-82a0-7524811f1245.gif)

**Comment by Dumluregn** [comment]
Hi, the white space appears because you copy format from the indented paragraph. The margin style is inherited from \<p> element, and when you apply formatting in different place it also adds margin. It's a by-design solution.
