### ISSUE TITLE
Unify GH labels between integration repositories

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor4#3758]
## Type of report

It would be nice to have unified labels between integration repositories like React, Angular, etc to reflect the one available for `ckeditor/ckeditor4` repository keeping the same names and colors. It would speed up a bit process of confirming issues. Of course, redundant labels like for plugins, etc should be skipped, so only labels needed for the given integration.

**Comment by Dumluregn** [comment]
:+1:  
I guess the most useful would be unifying `type:*`, `status:*` and `resolution:*` labels.

**Comment by f1ames** [comment]
Already fixed.
