### ISSUE TITLE
Let's greet a new, 2020 year!

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor4#3759]
## Type of report

Task

## Provide description of the task

Time to greet the year 2020. Let's update any references in license headers and docs.

**Comment by f1ames** [comment]
We should also greet 2020 in [ckeditor4-presets](https://github.com/ckeditor/ckeditor-presets) and integrations ([Angular](https://github.com/ckeditor/ckeditor4-angular) and [React](https://github.com/ckeditor/ckeditor4-react)).

I think that's all, but if anything more comes to your mind, feel free to update year there too.

PRs:

* https://github.com/ckeditor/ckeditor4/pull/3760
* https://github.com/ckeditor/ckeditor4-docs/pull/281
* ckeditor4-presets...
* ckeditor4-angular...
* ckeditor4-react...

**Comment by f1ames** [comment]
Reopening since we have few more repos to cover.

**Comment by f1ames** [comment]
All done (https://github.com/ckeditor/ckeditor4/issues/3759#issuecomment-572110715). The 2020 has just officially started!  2️⃣ 0️⃣ 2️⃣ 0️⃣ 🎉
