### ISSUE TITLE
Pasting images copied "as image" from a website does not trigger a file upload in Chrome

### ISSUE THREAD

**Issue by Matthijs-Wessels** [ckeditor/ckeditor4#3765]
## Are you reporting a feature request or a bug?
Bug

Pasting images copied from a website does not trigger a file upload in Chrome, but adds the image based on the image source url (i.e. `<img src="https://exmaple.com/myimage.png" />`. It does work in Firefox.

From debugging the issue, I have noticed that the `files` property of the clipboard data object gets lost when passing the object to the `setTimeout` handler through its closure (seen [here](https://github.com/ckeditor/ckeditor4/blob/master/plugins/clipboard/plugin.js#L1205-L1207)). 

I think this happens for security reasons as stated in [the w3c spec](https://w3c.github.io/clipboard-apis/#clipboard-event-api) which states:
> Access to the clipboard is performed using the standard DataTransfer methods to mutate the items on a ClipboardEvent's clipboardData attribute. One consequence of this is that these clipboard APIs can only access clipboard data in the context of a ClipboardEvent handler.

In Firefox, another handler is used for the paste event (see [here](https://github.com/ckeditor/ckeditor4/blob/master/plugins/clipboard/plugin.js#L1205-L1207)). Here, the image is converted to a base64 string synchronously in the context of the handler and the dataValue is set. If I let this code execute in Chrome, it also works in Chrome.

If I understand correctly, the `setTimeout`'s purpose is to do the image processing asynchronously. I think if you want to do that asynchronously, using [the (new?) async Clipboard api](https://w3c.github.io/clipboard-apis/#async-clipboard-api) allows you to do just that.

## Provide detailed reproduction steps (if any)

1. Browse to an image on the web
2. Right click and select Copy Image
3. Paste the image in the editor.

### Expected result

File gets uploaded to my upload file endpoint

### Actual result

img gets inserted with src pointing to the location from which I copied the image.

## Other details

* Browser: Chrome 79.0.3945.88
* OS: Mac/Windows
* CKEditor version: 4.7.3
* Installed CKEditor plugins: http://ckeditor.com/builder/e2d21243aa6b6522152b0a344b10c256

**Comment by Matthijs-Wessels** [comment]
I just realized that the [`cacheData` function](https://github.com/ckeditor/ckeditor4/blob/master/plugins/clipboard/plugin.js#L2584-L2591) is supposed to work around this (if I understand correctly). Not sure yet why this is not working then

**Comment by msamsel** [comment]
Hi @Matthijs-Wessels,
I suspect that issue might be caused by the situation that clipboard doesn't contain files in data transfer and only `text/html` content which is an `<img>` tag.

Since 4.7.3 editor modified the way how images are processed. Please check if the issue might be reproduced for you on 4.13.1. If so, then is worth inspecting this part of the code:
https://github.com/ckeditor/ckeditor4/blob/d1710c198d8f5007e8d04fed9870bfd4b182ae54/plugins/imagebase/plugin.js#L253

Please provide also more details about your configuration. What details do you add to editors config? Do you use some framework or it is a clear JS implementation? How do you copy image from a website (do you select it somehow, drag&drop, right-click + copy, or some other method)?

This could allow us on a better understanding of your case.

**Comment by Matthijs-Wessels** [comment]
I tried with CKEditor 4.13.1 and still see the same discrepancy. 

I have found [a JSFiddle that can reproduce the issue](http://jsfiddle.net/52cp790b/3/). You will noticed the upload error in firefox (because it tries to upload to example.org) and no error in chrome.

PS: The problem is not what I though it was. I.e. the cacheData function indeed actually stores the file on an `_` property. And that is actually accessible in the uploadimage plugin. However, [this line](https://github.com/ckeditor/ckeditor4/blob/major/plugins/uploadimage/plugin.js#L97-L98) explicitly checks if an image has been converted to a base64 string and just returns if that's not the case (for performance reasons according to the comment). 

The way I see it now is that we should either always convert to base64 like we do for Firefox (then it works), or change the paste handler in the uploadimage plugin to not only look at the dataValue property to see if there's a base64 image in there, but also look at the `_` property and read the file from there. Not sure what the performance impact would be.

**Comment by Matthijs-Wessels** [comment]
Here's a hacky jsfiddle that makes it work in all modern browsers: https://jsfiddle.net/89dfy14o/

**Comment by Matthijs-Wessels** [comment]
Still, it would probably be better to update the imageupload plugin to not only look at the dataValue's `data:` uri. 

It's not 100% clear to me yet how the imagebase plugin you referenced plays a role in this. Is that being used by the imageupload plugin?

**Comment by msamsel** [comment]
I'm sorry but I've became confused. Please correct me if I understand the case wrongly.

You're issue is the case where image which is a valid `<img>` tag with url to external resource is not uploaded to your endpoint. If this is the case, then it is default way how it is working. Please check page with editor integrated with CKFinder https://ckeditor.com/docs/ckeditor4/latest/examples/fileupload.html#uploading-dropped-and-pasted-images
The approach which you made in the https://jsfiddle.net/89dfy14o/ is the way how you can bypass this restriction, by manipulating `filteTransfer` object.

**Comment by Matthijs-Wessels** [comment]
> You're issue is the case where image which is a valid <img> tag with url to external resource is not uploaded to your endpoint.

Correct. I want the uploadimage plugin to try and upload the image to my uploadUrl when I paste the image in the editor. 

> (...) it is default way how it is working 
It works as I expected/desired in Firefox, just not in other browsers. So at minimum, it's not consistent.

You can see it in this fiddle: http://jsfiddle.net/52cp790b/3/ .
Steps:
* Right click an image on a webpage
* Choose copy image (not image url)
* Paste the image in the editor in the fiddle

Result:
* On FireFox, you'll see the upload error (because it tried to upload)
* On other browsers, it'll just add the image by the url and not try to upload

That's because there is an [`if(CKEDITOR.env.gecko)`](https://github.com/ckeditor/ckeditor4/blob/master/plugins/clipboard/plugin.js#L151-L191) that will add another 'paste' handler that converts the image data to base64 and sets the `dataValue` property to an image tag with that data in its `src`. The uploadimage plugin [listens to the 'paste' event and when it sees the `dataValue` prop has an image with a data url](https://github.com/ckeditor/ckeditor4/blob/major/plugins/uploadimage/plugin.js#L97-L98), only then will it upload the image. 

So only for FireFox will that handler upload the image.

In my [latest fiddle](https://jsfiddle.net/89dfy14o/) I basically add that one handler regardless of the browser.

Question about the [demo on the page you linked](https://ckeditor.com/docs/ckeditor4/latest/examples/fileupload.html#uploading-dropped-and-pasted-images). I can't get it to upload the image when copied from the web either. I can paste an image in the editor and it gets added by url, but no upload is triggered there. It only works if I copy the pixels from an image from within an editor and then paste it in. But if I do as described above (i.e. right click on an image on the web and select "Copy Image"), then it does not work (also in FireFox).

**Comment by jacekbogdanski** [comment]
Uploading images in CKEditor 4 is mostly done via [CKFinder](https://ckeditor.com/ckfinder/), you can see integration example at [File Upload through Dialogs and Drag&Drop](https://ckeditor.com/docs/ckeditor4/latest/examples/fileupload.html#uploading-dropped-and-pasted-images) demo. 

For a free solution, you will need to implement your own image file uploader using [File Browser API](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_file_browser_api.html). Also, additional cross-links inside this article may be helpful.

Note that differences in internal data propagation between browsers in the editor are required to implement the core feature, so it's not recommended to use them as they may be a subject of change (like most private API).

Please, if you find out that the editor works incorrectly, share your thoughts, so we can reopen this ticket. If you are missing some important editor API, post feature request or open PR - we are always happy for community ideas.

**Comment by nag5000** [comment]
> Please, if you find out that the editor works incorrectly, share your thoughts, so we can reopen this ticket.

The editor works incorrectly.

> From debugging the issue, I have noticed that the files property of the clipboard data object gets lost when passing the object to the setTimeout handler through its closure (seen [here](https://github.com/ckeditor/ckeditor4/blob/master/plugins/clipboard/plugin.js#L1205-L1207)).

Yes, as @Matthijs-Wessels said, `setTimeout` is the culpit. `ClipboardEvent.clipboardData` is cleared in subsequent event loop (after `setTimeout(..., 0)`) in Chrome. That's why uploading an image copied from website doesn't work in Upload Image plugin in Chrome.
