### ISSUE TITLE
Multiple copies of copied content get pasted in the continuously when Ctrl+P key pressed

### ISSUE THREAD

**Issue by loop-partha** [ckeditor/ckeditor4#3766]
## Type of report

Multiple copies of copied content get pasted in the continuously when Ctrl+P key pressed.

This issue still exists with ver 4.13.1. Please assist us to fix this. But it is not reproducible but happens. We are using the CKEditor to react.

## Provide detailed reproduction steps (if any)

1. …
2. …
3. …

### Expected result

*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by Dumluregn** [comment]
Hello,

1.  You didn't fill the template properly. If you don't tell us e.g. which operating system you use, we will be unable to help you.
2.  Are you using some custom key mapping? CTRL+P by default prints the page content, not pastes, so behaviour you described seems very odd.
3.  Does this issue happen in the basic editor too (e.g. try [here](http://cdn.ckeditor.com/4.13.1/full-all/samples/)) or just in React integration? If the latter, please report it [in the right repo](https://github.com/ckeditor/ckeditor4-react).

But after all, if you don't provide us any code sample, it will be difficult to help.

**Comment by jacekbogdanski** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
