### ISSUE TITLE
Fix error messages in passing unit tests

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor4#3772]
## Type of report

Task

## Provide description of the task

Issue extracted from #3744 
There are errors thrown in unit tests, which doesn't break the tests. However, those errors are visible in the log.
Errors should be tracked down and fixed to not confuse the users.

https://travis-ci.org/ckeditor/ckeditor4/builds/636241868

![Screenshot 2020-01-13 at 10 15 24](https://user-images.githubusercontent.com/9017322/72244071-bfd2b580-35ed-11ea-8dce-b64bcc7db688.png)
![Screenshot 2020-01-13 at 10 14 33](https://user-images.githubusercontent.com/9017322/72244072-bfd2b580-35ed-11ea-90b4-dfac2add085d.png)

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by sculpt0r** [comment]
It is not possible to track this issue since CI logs are gone after transfer to the `travis.com`
