### ISSUE TITLE
File Manager docs are slightly outdated

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4#3773]
## Type of report

Docs

## Provide a description of requested docs changes

The [Interaction Between CKEditor and File Manager](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_file_browser_api.html#interaction-between-ckeditor-and-file-manager) lacks information about `filebrowserUploadMethod ` which changed in `4.9.0` version. There is a community PR already covering that - https://github.com/ckeditor/ckeditor4-docs/pull/217. We should review if there is enough information or something more should be added and merge it.

**Comment by Dumluregn** [comment]
Besides [ckeditor/ckeditor-docs#217](https://github.com/ckeditor/ckeditor4-docs/pull/217) there is also [ckeditor/ckeditor-docs#279](https://github.com/ckeditor/ckeditor4-docs/pull/279) that also concerns File Manager docs and should also be taken care of.

**Comment by Dumluregn** [comment]
Instead of [ckeditor/ckeditor-docs#217](https://github.com/ckeditor/ckeditor4-docs/pull/217) we now have  [ckeditor/ckeditor-docs#285](https://github.com/ckeditor/ckeditor4-docs/pull/285).

**Comment by Dumluregn** [comment]
And due to lack of [#279](https://github.com/ckeditor/ckeditor4-docs/pull/279) author's response I included his contribution in [ckeditor/ckeditor-docs#285](https://github.com/ckeditor/ckeditor4-docs/pull/285), so we have only one PR to merge now.

**Comment by f1ames** [comment]
Fixed with ckeditor/ckeditor4-docs#285.
