### ISSUE TITLE
It's possible to remove part of the widget with cross content selection

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor4#3778]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

It's a followup issue for https://github.com/ckeditor/ckeditor4/issues/3498 where we decided to skip Edge fix due to incoming Chromium-based Edge #3655. Although, it's still worth to check if moving to Chromium fixes the issue for Edge.

1. Open sample with some widget based plugin. You can use `tests/plugins/widget/integration/selection/manual/crosscontentselection` manual tests from https://github.com/ckeditor/ckeditor4/pull/3553
2. Make a cross selection between editor content and widget.
3. Press CTRL + X (cut) keystroke.

![image](https://user-images.githubusercontent.com/1061942/72158019-874a9600-33b9-11ea-866c-5759be0cfe87.gif)

### Expected result

Widget is partially removed from the editor.

### Actual result

A widget cannot be partially changed as it's atomic structure.

## Other details

* CKEditor version: 4.13.0

**Comment by Dumluregn** [comment]
This issue is no longer reproducible in the latest Edge browser version.
