### ISSUE TITLE
Track colors used in the editor contents

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor4#3783]
## Type of report

Feature request

## Provide description of the new feature

Extracted as a separate issue from specification for #1795 described [here](https://github.com/ckeditor/ckeditor4/issues/1795#issuecomment-559809627). It will probably be closed in one PR, but both deserve separate changelog entries as they can be used independently.

**Comment by f1ames** [comment]
Isn't it like more like a new API? Or you marked it as a feature request meaning that it introduces some visible UI additions in colorpanel? :thinking:

**Comment by Dumluregn** [comment]
The latter - I described it a little in the \[PR\](https://github.com/ckeditor/ckeditor4/pull/3784#issue-363206245).
