### ISSUE TITLE
Microsoft Edge throw exception `SCRIPT5007: Object expected` after remove editor tag

### ISSUE THREAD

**Issue by wanliyang9012** [ckeditor/ckeditor4#3792]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. create simple html page as below
![image](https://user-images.githubusercontent.com/51030647/72599698-2ab52100-394d-11ea-97d4-29c6ca9dfb87.png)

2. open the page in Microsoft Edge.
3. scroll the page, no issue
4. delete the entire html tag "divEditor"
5. scroll the page, it throw exception `SCRIPT5007: Object expected`

6. open same page in Chrome / IE
7. delete the entire html tag "divEditor"
8. scroll the page, no exception
### Expected result

Microsoft Edge not throw exception.

### Actual result

Microsoft Edge throw exception.

## Other details

* Browser: Microsoft Edge 44.17763.831.0
* OS: Window 10
* CKEditor version: ckeditor_4.13.1_full
* Installed CKEditor plugins: …

**Comment by msamsel** [comment]
Removing editor's tag without proper clean up is an invalid approach. I'm surprised there is no errors in Chrome 😱.
Please remember to execute [`editor.destroy()`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#method-destroy) before removing tag containing the editor instance.

**Comment by wanliyang9012** [comment]
cool, `CKEDITOR.instances.txtEditor.destroy()` will remove ckeditor and set textarea to normal html.
thanks a lot.
