### ISSUE TITLE
dataIndentationChars disregarded if empty string

### ISSUE THREAD

**Issue by Znegl** [ckeditor/ckeditor4#3795]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

Set
`CKEDITOR.config.dataIndentationChars = '';`
Insert a list in the editor.

> 1. One
> 2. Two
> 3. Three

### Expected result

*What is the expected result of the above steps?*

```html
<ol><li>One</li><li>Two</li><li>Three</li></ol>
```

### Actual result

*What is the actual result of the above steps?*

```html
<ol><li>One</li>\t<li>Two</li>\t<li>Three</li></ol>
```

## Other details

* Browser: Chrome 79.0.3945.117 
* OS: macOS 10.15.2 (19C57)
* CKEditor version: 4.11.3
* Installed CKEditor plugins: N/A

I also found this old bug, but can't find any progress on it: https://dev.ckeditor.com/ticket/16949

**Comment by jacekbogdanski** [comment]
Closed in https://github.com/ckeditor/ckeditor4/pull/3796
