### ISSUE TITLE
Uncaught TypeError: Cannot read property 'unselectable' of null - laravel

### ISSUE THREAD

**Issue by lotusms** [ckeditor/ckeditor4#3807]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. … I followed the installation process with composer
2. … I added the script tags recommended in the docs
3. … I made sure the selector matches

### Expected result

I expected the editor to show up

### Actual result

It doesn't. And it obfuscates the textarea altogether. The console shows an error (`Uncaught TypeError: Cannot read property 'unselectable' of null`). I noticed in some internet chatter that I needed to take `defer` out from the app.js injection in my app.blade.php. I did that. I did notice that if I import it in my Vuejs main app.js file and make Vue require it, it works but it breaks pretty much everything else in the app. Am I supposed to import it differently? Am I missing anything not included in your docs?

## Other details

* Browser: … All of them
* OS: …Windows and Mac OS
* CKEditor version: … unisharp/laravel-ckeditor v.4.7 I believe
* Installed CKEditor plugins: … None (basic use)
* Platform: ... Laravel 5 + VueJs

**Comment by lotusms** [comment]
I was able to go around it with this

`<script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
  
<script>setTimeout(function(){
            CKEDITOR.replace( 'article-ckeditor' );
        },400);
    
</script>`
<br/><br/>
But that's hardly a fix. So I don't know if it should apply as a bug fix

**Comment by msamsel** [comment]
Hi @lotusms,
from what you describe, you're using 3rd party integration made for CKEditor (https://github.com/UniSharp/laravel-ckeditor). As this software is not developed by our team I cannot tell much about it.
If you find out that issue might be reproduced directly in CKEditor, or in of integration delivered by CKSource, I'll be happy to help you with that case.
