### ISSUE TITLE
editor.getSelection().getStartElement() returns wrong element

### ISSUE THREAD

**Issue by kuku711** [ckeditor/ckeditor4#3814]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Insert the next html into ckeditor:
div 1111 br br 2222 div

2. The editor shows:
1111
empty line
2222

3. Locate the cursor in the empty line

4. run this code:  const selectedElement=editor.getSelection().getStartElement() 

### Expected result
selectedElement is text node or br element

### Actual result
selectedElement is the div element

## Other details

* Browser:  chrome 79
* OS: win 10
* CKEditor version:  4.11.4

**Comment by Comandeer** [comment]
Text node can't be returned by `getStartElement` as it's not an HTML element. Additionally `br` can't be returned either, as there is no possibility to insert selection into this element (it's a void element). In that case, the parent element of text node/`br` element is returned. I assume that you use [`CKEDITOR.ENTER_BR` mode](https://ckeditor.com/docs/ckeditor4/latest/features/enterkey.html) within [inline editor](https://ckeditor.com/docs/ckeditor4/latest/examples/inline.html). In such case `div` (the editable) is a correct return value.
