### ISSUE TITLE
improperly add link or anchor when pasting text

### ISSUE THREAD

**Issue by ranielli** [ckeditor/ckeditor4#3825]
## Type of report

Bug

improperly add link or anchor when pasting text

### Expected result

text without links

### Actual result

![image](https://user-images.githubusercontent.com/1909238/73308550-49de6900-41ff-11ea-925e-b4606830031e.png)

## Other details

* Browser: all
* OS: Mint 19
* CKEditor version: 4.13
* Installed CKEditor plugins: all

**Comment by jacekbogdanski** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.
