### ISSUE TITLE
text disappear when changing color

### ISSUE THREAD

**Issue by kuku711** [ckeditor/ckeditor4#3837]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. insert into ckeditor the next html:
`<ol><li><span style="color:#e67e22;">check</span></li></ol><p></p>`
2. click ctrl +A
3. change the font color to any color
4. click ctrl+A
5. change the font color to any color
6. click ctrl+A
7. change the font color to any color

### Expected result
the text is present with the last color chosen

### Actual result
the text disappear

## Other details

* Browser: …chrome 79
* OS: …windows10
* CKEditor version: …4.13.1
* Installed CKEditor plugins: …

**Comment by jacekbogdanski** [comment]
Could you provide a minimal editor demo required to reproduce the issue? You could use tools like https://codepen.io, https://jsbin.com etc

**Comment by kuku711** [comment]
here is a clip the demonstrate the bug

[font_color_bug.zip](https://github.com/ckeditor/ckeditor4/files/4176498/font_color_bug.zip)

**Comment by jacekbogdanski** [comment]
I can reproduce the issue only when using dev tools, however, it's not a correct way to customize the editor's content. Please, use dedicated API instead, e.g. [`editor.setData`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#method-setData) or [Source Editing Area](https://ckeditor.com/cke4/addon/sourcearea) plugin for content modifications.

Please, share the feedback if you are able to reproduce the issue without browser developer tools, so we can reopen this issue.
