### ISSUE TITLE
CKEditor dialog input uneditable if ckeditor is in jqui dialog.

### ISSUE THREAD

**Issue by brunis** [ckeditor/ckeditor4#3841]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open a ckeditor in a jquery ui dialog
2. Write in the editor, works
3. Click any toolbar button that spawns a ckeditor dialog
4. Try and write in any input field

### Expected result

All writable inputs should receive input.

### Actual result

All input in all dialogs are broken 

## Other details

* Browser: Any
* OS: Windows
* CKEditor version: 4.13.1
* Installed CKEditor plugins: custom build from online-builder, but tried regular standard and full build.

Going back to 4.8 everything works again.

**Comment by Dumluregn** [comment]
Hello, please take a look at [this article](https://gist.github.com/Reinmar/b9df3f30a05786511a42) where you find an explanation how to make CKEditor work in modals. Please let us know if it was sufficient to solve your issue.

**Comment by Comandeer** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
