### ISSUE TITLE
Changes made within <head> tag is not detected as a change

### ISSUE THREAD

**Issue by Ben101293** [ckeditor/ckeditor4#3843]
* Browser: Chrome
* OS: Mac OS Mojave
* CKEditor version: 4

**Comment by Dumluregn** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

**Comment by Comandeer** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
