### ISSUE TITLE
Retain line spacing from Word when pasting to CKEditor

### ISSUE THREAD

**Issue by Freelensia** [ckeditor/ckeditor4#3845]
Issue type: Feature request (bug?)

**Steps to reproduce**
0. Install the line height add-in for CKEditor
1. Create some texts in Word
2. Apply Line Spacing, say 1.15
3. Paste to CKEditor

### Expected result
CKEditor should retain the line spacing from Word

### Actual result
Line spacing is not retained

## Other details
* Browser: Chrome
* OS: Windows 10
* CKEditor version: 4 or 5
* Installed CKEditor plugins: Line Height

**Comment by f1ames** [comment]
@Freelensia are you using [this 3rd-party Line Height](https://ckeditor.com/cke4/addon/lineheight) plugin? It is not authored by CKSource so we cannot provide any help here. We suggest reporting this issue directly to plugin creator.
