### ISSUE TITLE
In Angular component config enterMode and coreStyles_bold doesn't work

### ISSUE THREAD

**Issue by oneclickwebstudio** [ckeditor/ckeditor4#3846]
## Type of report
Trying to set
```
const config = {
  ckeditor: {
    enterMode: 2,
    coreStyles_bold : { element: 'b', overrides: 'strong' },
    toolbar: {
      items: ['undo', 'redo', '|', 'bold', 'italic', 'underline', 'strikethrough', 'code', 'link']
    }
  }
};
```
to
`<ckeditor [editor]="Editor" [config]="config" formControlName="about"></ckeditor>
`

### Expected result

While pressing ENTER should create <br/> instead new paragraph
the same with coreStyles_bold

### Actual result

pasting paragraph and strong tag instead of <b>

**Comment by f1ames** [comment]
Hello @oneclickwebstudio, since this is an Angular integration issue, it should be reported in `ckeditor4-angular` repo - https://github.com/ckeditor/ckeditor4-angular/issues/new. Could you move it there?

**Comment by oneclickwebstudio** [comment]
> Hello @oneclickwebstudio, since this is an Angular integration issue, it should be reported in `ckeditor4-angular` repo - https://github.com/ckeditor/ckeditor4-angular/issues/new. Could you move it there?

I'm using **[CKEditor 5 rich text editor component for Angular](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/angular.html)**

**Comment by f1ames** [comment]
If you are using CKEditor 5 Angular component, you should report an issue in [https://github.com/ckeditor/ckeditor5-angular](https://github.com/ckeditor/ckeditor5-angular) repository. Keep in mind that CKEditor 5 doesn't provide the exact same config options so `enterMode` and `coreStyles_bold` won't work there.
