### ISSUE TITLE
Font of the justified line is getting changed in ENTER_BR mode

### ISSUE THREAD

**Issue by tanmoyckeditor** [ckeditor/ckeditor4#3849]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Configure CKEditor with the following settings.
        CKEDITOR.replace( 'editor', {	
		enterMode : CKEDITOR.ENTER_BR,
		allowedContent : true
	});

2. Switch to Source Mode and paste the following html
    https://gist.github.com/tanmoyckeditor/93a226e3ad6c758ae5616f89efb7d293

3. Switch to WYSIWYG mode. Click on any line and click on center justify.

### Expected result

The particular line gets centered.

### Actual result

The particular line gets centered, **but the font gets changed to the default editor font.**

## Other details

* Browser: Any
* OS: Windows
* CKEditor version: 4.13.1
* Installed CKEditor plugins: …
* Attached sample CDN:
https://gist.github.com/tanmoyckeditor/c56de6b0673d8a223a4e771881abb029

* Debugging findings:
**Initial Copied content HTML**

![image](https://user-images.githubusercontent.com/60876818/74216284-ec035400-4cc9-11ea-9312-87c271b8fc84.png)

**Content after justifying a line in the middle**

![image](https://user-images.githubusercontent.com/60876818/74216428-70ee6d80-4cca-11ea-86ba-4ec300f45970.png)

When the entire text is split to justify the middle line, it does not copy the font-family of it's parent to the div encapsulating the justified line. Hence, it is picking up the font-family of the editor.

**Comment by jacekbogdanski** [comment]
Could you provide minimal demo allowing to reproduce the issue? You are using `pt` instead of pixels and some custom font-family properties, so we cannot reproduce the issue using default CKEditor settings. Also, it would be easier if you could correct your input HTML, so the issue can be reproduced using default settings instead of some custom implementation which may cause the issue itself.

**Comment by tanmoyckeditor** [comment]
![ckeditor2](https://user-images.githubusercontent.com/60876818/74816711-abd34f80-5321-11ea-8bed-f80eb490a431.gif)
Recorded issue with html after converting px to pt and removing custom classes

**Comment by jacekbogdanski** [comment]
Sorry, but I'm still unable to reproduce the issue using clean editor instance with `full-all` preset and provided configuration for enter mode and allowed content. Please, provide a demo application, with the issue.

**Comment by tanmoyckeditor** [comment]
> Sorry, but I'm still unable to reproduce the issue using clean editor instance with `full-all` preset and provided configuration for enter mode and allowed content. Please, provide a demo application, with the issue.

https://codepen.io/tanmoyckeditor/pen/PoqEozO

I have added the code as an application here. 
Please click on any line except the first to recreate the issue

**Comment by jacekbogdanski** [comment]
The given HTML is invalid semantically and overall it cannot be correctly recognized by Font plugins as they are using spans elements to handle fonts by default. You should use single styles spans for fonts instead:

```html
<span style="font-family: Arial;">foo bar</span>
```

You can also use your own font definition using [config.font_style](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-fontSize_style) configuration option.

The issue with incorrectly content splitting for BR mode is already reported: https://github.com/ckeditor/ckeditor4/issues/3847
