### ISSUE TITLE
CKEditor shows double underline (Paragraph height increased)

### ISSUE THREAD

**Issue by Mathiyazhagan07** [ckeditor/ckeditor4#3855]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Loading the table HTML into CKeditor
2. CKEditor shows the table differently compared to the original

### Expected result

Same as original file

### Actual result

Paragraph height increased 

## Other details

Table Source:
[tableHTML.txt](https://github.com/ckeditor/ckeditor4/files/4190221/tableHTML.txt)

Original:
![Orginal Computed Style](https://user-images.githubusercontent.com/60921414/74309458-cdb45b80-4d90-11ea-88ea-5eb17562bbd0.png)
![Orginal Style](https://user-images.githubusercontent.com/60921414/74309471-d311a600-4d90-11ea-8d35-0dfecc242447.png)

CKEditor:
![CKeditor Computed Style](https://user-images.githubusercontent.com/60921414/74309724-72369d80-4d91-11ea-8396-2e97027bb14d.png)

* Browser: Chrome
* OS: Windows 10
* CKEditor version: 4.7.1

**Comment by f1ames** [comment]
The `p` element `height` is a native browser styling (you can see in the `Computed` tab that `height` style is dimmed and has no reference to any CSS style, meaning it is style added by the browser itself). 

To align CKEditor 4 styling with you HTML displayed somewhere else you should adjust `content.css` file or add new styles via [`addCss` API](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR.html#method-addCss).

**Comment by Mathiyazhagan07** [comment]
> The `p` element `height` is a native browser styling (you can see in the `Computed` tab that `height` style is dimmed and has no reference to any CSS style, meaning it is style added by the browser itself).
> 
> To align CKEditor 4 styling with you HTML displayed somewhere else you should adjust `content.css` file or add new styles via [`addCss` API](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR.html#method-addCss).

Thank you for the immediate response. But Chrome shows correctly that same HTML element. CKEditor only shows double line.

**Comment by f1ames** [comment]
> Thank you for the immediate response. But Chrome shows it correctly when open that file. CKEditor only shows double line load that HTML into it.

Ok, I thought it is about the height, not the double line. I tried to reproduce it on https://ckeditor.com/ckeditor-4/demo/#article (via `editor.setData()` method and copy/paste) but then I got no underline:

![Zrzut ekranu z 2020-02-12 10-58-56](https://user-images.githubusercontent.com/1061942/74324103-cab46d80-4d86-11ea-8a46-8ccf3a19dc9c.png)

How do you insert the HTML into the editor and what Chrome version do you use?

**Comment by Mathiyazhagan07** [comment]
> > Thank you for the immediate response. But Chrome shows it correctly when open that file. CKEditor only shows double line load that HTML into it.
> 
> Ok, I thought it is about the height, not the double line. I tried to reproduce it on https://ckeditor.com/ckeditor-4/demo/#article (via `editor.setData()` method and copy/paste) but then I got no underline:
> 
> ![Zrzut ekranu z 2020-02-12 10-58-56](https://user-images.githubusercontent.com/1061942/74324103-cab46d80-4d86-11ea-8a46-8ccf3a19dc9c.png)
> 
> How do you insert the HTML into the editor and what Chrome version do you use?

Chrome Version: Version 79.0.3945.130 (Official Build) (64-bit)
We are using the editor.setData() method and facing issue in our application. But you can inspect and edit the HTML in the site itself to reproduce this issue in https://ckeditor.com/ckeditor-4/demo/#article
