### ISSUE TITLE
Video Disappears with CKeditor plugins for "HTLM5video" and "youtube" 

### ISSUE THREAD

**Issue by lightfoot68** [ckeditor/ckeditor4#3860]
### Bug
**Problems with plugins for "HTLM5video" and "youtube"**
While using Ckeditor 4 plugin "**HTML5video**", I can successfully load a working video with controls and thumbnail. 
The video goes away when I do one of the following three things:
1) Simply pressing the "Source" button to see HTML code and then pressing the "Source" button again to return to the presentation screen.  Video goes away. The HTML source remains. 
2) After building a Ckeditor 4 screen with a working video and saving the contents to a database then restore the saved HTML screen, video goes away.  When I look at the HTML code of the screen it looks intact and the same as the initial working screen.
3) After building a screen with a video and drag and drop (move) the video, the video goes away.  I believe this is the same described in bug: #3026.

While using Ckeditor 4 plugin "**youtube**", I can successfully load a working Youtube Link with controls and video. 
The video goes away when I do one of the following two things:
1) Simply pressing the "Source" button to see HTML code and then pressing the "Source" button again to return to the presentation screen.  "Youtube Video Link" goes away and leaves a red IFRAME message. The HTML source remains. 
2) After building a Ckeditor 4 screen with a working "Youtube Video Link"  and saving the contents to a database then restore the saved HTML screen, the "Youtube Video Link" goes away and leaves a red IFRAME message.  When I look at the HTML code of the screen it looks intact and the same as the initial working screen. 

Are all these above symptoms related to CKeditor bug: #3026?  Can you provide any updated to resolving bug #3026?  Can you provide any guidance to these issues above?

### Expected result
The Video and Youtube Video Link do not go away after doing on of the steps above. 

### Actual result
The Video and Youtube Video Link does go away after doing on of the steps above. 

## Other details
* Browser: …  Chrome Version 80.0.3987.100 (Official Build) (64-bit)
                      FireFox72.0.2 (64-bit)
* OS: …          Centos 6.5 
* CKEditor version: … Ckeditor_Full_4.13.1
* Installed CKEditor plugins: … config.plugins = 'dialogui,dialog,about,a11yhelp,dialogadvtab,basicstyles,bidi,blockquote,notification,button,toolbar,clipboard,panelbutton,panel,floatpanel,colorbutton,colordialog,templates,menu,contextmenu,copyformatting,div,resize,elementspath,enterkey,entities,popup,filetools,filebrowser,find,fakeobjects,flash,floatingspace,listblock,richcombo,font,forms,format,horizontalrule,htmlwriter,iframe,wysiwygarea,image,indent,indentblock,indentlist,smiley,justify,menubutton,language,link,list,liststyle,magicline,maximize,newpage,pagebreak,pastetext,pastetools,pastefromgdocs,pastefromword,preview,print,removeformat,save,selectall,showblocks,showborders,sourcearea,specialchar,scayt,stylescombo,tab,table,tabletools,tableselection,undo,lineutils,widgetselection,widget,notificationaggregator,uploadwidget,uploadimage,wsc,imageresizerowandcolumn,footnotes,resizewithwindow,uploadfile,dropdownmenumanager,placeholder_select,strinsert,stylesheetparser,zoom,scribens,texzilla';
	config.skin = 'moonocolor'; 

config.extraPlugins = 'html5video,oembed,video,youtube,html5audio';

**Comment by f1ames** [comment]
Hi @lightfoot68, `html5video` and `youtube` are you are referring to are third-party ones, and are not maintained by CKSource. Since we cannot fix issues with the code that does not belong to us, we are unable to help solve your issue. Please redirect your question to the plugin’s author who should be able to review the problem and suggest a solution.  
  
If, however, after contacting the plugin’s maintainer you find out the issue lies on the editor’s side, and you can provide a test case file showing the problem, we will be happy to have a look at it.
