### ISSUE TITLE
Config is not considered when setting startup read-only mode for inline editor

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor4#3866]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open https://jsfiddle.net/Comandeer/7c4y8x32/
2. Focus the editor.

### Expected result

Editor is in editable mode.

### Actual result

Editor is in read-only mode.

It seems that the logic inside inline creator has higher priority than the explicit config option.

## Other details

* CKEditor version: 4.5.0+

**Comment by jacekbogdanski** [comment]
Closed in https://github.com/ckeditor/ckeditor4/pull/3867
