### ISSUE TITLE
Update info about CKE4 and link to CKE5 real-time features

### ISSUE THREAD

**Issue by FilipTokarski** [ckeditor/ckeditor4#3873]
## Type of report

Docs

## Provide a description of requested docs changes

Right now when you open https://ckeditor.com/docs/ckeditor4/latest/guide/dev_basics.html#what-ckeditor-is-not it is written: _"CKEditor working out of the box in its default implementation is not a tool like Google Docs, where multiple users can edit the same article online in real time, track changes, and add comments. You can however try to find some plugins or tools that will help you expand its possibilities."_
For someone who sees this for the first time, and has no clue what CKEditor4 and CKEditor 5 ( and what are differences between them ) are, it may seem like the whole CKEditor ecosystem does not support things like real-time collaboration, comments, tracking changes, etc. But these are the features that are available in CKEditor 5.
So my proposition is, maybe we could change this to _"CKEditor **4** working out of the box..."_ and link to CKEditor 5, so it would be useful for the users who are looking for such things and are not sure if they are in the right place.

Add 👍 if this makes sense to you.

**Comment by Dumluregn** [comment]
Done in ckeditor/ckeditor4-docs@bf05c95.
