### ISSUE TITLE
Embed widget can't be dragged

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor4#3875]
## Are you reporting a feature request or a bug?

bug

## Provide detailed reproduction steps (if any)

1. Go to `/tests/plugins/embed/manual/embed`
2. Try to drag llama picture using drag handler

### Expected result

Llama can be dragged.

### Actual result

![Screenshot 2020-02-20 at 12 19 44](https://user-images.githubusercontent.com/10883184/74929201-52c7f200-53db-11ea-99d5-4df0b378217e.png)

## Other details

In previous versions it was working fine. Also you can still drag e.g. embed from twitter in the same test. And if you toggle to source mode and back it starts working fine. So it seems to be some edge case connected with the widget's position in document. I'm labelling it as `failingtest` until we encounter similar case outside tests.

* Browser: all
* OS: macOS
* CKEditor version: 4.14.0
* Installed CKEditor plugins: embed

**Comment by jacekbogdanski** [comment]
https://github.com/ckeditor/ckeditor4/issues/3926
