### ISSUE TITLE
Link and image are not displayed properly by print plugin

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor4#3876]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Go to `/tests/plugins/print/manual/print`
2. Click `Print` button
3. Check out preview

### Expected result

Preview content matches editor content exactly.

### Actual result

9/10 tries image is missing and link is displayed as plain text.

## Other details

In Edge Chromium it works fine if you click `Preview` button first and don't close the preview window. This workaround doesn't work for Chrome though. Also it seemed to work in `4.13.1` (check it out [here](http://cdn.ckeditor.com/4.13.1/full-all/samples/)).

* Browser: Chrome, Edge Chromium
* OS: macOS
* CKEditor version: `4.14.0`
* Installed CKEditor plugins: `print`, `preview`

**Comment by Dumluregn** [comment]
I checked this also during monkey clicking in full preset and it works correctly there 🤔 So I'm relabelling from `regression` to `failingtest`.

**Comment by Comandeer** [comment]
Closed by #4813.
