### ISSUE TITLE
ckeditor cdn not working

### ISSUE THREAD

**Issue by NadimSayaLife** [ckeditor/ckeditor4#3878]
i have used ck-editor cdn to implement ck-editor in my project but today it gives me error like ck-editor not define and i run the ckeditor.js in browser but it not working

**Comment by Dumluregn** [comment]
Hello, could you give us link you are using? The following one (current version) works for me:
[https://cdn.ckeditor.com/4.13.1/full-all/ckeditor.js](https://cdn.ckeditor.com/4.13.1/full-all/ckeditor.js)

**Comment by NadimSayaLife** [comment]
it working now , before it gives me IP Address error in browser
Thank you

**Comment by ducminhvu** [comment]
Is the server have some problem now? I can't access anymore
https://cdn.ckeditor.com/4.14.1/standard-all/ckeditor.js
