### ISSUE TITLE
Incorrect keyboard navigation in RTL mode

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor4#3879]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Go to [CDN](http://cdn.ckeditor.com/4.13.1/full-all/samples/)
2. Set `RTL` text direction for the first paragraph

*Scenario 1:*
3. Place caret at the end of line (after `world`)
4. Press right arrow

### Expected result

Caret moved left (that's default in RTL)

### Actual result

Caret is stuck in the same place

*Scenario 2:*
3. Place caret in the middle of line (e.g. between words)
4. Try to navigate to the `!` using right arrow

### Expected result

Navigation is intuitive and caret moved character by character.

### Actual result

When caret is between letters `H` and `e` and right arrow is pressed, caret is moved to the end (beginning) of the line.

## Other details

It looks similar as #2104, which however turned out to be an upstream issue.

* Browser: all
* OS: macOS
* CKEditor version: `4.14.0`, `4.10.0`
* Installed CKEditor plugins: `BiDi`

**Comment by Comandeer** [comment]
It seems to be Chrome's bug as it's reproducible also without CKEditor 4 instance: https://jsfiddle.net/Comandeer/mn8h76tw/

**Comment by Dumluregn** [comment]
Confirmed - Chrome and Edge are broken. I'm reporting an issue in Chromium tracker.

**Comment by Dumluregn** [comment]
Closing issue as an upstream - [https://bugs.chromium.org/p/chromium/issues/detail?id=1055757](https://bugs.chromium.org/p/chromium/issues/detail?id=1055757).
