### ISSUE TITLE
Security template can now point directly to a proper URL

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor4#3890]
## Type of report

Task

## Provide description of the task

Some time ago [GitHub added more template configuration options](https://github.blog/changelog/2019-10-28-new-issue-template-configuration-options/).

This includes an option to make a given issue type point to an arbitrary URL. So we could make the "Issue: 🚨 Security issue" template to point to our contact form directly.

An example can be seen here: https://github.com/SpiderLabs/owasp-modsecurity-crs/issues/new/choose

![](https://user-images.githubusercontent.com/5353898/75159096-c76e9980-5717-11ea-9df4-c90a1d169959.png)

Note it also allows disabling the "Don’t see your issue here? Open a blank issue.", but that's not related to this particular thing.

**Comment by f1ames** [comment]
Good point :+1: We could also add entry for Licensed Customers so they can have reach support easier :thinking:
