### ISSUE TITLE
Adding autogrow plugin causes text to flicker

### ISSUE THREAD

**Issue by mlearncore2018** [ckeditor/ckeditor4#3894]
1. Add autogrow plugin to the config
2. Notice that the body text flickers

**Comment by Comandeer** [comment]
We would like to help solve your issue but it seems you have missed our [template sfor feature requests and bug reports](https://github.com/ckeditor/ckeditor4/issues/new/choose). Their purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.
