### ISSUE TITLE
快捷键如何设置

### ISSUE THREAD

**Issue by R2h1** [ckeditor/ckeditor4#3896]
请问如何设置工具栏中标题h1,和h2 的快捷键？

**Comment by Comandeer** [comment]
We would like to help solve your issue but it seems you have missed our [templates for feature requests and bug reports](https://github.com/ckeditor/ckeditor4/issues/new/choose). Their purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now. Please also note that issue should be reported in English.
