### ISSUE TITLE
Use 'ckeditor4-docs-samples' submodule during 'ckeditor4-docs' build instead of static plugins code

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor4#3897]
## Type of report

Docs

## Provide a description of requested docs changes

#3840 was caused by a wrong `ckeditor4-docs-samples` linking, but it was strange that there were no similar issues. So it seems that this submodule is no longer necessary (as all tutorial plugins are now also in `ckeditor4-docs/docs/sdk/examples/assets/plugins/` and this folder is referenced everywhere).

I've already did a simple test and it seems docs are working fine then.

**Comment by Comandeer** [comment]
I'm for keeping that repo as a submodule and instead modifying our build flow to generate `assets/plugin` directory from the submodule. This way we will have always the same version of plugins in docs and in samples repo, without additional efforts to keep them in sync.

**Comment by f1ames** [comment]
Agree with @Comandeer on this one, it's better to have one source of samples so there is no issue in keeping them in sync and more intuitive (it was quite surprising for me that we have this repo as submodule but docs don't use it). This will require adjusting build flow so plugins from submodule are copied to a right place during building.

**Comment by Dumluregn** [comment]
As we agreed during standup talk, we will rather aim at removing static plugin files and want to use `ckeditor4-docs-samples` repo as the source for tutorial plugins, so I'm renaming this issue and closing current PR targeting it.

It seems that this repo was added as a submodule in [ckeditor/ckeditor4-docs#184](https://github.com/ckeditor/ckeditor4-docs/pull/184), but even then it wasn't directly used during build process. I guess maybe it was about to be the next docs revamp step (which never occured).

**Comment by f1ames** [comment]
I think we have one more thing to fix here, since ckeditor/ckeditor4-docs@2812332 (PR fixing autotag sample) where also module name was changed we have two `ckeditor*-docs-samples` directories:

![](https://user-images.githubusercontent.com/1061942/75901001-229e3b80-5e3e-11ea-9969-244e2d1243f6.png)

See e.g. https://github.com/ckeditor/ckeditor4-docs/tree/stable/docs/sdk/examples/assets.

**Comment by Dumluregn** [comment]
Right, the old submodule should be properly removed.

**Comment by f1ames** [comment]
Fixed in ckeditor/ckeditor4-docs@666f721.
