### ISSUE TITLE
CKEditor seems to have inconsistent behaviour.

### ISSUE THREAD

**Issue by deshdeep91** [ckeditor/ckeditor4#3909]
![SA-14189_1](https://user-images.githubusercontent.com/50594028/75758353-f4473000-5d59-11ea-9ae8-230a3ad9d170.gif)
## Type of report

Bug

## Provide detailed reproduction steps (if any)

I have added a gif file to explain my issue.
Explanation of gif sequence: 
1) Select first description box.
2) Select bullet list button.
3) Then enter text in the description box.
4) Now, inspect this description box, you will see a div with class name : "rubricblock-anchor-div" is created, under which a div with id name : "p_info-cell_r1_c1" is created, under which there is a list created.

1) Now, if I enter text in next description box in 3 consecutive lines and then select all the 3 lines.
2) Now, I will click on bullet button.
3) Now, inspect this description box, you will see a div with class name : "rubricblock-anchor-div"
is created, under which 2 divs with class name : "info-cell_r1_c2 cke_widget_editable cke_widget_editable_focused" is created and one div with id name : "p_info-cell_r1_c2" is created. Now, each of these 3 divs have individual lists.

This is the inconsistency due to which I am unable to capture data to store it in backend on clicking "save" button.

### Expected result

I expect, it should have similar div tree creation in both the situations. Like a parent div with class name : "rubricblock-anchor-div" under which one div with id name : "p_info-cell_r1_c1". Here, number of c1 will change based on description box selected.

### Actual result

In first scenario, it creates one div with a list of 3 items but in 2nd scenario it creates 3 divs each with single item list. On top of that, out of those 3 divs, 2 divs have class name and last div follow the regular convention.

So, ask is to bring consistency in these div elements generation. Generally, div created has id name : "p_info-cell_r1_c1". If this is expected behaviour then please provide some convention under which those 2 different types of divs get created.

## Other details

Browser: Google Chrome
OS: macOS
CKEditor version: 4.13.0
Installed CKEditor plugins: MathJax, WYSIWYG

**Comment by Comandeer** [comment]
The plugin you are using (rubric widget) is a third-party one, and it is not maintained by CKSource. Since we cannot fix issues with the code that does not belong to us, we are unable to help solve your issue. Please redirect your question to the plugin’s author who should be able to review the problem and suggest a solution.

If, however, after contacting the plugin’s maintainer you find out the issue lies on the editor’s side, and you can provide a test case file showing the problem, we will be happy to have a look at it.

**Comment by deshdeep91** [comment]
@Comandeer  Thanks for the help.
Do you have any idea where I should raise concern for this rubric issue(there issue tracker)?

**Comment by Dumluregn** [comment]
Unfortunately plugin's author didn't offer to share it with us and it isn't available to download through our [online builder](https://ckeditor.com/cke4/addons/plugins/all), so you should probably turn to a maintainer of the website where you found this issue.

**Comment by deshdeep91** [comment]
@Dumluregn Ok, thanks for the help.
