### ISSUE TITLE
Is ckeditor-vue is production ready?

### ISSUE THREAD

**Issue by farazshuja** [ckeditor/ckeditor4#3913]
## Type of report

Task

## Provide description of the task
I just downloaded the ckeditor-vue via yarn add command and found that its version 0.1. Can someone plz confirm whether its safe to use it on production?

*What steps should be taken to fulfil the task?*
https://ckeditor.com/docs/ckeditor4/latest/guide/dev_vue.html

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by f1ames** [comment]
Hello @farazshuja, yes the CKEditor 4 Vue integration is production ready. As you can ready in e.g. [official release blogpost](https://ckeditor.com/blog/CKEditor-4-integrate-WYSIWYG-editor-with-Vuejs/#feedback):

> The CKEditor 4 Vue.js integration is stable, but we still deem it a beta version. We are [awaiting your feedback and ideas on how it can be improved further](https://github.com/ckeditor/ckeditor4-vue/issues/new).

So it can be used safetly. We are also open for your feedback, so if you have any, please don't hesitate to report in [\`ckeditor4-vue\` repository](https://github.com/ckeditor/ckeditor4-vue)!
