### ISSUE TITLE
On Integrations landing page one of jQuery links leads to Vue.js integration instead

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor4#3914]
## Type of report

Docs

## Provide a description of requested docs changes

On [Introduction page](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_integration.html) this link: 
<img width="360" alt="Screenshot 2020-03-05 at 14 25 30" src="https://user-images.githubusercontent.com/10883184/75985830-479db780-5eed-11ea-9c9d-e726f629b12f.png">

leads to Vue instead of jQuery.

**Comment by f1ames** [comment]
Fixed in ckeditor/ckeditor4-docs#291.
