### ISSUE TITLE
Usage of document editor in vuejs 

### ISSUE THREAD

**Issue by JoeWitchy** [ckeditor/ckeditor4#3917]
Hey guys, I'm kinda new to ckeditor and I'm using vuejs as a framework of choice. I was easily able to run ckeditor but I'm trying to use the document editor and I'm not able to find any solution as to how to achieve it. Would be great if someone can help me out on this. Have a great day.

**Comment by f1ames** [comment]
@JoeWitchy could you report this issue in the Vue integration repository to keep things in order - https://github.com/ckeditor/ckeditor4-vue?

Also could you share more details what you mean by document editor - is this [full page editing](https://ckeditor.com/docs/ckeditor4/latest/features/fullpage.html) or something else?
