### ISSUE TITLE
CKEDITOR.tools.object.merge() method throws error when first argument is undefined or null

### ISSUE THREAD

**Issue by Wizard13** [ckeditor/ckeditor4#3924]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

`CKEDITOR.tools.object.merge()` method in `core/tools.js` throws error if first argument `obj1` is undefined or null.

### Expected result

The method should return the second argument.

### Actual result

An error is thrown.

## Other details

* Browser: Firefox, Chrome
* OS: Windows 7 SP1 64bit
* CKEditor version: 4.14.0
* Installed CKEditor plugins: Full

 A fix such as `obj1 = obj1 || {}` inside the method as a first line works well.

**Comment by Comandeer** [comment]
This method was designed to work only with two objects provided. If you want to make the copy of the object, please use [`CKEDITOR.tools.copy`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_tools.html#method-copy) or [`CKEDITOR.tools.clone`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_tools.html#method-clone) instead.
