### ISSUE TITLE
Error thrown when dragging and dropping only the first inserted widget

### ISSUE THREAD

**Issue by Wizard13** [ckeditor/ckeditor4#3926]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Go to https://jsfiddle.net/pwfjv6xs/
2. Insert at least one simplebox widgets by clicking "Insert Widget" button above CKEditor or by clicking the button with no icon right next to the Image button.
3. Try to drag and drop the first inserted widget.

### Expected result

Drag and drop should work.

### Actual result

An error is thrown for the first widget only. The next ones can be dragged and dropped.
If I click Source button twice, the first widget can finally be dragged and dropped.

* Browser: Firefox, Chrome
* OS: Windows 7 SP1 64bit
* CKEditor version: 4.14.0
* Installed CKEditor plugins: Full

**Comment by NogaMan** [comment]
I have fixed it locally already by changing the widget plugin code.
I have the full preset, so widget plugin was embedded in ckeditor.js.
I assume that with lower presets it may not be embedded and would be stored separately in `plugins/widget/plugin.js` instead.

The details of the change are in the commit here in my fork https://github.com/NogaMan/ckeditor4/commit/d4375ba140d8964361014153884e5e91f66a6f91.
I am too lazy to write tests to open PR here.

**Comment by Dumluregn** [comment]
Closed via #4045.
