### ISSUE TITLE
Example 

### ISSUE THREAD

**Issue by skyview059** [ckeditor/ckeditor4#3929]
Document and Example not working in my end. 

![image](https://user-images.githubusercontent.com/9079143/76628950-c63aca80-6567-11ea-9da7-5c7206c48442.png)

**Comment by f1ames** [comment]
We would like to help solve your issue but it seems you have missed our [templates for feature requests and bug reports](https://github.com/ckeditor/ckeditor4/issues/new/choose). Their purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.
