### ISSUE TITLE
IE Clipboard Access Prompt; On allow hits: Unable to get property 'plugins' of undefined or null reference

### ISSUE THREAD

**Issue by SandisA** [ckeditor/ckeditor4#3931]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

 _Setup steps:_ 
1. use IE 11 (this is Internet Explorer specific issue)
2. Ckeditor "samples" hosted in IIS; Put the ckeditor access site in Trusted sites. 
3. Make sure the default level for Clipboard access is Prompt
Scripting > Allow Programmatic clipboard access -> Prompt

_Steps to reproduce:_

1. Use Paste icon to trigger prompt call
2. On IE prompt: "Do You want to allow this webpage to access your Clipboard"
3. Press "Allow access"

### Expected result

After prompt Allow action the clipboard is pasted

### Actual result

The content is pasted. But it triggers also undefined exception in selection,js 
: Unable to get property 'plugins' of undefined or null reference
line 1974 (v4.14.0 full source)
editor.plugins.tableselection
editor is undefined

## Other details

* Browser: Internet Explorer 11.1098.17763.0
* OS: Windows 10 1809; IIS 10.0.17763.1
* CKEditor version: 4.13.1;  4.14.0
* Installed CKEditor plugins: 
Using this build configuration, with defines plugins
[build-config.txt](https://github.com/ckeditor/ckeditor4/files/4337273/build-config.txt)

The error is reproducible on samples from the Build source
![20200316 ErrorCondition Selection undefined editor](https://user-images.githubusercontent.com/6853728/76741907-fc02cd80-6778-11ea-956d-ca5f861d1da8.PNG)

_Thoughts on the condition_
I see that on-line 2085 the editor is checked also for undefined condition. 

So I wonder 
- if this place (line 1974) is amiss for undefined check
- or it is some other context initialization error in case of broken clipboard access flow

**Comment by Comandeer** [comment]
Yes, it seems that it's a regression introduced in #3241. Adding simple check if `editor` is undefined should be enough.

**Comment by f1ames** [comment]
Fixed in 7468d1c.
