### ISSUE TITLE
Autocomplete loses navigation keybindings after switching source mode

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor4#3938]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open any sample with autocomplete and sourcearea plugins.
2. Switch between source editing and content editing.
3. Trigger autocompletion.
4. Navigate using arrow keys.

### Expected result

You can navigate through the completion panel using a keyboard.

### Actual result

Keybindings are removed.

## Other details

Probably standard issue with incorrect event listener on editable where we should use `attachListener` instead:
https://github.com/ckeditor/ckeditor4/blob/5ace43e789f84c74f74fb1b163715aa2ba04e826/plugins/autocomplete/plugin.js#L307-L309

**Comment by f1ames** [comment]
The correct way is to attach key listeners inside `contentDom` event listener, same as e.g. here:

https://github.com/ckeditor/ckeditor4/blob/258c8ec13469003fda64c6d6cfc5d2196e3f073c/core/selection/optimization.js#L24-L38

**Comment by f1ames** [comment]
Fixed in f0dfded.
