### ISSUE TITLE
CKEDITOR.skinName is undefined

### ISSUE THREAD

**Issue by kazemimorteza68** [ckeditor/ckeditor4#3943]
Hi.
i want us ckeditor with selected plugin. i have choose video plugins.but i have this error.
```js
CKEDITOR.skinName is undefined
```

i have tested below config in config.js file.

```js
CKEDITOR.config.skin = 'moono-lisa';
```

but i have not any change.

**Comment by jacekbogdanski** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.
