### ISSUE TITLE
Inline editor issues when contained within a table

### ISSUE THREAD

**Issue by lkues** [ckeditor/ckeditor4#3952]
## Type of report

Bug
1. Run the attached sample 
2. Double click on the word 'purpose' to select it. 
3. Drop down Text Color picker and select Dark Cyan.

### Expected result

Selected text is changed to Dark Cyan.

### Actual result

Selected text is not changed to Dark Cyan.

## Other details
Our application uses the inline editor within a table to support spreadsheet-like editing.  The ckeditor selection code is testing for selection within a table, but when doing so (via getAscendant) is picking up table elements that are outside of the editor dom.

* Browser: Chrome
* OS: Windows 10
* CKEditor version: 4.7.2
* Installed CKEditor plugins: table, tabletools, tableselection, tableselectioncell, tableresize

[inlineeditor-table.txt](https://github.com/ckeditor/ckeditor4/files/4382506/inlineeditor-table.txt)
file.

**Comment by jacekbogdanski** [comment]
The issue has been fixed as a part of https://github.com/ckeditor/ckeditor4/issues/2403 in `4.11.2`

Please, upgrade the editor to the latest version to get rid of this issue.
