### ISSUE TITLE
append style and quote in ckeditor

### ISSUE THREAD

**Issue by jaafarscorpion** [ckeditor/ckeditor4#3959]
Hi I'm work in reply to a comment my problem how to append form blockquote

**Comment by f1ames** [comment]
Hello @jaafarscorpion, I'm not sure what is your issue, could you describe it more precisely?

**Comment by jaafarscorpion** [comment]
I'm working to replies to a comment, for the moment i can add the text quote
but i want to add styles too

**Comment by Dumluregn** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.
