### ISSUE TITLE
Find & Replace feature documentation and demo is missing

### ISSUE THREAD

**Issue by wwalc** [ckeditor/ckeditor4#3970]
We are getting requests from users looking for Find & Replace in CKEditor 5. I was surprised to see that we actually do not have any feature documentation for it in CKEditor 4 although the feature itself is not available in the standard demo and as such may be hard to find.

**Comment by usmannoor10p** [comment]
@f1ames any update on this ticket? Thanks

**Comment by f1ames** [comment]
Hi @usmannoor10p, @jacekbogdanski will be the best person to answer your question since I no longer participate in maintaining CKEditor 4.

**Comment by jacekbogdanski** [comment]
Unfortunately, there is no update regarding this ticket yet due to other priorities we are working on in CKEditor 4. Thank you @usmannoor10p for bumping this ticket to our attention.

**Comment by usmannoor10p** [comment]
@jacekbogdanski thanks for the update.

**Comment by jacekbogdanski** [comment]
Closed in https://github.com/ckeditor/ckeditor4-docs/pull/378
