### ISSUE TITLE
CKEditor - footnotes Navigation not working on the first load after refresh

### ISSUE THREAD

**Issue by vallikumar** [ckeditor/ckeditor4#3973]
Normally, a user can align the bullet lists/numbered lists and it should align left right or center properly along with the bulleted points or the numbers..

CK Editor is not supporting the align the bullet lists/numbered lists properly to left/right / center or justify. We have tried with CK editor version 4 and 5.

Steps to reproduce.

Enter some random text e.g Test1 , Test2, Test3, Test4
Create a  footnotes
Save tghe content.
Refresh the page.
Click on Footnotes Marker now.
The navigation between Marker to cite and vice versa is not happening
Expected result:
The on click of End notes or Cite needs to naviagte back and forth
Actual Results:
But No action is happening. No console errors as well.
But this issue is not happening with Firefox or IE Edge

Browser: …Chrome 78 and 79
OS: …Windows 10
CKEditor version: …7.1
Installed CKEditor plugins: …additionalplugins downloaded apart from the  package.

**Comment by Dumluregn** [comment]
Hello! To act we definitely need more information. First of all, please provide us a demo to reproduce the issue (e.g. on CodePen or JSFiddle). Second, we need the list of additional plugins - if you are using footnotes from [this plugin](https://ckeditor.com/cke4/addon/footnotes), please note that we are not it's authors and therefore can't fix it.

**Comment by vallikumar** [comment]
I have using the mentioned Footnotes plugin, SO contacting the mentioned footnotes Support group, Thank you
