### ISSUE TITLE
Bullet point not getting deleted on Backspace, key, when there is a footnotes present in the previous bulleted point

### ISSUE THREAD

**Issue by vallikumar** [ckeditor/ckeditor4#3974]
Normally, a user can delete the bullet lists/numbered lists by using the backspace and delete keys.

CK Editor is not identifying the bullet point, when there is a footnote present above the in previous bulleted / Numbered item.

Steps to reproduce.

Enter some random text e.g Test1 , Test2, Test3, Test4, Test5
Select the bullet list / Numbered list.
Now create footnotes at the end of 2nd bulleted item and the 4th bulleted item
Now keep teh cursor at the end of the 5th bulleted item and start deleting by using backspace keys.
While deleting we can see, the ck editor missing to identify the bullet point in the bulleted item below the ones in the footnotes.

Observe only text getting deleted and escaping the bullet / numbered item.
Expected result:
The bullet list / Numbered list should also be deleted, when teh suer deleting it.
Actual Results:
But only the text is deleting and the bullet points are getting retained.

Browser: …Chrome 78 / 79
OS: …Windows 10
CKEditor version: …7.1
Installed CKEditor plugins: …addiitonal footnotes plugins downloadedalong with  package.

**Comment by Dumluregn** [comment]
Just as I stated [here](https://github.com/ckeditor/ckeditor4/issues/3973#issuecomment-610270212), please send us demo and list of plugins.

**Comment by vallikumar** [comment]
Sure i will provide some details shortly

**Comment by zoarif** [comment]
Hi, is this issue fixed already?

**Comment by f1ames** [comment]
@zoarif, there was no fix introduced AFAIK, but I'm not also sure why this issue was closed? @Dumluregn, is it an upstream issue as labeled?

**Comment by Dumluregn** [comment]
The [Footnotes plugin](https://ckeditor.com/cke4/addon/footnotes) is not maintained by CKSource, so as the issue is only reproducible with it (as stated in issue title and description), I indeed considered it to be an upstream problem with a mentioned plugin.
