### ISSUE TITLE
Not able to see the cursor when placed after the footnote  Cursor not visible after the foot note,

### ISSUE THREAD

**Issue by vallikumar** [ckeditor/ckeditor4#3975]
Normally, a user can be able to see teh cursor blinking wherever we clicked inside teh editor

CK Editor is pushing teh cursor to teh end of teh editor or making invisible, once the iuser hover on cke_widget_drag_handler_container and the drag handler image(handle.png) is made visible via the "display: block" property"

This disolay block property pushing the cursor to the end of teh editor.

Steps to reproduce.
Enter some random text e.g Test1 , Test2, Test3, Test4
Create a footnotes at end of some bulleted items.
create some bullet points at end of any paragraphs.
Save the content.

Mouse overon Footnotes Marker now.
when  the drag hander icon is visible above, it starts pushing the blinking cursor to teh end of teh line
Expected result:
The cursor should stay at the same position just next to teh foot note marker
Actual Results:
But teh cursor is pushed towards the end of edtor or teh next line.

Browser: …Chrome 79 and 78
OS: …Windows 10
CKEditor version: …7.1
Installed CKEditor plugins: …addiitonal footnotes plugins downloadedalong with package.

**Comment by Dumluregn** [comment]
[Same as here](https://github.com/ckeditor/ckeditor4/issues/3973#issuecomment-610270212).

**Comment by vallikumar** [comment]
This is also the 3rd party Footnotes plugin, So  contacting the other Support group,
Thank you
