### ISSUE TITLE
When saving using ckedtior, the tag is not saved properly

### ISSUE THREAD

**Issue by dudgkr** [ckeditor/ckeditor4#3985]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. …
2. …
3. …

### Expected result

*What is the expected result of the above steps?*
![image](https://user-images.githubusercontent.com/53809612/79037654-0ac09100-7c0e-11ea-963f-ca700c1052ad.png)

### Actual result

*What is the actual result of the above steps?*
tag is save as [br] in front end - webpage
![image](https://user-images.githubusercontent.com/53809612/79037678-3fcce380-7c0e-11ea-875a-f4749916b49b.png)

## Other details

* Browser:chrome
* OS: window10 64bits
* CKEditor version: ckedtior4
* Installed CKEditor plugins: …

**Comment by Comandeer** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.
