### ISSUE TITLE
Hindi Font is not Working

### ISSUE THREAD

**Issue by shalukashyap** [ckeditor/ckeditor4#3989]
## Type of report

I have added following code in contents.css

@font-face {
    font-family: 'kruti_dev_070regular';
    src: url('KrutiDev070/kruti_dev_070-webfont.eot');
    src: url('KrutiDev070/kruti_dev_070-webfont.eot?#iefix') format('embedded-opentype'),
         url('KrutiDev070/kruti_dev_070-webfont.woff') format('woff'),
         url('KrutiDev070/kruti_dev_070-webfont.ttf') format('truetype'),
         url('KrutiDev070/kruti_dev_070-webfont.svg#kruti_dev_070regular') format('svg');
    font-weight: normal;
    font-style: normal;
 
}
and following code in config.js

config.font_names = 'Hindi/kruti_dev_070regular;' +config.font_names;

it is displaying in drop down list but when selecting and typing it is not working?

**Comment by f1ames** [comment]
We would like to help solve your issue but it seems you have missed our [templates for feature requests and bug reports](https://github.com/ckeditor/ckeditor4/issues/new/choose). Their purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.
