### ISSUE TITLE
Added a new Font Hindi but i am unable to type in Hindi in Editor

### ISSUE THREAD

**Issue by shalukashyap** [ckeditor/ckeditor4#3991]
Added a new Font Hindi but i am unable to type in Hindi in Editor.

**I did few changes in config.js which is below**
CKEDITOR.editorConfig = function( config ) {
	// Define changes to default configuration here. For example:
	// config.language = 'fr';
	config.uiColor = '#AADC6E';
	config.font_names = 'Hindi/kruti_dev_070regular;' +config.font_names;

};
**i did few changes in content.css which is below**
@font-face {
    font-family: 'kruti_dev_070regular';
    src: url('KrutiDev070/kruti_dev_070-webfont.eot');
    src: url('KrutiDev070/kruti_dev_070-webfont.eot?#iefix') format('embedded-opentype'),
         url('KrutiDev070/kruti_dev_070-webfont.woff') format('woff'),
         url('KrutiDev070/kruti_dev_070-webfont.ttf') format('truetype'),
         url('KrutiDev070/kruti_dev_070-webfont.svg#kruti_dev_070regular') format('svg');
    font-weight: normal;
    font-style: normal;
 
}
**my HTML file from where i m calling my editor**
<body>
	<p>
		My Editor:<br />
		<textarea id="editor1" class="ckeditor" name="editor1"> Testing the editor  </textarea>

		<ckeditor:replace replace="editor1" basePath="/ckeditor/ckeditor.js">
		</ckeditor:replace>

	</p>
</body>

### Expected result
Font has been added after making changes in these file but the result i am getting is not upto mark.

![ScreenShot](https://user-images.githubusercontent.com/53996293/79238393-f50ccf00-7e8c-11ea-83f9-b6d45c805700.jpg)

### Actual result
I want if anyone want to write in Hindi than  user just pickup the font/style in Hindi which has been added in CKEditor and start typing in HINDI.

## Other details
* Browser: …Chrome
* OS: … Windows
* CKEditor version: …CKEditor 4
* Installed CKEditor plugins: …Yes

**Comment by Comandeer** [comment]
Typing in Hindi is connected to the used operating system and its [IMEs](https://en.wikipedia.org/wiki/Input_method), not to the CKEditor 4 or used font. Please install appropriate IME in your system and typing in Hindi should be working inside CKEditor 4.

**Comment by shalukashyap** [comment]
> Typing in Hindi is connected to the used operating system and its [IMEs](https://en.wikipedia.org/wiki/Input_method), not to the CKEditor 4 or used font. Please install appropriate IME in your system and typing in Hindi should be working inside CKEditor 4.

Thank you so much.
