### ISSUE TITLE
Div plugin - Not localized for Arabic Language

### ISSUE THREAD

**Issue by SudarshanSudie** [ckeditor/ckeditor4#4001]
## Arabic Language string not localized for "Div" plugin

Bug

## Provide detailed reproduction steps (if any)

1) Enable Div plugin in your CKEditor instance
2) Open Ckeditor in Arabic language.
3) Click the "div" button in the Toolbar 
4) Notice that the container title is in English and not in Arabic.

Root cause : The file - plugins/div/lang/ar.js does not have the correct localized string.

### Expected result

*Title for Div dialog should be in Arabic*

### Actual result

*Title for Div dialog is in English*

## Other details

* Browser: NA
* OS: NA
* CKEditor version: NA
* Installed CKEditor plugins: div

**Comment by jacekbogdanski** [comment]
Hello @SudarshanSudie,

thanks for the information! In general, localization files are mostly handled directly by [Transifex Platform](https://www.transifex.com/ckeditor/ckeditor/) by our community. Only a part of our localization files is handled by the CKEditor 4 team which we have native speakers for. We could very much appreciate if you could join the team and help with this particular language translation.
