### ISSUE TITLE
Add info about colorName property in colorbutton plugin

### ISSUE THREAD

**Issue by hub33k** [ckeditor/ckeditor4#4004]
## Type of report

Docs

## Provide a description of requested docs changes

Add mention about new `colorName` property (added [here](https://github.com/ckeditor/ckeditor4/pull/3977)).

Places to cover:
- https://ckeditor.com/docs/ckeditor4/latest/features/colorbutton.html

**Comment by f1ames** [comment]
Fixed in ckeditor/ckeditor4-docs@d736417.
