### ISSUE TITLE
Update screen of sample in 'Basic Configuration' section

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor4#4006]
## Type of report

Docs

## Provide a description of requested docs changes

The screen [here](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_howtos_basic_configuration.html#how-do-i-find-code-examples-showing-ckeditor-customization) is very old. Should be updated to match how our samples currently look [here](https://ckeditor.com/docs/ckeditor4/latest/examples/mathjax.html).

**Comment by f1ames** [comment]
Fixed in ckeditor/ckeditor4-docs@0a8adb5.
