### ISSUE TITLE
Remove Format button no longer works when no text is selected

### ISSUE THREAD

**Issue by murat-amazon** [ckeditor/ckeditor4#4008]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Load the editor version 4.14.0: https://jsfiddle.net/xda4omnr/1/
2. Select "bold" and "underlined"
3. Type: `Hello, `
4. Click "Remove Format" button
5. Type: `world!`

### Expected result

The text `world!` has normal style.

### Actual result

The text `world!` is bold and underlined.

## Other details

This feature used to work before - up to and including version 4.11.1. See https://jsfiddle.net/xda4omnr/2/ where the feature works.

The culprit which introduced the regression is most likely this commit: https://github.com/ckeditor/ckeditor4/pull/2625/commits/4a2929658c62f15d0c721e0e5c3027b7be40cf09

Note that you can still remove formatting after selecting some text, but some users use this button just to reset their styling from a particular moment on without selecting any text.

* Browser: Chrome
* OS: Mac OS
* CKEditor version: 4.14.0
* Installed CKEditor plugins: full/all

**Comment by Dumluregn** [comment]
Hello, thank you for very thorough research on this issue! Unfortunately I can confirm this behaviour.

**Comment by Comandeer** [comment]
Merged in [`453880`](https://github.com/ckeditor/ckeditor4/commit/4538808935e9c88eabbf8a8cad5728f216ce0068), will be released in 4.14.1.
