### ISSUE TITLE
Image2 addon is not used by Smiley addon because of "insertElement" command insted of "insertHtml"

### ISSUE THREAD

**Issue by Wizard13** [ckeditor/ckeditor4#4012]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Go https://jsfiddle.net/qm9dtgx8/
2. Insert a smiley

### Expected result

Smiley is converted to "image2" image

### Actual result

Smiley is not converted to "image2" image because it is inserted with "insertElement" command insted of "insertHtml". You can see that in the 2 images that are already inserted. The first one is inserted with "insertHtml" and it's converted to "image2" image, but the second one is inserted with 
"insertElement" command and it's not converted to "image2" image. By entering Source mode and then back to WYSIWYG mode, all images are converted to "image2" images.
## Other details

* Browser: Firefox, Chrome
* OS: Windows 7
* CKEditor version: 4.14.0
* Installed CKEditor plugins: image2

**Comment by Wizard13** [comment]
Is it safe to replace this code in smiley\dialog\smiley.js:
```
var img = editor.document.createElement( 'img', {
	attributes: {
		src: src,
		'data-cke-saved-src': src,
		title: title,
		alt: title,
		width: target.$.width,
		height: target.$.height
	}
} );

editor.insertElement( img );
```
with this:
`editor.insertHtml(  '<img alt="' + title + '" src="' + src + '" title="' + title + '" width="' + target.$.width + '" height="' + target.$.height + '" data-cke-saved-src="' + src + '" />'  );`

I've tried it and it works...

**Comment by f1ames** [comment]
I'm not sure if smiley should be converted into `image2` instance - then it would be possible to edit it via `image2` dialog which is not the intention here.

I would consider the fact that smiley is converted into `image2` instance upon switching to source mode and back an issue here.

@Wizard13 could you tell us more about your use case? Why would you expect smiley to be an `image2` instance?

**Comment by Wizard13** [comment]
I need the smiley to be image2 because of consistency. I would expect that all images should show the same behavior with the resize handlers. But OK, I understand. I'm fine with the modification I've made since I have disabled image properties (captions, alignment etc).

**Comment by f1ames** [comment]
> I need the smiley to be image2 because of consistency. I would expect that all images should show the same behavior, because if you switch from Source to WYSIWYG all images become image2. The same thing happens when CKEditors initializes with contents that have smileys, they all become image2.

Thanks for the explanation. However, emoji shouldn't be treated as an image (same as for example anchor flag) as it is different entity with completely different purpose in mind - user shouldn't be able to edit its properties like URL, add caption, etc. So the issue here is basically the fact that emoji is converted to `image2` upon switching to source mode or when loading data with it into editor.

I have extracted two issues regarding this behavior - #4036 and #4037.
