### ISSUE TITLE
License explanation

### ISSUE THREAD

**Issue by MoroseCorpse** [ckeditor/ckeditor4#4015]
Hello,

I would like to have it explained to me in detail if I can use CKEditor 4 or 5 for free.
As I understood, yes, but I also read that our source code has to be released then. Is this true? 

I'm confused by the fact that it is open source on the one hand, but on the other hand it costs money.
 
Could someone explain to me how I can use the editor and if I can freely use all the plugins that are available? And is there a user restriction then?

I just want a good editor that supports Markdown like Github and has all the features of Github. That's all I need. 

I hope someone can help me there

**Comment by jacekbogdanski** [comment]
@MoroseCorpse thanks to getting in touch!

License for CKEditor 4 is basically explained by [LICENSE.md](https://github.com/ckeditor/ckeditor4/blob/major/LICENSE.md) file. It should be enough to understand how it works, but if you have some doubts, it's highly recommended to get in touch with law experts. I can also suggest contacting our [support team](https://ckeditor.com/contact/) as they certainly have better knowledge about licensing than developer team.
