### ISSUE TITLE
Deprecated "name" atttribute created when clicking Anchor button.   "name" attribute obsolete in HTML5

### ISSUE THREAD

**Issue by pkbarbiedoll** [ckeditor/ckeditor4#4027]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Click Anchor button in CKEditor gui
2. Enter string then click OK

### Expected result

View source to see `<a id="string"></a>`

### Actual result

View source to see `<a name="string"></a>`

Per HTML5, the `name` attribute is [obsolete](https://www.w3.org/TR/2011/WD-html-markup-20110525/a.html) and should not be used.  

## Other details

* Browser: Chrome, Firefox (no difference in behavior)
* OS: Linux Mint 18
* CKEditor version:  4.7.3
* Installed CKEditor plugins: format,link

**Comment by Comandeer** [comment]
According to the HTML specification, the feature is [obsolete but conforming](https://html.spec.whatwg.org/multipage/obsolete.html#obsolete-but-conforming-features). Also please note that by default CKEditor 4 creates link with both `[id]` and `[name]` atttibutes:

```html
<a id="anchor" name="anchor">anchor</a>
```

However it should be possible to delete `[name]` attribute and keep only the `[id]` one.

**Comment by pkbarbiedoll** [comment]
Could you potentially show how to configure CKeditor 4 to write the id attribute?  My current config (which I thought was pretty much default) is only writing the name attribute.

**Comment by pkbarbiedoll** [comment]
I erred in listing my version before, I am on CKEditor 4.7. 

Here are my configs: 

// inline creation of editor box:

				var editor = CKEDITOR.replace( 'editbox', {
					customConfig: 		'/js/ckeditor_4.7.3/custom_config_advanced.js',
					uiColor: 			'#FFF6DA',
					allowedContent: 	true,
					removeButtons: 		'Strike,Cut,Copy,Paste,Undo,Redo,Code,Styles,About', 
					height:				300,
				});
					
				CKEDITOR.instances['editbox'].on('instanceReady', function() {
						// Output self-closing tags the HTML4 way, like <br>.
						this.dataProcessor.writer.selfClosingEnd = '>';
				});		


// custom_config_advanced.js
				
				CKEDITOR.editorConfig = function( config ) {
					config.toolbarGroups = [
						{ name: 'document', groups: [ 'mode', 'document', 'doctools' ] },
						{ name: 'clipboard', groups: [ 'clipboard', 'undo' ] },
						{ name: 'editing', groups: [ 'find', 'selection', 'spellchecker', 'editing' ] },
						{ name: 'forms', groups: [ 'forms' ] },
						{ name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ] },
						{ name: 'paragraph', groups: [ 'list', 'indent', 'blocks', 'align', 'bidi', 'paragraph' ] },
						{ name: 'insert', groups: [ 'insert' ] },
						{ name: 'links', groups: [ 'links' ] },
						{ name: 'tools', groups: [ 'tools' ] },
						{ name: 'others', groups: [ 'others' ] },
						{ name: 'styles', groups: [ 'styles' ] },
						{ name: 'colors', groups: [ 'colors' ] },
						{ name: 'about', groups: [ 'about' ] }
					];
					config.extraPlugins = 'format,link';
					config.format_tags = 'p;h2;h3;h4;h5;h6;pre;address;div';
					config.extraAllowedContent = 'a[*]';
					config.removeButtons = 'Cut,Copy,Paste,PasteText,Undo,Redo,Scayt,Syntaxhighlight,HorizontalRule,Strike';
				};

**Comment by Comandeer** [comment]
It should work. I prepared a demo using your config and anchor is inserted with both `[name]` and `[id]` attributes: https://jsfiddle.net/Comandeer/94Lre1sd/

**Comment by pkbarbiedoll** [comment]
Confirmed this is working now.

**Comment by nicrodgers** [comment]
> Also please note that by default CKEditor 4 creates link with both [id] and [name] atttibutes:
> However it should be possible to delete [name] attribute and keep only the [id] one.

Manually removing the name attribute from the a element causes a problem: you can no longer edit the anchor.  If you double-click the anchor element after removing the name attribute, it opens the link popup instead of the anchor link popup.

Would you consider removing the name attribute as a feature request?
