### ISSUE TITLE
Background Color button does not recognize active styles using custom class and colorName

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4#4031]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

Follow-up of #3940 (and #3977 PR).

1.  Go to `tests/plugins/colorbutton/manual/customclassbackground.html`.
2.  Follow the scenario to apply custom background color.
3.  Focus text where background color was applied.

### Expected result

Background Color button changes its state to active.

### Actual result

Background Color button stays inactive.

![](https://user-images.githubusercontent.com/1061942/81274025-0a21eb80-9050-11ea-92e2-67ac09ea12f9.gif)

## Other details

It seems to be related to specific config:

```javascript
colorButton_backStyle: {
    element: 'span',
    attributes: { 'class': '#(colorName)' },
    overrides: [ {
        element: 'span',
        attributes: {
            'class': /text/
        }
    } ]
}
```

and the fact that background color transformations doesn't take such styling into account probably:https://github.com/ckeditor/ckeditor4/blob/258c8ec13469003fda64c6d6cfc5d2196e3f073c/plugins/colorbutton/plugin.js#L51-L86

*   Browser: Tested on Chrome
*   OS: Linux Mint
*   CKEditor version: Latest major with #3977 PR (targeted to `4.15`)
*   Installed CKEditor plugins: `colorbutton`

**Comment by hub33k** [comment]
@f1ames, after doing some research I think that the problem is in `colorButton_backStyle` option in `overrides.attributes` property. When we remove `overrides.attributes` or change regex `/text/` to eg. `/bg-/` it works good.

Here is config we use in `customclassbackground.html`:
```
CKEDITOR.addCss( '.bg-red { background-color: #F00; } .bg-blue { background-color: #00F; }' );
CKEDITOR.replace( 'editor', {
	colorButton_colors: 'bg-red/F00,bg-blue/00F',
	colorButton_backStyle: {
		element: 'span',
		attributes: { 'class': '#(colorName)' },
		overrides: [ {
			element: 'span',
			attributes: {
				'class': /text/
			}
		} ]
	},
	// Config necessary due to #3994 and #3996
	extraAllowedContent: 'span(*)',
	removeButtons: 'TextColor'
} );
```

**Comment by f1ames** [comment]
@hub33k ok, so it means this is just misconfiguration here? Could you prepare a PR with updated https://github.com/ckeditor/ckeditor4/blob/major/tests/plugins/colorbutton/manual/customclassbackground.html manual test with proper configuration?
