### ISSUE TITLE
Allow to use Emoji plugin without Autocomplete funcionality

### ISSUE THREAD

**Issue by RvdHout** [ckeditor/ckeditor4#4039]
## Type of report

If i enable emoji, i am able to hide the dropdown button on editor toolbar config where i choose not to include emoji, but the autocomplete still works on this editor instance... i don't want that (especially for DB field that are not utfmb4)

## Provide description of the new feature

emoji dropdown only (without autocomplete while typing)

i think it should be be possible to disable autocomplete plugin, only editor complains when i do this

```
Objectplugin: "autocomplete"
requiredBy: "emoji"
```

**Comment by f1ames** [comment]
`Emoji` plugin depends on autocomplete and couldn't be used without it for now. So your issue would be basically a feature request to allow using `Emoji` plugin without `Autocomplete` functionality.

@RvdHout could you tell us more about your use case? What is the reason you would like to us it that way.

**Comment by RvdHout** [comment]
We have some ckeditor instances in a custom CMS that are saved in a db that may not contain emoji's, like i said i can hide the emoji dropdown for those fields, but if i type :roll...etc the emoji can still be inserted. i also realize emoji's can still be pasted in, but that is a different story...

I solved it for now by removing the emoji plugin in those ckeditor instances i don't want emoji's to be inserted using the removePlugins config option

**Comment by f1ames** [comment]
> We have some ckeditor instances in a custom CMS that are saved in a db that may not contain emoji's

This means you should disable emoji plugin entirely and `removePlugins` is a correct way to do this. And if you don't need emoji plugin in any editor instance you can always customize your build in [CKEditor 4 online builder](https://ckeditor.com/cke4/builder) to have only the plugins which are used.

> i also realize emoji's can still be pasted in, but that is a different story...

Yes, that's another story completely separate from emoji plugin itself. That would require custom content filtering on [`paste`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#event-paste) event.
