### ISSUE TITLE
The scrollIntoView() method uses non-existent "selection.type" property

### ISSUE THREAD

**Issue by zentby** [ckeditor/ckeditor4#4041]
https://github.com/ckeditor/ckeditor4/blob/8a12b041718e05eeffb62a931d95995ac72cbe22/core/selection.js#L2495

`this.type` in the code above is always "undefined" as the `type` is not being maintained anywhere else. The correct reference call should be `this.getType()`.

**Comment by f1ames** [comment]
Hello @zentby,

how did you find this issue, observed somewhere "in the wild"? This would mean that `scrollIntoView()` also executes when there is no selection in the editor probably throwing an error :thinking:

**Comment by zentby** [comment]
Hi @f1ames ,

I ran into this issue with my customized plugin that integrates with "autocomplete". The error is thrown within the execution of the next line, `this.getRanges()` is an empty list. The higher call stack is the "autocomplete"'s `commit` call. I marked a breakpoint here and observed the value is always `undefined`. The issue happens in Safari only.

**Comment by f1ames** [comment]
Thanks for the clarification @zentby :+1: Would yo be able to prepare a simple demo which reproduces this issue (e.g. on Codepen - you can start by forking [this pen](https://codepen.io/Comandeer/pen/ExaMgpz?editors=1010))?

**Comment by zentby** [comment]
Try [this one](https://codepen.io/zentby/full/NWGoemj)
The issue could be observed in Safari (Mac) console. The editor didn't crash in the pen because I couldn't easily get a minimal example from my plugin. 

If you set a breakpoint at LN:10574 as shown below, you'll be able to see that the `this.type` is always undefined.

![image](https://user-images.githubusercontent.com/4077259/82662932-db785780-9c82-11ea-8d07-bf15ee3e8887.png)

Reproduce step:

1. Click the plugin button on the toolbar

**Comment by f1ames** [comment]
Thanks for the demo @zentby. There is something strange going on - from what I have checked our `CKEDITOR.dom.selection` class has only `getType()` method and no `type` property. The `type` property is available in native selection object. While `scrollIntoView` is `CKEDITOR.dom.selection` method it means it is using non-existent property :thinking: You can check what is logged here - https://codepen.io/f1ames/pen/wvKZGBW?editors=1010.

We will have to take a closer look into this one.

**Comment by jacekbogdanski** [comment]
Closed in #4127
