### ISSUE TITLE
First menu item is always highlighted in context menu

### ISSUE THREAD

**Issue by asyrk** [ckeditor/ckeditor4#4054]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open CKEditor4 official demo site
2. Create a table
3. Right click on any table cell to open context menu
4. Hover over different menu items in the context menu

### Expected result

Initially after opening the context menu, the first item should be highlighted. As user hovers over different menu items, only the menu item that the cursor is hovering over should be highlighted.

### Actual result

First menu item is always highlighted, when hovering over other menu items there are two items being highlighted.

Example: hovering over "Delete Table" results in both "Paste" and "Delete Table" being highlighted.
![image](https://user-images.githubusercontent.com/1496900/81911638-e4579200-95cd-11ea-91db-af307d6361cd.png)

## Other details

* Browser: Chrome
* OS: Windows10
* CKEditor version: 4.14.0 (Standard)
* Installed CKEditor plugins: …

**Comment by Comandeer** [comment]
It's intentional. The first item is focused (note additional outline around the item) and the other element is hovered by mouse. In CKEditor 4 keyboard focus and mouse hover are treated separately.
