### ISSUE TITLE
Different fontSize & bgColor operation sequences lead to different styles

### ISSUE THREAD

**Issue by woody-li** [ckeditor/ckeditor4#4058]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

Reproduction url:
https://ckeditor.com/docs/ckeditor4/latest/examples/pastefromword.html

1. Select some normal words.
2. Set background color.
3. Select part of it, and set a bigger font size.
4. The height of bg-color doesn't match the bigger font size.
5. Back to 1, and set font size first, then set bg-color.
6. The height of bg-color match the bigger font size now.

### Expected result

It leads to a same style.

**Comment by Dumluregn** [comment]
Hello, thank you for reporting this issue. I can confirm this behaviour. Unfortunately, fixing it would inquire major changes in the whole styling engine, so for now we will not make any changes here unless more similar bugs appears.
