### ISSUE TITLE
Vendor directory not included for unoptimised builds 

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor4#4059]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Go to [CKEditor 4 builder](https://ckeditor.com/cke4/builder).
2. Prepare any build
3. Download "Source (Big N’Slow)" version.
4. Look into downloaded archive.

### Expected result

There is a `vendor` directory with `promise.js` file.

### Actual result

There isn't `vendor` directory.

**Comment by f1ames** [comment]
@vokiel could you take a look or is it something we should fix on our side?

**Comment by vokiel** [comment]
Reported in website repository, will look into it today.

**Comment by vokiel** [comment]
Fixed, please verify.

**Comment by f1ames** [comment]
LGTM :+1:
