### ISSUE TITLE
save as pdf

### ISSUE THREAD

**Issue by 1baoxiaobowfj** [ckeditor/ckeditor4#4061]
Hello：
    Ckeditor has helped us a lot, thanks。
I would like to ask about save as PDF，I Downloaded  ‘Basic’ and  ‘full’ ， what are the functions，Although ‘save as PDF’ button can appear in the toolbar, clicking it has no response。I use the latest version of Google browser，
   How can I use it correctly, or can you send a usable package to me, thank you

**Comment by wwalc** [comment]
It looks like you are trying to use a 3rd party plugin for saving documents as PDF. In such case you should contact the author of the plugin for support.   
  
We are currently working on an official plugin to export documents to PDF. If you are interested in using it, please contact us.
