### ISSUE TITLE
Invalid link formatting in "fileUploadResponse" event API docs

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4#4062]
## Type of report

Docs

## Provide a description of requested docs changes

See https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#event-fileUploadResponse:

![image](https://user-images.githubusercontent.com/1061942/82313776-1fd8ce80-99c9-11ea-8987-4696ae2626a8.png)

**Comment by Dumluregn** [comment]
Closed in c3fd42d.
