### ISSUE TITLE
Broken links in generated docs

### ISSUE THREAD

**Issue by vokiel** [ckeditor/ckeditor4#4069]
## Type of report

Docs

## Provide a description of requested docs changes

* https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html
  - Link: http://highlightjs.org/static/test.html
* https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_dialog_definition_textarea.html
  - Link: http://unicode.org/cldr/utility/character.jsp?a=202A
  - Link: http://unicode.org/cldr/utility/character.jsp?a=202B

**Comment by f1ames** [comment]
The `http://highlightjs.org/static/test.html` link was already fixed on `master` so will be resolved with the next CKEditor 4 release.

Unicode site changed significantly (see https://home.unicode.org/ and https://unicode.org/main.html and http://cldr.unicode.org/) and I was really not bale to find something which will have similar content as old links - characters tables are now available in PDF files :thinking:

**Comment by Dumluregn** [comment]
Closed in c3fd42d.
