### ISSUE TITLE
͸ there is a problem in inserting code block HTML onclick o escape. Copy and paste cannot implement onclick event

### ISSUE THREAD

**Issue by 15836909675** [ckeditor/ckeditor4#4074]

**Comment by f1ames** [comment]
We would like to help solve your issue but it seems you have missed our [templates for feature requests and bug reports](https://github.com/ckeditor/ckeditor4/issues/new/choose). Their purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.
