### ISSUE TITLE
Double click the picture in the editor to show the mask, so other operations cannot be performed

### ISSUE THREAD

**Issue by Dream-without-trace** [ckeditor/ckeditor4#4082]
The editor saves the picture and echoes it. Open the editor again, double-click the picture echoed in the editor to show a black mask, which makes other operations impossible
<div tabindex="-1" style="position: fixed; z-index: 10000; top: 0px; left: 0px; background-color: black; opacity: 0.5; width: 1920px; height: 501px;" class="cke_ dialog_ background_ cover"></div>

**Comment by jacekbogdanski** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.
