### ISSUE TITLE
Failing tests tests/core/creators/themedui

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor4#4084]
## Type of report

Failing tests

## Provide detailed reproduction steps (if any)

Tests from `tests/core/creators/themedui` are randomly failing on the built version (`master` branch). Introduced with https://github.com/ckeditor/ckeditor4/commit/040782c393afa8819e008b1b1837b2cce0096c19

![image](https://user-images.githubusercontent.com/10279586/83140417-56f85f80-a0ee-11ea-94f8-1559be30ec49.png)

**Comment by f1ames** [comment]
Fixed in a60c055.
