### ISSUE TITLE
Event binding lost after undo command

### ISSUE THREAD

**Issue by Dreamer-Somebody** [ckeditor/ckeditor4#4091]
## Type of report

Bug

## Provide detailed reproduction steps (if any)
1. insert my own Html to editor by using setData.
2. binding events on html（In my situation is Vue instantiation）.
3. do something else...
4. execute undo command.

### Expected result

event binding is effective.

### Actual result

Event binding lost

## Other details
I think the bug is related to the implement of undo，html is saved to the undo images，but not the events（ Vue instantiation）. Is there any solution to solve this problem ?

* Browser: Google Chrome 80
* OS: win10
* CKEditor version: 4
* Installed CKEditor plugins: none

**Comment by Dumluregn** [comment]
Hello, please note there is a dedicated issue tracker for [ckeditor4-vue](https://github.com/ckeditor/ckeditor4-vue/issues) package. Please report this problem there.
