### ISSUE TITLE
url link doesn't open in ckeditor

### ISSUE THREAD

**Issue by gshneider** [ckeditor/ckeditor4#4092]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

When adding URL link such as:
[www.google.com](url)
The expected behavior on clicking the url to be open in that tab (or another tab).
instead the popup of the link is opened and there is no way to walk around this.
I searched google, but nothing seems to be working.
Only possible options are:
1.adding open link plugin which is not created by CKSource -> not an option
2.upgrade to ckeditor 5.x -> not an option

You can use one of our samples to create the reproduction sample:

* CodePen: https://codepen.io/Comandeer/pen/ExaMgpz?editors=1010
* JSFiddle: https://jsfiddle.net/Comandeer/d6ey8a2w
* JSBin: https://jsbin.com/keqekef/1/edit?html,js,output
* StackBlitz: https://stackblitz.com/edit/js-vcqfw3
-->

1. …
2. …
3. …

### Expected result

*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by f1ames** [comment]
This is  a duplicated of #2463 and also related to #3823.
