### ISSUE TITLE
After closing the dialog, the mask behind is not hidden

### ISSUE THREAD

**Issue by Dream-without-trace** [ckeditor/ckeditor4#4095]
##Report type
Error: after closing the dialog box, the mask behind will not be hidden

1. Open the editor, click the picture button to upload the picture, and then click save.

2. Select the Edit button, the editor will be opened, and the image echo in the editor will be normal. Double click the image to open the image property dialog box, stretch at will, and then click the Cancel button. The pop-up picture property dialog box closes normally, but the mask at the back of the picture property dialog box (< div tabIndex = "- 1" style = "position: fixed; Z-index: 20; top: 0px; left: 0px; background color: black; opacity: 0.5; width: 1920px; height: 947px;" class = "CK"_ dialog_ background_ Cover ">.

###Expected results
Should close with dialog
###Actual results
Dialog box closed, mask not closed
##Other details
*Browser: Google Chrome 83.0.4103.97 (official version) (64 bit)
*Operating system: Windows 10 enterprise
*Ckeditor version: 4. X
*Installed ckeditor plug in: not installed

**Comment by Dumluregn** [comment]
Hello, thank you for the report. We need more information to understand this issue. If it's possible, please create the demo presenting an issue using our template e.g. on [CodePen](CodePen: https://codepen.io/Comandeer/pen/ExaMgpz?editors=1010). Also, based on what you wrote:

> click the picture button to upload the picture, and then click save

I suppose you are using the customised editor. Please provide us its detailed configuration (list of plugins and config options).

**Comment by jacekbogdanski** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
