### ISSUE TITLE
Multiple mentions causes keyboard navigation issues

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4#4107]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Add `sourcearea` plugin to `tests/plugins/mentions/manual/mentions` test.
1. Go to http://localhost:1030/tests/plugins/mentions/manual/mentions.
1. Switch editor to source mode and back.
1. Type `$` or `#`.
1. Navigate with down/up arrow key through suggestions.

### Expected result

It's possible to navigate through panel.

### Actual result

It's not possible to navigate through panel.

## Other details

From what I have checked, the listeners are correctly attached and model/view also correctly updated. However, it seems the suggestions panel DOM element is incorrect (because there are 3 for each mentions instance) and thus not being updated. I'm not 100% sure if that's what exactly happens because I did only quick check here.

* Browser: All
* OS: All
* CKEditor version: 4.12.1 (the oldest one I checked), 4.14.1
* Installed CKEditor plugins: `mentions`

**Comment by Dumluregn** [comment]
Closed in https://github.com/ckeditor/ckeditor4/commit/21b24d9165e639d8b3333e6485e6f41aeb3e2f44.
