### ISSUE TITLE
Unable to unregister change event using removeListener method of CKEditor instance.

### ISSUE THREAD

**Issue by syedabdulaala** [ckeditor/ckeditor4#4112]
## Type of report

Bug

## Reproduction steps

1. Bind change event using "on" method of CKEditor instance.
2. Type something in the editor, the change should fire.
3. Unregister change event using the "removeListener" method.
4. Type something again in the editor.

### Expected result

*The "removeListener" method should unregister change event*

### Actual result

*Change event callback is still invoked after unregistering it using "removeListener" method*

## Other details

* Browser: Google Chrome 83.0.4103.106 (Official Build) (64-bit)
* OS: Windows 10
* CKEditor version: 4.14.0
* Installed CKEditor plugins: basicstyles, clipboard, contextmenu, enterkey, entities, font, format, indentblock, indentlist, justify, list, magicline, sharedspace, showborders, stylescombo, table, tableresize, tableselection, toolbar, undo, widget, wysiwygarea

**Comment by jswiderski** [comment]
I have just made a quick test and everything is working fine. Please make sure that you have did everything as shown in the docs:  https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#method-removeListener.

----
Test code:
```
editor.on( 'instanceReady', function( evt ){
	var myListener = function( event ) { console.log( event.name || 'empty' ) };
	evt.editor.on( 'change', myListener );
	window.setTimeout( function() {
		console.log( 'change listener removed' );
		evt.editor.removeListener( 'change', myListener );
	}, 5000 );
});
```
Result:
![obraz](https://user-images.githubusercontent.com/5314687/85153976-23c17000-b257-11ea-8bb0-6f515d720b2e.png)
