### ISSUE TITLE
Typing in Russian in some cases deletes part of the text

### ISSUE THREAD

**Issue by slashdc** [ckeditor/ckeditor4#4120]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open editor sample on android mobile phone using Chrome Mobile.
1. Change phone input language into Russian.
1. Move the caret position at the beginning of the editable text.
1. Type space.

### Expected result

Typing should work correctly i.e. input should be registered.

### Actual result

The beginning of the text is replaced by a space character.

You can observe this behavior in https://youtu.be/htejSIN3YCQ

Note that the issue probably touches all Cyrillic alphabet languages.

## Other details

* CKEditor version: 4.14.2

**Comment by jacekbogdanski** [comment]
I can't reproduce the issue with the latest CKEditor 4.14.2. and Android 10. Could you tell if you are able to reproduce the issue with the newest CKEditor? If so, please provide more details about your testing environment, like used phone, OS version, and missing reproduction steps.

**Comment by slashdc** [comment]
Hello, sir. Unfortunately the same problem
https://youtu.be/uHy2gwNdibU

**Comment by jacekbogdanski** [comment]
> If so, please provide more details about your testing environment, like used phone, OS version, and missing reproduction steps.

Could you provide this information?

**Comment by slashdc** [comment]
Hello, didn't you get my previous email? There were video link and
screenshot with phone data, but I can tell that phone and android version
is not metter. I have the same problem on all phones:
Xiaomi mi mix 2s with miui
Oneplus 7t with android 10
Samsung Galaxy a70 with android 10

I found this problem few years ago.
Just put cursor in front of any word and touch space few times. Words miss
letters.

**Comment by slashdc** [comment]
Hello, problem connect with Gboard:
https://youtu.be/tFqTP6hTg84

**Comment by jacekbogdanski** [comment]
Ok, I managed to reproduce the issue. I will update the issue description to make it more understandable.

**Comment by jacekbogdanski** [comment]
After a bit of testing, I see that the issue is caused by Chrome Mobile browser itself, as it behaves the same with native contenteditable. Please, see https://bugs.chromium.org/p/chromium/issues/detail?id=1099598 for updated on the issue status.

**Comment by slashdc** [comment]
It is really only in chrome, but not only with russian language.
