### ISSUE TITLE
Link underline style cannot be removed

### ISSUE THREAD

**Issue by jomarek** [ckeditor/ckeditor4#4121]
## Type of report

Bug

## Provide detailed reproduction steps (if any)
1) Open ckeditor (for example a [demo editor](https://ckeditor.com/ckeditor-4/demo/#document))
2) Add some text and turn it into a link.
3) Try to remove the underline style by selecting the link and clicking the underline button.

![linkbug](https://user-images.githubusercontent.com/67270210/85284058-c6176880-b48e-11ea-9dbe-a3a08ca2ec3b.gif)

### Expected result
The underline style should be removed.

### Actual result
No style changes are visible.

## Other details

* Browser: Chrome
* OS: Windows 10
* CKEditor version: 4

**Comment by jacekbogdanski** [comment]
It's just how anchor elements are represented by most browsers using their default CSS stylesheets. If you want to change this behavior you should provide your own CSS style for anchors removing this text decoration. You can do it by e.g. adding your custom CSS rule to `contents.css` file, like:

```css
a { 
  text-decoration: none;
}
```
