### ISSUE TITLE
Add info that a named function can't be listening for the same event more than once

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor4#4123]
## Type of report

Docs

## Provide a description of requested docs changes

In `editor.on()` method if named listener function is already registered, it can't be added for the second time. However it isn't mentioned in docs, so surprises occur like in #4107. As we are definitely not going to modify the event engine, we could add a mention about this behaviour to docs together with a workaround - using a wrapper function, like in https://github.com/ckeditor/ckeditor4/blob/4b9240f59b4effd86ce152ee07a5fbcb89e0b8ae/plugins/autocomplete/plugin.js#L282-L286.

**Comment by f1ames** [comment]
Fixed in d2e8445.
