### ISSUE TITLE
unable to use v-model on ckeditor 4 in vuejs

### ISSUE THREAD

**Issue by natnaelabay** [ckeditor/ckeditor4#4126]
I am working on a vue project with a simple form that sends data from bootstrap-vue form components b-form-select and b-form input and ckeditor two way data binding works perfectly for the two components but not for the ckeditor.

`app.js:57676 [Vue warn]: Error in callback for watcher "value": "TypeError: Cannot read property 'getSelection' of undefined"

    found in
    
    ---> <Ckeditor>
           <BFormGroup>
             <BTransporterSingle>
               <BModal>
                 <NoticeForm> at resources/js/components/admin/dashboard/noticeForm.vue
                   <Dashboard> at resources/js/views/admin/dashboard/dashboard.vue
                     <Index> at resources/js/views/admin/index.vue
                       <App> at resources/js/views/app.vue
                         <Root>
    warn @ app.js:57676
    logError @ app.js:58935
    globalHandleError @ app.js:58930
    handleError @ app.js:58890
    run @ app.js:61611
    flushSchedulerQueue @ app.js:61353
    (anonymous) @ app.js:59031
    flushCallbacks @ app.js:58957
    app.js:58939 TypeError: Cannot read property 'getSelection' of undefined
        at CKEDITOR.dom.selection.getNative (ckeditor.js:449)
        at new CKEDITOR.dom.selection (ckeditor.js:447)
        at a.CKEDITOR.editor.getSelection (ckeditor.js:444)
        at new CKEDITOR.plugins.undo.Image (ckeditor.js:1123)
        at CKEDITOR.plugins.undo.UndoManager.save (ckeditor.js:1117)
        at a.<anonymous> (ckeditor.js:1113)
        at a.d (ckeditor.js:10)
        at a.<anonymous> (ckeditor.js:11)
        at a.CKEDITOR.editor.CKEDITOR.editor.fire (ckeditor.js:13)
        at a.setData (ckeditor.js:279)`enter code here``

**Comment by jacekbogdanski** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.

Also, note that Vue related issues should be reported on [CKEditor 4 Vue Integration](https://github.com/ckeditor/ckeditor4-vue/issues) GH tracker.
