### ISSUE TITLE
Add npmignore and update our gitignore

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor4#4129]
## Type of report

Task

## Provide description of the task

Unwanted `.idea` directory sneaked into [CKE 4.13.0 release](https://npmfs.com/package/ckeditor4/4.13.0/.idea/). We should probably update our `.gitignore` file with settings dir for the most popular editors (mostly WebStorm and VSC).

Additionally we should also introduce `.npmignore` file with additional ignores for npm, e.g. `.github` directory is unneeded for the npm package.

**Comment by f1ames** [comment]
It also requires release script update as mentioned in https://github.com/ckeditor/ckeditor4-releases/pull/93#pullrequestreview-475284113.

**Comment by f1ames** [comment]
Done in ckeditor/ckeditor4-releases#93 and cksource/tools@1925d74.

> Unwanted `.idea` directory sneaked into [CKE 4.13.0 release](https://npmfs.com/package/ckeditor4/4.13.0/.idea/). We should probably update our `.gitignore` file with settings dir for the most popular editors (mostly WebStorm and VSC).

And as for the above [we already have it in ckeditor4 repo](https://github.com/ckeditor/ckeditor4/blob/a8edfa0ca37dd03c302472c4d62936b18438bea6/.gitignore#L8) which should be enough.
