### ISSUE TITLE
Mentions Plugin does not delete whole tag and allows tags to be edited

### ISSUE THREAD

**Issue by weiljx** [ckeditor/ckeditor4#4134]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

[Example](https://codepen.io/weiljx/pen/VweybNR?editors=1010) 

1. Type @ select a Mention Tag
2. Type some additional text
3. Go to delete or edit a portion of the edit tag

### Expected result

Editing a Mention Tag should Not Be allowed

### Actual result

The user is able to edit the contents of the mention tag. The output template does not respect contenteditable="false" with the a tag, and if using a different tag like a span when you select the mention the editor looses focus.

## Other details

* Browser: chrome
* OS: windows 10
* CKEditor version: 4
* Installed CKEditor plugins: mentions

**Comment by Comandeer** [comment]
This is the intended behaviour of CKEditor 4: to allow some specific markup, you need to configure it using [`extraAllowedContent`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-extraAllowedContent) – [example](https://codepen.io/Comandeer/pen/NWxyMgY?editors=1010).

**Comment by weiljx** [comment]
@Comandeer  You are correct. I did try that and as seen in your example - when you do that it works however the text editor looses focus when you select the tag, this forces the user to need to re-focus the editor to continue typing, This does not seem like an ideal solution, open to any ideas. Thanks

**Comment by pdaw** [comment]
@weiljx Hey, I run into the same trouble and the solution for that was adding an extra space after <a/> closing tag in outputTemplate.
