### ISSUE TITLE
Content remove when insert path in source code editor

### ISSUE THREAD

**Issue by rsenet** [ckeditor/ckeditor4#4138]
## Bug report ?

If I try to add the following code in a CKEditor source:

```
<Directory /usr/local/apache2/htdocs/listme>
  Options +Indexes
</Directory>
```

When I go back to the WYSIWYG editor, I am just able to see **Options +Indexes**, the rest of the code has been dropped

It is possible to have the same issue on the editor website: https://nightly.ckeditor.com/20-07-03-06-04/full/samples/

A bug? A bad use? Anything else?

Thank you

**Comment by Comandeer** [comment]
When inserted using source mode, this code is treated as HTML code and sanitised by our [Advanced Content Filtering mechanism](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_acf.html). To insert it as is, without interpreting it as HTML, you should replace angle brackets with appropriate HTML entities (`&lt;` and `&gt;`) or insert the text via WYSIWYG mode.

**Comment by rsenet** [comment]
Currently, the content is inserted in a MySQL database. The content is:


&lt ; Directory /usr/local/apache2/htdocs/listme & gt ;
  Options +Indexes
&lt ; /Directory & gt;

During the insertion, it is working. However, When I want to edit the data, I get them from the database and here, all the content is removed.

In summary, I can add content without any problem but I cannot update it. I tried to disable ACF (allowedContent: true) withtout any success.

Any additionnal idea?
