### ISSUE TITLE
Uncaught TypeError: Cannot read property 'options' of undefined

### ISSUE THREAD

**Issue by VizualAbstract** [ckeditor/ckeditor4#4139]
## Type of report

Bug

Wanted to report a JS error I'm encountering on version 4.13.1. Essentially, `editor.lang.contextmenu` can't be found. 

```'Uncaught TypeError: Cannot read property 'options' of undefined```

I was able to resolve the issue by making a slight change:

#### original code

```
			$: function( editor ) {
				this.base.call( this, editor, {
					panel: {
						// Allow adding custom CSS (#2202).
						css: editor.config.contextmenu_contentsCss,
						className: 'cke_menu_panel',
						attributes: {
							'aria-label': editor.lang.contextmenu.options
						}
					}
				} );
			},
```

##### Replace this:

`editor.lang.contextmenu.options`

##### With this:

`editor.lang.contextmenu && editor.lang.contextmenu.options`

**Comment by Comandeer** [comment]
Can you provide more information about your CKEditor 4 configuration? The language file should be present alongside the plugin itself.

**Comment by VizualAbstract** [comment]
Going to close the issue, it actually ended up that I had an underlining plugin that wasn't at 4.13.1, while all the others were.
