### ISSUE TITLE
"Edit Link" option in context menu (when right-clicking image that contains a link) can replace image

### ISSUE THREAD

**Issue by mborjas96** [ckeditor/ckeditor4#4146]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Add an image that contains a link (you can use the image in https://ckeditor.com/docs/ckeditor4/latest/examples/image.html and add link by editing image properties)
2. Right click the image to open the context menu
3. Notice that one of the availble options is "Edit Link"
4. Click "Edit Link" and the link dialog box will open.
5. Populate the "Display Text" field and click okay
6. Notice the image will be removed (image tag removed from the anchor tag and replaced with the "Display Text" )

### Expected result

If allowed, image link should be able to be modified without having the risk of accidentaly replacing the image. Should either:

- "Edit Link" option not be present in the context menu for images?
- "Edit Link" opens the "image dialog box: link tab" instead of the "link dialog box"?

### Actual result

Clicking edit link of image's context menu opens link dialog box which contains the display text field which allows accidentally overriting image

**Comment by Dumluregn** [comment]
Hello,
this is an expected behaviour. If user overwrites the image this way, they can always use an `undo` button to cancel the changes. Adding a different dialog is not only an overkill here but also would take away the possibility to replace an image with a text in link if that is indeed the user intention.
