### ISSUE TITLE
Bug: Removing all buttons from config.js causes HTML to break

### ISSUE THREAD

**Issue by azadnalbandian** [ckeditor/ckeditor4#4152]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Create two config files in the same location 
[readonlyconfig.js.txt](https://github.com/ckeditor/ckeditor4/files/4895932/readonlyconfig.js.txt)
[config.js.txt](https://github.com/ckeditor/ckeditor4/files/4895933/config.js.txt)
I've attached examples above, for reference -- they're virtually identical (apart from the toolbars and the removal of the Save plugin).
2. Instantiate a CKeditor instance like so (in this instance I'm using the JQuery adapter):
        var editorInstance = $(page).ckeditor(function () {
            LoadData();
        },
        {
            customConfig: '/lib/ckeditor/config.js',
            "height": 450
        }).editor;
3. Load the instances in browser with the same HTML content.

### Expected result

The two CKEditor instances should be the same, except for the removal of the toolbar icons.

### Actual result

HTML content is not parsed (at all) when using the readonly config. Changing it to use the other config, while changing nothing else, allows the HTML to be parsed correctly and properly displayed in the CKEditor instance.

## Other details

* Browser: Tested on latest Chrome and Firefox builds
* OS: Windows 10
* CKEditor version: CKEditor 4
* Installed CKEditor plugins: Save

**Comment by Dumluregn** [comment]
Hello,
when you remove buttons from the toolbar, you effectively disable the plugins. And the lack of plugins affects the [Advanced Content Filtering](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_advanced_content_filter.html) configuration, making it remove the unhandled `HTML` from the content. If you don't need plugins, but still want to keep the whole `HTML` intact, use the custom `ACF` config, like
```javascript
config.allowedContent = true;
```
This will disable the filter completely, so your `HTML` will not be truncated. On the other hand keep in mind you have to sanitise it yourself to remove invalid tags etc.

**Comment by azadnalbandian** [comment]
Thanks very much for the clarification!
