### ISSUE TITLE
Table align doesn't show label of value

### ISSUE THREAD

**Issue by samixchoumi** [ckeditor/ckeditor4#4153]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

Just click on Table > More...
Then the setting pages appear.

### Expected result

All options have a label using trad file (in my case fr.js trad).

### Actual result

No label shown :
![image](https://user-images.githubusercontent.com/22171928/87056063-61396d80-c205-11ea-80c2-b00864c59321.png)

## Other details

* Browser: chrome
* OS: Linux
* CKEditor version: 4.6
* Installed CKEditor plugins: tabletool

**Comment by jacekbogdanski** [comment]
@samixchoumi it looks like you are using some 3rd party plugin or custom editor configuration. Could you provide a minimal demo with the issue using a chosen online editor?

* CodePen: https://codepen.io/Comandeer/pen/ExaMgpz?editors=1010
* JSFiddle: https://jsfiddle.net/Comandeer/d6ey8a2w
* JSBin: https://jsbin.com/keqekef/1/edit?html,js,output
* StackBlitz: https://stackblitz.com/edit/js-vcqfw3

**Comment by samixchoumi** [comment]
Hello, with your link, i saw that the traduction of the left, center, right was wrong, in my case i've "alignLeft", "alignRight", "alignCenter" after changing it to "left", "right", "center" it works fine.
The traduction has changed ? (I'm new on the project using ckeditor)

**Comment by jacekbogdanski** [comment]
I'm not sure what do you mean. Could you attach some GIF image with the issue and provide minimal demo mentioned in https://github.com/ckeditor/ckeditor4/issues/4153#issuecomment-656518699 ?

**Comment by Comandeer** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.

**Comment by aviral2311** [comment]
I also faced the same issue. 
When I was debugging it, I found out that in Table.js 


using this -
```
items: [
                                [a.lang.common.notSet, ""],
                                [a.lang.common.alignLeft, "left"],
                                [a.lang.common.alignCenter, "center"],
                                [a.lang.common.alignRight, "right"]
                            ],
```

instead of 
```
items: [
                                [a.lang.common.notSet, ""],
                                [a.lang.common.left, "left"],
                                [a.lang.common.center, "center"],
                                [a.lang.common.right, "right"]
                            ],
```

worked. Could you please tell me the reason behind that? I am not sure what am I doing wrong.
