### ISSUE TITLE
Building docs with node 12 fails

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4#4157]
## Type of report

Docs

## Provide a description of requested docs changes

Buliding docs with node v12 fails due to older version `node-sass`, which is a dep of `@angular-devkit/build-angular`. Probably bumping these packages could be enough here.

We need to build docs with node 12 for production (due to CKEditor 5 docs).

**Comment by Dumluregn** [comment]
Closed with https://github.com/ckeditor/ckeditor4-docs/commit/af29da35ad4a77e1ce288340388da61a254c07f0.
