### ISSUE TITLE
"Undefined is not an object" when loading LTR/RTL configuration

### ISSUE THREAD

**Issue by ostrolucky** [ckeditor/ckeditor4#4164]
See sentry error we get https://sentry.io/share/issue/b66628968ae2425481622ff3b057c9b3/

Error seems to be matchin code at https://github.com/ckeditor/ckeditor4/blob/d1710c198d8f5007e8d04fed9870bfd4b182ae54/core/lang.js#L54

## Other details

* Browser: Mobile Safari 13.1.1
* OS: iOS 13.5.1
* CKEditor version: 4.14.1
* Installed CKEditor plugins: …

**Comment by jacekbogdanski** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.
