### ISSUE TITLE
Document use of CKEDITOR.dtd object

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor4#4165]
## Type of report

Docs

## Provide a description of requested docs changes

Based on https://github.com/ckeditor/ckeditor4-docs/pull/261.
However we decided this content fits better to the [`CKEDITOR.dtd` API docs](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_dtd.html) than the guides, so it should be merged to the `ckeditor4` repo instead of `ckeditor4-docs`.

**Comment by f1ames** [comment]
Fixed in #4166.
