### ISSUE TITLE
\n newline invalid

### ISSUE THREAD

**Issue by chenhua19940128** [ckeditor/ckeditor4#4176]
copy: [1,2,3,4].join("\n")
paste to ckeditor , \n is not have newline
echo: 1 2 3 4
don't is:
1
2
3
4
why?

**Comment by Dumluregn** [comment]
Hello, `\n` is not a valid HTML element, so it isn't converted to a new line. Use `<br>` elements instead.

**Comment by chenhua19940128** [comment]
First of all, thanks for your reply

<br> need Source model can insert 
![image](https://user-images.githubusercontent.com/13412354/88642823-8b3ecb00-d0f3-11ea-83e2-7a6f29a86336.png)

If I type it in directly <br>， No effect
![image](https://user-images.githubusercontent.com/13412354/88643059-cf31d000-d0f3-11ea-82e2-98484351cd95.png)

Looking forward to your reply. Thank you

**Comment by chenhua19940128** [comment]
> Hello, `\n` is not a valid HTML element, so it isn't converted to a new line. Use `<br>` elements instead.

First of all, thanks for your reply

<br> need Source model can insert 
![image](https://user-images.githubusercontent.com/13412354/88642823-8b3ecb00-d0f3-11ea-83e2-7a6f29a86336.png)

If I type it in directly <br>， No effect
![image](https://user-images.githubusercontent.com/13412354/88643059-cf31d000-d0f3-11ea-82e2-98484351cd95.png)

Looking forward to your reply. Thank you

**Comment by Dumluregn** [comment]
Thank you for clarification, but I'm still not sure, what do you need to achieve. If you are just typing in the editor, please use the `Enter` key for adding the new line. If you need to add those new lines during the editor initialisation, use `<br>`. As I mentioned before, `\n` character is not a valid HTML element and thus it is not interpreted by CKEditor.

**Comment by chenhua19940128** [comment]
> Thank you for clarification, but I'm still not sure, what do you need to achieve. If you are just typing in the editor, please use the `Enter` key for adding the new line. If you need to add those new lines during the editor initialisation, use `<br>`. As I mentioned before, `\n` character is not a valid HTML element and thus it is not interpreted by CKEditor.

thanks
