### ISSUE TITLE
Unmerge table cell disables undo

### ISSUE THREAD

**Issue by matthewtranmindtouch** [ckeditor/ckeditor4#4179]
## Type of report

Bug

### Summary

Merging table cells, saving the page, and then editing the page and unmerging the cells disables undo

## Provide detailed reproduction steps (if any)

1. Create a table and merge two cells
2. Save the page
3. Edit the page
4. Unmerge cells
5. Make another edit
6.  Try to undo with CTRL + Z or the toolbar option

![captured](https://user-images.githubusercontent.com/46456988/88694552-8b1fda80-d0b5-11ea-90ca-2b8d6805688f.gif)

### Expected result

Undo works

### Actual result

Undo stops working

## Other details
* CKEditor version: 4.7.3

**Comment by Comandeer** [comment]
Can you provide more info about plugins used in your instance of CKEditor 4? By default our [Table Tools](https://ckeditor.com/cke4/addon/tabletools) plugin does not have an "Unmerge cells" option.

**Comment by jacekbogdanski** [comment]
Hi, It's been a while since we last heard from you. We're closing this issue for now. Still, feel free provide us requested feedback, so that we can reopen this issue.
