### ISSUE TITLE
Image disappears in Safari when switching to source mode and back 

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor4#4183]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1.  Upload na image using Easy Image
2.  Switch to Source mode and back

### Expected result

Image is visible in wysiwyg mode

### Actual result

Only html is visible in source mode but there is no image in wysiwyg mode  
 

![safari](https://user-images.githubusercontent.com/5314687/88926067-b9e4af00-d275-11ea-9f8d-3b2b800a5c00.gif)

## Other details

*   Browser: Safari
*   OS: Mac
*   CKEditor version: 4.9.0 (when EI has been introduced)
*   Installed CKEditor plugins: easyimage

NOTE: Problem can be reproduced in Classic as well as DivArea editor.

**Comment by jswiderski** [comment]
Could be related to #778.

NOTE: When reproducing the problem natively, I have been only able to reproduce this problem in iframe (although in CKEditor, I can reproduce it in iframe as well as divarea) and only when dev-tools were disabled. 

```
<div id="testdiv1" style="margin:20px; width:500px; height:200px; border:1px solid black;"></div>
<script type="text/javascript">
	document.getElementById( 'testdiv1' ).innerHTML = 
	'<figure class="easyimage easyimage-full">'+
	'<img alt="" sizes="100vw" src="https://16589.cdn.cke-cs.com/Ru5MR2sQZt6979jkyNnp/images/d02e4ac3b46cb9b82c08f97e9374cf7367ff033027551aa5.png" srcset="https://16589.cdn.cke-cs.com/Ru5MR2sQZt6979jkyNnp/images/d02e4ac3b46cb9b82c08f97e9374cf7367ff033027551aa5.png/w_133 133w" width="133" />'+
	'<figcaption></figcaption>'+
	'</figure></body></html>';
</script>

<div id="testdiv2" style="margin:20px; width:500px;"></div>
<script type="text/javascript">
function createIframe() {
	var fragment = document.createDocumentFragment(),
		iframe = document.createElement( 'iframe' );
	
	iframe.setAttribute( 'width', '500px' );
	iframe.setAttribute( 'height', '200px' );
	iframe.setAttribute( 'id', 'testIframe' );
	//iframe.setAttribute( 'scrolling', 'yes' );	
	var html = '<!DOCTYPE html><html><title>Cursor Stays</title><head><meta charset="utf-8"></head><body contenteditable="true">'+
	'<figure class="easyimage easyimage-full">'+
	'<img alt="" sizes="100vw" src="https://16589.cdn.cke-cs.com/Ru5MR2sQZt6979jkyNnp/images/d02e4ac3b46cb9b82c08f97e9374cf7367ff033027551aa5.png" srcset="https://16589.cdn.cke-cs.com/Ru5MR2sQZt6979jkyNnp/images/d02e4ac3b46cb9b82c08f97e9374cf7367ff033027551aa5.png/w_133 133w" width="133" />'+
	'<figcaption></figcaption>'+
	'</figure></body></html>';
	
	iframe.setAttribute( 'src', 'data:text/html;charset=utf-8,' + encodeURI( html ) );
	fragment.appendChild( iframe );
	document.getElementById( 'testdiv2' ).appendChild( fragment );
			
}
createIframe();	
```

![](https://user-images.githubusercontent.com/5314687/88931501-3333d000-d27d-11ea-8277-46348924fd95.png)

**Comment by jswiderski** [comment]
As a workaround, users could use Inline CKEditor with Source Dialog plugin:  
[https://ckeditor.com/docs/ckeditor4/latest/examples/inline.html](https://ckeditor.com/docs/ckeditor4/latest/examples/inline.html)  
[https://ckeditor.com/cke4/addon/sourcedialog](https://ckeditor.com/cke4/addon/sourcedialog)  
  
or Classic Editor with Source Dialog plugin, but they will need to configure the toolbar to drop classic 'Source' button and replace it with 'Sourcedialog' button. Fortunately one can use, [Online Builder](https://ckeditor.com/cke4/builder) (to add Source Dialog to build) as well as toolbar configurator available in each build: https://ckeditor.com/docs/ckeditor4/latest/features/toolbar.html, [https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-toolbar](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-toolbar)

**Comment by cantonbecker** [comment]
**Note that this bug is not limited to switching back and forth from Source to WYSIWYG**. More significantly, images simply won't show on Safari if they are simply pre-loaded in the <textarea> being targeted. Switching back and forth from source is just the fastest way to demonstrate the problem.

Steps:

1) Add a <textarea> to your page which includes the HTML for a previously loaded Easy Image
2) Target the <textarea> with Ckeditor4 + easy image
3) Result: On Safari, the image will not display.

![Screenshot 2020-07-30 09 11 12](https://user-images.githubusercontent.com/4149987/88940271-cbfa2980-d244-11ea-944b-47998a904a2e.png)

**Comment by jswiderski** [comment]
@[**cantonbecker**](https://github.com/cantonbecker) **I** haven't been able to reproduce your case in inline editor. Whenever I load content from EI into inline editor, everything works as expected in my case.

![](https://user-images.githubusercontent.com/5314687/89022869-f9b5a000-d322-11ea-8f8e-56645f886be6.png)

**Comment by Comandeer** [comment]
I've reported a [bug to WebKit](https://bugs.webkit.org/show_bug.cgi?id=215375). Basically it seems that when `img` element with `[srcset]` attribute is added to dynamically created `iframe` element (like CKE4 in classic mode), then its dimensions are set to 0, despite the real dimensions, resulting in invisible image.

I wasn't able to reproduce it on non-\`iframe\` based editor.

I'm not sure if we can fix it on our side. The only solution I can think of is just forcing the image to reload, if it has 0x0 dimensions. But for editors with many images that can become cumbersome.

**Comment by Dumluregn** [comment]
Closed in https://github.com/ckeditor/ckeditor4/commit/a5ec67e968aa71ee4e25a297c49260a05451a39f.
