### ISSUE TITLE
Image upload window does not appear

### ISSUE THREAD

**Issue by bearstown1** [ckeditor/ckeditor4#4199]
## Type of report

Task

## Provide description of the task

*What steps should be taken to fulfil the task?*

## Other details

* Browser: …
* OS: … Chrome
* CKEditor version: … ckeditor_4.14.1
* Installed CKEditor plugins: …
full version
When you call up the ckeditor, the 'cke_upload' style property comes out as none. How do you solve it?
It looks like the writing below.

a class="cke_dialog_tab" cke_last="" title="업로드" style="display: none; user-select: none;" id="cke_Upload_215" href="javascript:void(0)" tabindex="-1" hidefocus="true" role="tab"업로드

**Comment by Dumluregn** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.
