### ISSUE TITLE
Path calculated in plugins/dialog/plugin.js is not plugin relative

### ISSUE THREAD

**Issue by shadowspawn** [ckeditor/ckeditor4#4207]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

I upgraded our application using ckeditor from 4.10.0 to 4.14.1. We include `dialog` as one of the plugins.

We have the plugins stored in a different location than ckeditor itself. (We also have webpack involved and a custom loading shim, but I think the key detail is using different location for plugins.)

### Expected result

`styles/dialog.css` loads (i.e. found from `plugins/dialog/styles/dialog.css`)

### Actual result

Error message in browser, which is attempting to load `styles/dialog.css` from a location relative to ckeditor (I think).

## Other details

The code in `dialog` which breaks is:
https://github.com/ckeditor/ckeditor4/blob/965f621e6ab15f7f62345b9b21785d9fdf02895d/plugins/dialog/plugin.js#L3507

```js
CKEDITOR.document.appendStyleSheet( this.path + 'styles/dialog.css' );
```

I see more flexible code in `template`:
https://github.com/ckeditor/ckeditor4/blob/d1710c198d8f5007e8d04fed9870bfd4b182ae54/plugins/templates/dialogs/templates.js#L127

```js
var plugin = CKEDITOR.plugins.get( 'templates' );
CKEDITOR.document.appendStyleSheet( CKEDITOR.getUrl( plugin.path + 'dialogs/templates.css' ) );
```

and in colordialog:
https://github.com/ckeditor/ckeditor4/blob/d1710c198d8f5007e8d04fed9870bfd4b182ae54/plugins/colordialog/dialogs/colordialog.js#L274

```js
CKEDITOR.document.appendStyleSheet( CKEDITOR.getUrl( CKEDITOR.plugins.get( 'colordialog' ).path + 'dialogs/colordialog.css' ) );
```

(I found `this.path` used in `tableselection` as well as `dialog`.)

**Comment by shadowspawn** [comment]
I tried editing the configured and downloaded `ckeditor.js` directly to use `CKEDITOR.getUrl` and `CKEDITOR.plugins.get` as seen in the other plugins, and it did not work (perhaps because needs to go through the build process?).

For my direct hack, this appears to be working:

```js
CKEDITOR.plugins.getPath("dialog")+"styles/dialog.css"
```

**Comment by jacekbogdanski** [comment]
@shadowspawn could you tell how do you load external plugins? Do you use [`CKEDITOR.plugins.addExternal`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_plugins.html#method-addExternal) method for that? From what I've checked it looks in if a plugin has been loaded via this method, its path should be corrected resolved:
https://github.com/ckeditor/ckeditor4/blob/c4a47ecbb7a8c20be3b4f6dee837a9a710f730fd/core/resourcemanager.js#L105-L108

So, if you didn't change the plugin structure by moving styles somewhere else, it should work correctly.

**Comment by shadowspawn** [comment]
Thanks, I'll dig into the details tomorrow. (I'll apologise in advance if it turns out we did something misguided!)

**Comment by shadowspawn** [comment]
Trying to answer the question for `dialog`, we don't explicitly load it. We use  <https://ckeditor.com/cke4/builder> and include `dialog` in the `plugins` property of `build-config.js`. So the line of dialog code that fails is embedded in the downloaded `ckeditor.js`.

After loading ckeditor with `require`, we set:

```js
CKEDITOR.basePath = `${prefix}third-party/ckeditor/4.14.1/`;
CKEDITOR.plugins.basePath = `${prefix}ckeditor-loading/v8/ckeditor-resources/plugins/`;
CKEDITOR.config.skin = `desktop,${prefix}ckeditor-loading/v8/ckeditor-resources/skins/desktop/`;
```

(Seeing that order, I wonder whether we should be setting an environment variable so the custom locations are available while the base ckeditor is loading. I'll research that.)

If I haven't answered the right question, please feel free to ask for different information. Thanks for the response.

**Comment by jacekbogdanski** [comment]
Thanks for the code sample. When you are using an optimized version of the build, some plugins are embedded inside `ckeditor.js` file to improve load performance. However, it also means that setting `CKEDITOR.plugins.basePath` manually will change the base path for both, embedded code and external. Using a not optimized version should resolve your issue, so all plugins are placed in an external directory.

![image](https://user-images.githubusercontent.com/10279586/91012458-6e0ff600-e5e6-11ea-8fd6-1a3c4e4161e2.png)

@shadowspawn could you check if that solution would work for you?

**Comment by shadowspawn** [comment]
Thanks for the info, that makes sense. I'll talk with my team about best way forward.

I am happy to close this issue based on this information as not-a-bug. Should I close?

**Comment by jacekbogdanski** [comment]
Indeed it's expected behavior, so we can close the issue. Let's get back to it if you find out that proposed solution didn't fix your issue.
