### ISSUE TITLE
Support inferring CKEDITOR_BASEPATH from hashed ckeditor file

### ISSUE THREAD

**Issue by markjm** [ckeditor/ckeditor4#4209]
## Type of report

Task

## Provide description of the task

Currently, CKEditor will infer the CKeditor basepath by finding a script that matches a particular regex (looking for `<basepath>/ckeditor.js`), and extracting `<basepath>` for further use. In many build processes, we hash files for long-term-caching benefits across build versions. Due to this hashing, CKEDITOR_BASEPATH could not be inferred and had to be set manually. With these proposed changes, we can extend the ability for inference to cases where ckeditor has a trailing hash.

## Other details
n/a

**Comment by jacekbogdanski** [comment]
I'm not sure if such a change wouldn't be too aggressive, see https://github.com/ckeditor/ckeditor4/pull/4210#pullrequestreview-471292407 for more details.

Let's wait for how things go with #4210 to determine what to do with this issue ticket.

**Comment by markjm** [comment]
@jacekbogdanski no problem - just thought id float the PR. I chose this regex mainly to support what seems to be fairly standard practice for hashing assets for longterm caching (ex. in webpack and the like). In these webpack-like instances (which I think are fairly standard), the hash would typically be appended as presented in this regex ([filename]-[hash of hex digits]). It could be expanded further to include all alphanumerics to cover some more nonstandard cases.

I think you are right that this is slightly a breaking change, but only in the case where someone is using ckeditor and:
1. has another feature-specific script matching the hexadecimal hash pattern naming...
2. ...hosted at a different basepath as the base ckeditor.js...
3. ...and does not have CKEDITOR_BASEPATH set.
The case feels very unlikely to me, but I'm sure you have a clearer picture of how people are using the product

**Comment by jacekbogdanski** [comment]
@markjm we did some small discussion about this change in our team. Taking into account that the CKEditor 4 already implements an option to change [base path of the editor](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_basepath.html#solution-ckeditor_basepath) we prefer to avoid possible regressions going with changes to the core editor loader.

I'm closing the issue (and PR) for now, but feel free to give us some feedback if you see that there are some other options to improve this feature, so we can reopen this ticket.
