### ISSUE TITLE
Correction in "Uploading dropped or pasted files" guide

### ISSUE THREAD

**Issue by Wizard13** [ckeditor/ckeditor4#4224]
## Type of report

Docs

## Provide a description of requested docs changes

In https://ckeditor.com/docs/ckeditor4/latest/guide/dev_file_upload.html#request-2, all mentions of `evt.requestData` should be changed to `evt.data.requestData`, as shown in 
https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#event-fileUploadRequest

**Comment by Dumluregn** [comment]
You're right @Wizard13, thanks for bringing our attention to this.
