### ISSUE TITLE
CSS for assets in docs examples are pointing to wrong place

### ISSUE THREAD

**Issue by hub33k** [ckeditor/ckeditor4#4231]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

In Sample Source Code in [Mentions, Tags and Emoji](https://ckeditor.com/docs/ckeditor4/latest/examples/mentions.html) example this CSS file `https://ckeditor.com/docs/vendors/4.14.1/ckeditor/assets/mentions/contents.css` throws 404 error.

`https://ckeditor.com/docs/ckeditor4/latest/examples/` - correct url
`https://ckeditor.com/docs/vendors/4.15.0/ckeditor/` - wrong url

### Expected result

CSS file is available.

### Actual result

CSS file is unavailable and throws 404.

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by f1ames** [comment]
I think the URL changed and the proper one is `https://ckeditor.com/docs/ckeditor4/latest/examples/assets/mentions/contents.css`.

**Comment by f1ames** [comment]
Looks like it's Umberto issue, reported.

**Comment by hub33k** [comment]
cksource/umberto#881

**Comment by f1ames** [comment]
Pinged @pomek to look at the Umberto issue so we can decide what to do next regarding this issue.

**Comment by f1ames** [comment]
@Dumluregn took over this issue.

**Comment by Dumluregn** [comment]
Fixed in https://github.com/cksource/umberto/pull/885. We should remember to update docs to the newest Umberto version after its release to see the fix live, so I'm not closing the issue yet.

**Comment by Dumluregn** [comment]
Done in https://github.com/ckeditor/ckeditor4-docs/commit/50ceadc05bd3ccd09f07fb5552daab94bfa087bb.
