### ISSUE TITLE
Mathjax unit tests fails in Chrome 85

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4#4232]
## Type of report

Failing tests

## Provide description of the task

Mathjax unit tests started to fail on Chrome 85:

![image](https://user-images.githubusercontent.com/1061942/91411463-a6167380-e848-11ea-891d-7984f484486a.png)

The plugin itself when tested manually seems to be working fine.

## Other details

* Browser: Chrome 85
* OS: All
* CKEditor version: Latest `master` / `major`
* Installed CKEditor plugins: `mathjax`

**Comment by jacekbogdanski** [comment]
Closed in #4233
