### ISSUE TITLE
Add docs about colorbutton 'preserve colors' feature

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor4#4237]
## Type of report

Docs

## Provide a description of requested docs changes

As a follow-up of #1795 we should add a few words about the feature [here](https://ckeditor.com/docs/ckeditor4/latest/features/colorbutton.html).

May collide with https://github.com/ckeditor/ckeditor4/issues/4078.

**Comment by f1ames** [comment]
Fixed in ckeditor/ckeditor4-docs@a529b36.
