### ISSUE TITLE
Failing test in `emoji/dropdown` plugin

### ISSUE THREAD

**Issue by hub33k** [ckeditor/ckeditor4#4243]
## Type of report

Failing test

## Provide detailed reproduction steps (if any)

![image](https://user-images.githubusercontent.com/3370806/91852804-9ee4d080-ec61-11ea-813c-c4090a1b49ba.png)

### Expected result

Test passes.

### Actual result

Test fails.

## Other details

Unstable. Sometimes it fails and sometimes it passes - http://0.0.0.0:1030/tests/plugins/emoji/dropdown.

When test is executed alone it passes.

Related to: https://github.com/ckeditor/ckeditor4/issues/2831 and https://github.com/ckeditor/ckeditor4/pull/3095.

* Browser: Chrome 85 (Incognito mode)
* OS: Linux
* CKEditor version: 4.15
* Installed CKEditor plugins: …

**Comment by f1ames** [comment]
Verified with Chrome (`v90`) with 4.16.1 pre-release version and test is green.
