### ISSUE TITLE
Incorrect rendering of the color button on first opening

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor4#4247]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open manual test `tests/plugins/colorbutton/manual/customclasstext`.
2. Click "Text Color" button.

### Expected result

The color panel is rendered incorrectly:
<img width="927" alt="The text Automatycznie is incorrectly positioned" src="https://user-images.githubusercontent.com/1078728/91967930-330f7000-ed14-11ea-902e-56d6613f43da.png">

### Actual result

The color panel should be rendered correctly.

## Other details

* CKEditor version: 4.7.0+ with Polish language
* Installed CKEditor plugins: colorbutton

**Comment by f1ames** [comment]
@Comandeer Is it a regression related to recent changes in color panel?

**Comment by Comandeer** [comment]
Nope, it can be reproduced since at least 4.7.0 → https://jsfiddle.net/Comandeer/3vjLn4wb/

**Comment by Comandeer** [comment]
Merged in [`0ed2a21`](https://github.com/ckeditor/ckeditor4/commit/0ed2a21bb92ccc485070f17fecf69c181827233f).
