### ISSUE TITLE
Keyboard goes down when changing line in Android Chrome

### ISSUE THREAD

**Issue by ChoSeoHwan** [ckeditor/ckeditor4#4252]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

The same symptom appears on the [demo page.](https://ckeditor.com/ckeditor-4/demo/)

1. enter any alphabet
2. press enter key 
3. android keyboard goes down. - issue 
4. press backspace key to remove line
5. android keyboard goes down. - issue 

### Expected result

Android keyboard keeps when creating or removing line.

### Actual result

Android keyboard goes down when creating or removing line

## Other details

* Browser: Chrome 85.0.4183.81
* OS: Android 10
* CKEditor version: 4.14 or higher

**Comment by JimVT** [comment]
Same thing is happening to me, it is very annoying and discouraging me from using CKEditor.

**Comment by jackwickham** [comment]
This is a chrome bug, fixed by Google in https://bugs.chromium.org/p/chromium/issues/detail?id=1121179

**Comment by Comandeer** [comment]
I can confirm that it seems to be a Chrome bug.

**Comment by f1ames** [comment]
Hi @ChoSeoHwan, @JimVT and @jackwickham. The issue was indeed a regression in Chrome v85 and is already fixed in Chrome v86.
