### ISSUE TITLE
[Android] Keyboard hides after removing a character in a word highlighted as incorrect

### ISSUE THREAD

**Issue by Mgsy** [ckeditor/ckeditor4#4256]
## Type of report

Bug

## Provide detailed reproduction steps (if any)
1. Open a sample with SCAYT.
2. Enable spellchecking.
3. Insert some incorrect word and wait until it's highlighted.
4. Put the caret at the end of this word.
5. Remove one character.

### Expected result

The keyboard is visible.

### Actual result

The keyboard hides.

## Other details

* Browser: Chrome
* OS: Android
* CKEditor version: 4.15.0

**Comment by Comandeer** [comment]
It can be connected with https://bugs.chromium.org/p/chromium/issues/detail?id=1121179, see also #4252.

**Comment by Comandeer** [comment]
It seems that it was in fact connected with the mentioned upstream issue and it's no longer reproducible.
