### ISSUE TITLE
removeButtons in config doesn't work

### ISSUE THREAD

**Issue by Mist3** [ckeditor/ckeditor4#4258]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Get standard build from a builder (ver. 4.14.1)
2. In config.js add line: 
`config.removeButtons = 'Underline,Subscript,Superscript'; `
above line should be present in the standard package

### Expected result

The underline, subscript and superscript should be hidden from toolbar.

### Actual result

The underline, subscript and superscript are visible and functional. 

## Other details

I am embedding editor in Odoo 10 using CKEditor 4.x widget.  

* Browser: Chrome
* OS: Windows
* CKEditor version: 4.14.1
* Installed CKEditor plugins: standard build

**Comment by hub33k** [comment]
We would like to help solve your issue but it seems you have missed our [templates for feature requests and bug reports](https://github.com/ckeditor/ckeditor4/issues/new/choose). Their purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.

**Comment by hub33k** [comment]
@Mist3, you leave opening comment tag in template. I fixed it.

**Comment by Comandeer** [comment]
I can't reproduce the issue, it works correctly → https://jsfiddle.net/Comandeer/v4nqjk1r/

Probably the issue is connected with the application in which the editor is embedded. @Mist3, can you check if the option works in the editor outside the Odoo?

**Comment by Mist3** [comment]
> I can't reproduce the issue, it works correctly → https://jsfiddle.net/Comandeer/v4nqjk1r/
> 
> Probably the issue is connected with the application in which the editor is embedded. @Mist3, can you check if the option works in the editor outside the Odoo?

@Comandeer in your jsfiddle you used 
`CKEDITOR.replace( 'editor', {
	removeButtons: 'Cut,Paste,Copy,Bold,Italic,Underline,Subscript,Superscript,About,Anchor,Unlink'
} );`

What I meant is that the removeButton function doesn't work in the configuration (even the one generated by the toolbar configurator) e.g .:

`/**
 * @license Copyright (c) 2003-2020, CKSource - Frederico Knabben. All rights reserved.
 * For licensing, see https://ckeditor.com/legal/ckeditor-oss-license
 */

CKEDITOR.editorConfig = function( config ) {
	// Define changes to default configuration here.
	// For complete reference see:
	// https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html

	// The toolbar groups arrangement, optimized for two toolbar rows.
	config.toolbarGroups = [
		{ name: 'clipboard',   groups: [ 'clipboard', 'undo' ] },
		{ name: 'editing',     groups: [ 'find', 'selection', 'spellchecker' ] },
		{ name: 'links' },
		{ name: 'insert' },
		{ name: 'forms' },
		{ name: 'tools' },
		{ name: 'document',	   groups: [ 'mode', 'document', 'doctools' ] },
		{ name: 'others' },
		'/',
		{ name: 'basicstyles', groups: [ 'basicstyles', 'cleanup' ] },
		{ name: 'paragraph',   groups: [ 'list', 'indent', 'blocks', 'align', 'bidi' ] },
		{ name: 'styles' },
		{ name: 'colors' },
		{ name: 'about' }
	];

	// Remove some buttons provided by the standard plugins, which are
	// not needed in the Standard(s) toolbar.
	config.removeButtons = 'Underline,Subscript,Superscript';

	// Set the most common block elements.
	config.format_tags = 'p;h1;h2;h3;pre';

	// Simplify the dialog windows.
	config.removeDialogTabs = 'image:advanced;link:advanced';
};
`

![image](https://user-images.githubusercontent.com/15092629/92382208-83b80c00-f10c-11ea-9aca-6a9f5221ef37.png)


But the configuration above is not ignored totally - if i remove section, or change order it will impact the toolbar.

**Comment by Comandeer** [comment]
I can't it reproduce even using the config you provided via external file: https://plnkr.co/edit/W0ENGAqX1zIWNnBo?open=lib%2Fscript.js
