### ISSUE TITLE
Mobile: Pressing enter key closes keyboard

### ISSUE THREAD

**Issue by fwmone** [ckeditor/ckeditor4#4259]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open Website containing ckeditor4, e. g. https://nightly.ckeditor.com/20-09-01-06-04/standard/samples/ using an Android 10 phone with Chrome and a random keyboard, I tested it with SwiftKey and Gboard.
2. Type some text and press then "enter"

### Expected result

The keyboard should stay visible.

### Actual result

The keyboard disappears. You have to touch the edit area to show it again

## Other details

Works fine in sourcecode mode. On CkEditor 5, too.

* Browser: Chrome 85 
* OS: Android 10 (tested on OnePlus 6 and Samssung S10e)
* CKEditor version: 4.14.1 or nightly
* Installed CKEditor plugins: Standard version as of https://nightly.ckeditor.com/20-09-01-06-04/standard/samples/ - plugins make no difference

**Comment by fwmone** [comment]
**Correction**: Happens not only with SwiftKey Keyboard but also with Gboard and others. It just isn't replicable using Browserstack.

**Comment by JimVT** [comment]
Same issue as #4252

I can reproduce as well.

**Comment by fwmone** [comment]
Thanks! Duplicate, so I close this one.
