### ISSUE TITLE
Hyperlink is not clickable in the `readonly` mode

### ISSUE THREAD

**Issue by holmessherlock** [ckeditor/ckeditor4#4265]
## Type of report

Bug

In my app, I needed to load `CKEditor` in the `readonly` mode (like an HTML `<textarea>` tag) just to render the HTML content, while disallowing the user to make any changes. Unfortunately, though the hyperlinks get correctly rendered, those can't be clicked anymore. If the mouse hovers over the linked word, the link is displayed in the browser's status bar, as expected. But, neither clicking the word triggers the link, nor right-clicking the word brings up the context menu. Any idea how to get around this issue?

### Expected result

The editor will disallow editing, but the existing hyperlinks will remain clickable.

### Actual result

The editor disallows editing, but the hyperlinks are not clickable. Please note, that the hyperlink still renders as a hyperlink with different formatting.

## Other details

* Browser: Google Chrome  v85.0.4183.83 (Official Build) (64-bit)
* OS: Ubuntu 18.04
* CKEditor version: 4
* Installed CKEditor plugins: Whatever comes with [flask-ckeditor](https://github.com/greyli/flask-ckeditor)

**Comment by Dumluregn** [comment]
Hello, please notice that link in editor are **never** clickable - not only in read-only, but also in editable state. The formatting for hyperlinks is preserved for the same reason as bolded text is still bolded, but it still isn't intended to allow users to click them.
