### ISSUE TITLE
The `editor-element-conflict` error still visible in React docs example

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4#4267]
## Type of report

Docs

## Provide a description of requested docs changes

It seems the error is still there, however, I'm not sure if it's caused by sample itself or integration (since we did some work there to fix it - https://github.com/ckeditor/ckeditor4-react/pull/83).

Visible on https://ckeditor.com/docs/ckeditor4/latest/examples/react.html.

![image](https://user-images.githubusercontent.com/1061942/92493863-4da28700-f1f5-11ea-8f00-94b019fccdd6.png)

**Comment by Dumluregn** [comment]
Closed in https://github.com/ckeditor/ckeditor4/commit/36dc5ffb6d0566daf806dfb74b1fdad6386f4cfb.
