### ISSUE TITLE
`onOK` handler in Mathtype

### ISSUE THREAD

**Issue by henok-tesfaye** [ckeditor/ckeditor4#4268]
## Are you reporting a feature request or a bug?
It's a feature request

<img width="716" alt="Screen Shot 2020-09-08 at 5 20 09 PM" src="https://user-images.githubusercontent.com/51118408/92489897-f9010b00-f1f8-11ea-8016-071d7e23e82f.png">

I would like to know when `OK` is clicked in Mathtype Panel. Is there `onOK` handler for this purpose?

## Other details

* Browser: Version 85.0.4183.83 (Official Build) (64-bit)
* OS: OSX
* Integration version: 
* CKEditor version: latest (`npm install ckeditor4-react`)
* Installed CKEditor plugins: https://www.npmjs.com/package/@wiris/mathtype-ckeditor4

**Comment by jacekbogdanski** [comment]
I couldn't find any information about public API for that. I would gladly ask @carlawiris for help with this issue, as we are not able to find any information on this feature. Could you tell if it's possible to listen on `click` event on OK button via public MathType API or there is some other feature that would be helpful here?

**Comment by dcanetma** [comment]
You can follow the request here https://github.com/wiris/html-integrations/issues/116
