### ISSUE TITLE
Autolink: Doesn't detect links like 'www.google.com' without 'https://'

### ISSUE THREAD

**Issue by Kitwradr** [ckeditor/ckeditor4#4269]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. …
2. …
3. …

### Expected result

*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: Chrome, Microsoft Edge
* OS: Windows 10
* CKEditor version: 4.9
* Installed CKEditor plugins: autolink,pastefromword

**Comment by jacekbogdanski** [comment]
You can customize URL regex for your's needs using [config.autolink_urlRegex](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-autolink_urlRegex).

**Comment by Kitwradr** [comment]
Thanks for quick response @jacekbogdanski
