### ISSUE TITLE
ckeditor 4 , cell properties not working

### ISSUE THREAD

**Issue by arvindpundir** [ckeditor/ckeditor4#4271]
I am using CKeditor 4 and if I try to change cell properties its giving error "Uncaught TypeError: this.getModel is not a function", I want to change the background of cells.

I am using chrome
![Screenshot_1](https://user-images.githubusercontent.com/28301987/93055465-9b514080-f688-11ea-8c0e-75be0a88e77f.png)

**Comment by Comandeer** [comment]
Could you provide some more information, like the version of CKEditor 4 you're using?
