### ISSUE TITLE
ckEditor editor.js leaking 'load' eventListener attached to the window object

### ISSUE THREAD

**Issue by rohit1** [ckeditor/ckeditor4#4273]
## Type of report

in ckEditor_base, we register 'load' event listener to window object, but never remove it

See below - 

https://github.com/ckeditor/ckeditor4/blob/8fccb33c878b0ec2bcc414d3ca2b1b85c0eafd2e/core/ckeditor_base.js#L234						`window.addEventListener( 'load', onReady, false );`

if you see in destroy function at removeAllListeners()
https://github.com/ckeditor/ckeditor4/blob/8fccb33c878b0ec2bcc414d3ca2b1b85c0eafd2e/core/editor.js#L924

![image](https://user-images.githubusercontent.com/1480600/93137295-1539f780-f692-11ea-9a57-b0dc11dfe86e.png)

Probably we should remove this from window object under onReady() function at this try block where we detach others
https://github.com/ckeditor/ckeditor4/blob/8fccb33c878b0ec2bcc414d3ca2b1b85c0eafd2e/core/ckeditor_base.js#L202
`document.removeEventListener( 'DOMContentLoaded', onReady, false );`

![image](https://user-images.githubusercontent.com/1480600/93137342-28e55e00-f692-11ea-99b2-8cc29cc2c0a5.png)

Proposing the fix from this change - 
rohit1:rohit1-ckeditor4-load-eventlistener-leak-fix

Raising a PR here for inputs on this proposed solution - 
https://github.com/ckeditor/ckeditor4/pull/4272

please advise if this is NOT the right way to fix this:)
thank you

Bug

## Provide detailed reproduction steps (if any)

1. …
2. …
3. …

### Expected result

*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by Comandeer** [comment]
Good catch! It seems that we really don't remove that `load` listener.

**Comment by Comandeer** [comment]
Merged in [`170451`](https://github.com/ckeditor/ckeditor4/commit/1704510145f39ac8c36b42c7bf7d172274706ffc) and will be released in CKEditor 4.15.1.
