### ISSUE TITLE
onChange event is getting called, but with no data, when content is added via plugin like mathtype or wiris

### ISSUE THREAD

**Issue by jvanwyk1** [ckeditor/ckeditor4#4278]
Thank you @f1ames `onChange` is now triggered. 

I'm also facing similar issue that @jvanwyk1 pointed out.

@jvanwyk1 can you please create a new ticket?

_Originally posted by @henok-tesfaye in https://github.com/ckeditor/ckeditor4/issues/3817#issuecomment-692638198_

**Comment by Comandeer** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.
