### ISSUE TITLE
Failing tests/plugins/tableselection/integrations/tabletools/tabletools tests

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor4#4287]
## Type of report

Failing test

## Provide detailed reproduction steps (if any)

1. Open http://tests.ckeditor.test:1030/tests/plugins/tableselection/integrations/tabletools/tabletools#tests%2Fplugins%2Ftableselection%2Fintegrations%2Ftabletools%2Ftabletools%20test%20delete%20nested%20cells%20(classic)

### Expected result

Test passes

### Actual result

This test and its inline counterpart fails in Safari 14:
<img width="644" alt="Screenshot 2020-09-18 at 14 56 43" src="https://user-images.githubusercontent.com/1078728/93599934-3155d580-f9bf-11ea-9935-a49065c85542.png">

## Other details

* Browser: Safari 14
* Installed CKEditor plugins: tableselection, tabletools

**Comment by Comandeer** [comment]
Seems like the failing test is connected with #4306.

**Comment by Dumluregn** [comment]
Closed in https://github.com/ckeditor/ckeditor4/commit/3b9332118865841267dff9529997876a62f43d1b.
