### ISSUE TITLE
Emojis not loaded/displayed on Chrome

### ISSUE THREAD

**Issue by FilipQL** [ckeditor/ckeditor4#4288]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

Emojis are not displayed on Google Chrome version 85.0.4183.102 (Official Build) (64-bit) (Windows 7): 

![CKEditor 4 Demo - The battle-tested WYSIWYG HTML editor - Google Chrome 2020-09-19 11 24 14](https://user-images.githubusercontent.com/18264428/93663833-d8437b80-fa6a-11ea-84ad-289849f7a824.png)

This issue exists on https://ckeditor.com/ckeditor-4/demo/ and also on the latest version of CKEditor that I get from [builder page](https://ckeditor.com/cke4/builder) (e.g. after adding Emoji plugin to the "Standard" preset) ("version:"4.15.0",revision:"cc4885b53")

No issues on Firefox.

### Expected result

Load and display Emojis on all browsers. 

### Actual result

See the uploaded image above.

## Other details

* Browser: Google Chrome version 85.0.4183.102 (Official Build) (64-bit)
* OS: Windows 7 (64-bit)
* CKEditor version: "version:"4.15.0",revision:"cc4885b53" (the latest one from from [builder page](https://ckeditor.com/cke4/builder). This issue exists on https://ckeditor.com/ckeditor-4/demo/
* Installed CKEditor plugins: Emoji

**Comment by f1ames** [comment]
Hi @FilipQL,

the `emoji` plugin uses native OS fonts. And so if the OS doesn't provide ones (as for example Windows 7) it may render emojis incorrectly. There is already a feature request reported related to this issue - #2597. Please vote with :+1: there if you find this useful.

**Comment by FilipQL** [comment]
Thanks @f1ames!
