### ISSUE TITLE
Inline editor changes the original css style of the content

### ISSUE THREAD

**Issue by pupattan** [ckeditor/ckeditor4#4289]
I am using `CKEDITOR.inline( 'editor1');` , but the ckeditor changes the original style of the div .
How to provident it ?

**Comment by Dumluregn** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.
