### ISSUE TITLE
Add info that Emoji plugin is OS-dependant

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor4#4292]
## Type of report

Docs

## Provide a description of requested docs changes

Currently there is no information that [Emoji plugin](https://ckeditor.com/docs/ckeditor4/latest/features/emoji.html) needs the system emojis to work properly. On the contrary, one can understand that CKEditor provides the emojis [by itself](https://ckeditor.com/docs/ckeditor4/latest/features/emoji.html#custom-emoji-list):

> By default CKEditor 4 comes with a list of around 1500 emojis, which is just a subset of the entire Unicode Standard.

**Comment by f1ames** [comment]
Fixed in ckeditor/ckeditor4-docs#328.
