### ISSUE TITLE
CKEDITOR.inlineAll inlines also already ckeditorized elements

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor4#4293]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open console.
2. Open https://jsfiddle.net/Comandeer/1yxjt0oL/

### Expected result

There are no errors in the console.

### Actual result

There is an error in the console:

```
ckeditor.js:19 [CKEDITOR] Error code: editor-element-conflict. {editorName: "editor"}
```

## Other details

* CKEditor version: 4.5.0+

It seems that `CKEDITOR.inlineAll` is fired after `CKEDITOR.replace` call, trying to inline element with editor already attached to it. Simple check if the element has editor should be enough.

See also #4267, ckeditor/ckeditor4-react#126.

**Comment by Dumluregn** [comment]
Closed in https://github.com/ckeditor/ckeditor4/commit/36dc5ffb6d0566daf806dfb74b1fdad6386f4cfb.
