### ISSUE TITLE
Failing tests/plugins/exportpdf/tests/statistics tests

### ISSUE THREAD

**Issue by hub33k** [ckeditor/ckeditor4#4299]
## Type of report

Failing test

## Provide detailed reproduction steps (if any)

https://travis-ci.org/github/ckeditor/ckeditor4/jobs/729892014

### Expected result

Test passes

### Actual result

`Unexpected error: CSSStyleSheet.cssRules getter: Can't access rules of still-loading stylsheet`

## Other details

* CI: https://travis-ci.org/github/ckeditor/ckeditor4/jobs/729892014
* CKEditor version: 1.16

**Comment by f1ames** [comment]
This issue is already fixed in `1.0.1` version of  `exportpdf` plugin.
