### ISSUE TITLE
Can't select last column if there is a header in the table

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor4#4306]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open https://jsfiddle.net/Comandeer/2841j0cw/
2. Try to select the last column

### Expected result

The last column can be selected.

### Actual result

The last column can't be selected or the selection is selecting the whole table.

## Other details

* Browser: Safari 14
* OS: macOS
* CKEditor version: 4.7.0+
* Installed CKEditor plugins: tableselection

Behaviour of the bug is different in different CKE4 versions:
* **4.7.0–4.12.1**: the table selection is not possible for the last column, the native selection is kicking in;
* **4.13.0+**: the table selection is activated, but it selects the first row of the table or the whole table – it can't be dragged down the column.

**Comment by Comandeer** [comment]
It seems that Safari creates correct ranges for the last column, but information about them is lost somewhere in our fake selection mechanism and `performFakeTableSelection` receives incorrect info at the end :thinking:.

**Comment by Comandeer** [comment]
I've reported the upstream issue to WebKit: https://bugs.webkit.org/show_bug.cgi?id=217221.

**Comment by Dumluregn** [comment]
Closed (actually ignored failing test and added a new one) in https://github.com/ckeditor/ckeditor4/commit/3b9332118865841267dff9529997876a62f43d1b.
