### ISSUE TITLE
Why does the Standard edition recognise the "justify" plugin?

### ISSUE THREAD

**Issue by rowild** [ckeditor/ckeditor4#4329]
## Type of report

Clarification of a riddle?

## Provide description of the riddle

Hope a stackoverflow is allowed!
https://stackoverflow.com/questions/64350734/how-to-understand-ckeditor4s-justify-option

## Other details

* Browser: Chrome, Firefox
* OS: Mac OS 10.13.6
* CKEditor version: 4.15 (latest CDN)
* Installed CKEditor plugins: Standard Edition

## Further Question

I was looking for a "favourite" place to get CKEditor support, but couldn't find any recommendation on your website nor a forum that you offer. It would be great to know, which is the most supported channel, where you guys provide support. I thought stackoverflow would be one source, but maybe you have another preference (Slack, Gitter, ...). Any chance to add this info to your website? Thank you!

**Comment by f1ames** [comment]
Hi @rowild, we usually encourage CKEditor 4 users to ask questions on SO where we or anyone familiar with the topic can answer the question and spread the knowledge this way. So this is the preferred communication channel (apart from bugs and feature request which should be reported here).

Please take a look at my answer there - https://sdk.ckeditor.com/samples/standardpreset.html :+1:

**Comment by rowild** [comment]
Thank you so much!
