### ISSUE TITLE
CK Editor font tag issue when inlining

### ISSUE THREAD

**Issue by stefan-w1** [ckeditor/ckeditor4#4331]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

Setup a ckeditor like this:
CKEDITOR.config.extraPlugins = "font";
CKEDITOR.config.font_names= "Segoe UI/Segoe UI;Frutiger;Helvetica Neue;Arial;sans-serif;MS UI Gothic";
CKEDITOR.config.height = 350;
CKEDITOR.config.width = 'auto';
delete CKEDITOR.dtd.$inline.font;
editorElement.setAttribute( 'contenteditable', 'true' );

Use following html in the editor:
![image](https://user-images.githubusercontent.com/72915758/96103187-b0173300-0ed7-11eb-80c5-fb64c8e29ca4.png)

### Expected result
All lines have the same size.

### Actual result
The line 5, 6 and 7 are of smaller font size.

I will also attach a file with a fully working sample code.

## Other details

* Browser: chrome
* CKEditor version: 4.15
* Installed CKEditor plugins: font

**Comment by stefan-w1** [comment]
Repro in this file:

[fonts_repro.zip](https://github.com/ckeditor/ckeditor4/files/5383701/fonts_repro.zip)

Open 4.15\samples\index.html in a browser, you will find that “line 5, line 5, line 7” are of a different size to the rest of the edited text. This is unexpected, as those lines should have the same size according to the input html.

The setup of the ckeditor is in 4.15\samples\js\sample.js.
(I just edited the example code for ckeditor 4.15 version).

**Comment by jswiderski** [comment]
Hello Stefan. Based on what you have shown us we believe this is not a bug but a result of invalid configuration. From what we have checked removing this line produces expected result in CKEditor - `delete CKEDITOR.dtd.$inline.font;`. If your goal is to get better control over that "font" content, we recommend using Advanced Content Filter (ACF) transformations - [https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_filter.html#method-addTransformations](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_filter.html#method-addTransformations).
