### ISSUE TITLE
Japanese/Hiragana keyboard missing text error in IE11

### ISSUE THREAD

**Issue by HariPriyaJupally** [ckeditor/ckeditor4#4332]
While using the Hiragana keyboard, after entering the text in the CKEditor and posting it, the text entered is truncated and the remaining text is missing. We can reproduce the scenario only in IE11 and works fine in chrome.

**Comment by Dumluregn** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.
