### ISSUE TITLE
Ad info about new PT errors

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor4#4334]
## Type of report

Task

## Provide description of the task

Followup for #4291. This PR added new errors connected with pasting images:

* [`pastetools-failed-image-extraction`](https://github.com/ckeditor/ckeditor4/pull/4291/files#diff-44f1423ecc041adf1f393d65e2138451f521c1e5cb543cb204d9210d55282861R51-R54),
* [`pastetools-unsupported-image`](https://github.com/ckeditor/ckeditor4/pull/4291/files#diff-44f1423ecc041adf1f393d65e2138451f521c1e5cb543cb204d9210d55282861R64-R67)

**Comment by f1ames** [comment]
Fixed in ckeditor/ckeditor4-docs#330.
