### ISSUE TITLE
insertElement() Cannot read property 'checkReadOnly' of undefined (in insertElementIntoRange)

### ISSUE THREAD

**Issue by epchristi** [ckeditor/ckeditor4#4335]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

I don't yet have an independent small piece of code that reproduces this defect. But we are using CKEDITOR 4.13.1 in a production environment and a customer has an image that cannot be replaced, when we try do call insertHtml with a new image to replace it. We are using multiple editors on this page.

1. …
var newImage = CKEDITOR.dom.element.createFromHtml(contents, CKEDITOR.dialog.getCurrent().getParentEditor().document);
2. …
var newImage = CKEDITOR.dom.element.createFromHtml(contents, CKEDITOR.dialog.getCurrent().getParentEditor().document);

### Expected result

Image should replace existing content. (Which works in most cases.) 

### Actual result

ckeditor.js?E304:formatted:8658 Uncaught TypeError: Cannot read property 'checkReadOnly' of undefined
    at b.insertElementIntoRange (ckeditor.js?E304:formatted:8658)
    at b.insertElement (ckeditor.js?E304:formatted:8642)
    at b.<anonymous> (ckeditor.js?E304:formatted:8859)
    at a.l (ckeditor.js?E304:formatted:136)
    at a.<anonymous> (ckeditor.js?E304:formatted:200)
    at a.CKEDITOR.editor.CKEDITOR.editor.fire (ckeditor.js?E304:formatted:244)
    at a.insertElement (ckeditor.js?E304:formatted:6764)

## Other details

I verified in the "insertElementIntoRange" that the second argument is undefined, and there is a dereference of checkReadOnly() on it, without validating its a valid object. This happens, because in insertElement, the call to ".getRanges()" returns an empty length iterator. But the argument is assigned to the [0] element of the range, which doesn't exist.
(form the minified version:) 

 b || (b = d.getRanges()[0]);
 this.insertElementIntoRange(a, b)

It would seem that before accessing the 0th element of the array, it should check if it's empty. (And in insertElementIntoRange, it would seem there should be a  "b && b.checkReadOnly()" -- this protecting against an undefined.

After looking further, that won't resolve the issue. "the second argument" looks like the element to be replaced, because of the call to "deleteContents." So it would seem that the original getRanges() needs to return a valid range, but for some reason is not. I can do additional debugging if someone can help me understand why getRanges might fail to return anything in the array. It does appear to return an object with CreateBookmarks, createBookmarks2, createIterator and moveToBookmarks, with a length of 0.

* Browser: … Chrome
* OS: … Linux / Windows
* CKEditor version: … 4.13.1
* Installed CKEditor plugins: …

**Comment by jacekbogdanski** [comment]
@epchristi please provide some code demo with the issue. You could use e.g.

* CodePen: https://codepen.io/Comandeer/pen/ExaMgpz?editors=1010
* JSFiddle: https://jsfiddle.net/Comandeer/d6ey8a2w
* JSBin: https://jsbin.com/keqekef/1/edit?html,js,output
* StackBlitz: https://stackblitz.com/edit/js-vcqfw3

We won't be able to debug the issue without proper reproduction steps, partial code, or from minified JS.

**Comment by epchristi** [comment]
I will work on that. However, I must just add, that tools like bugsnag could be implemented so paying customers don't also have to pay to triage the code they purchase. It's clear that others have reported this issue over time and I have a reproducible case inside of the environment we use it in. (happens every time-- and from what I can tell you, it's when there is a certain html layout.) The layout is <div><a><img/></a></div> -- in this context, trying to replace the <img> will result in this path. Again, I will continue to narrow it down into a reproducible step, which will take time. (and if you used triage libraries, you could probably already have the call stack and other meta data that led to the failure, without requiring customers to do extra work.)

**Comment by jacekbogdanski** [comment]
@epchristi if you have CKEditor license, you can always contact our support team which could help with your custom editor implementation. However, we still need anything reproducible to be able to find out what's wrong and tell if it's CKEditor bug or invalid API usage. I appreciate your debugging feedback, however, we just need a chunk of incorrectly working code or a small demo. Since you are using custom editor implementation, we are not able to tell what's wrong just by using the default editor setup.

**Comment by epchristi** [comment]
I have initiated contact with the support team on this issue, for help reproducing it outside our environment. I am waiting to hear back on the best way I can help triage this issue.

**Comment by jacekbogdanski** [comment]
Since the issue is managed by the support team I'm closing this ticket.
