### ISSUE TITLE
CKEDITOR.ui.get() method docs lack the return value

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor4#4337]
## Type of report

Docs

## Provide a description of requested docs changes

[CKEDITOR.ui.get()](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_ui.html#method-get) returns a UI object, which is not documented.

**Comment by sculpt0r** [comment]
Fixed in: https://github.com/ckeditor/ckeditor4/pull/4714
