### ISSUE TITLE
Since update to 4.51.0 with bbcode plugin render in html but not in bbcode

### ISSUE THREAD

**Issue by xillibit** [ckeditor/ckeditor4#4341]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

Use CKeditor 4.51.0 with bbcode plugin, i share my build config to use the same plugins : https://gist.github.com/xillibit/5fce34992f1ad8edacc6f3cf547acfae

### Expected result

When looking at the source in editing area it should be bbcode

### Actual result

When looking at the source in editing area it renders HTML

## Other details

* Browser: Firefox 81.0.2
* OS: Windows 10 2004
* CKEditor version: 4.15.0
* Installed CKEditor plugins:look the build config

**Comment by Comandeer** [comment]
I can't reproduce the issue, source view displays BBCode for me: https://jsfiddle.net/Comandeer/fjzc9pwo/

Could you provide some simple demo of the issue?

**Comment by xillibit** [comment]
I generated a new optimised CKeditor package from the online builder this time teh source view show right the bbcodes
