### ISSUE TITLE
widget template defaults/variables support

### ISSUE THREAD

**Issue by voborl00** [ckeditor/ckeditor4#4344]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

we are using ck editor 4.15.0 for visual editation of email templates which contains variables wrapped in { } brackets

when using default simplebox (or any other widget) config with template definition containing these { variables } definition, for example

CKEDITOR.plugins.add( 'simplebox', {
    requires: 'widget',

    icons: 'simplebox',

    init: function( editor ) {
        editor.widgets.add( 'simplebox', {

            button: 'Create a simple box',

            template: '<h1>{firstName}</h1>'
...
...
}

ckeditor fails to use/execute this widget as there is no function defaults property for this template object

Uncaught TypeError: Cannot read property 'firstName' of undefined
    at ckeditor.js:361
    at String.replace (<anonymous>)
    at CKEDITOR.template.output (ckeditor.js:361)
    at CKEDITOR.command.exec (ckeditor.js:1184)
    at CKEDITOR.command.exec (ckeditor.js:219)
    at a.execCommand (ckeditor.js:292)
    at CKEDITOR.ui.button.CKEDITOR.tools.extend.click (ckeditor.js:689)
    at Object.execute (ckeditor.js:690)
    at ckeditor.js:691
    at ckeditor.js:33

### Expected result

either ignore bracketed { variables } in widget template definition or add support for defining their "defaults" or point us some standard way how to use widget template with bracketed {variable}

as workaround add

b.defaults=function(){return {}};

just after

b=CKEDITOR.tools.prototypedCopy(b);
b.name=a;

**Comment by Comandeer** [comment]
There is [`defaults` property in widget's definition](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_plugins_widget_definition.html#property-defaults) that can be used to set default values for template's variables. Example: https://jsfiddle.net/Comandeer/qmngk823/
