### ISSUE TITLE
Failing tests: /tests/plugins/mathjax/mathjax

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor4#4345]
## Type of report

Failing tests

## Provide detailed reproduction steps (if any)

Tests from `/tests/plugins/mathjax/mathjax` suite are failing randomly. It looks like ios is not able to close the mathjax dialog.

Used IPhone 11 pro max with XCode.

![image](https://user-images.githubusercontent.com/10279586/97708679-76d6e980-1ab9-11eb-9bdd-c89bf12187b9.png)

**Comment by f1ames** [comment]
Verified with Safari Mobile on iOS (`14.5.1`) with `4.16.1` pre-release version and tests are green.
