### ISSUE TITLE
Add support for CSS class and ID in bulleted/numbered list dialogs

### ISSUE THREAD

**Issue by mvl22** [ckeditor/ckeditor4#4361]
## Type of report

Feature request

## Provide description of the new feature

The bulleted/numbered list dialogs allow alignment, but do not have any means to specify a class (or ID).

It would be useful for those to be able to be set without having to edit the HTML source.

**Comment by Dumluregn** [comment]
Hello! This is possible right now. You can predefine [custom styles](https://ckeditor.com/docs/ckeditor4/latest/features/styles.html) for [Styles Combo plugin](https://ckeditor.com/cke4/addon/stylescombo) (remember to mark them as the correct [object styles](https://ckeditor.com/docs/ckeditor4/latest/features/styles.html#style-types)) and this way lists may use any class you need.
