### ISSUE TITLE
"writer.setRules" migrate information missing

### ISSUE THREAD

**Issue by rowild** [ckeditor/ckeditor4#4364]
## Type of report

Docs

## Provide a description of requested docs changes

When switching from CKEditor 4 to 5, it would be great to somehow know, what to do with "setRules", e.g.:

```js
        this.dataProcessor.writer.setRules( 'br', {
          indent: false,
          breakBeforeOpen: false, // instead of "true"
          breakAfterOpen: false,
          breakBeforeClose: false,
          breakAfterClose: false // instead of "true"
        });
```

Even though I search hard through all available docu and stackoverflow, I do not find any single hint on how such a configuration – should it be necessary or even  possible at all –  is done in CKEditor 5.

IMO the plugin "HTML Output Writer" as well as places like this one `https://ckeditor.com/docs/ckeditor4/latest/features/output_format.html` should either explain, what to do when a migration to v5 is planned, or link to a document.

My question on stackoverflow is still unanswered:
https://stackoverflow.com/questions/64711461/how-does-ckeditor-5-handle-what-was-ckeditor-4s-writer-setrules

Maybe someone of you reading this can find a moment and provide an answer there, too. This would also help people, who look for this topic. Thank you very much!

**Comment by rowild** [comment]
Any chance to get an answer on stackoverflow, please? Would be really, really helpful! Thank you!

**Comment by Dumluregn** [comment]
Hello!
As mentioned in the [CKE4->CKE5 migration guide](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/migrate.html), CKEditor 5 is entirely new editor and not all configuration options existing in CKE4 are available there, and the one you are asking about is one of those. Similar issue was mentioned [here](https://stackoverflow.com/questions/47555667/ckeditor-5-htmlencodeoutput-doesnt-work). 

However in your use case it should not be too difficult to use the external tools to achieve what you need - just use some kind of HTML beautifier to format the code any way you need.

**Comment by rowild** [comment]
@Dumluregn Thank you for your answer! – I know the migration guide. I actually read a lot of docu, before I posted here. However, the problem is still not solved or cleared up, therefore please do not close this issue so fast.

Do I understand you correctly, that CKEditor 4 no longer offers a possibility to define formatting rules on a per-tag basis? Does CKEditor format the source code at all?

Just to clarify my scenario: I need to format the code **within** CKEditor source view (not in the outputted HTML, that's not a problem). If this can be done via external tools, please refer me to a snippet, which show, how and where.

My situation happens within a backend application (an e-commerce software), where during development a lot of debugging is done (php, var_export() --> displays huge white space areas cause immense scrolling times).

**Comment by Dumluregn** [comment]
Hi,
I closed the issue because our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them.

Answering to your question - yes, CKEditor 5 doesn't have a source mode - you can read more about it in [FAQ](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/faq.html#how-to-turn-the-source-mode-on-how-to-write-a-source-mode-plugin).

If you have CKEditor license, please contact our support team - we will try to dive deeper into how we can make your migration complete.

**Comment by rowild** [comment]
I understand the reason for closing, but you also say that there is support via Stackoverflow, but my question remains unanswered there. So what to do if not bothering you guys here? Sorry for that. Of couse it would be better if you could anser on SO... Maybe i can motivate you to do so.

**Comment by Dumluregn** [comment]
Well, I could answer on SO too, but it will be basically the same as my first comment here - so I'm not sure what is the difference 🤔  If you need to format code before saving (as I understood your question at first) - please use another tool for HTML formatting (e.g. [`pretty`](https://www.npmjs.com/package/pretty)) and inject it between the editor and database. If this concerns the source code in the editor, then the issue doesn't exist at all as CKEditor 5 doesn't have source mode. So I'm a little confused about how else can I help you.

**Comment by rowild** [comment]
@Dumluregn Again- thank you for your report! Your "confusion" helped me to understand CKEditor 5 better. I think I grasped the idea of data modules, missing source and adding plugins for unknown html5 elements.

As for answering: I actually thought from the beginning , that my question would be answered on SO,  since I am aware that github is not a QA forum. This is why posted a link to my question. But everything ok now. 

Have a good day and stay safe!
