### ISSUE TITLE
Invalid "See source" links for SCAYT/WSC config option

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4#4368]
## Type of report

Docs

## Provide a description of requested docs changes

Previously there were no links at all. Since the build process changed a little, `See source` button appeared suddenly (not sure why ATM) and links are invalid:

![image](https://user-images.githubusercontent.com/1061942/98568423-60970d80-22b1-11eb-9bda-dae2de0308aa.png)

We can either go with `@skipsource` or try to fix the links to point to SCAYT/WSC GH repos.

**Comment by f1ames** [comment]
Caused by this change most probably - https://github.com/ckeditor/ckeditor4-docs/blame/81b494d4033141fea5d3796d1c7cfdc1b5d7412c/gruntfile.js#L164.

**Comment by sculpt0r** [comment]
I moved `ckeditor4`, `ckeditor4-docs` and `ckeditor4-presets` to commit `@{'27 days ago'}. Then builded docs with `--dev` flag.
There are errors about angular, vue and react, but finally with flag `--force` build finished.

Also there are warnings about `scayt` missing doclets, but 'source code` button is present.

**Comment by sculpt0r** [comment]
I've built docs with `--dev` flag and `ckeditor4-presets` at `4.15.0` tag and... There is `see source` button. Leading to an invalid path, but on [official 4.15.0 docs](https://ckeditor.com/docs/ckeditor4/4.15.0/api/CKEDITOR_config.html#cfg-scayt_autoStartup) button is gone :thinking:

**Comment by f1ames** [comment]
> I've built docs with `--dev` flag and `ckeditor4-presets` at `4.15.0` tag and... There is `see source` button. Leading to an invalid path, but on [official 4.15.0 docs](https://ckeditor.com/docs/ckeditor4/4.15.0/api/CKEDITOR_config.html#cfg-scayt_autoStartup) button is gone

Interesting... :thinking: Are you sure docs haven't used your local `ckeditor4-presets` or maybe you have local SCAYT/WSC plugin leftovers from previous build? Because changing presets only should not work with latest docs due to different SCAYT/WSC paths defined in Gruntfile.

Also `4.15.0` docs were build with older Umberto version... (but if that's the case it would mean this regression was introduced due to changes in Umberto) :thinking:

**Comment by sculpt0r** [comment]
I make sure about caching after previous builds.

In mean-time I found probably what is responsible for missing `see source` buttons:

Can't link to `umberto` repository, but in `node_modules` found method responsible for building links to `see source` button.
There is strange `if` inside file `src\helpers\github-url.js`, and then method `utils.getFullGithubLink()`:
```js
if ( filePath.endsWith( '/wsc/plugin.js' ) || filePath.endsWith( '/scayt/plugin.js' ) ) {
	return null;
}
```

And `gruntfile.js` history says that plugins were linked like this:
```
'repos/ckeditor-presets/plugins/scayt',
'repos/ckeditor-presets/plugins/wsc'
```
I assume that there is some method which add `plugin.js` to the plugin path. In that case: old URLs match the previously mentioned `if` so no `see source` link was generated.

That could be an explanation for missing links, but still not resolving an issue with current invalid URLs.

**Comment by sculpt0r** [comment]
@f1ames - based on https://github.com/ckeditor/ckeditor4/issues/4368#issuecomment-734111041 it looks like we should make `@skipsource` since someone adds to umberto `// Ignore third party plugin providers (CKE4)` comment?
It appears - it was intentionally - so we should stick with this?

**Comment by f1ames** [comment]
https://github.com/ckeditor/ckeditor4/issues/4368#issuecomment-734111041 - nice catch @sculpt0r :+1: That's, unfortunately, the worst case scenario so hardcoded stuff in Umberto itself... :see\_no\_evil:  

I think the most correct solution would be getting rid of this check in Umberto itself (so we get more cleaner, less-custom code). And then add `@skipsource` annotations to SCAYT/WSC docs (`@skipsource` was introduced recently so that's the reason I suppose we went this way some time ago). Keep in mind that SCAYT/WSC source code is held in separate repos (maintained by WebSpellChecker Team) so we need to fork and add PRs there.

Ofc, we could add `@skipsource` during docs build with some replace magic, but let's stick to proper solution without introducing another workarounds.

**Comment by sculpt0r** [comment]
Builded docs with `grunt build-serve --dev`, with `@skipsource` in one of scayt properties.
As we talk @f1ames : `ckeditor4-docs` repo under `docs/api/data/CKEDITOR.config.json` contains `skipsource` tag - so it was parsed properly. There are also this tags for `exportpdf` plugin.
However final docs still contain `see source` button. Same for `exportpdf` plugin. Current online docs don't have `see source` for `exportpdf`.

So either I'm doing something wrong with docs building or something broke in some weird way...

**Comment by sculpt0r** [comment]
Plugins PRs merged:
https://github.com/WebSpellChecker/ckeditor-plugin-scayt/pull/179
https://github.com/WebSpellChecker/ckeditor-plugin-wsc/pull/60

Umberto PR is waiting:
https://github.com/cksource/umberto/pull/892

@f1ames write to `WebSpellChecker` to tag new version. After this - we could bump plugins versions in `package` in `ckeditor4-presets`

**Comment by sculpt0r** [comment]
@f1ames I see that both plugins have new releases, but those are still the same commit - without our changes?

**Comment by f1ames** [comment]
@sculpt0r Well, maybe let's update to specific git hash from `master` and when the change is propagated to a new tag we can use this tag then. It will be good to close this since it's blocked for more than a month already.
