### ISSUE TITLE
scayt language not change after setData

### ISSUE THREAD

**Issue by mesutsevgin** [ckeditor/ckeditor4#4373]
Hi,
I am trying to change scayt language and set data.    editor.scayt.setLang("en-US")  change the scayt language but when  editor.setData work editor.scayt is getting undefined. how can i fix this?

var editor = CKEDITOR.replace('editor3', {
                language: "es",
                scayt_autoStartup: true,
                scayt_sLang: "es-ES",
                scayt_disableOptionsStorage: 'lang',
                scayt_uiTabs: '0,0,0',
                scayt_contextCommands: "off",
                scayt_ignoreAllCapsWords: true,
                scayt_ignoreWordsWithMixedCases: true,
                scayt_ignoreDomainNames: true,
                scayt_maxSuggestions: 3,
                grayt_autoStartup: true,
                removePlugins: "wsc,wordcount",
                enterMode: CKEDITOR.ENTER_BR,
                shiftEnterMode: CKEDITOR.ENTER_BR,
                height: 200,
                forcePasteAsPlainText: false
            });

       function setDataAndChangeLanguage() {
            editor.scayt.setLang("en-US");
            editor.setData("Lorem Ipsum is simply dummy text of the printing and typesetting industry", {noSnapshot: true});
        }

**Comment by jacekbogdanski** [comment]
@mesutsevgin from what I see you are using private API which isn't really recommended. I didn't find out any public API which could allow you to change SCAYT language, but I've opened a ticket on WebSpellChecker issue tracker for that feature - https://github.com/WebSpellChecker/ckeditor-plugin-scayt/issues/178

Please, follow the linked ticket for updates on the issue.
