### ISSUE TITLE
Cursor on editor displays on print dialog.

### ISSUE THREAD

**Issue by rkarina94** [ckeditor/ckeditor4#4392]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

When you press the print button with the text cursor displayed, it also shows on the print dialog.

1. Put sample text on the editor and make sure it's focused.
2. Press the print button when the text cursor is showing.

### Expected result

Expecting only the sample text to be displayed on the print dialog.

### Actual result

The text cursor also shows with the sample text.

Have attached screenshots.

[
![Print_Issue#1](https://user-images.githubusercontent.com/28332589/99895777-1ca6fe00-2cde-11eb-880d-f81e80b57bd4.PNG)
](url)
![Print_Issue#2](https://user-images.githubusercontent.com/28332589/99895779-1dd82b00-2cde-11eb-8815-ff3920b8396f.PNG)

## Other details

Browser: Chrome
OS: Windows 10
CKEditor version: 4.11.4

**Comment by Comandeer** [comment]
It's an upstream issue in Chromium, I've reported it: https://bugs.chromium.org/p/chromium/issues/detail?id=1151724
