### ISSUE TITLE
Forms value change with double click

### ISSUE THREAD

**Issue by gaproset** [ckeditor/ckeditor4#4395]
Feature request

Provide detailed reproduction steps (if any)
I have installed the forms plugin.
When i press to create a new textfield, the pop up comes up and i insert the details i need.
After that, when i double click the input/textfield in the editor, the same popup appears. 
Can we change the effect of the double click to change the value at once, and not show the dialog?

Other details
Browser: chrome
OS: windows
Integration version:
CKEditor version: "ckeditor4": "^4.15.1",
"ckeditor4-react": "^1.2.1",
Installed CKEditor plugins:  forms

**Comment by f1ames** [comment]
Hi @gaproset,

This is the standard behavior for most elements inserted via dialog. It is consistent across all plugins, allows easy editing of the element properties and makes working with the editor simpler.

The feature you have requested is doable and can be done thanks to flexible [CKEditor 4 API](https://ckeditor.com/docs/ckeditor4/latest/api/index.html) but we are not planning to work on such change any time soon.
