### ISSUE TITLE
where is builder.jar?

### ISSUE THREAD

**Issue by piotr-nikolajuk** [ckeditor/ckeditor4#4401]
I cant find dev/builder/ckbuilder/2.3.2/ckbuilder.jar in repo. Please help.

1. …
2. …
3. …

### Expected result

*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by Dumluregn** [comment]
Hello, refer to [this line](https://github.com/ckeditor/ckeditor4/blob/major/dev/builder/build.sh#L13) - https://download.cksource.com/CKBuilder/2.3.2/.
