### ISSUE TITLE
CKEdtior 4.15.1 generating a get request with [object%20Object]

### ISSUE THREAD

**Issue by RummanSadiq** [ckeditor/ckeditor4#4403]
## Type of report

Bug

When I click on the formatting drop down in the toolbar this request is generated which resolve to 404 on production. Request is initialized from ckeditor.js:92

<img width="1439" alt="Screenshot 2020-11-26 at 12 08 44 PM" src="https://user-images.githubusercontent.com/20723068/100318981-c2a97f80-2fe0-11eb-9f09-a778a1455b20.png">

* Browser: Chrome
* OS: MacOS
* CKEditor version: 4.15.1
* Installed CKEditor plugins: none

**Comment by Dumluregn** [comment]
Hello, I'm unable to reproduce the issue using [our CDN](http://cdn.ckeditor.com/4.15.1/full-all/samples/). Please, provide us more information and demo where we can see the error.
