### ISSUE TITLE
Toolbar is out of the top page when maximized and scroolbar is needed

### ISSUE THREAD

**Issue by Lorantus** [ckeditor/ckeditor4#4404]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

Hello.

https://github.com/ckeditor/ckeditor4/issues/3584
The bug is "closed" but I am facing the same bug.

It appears when the preloaded text is longer (more lines) that the input area. In fullscreen mode the scroll bar is needed.

The toolbar is visible when I use the devtool to change the CSS of the element with .cke_maximized rule to "uncheck top: 0px;".
The maximize is ok when I set "top: 76px" which the exact toolbar height + 1px.

Note : the toolbar is visible and working well in fullscreen if I click anywhere in the input area before.

Any idea ?

Thanks for consideration.

### Expected result

See the toolbar -but I think is "See the top of the page".

### Actual result

At the setup and without typing in, fill the input area with as much lines as needed to show the scroll bar when full-screen is requested.

When page is ready, without click inside input area, maximize the editor. The toolbar is hidden.

When maximize after click inside input area is working well.

## Other details

* Browser: FireFox 83.0
* OS: Linux 5.4.0-54
* CKEditor version: 4
* Installed CKEditor plugins: …

**Comment by Dumluregn** [comment]
Hello, this issue is still irreproducible for me:
![firefox-maximize](https://user-images.githubusercontent.com/10883184/100333985-7e63b280-2fd3-11eb-93f5-3991a101de8c.gif)

I'm afraid you need to provide more detailed steps, maybe demo or recording of the issue. Without it we can't do much.

**Comment by Lorantus** [comment]
Hello,

In the html page I found a div with a "position: absolute" rule. Commenting this part of code and ckeditor works as expected.

To keep the div with this "position: absolute" I wrote a listener the "maximize" event and forced the focus to the ckeditor instance :
```javascript
on: {
    beforeCommandExec: function(evt) {
    if (evt.data.name === 'maximize' && evt.data.command.state === CKEDITOR.TRISTATE_OFF) {
        evt.editor.focus();
    }
}
```
