### ISSUE TITLE
Page scroll when paste text

### ISSUE THREAD

**Issue by yucomds** [ckeditor/ckeditor4#4405]
## Type of report

Bug

When pasting a text with some empty rows at the end, the page scroll down (or up in some rare cases).  See following image for demo.

![Image](https://s2.gifyu.com/images/ticketing-2020-11-24.gif)

### Expected result

Page should remain in the current position

### Actual result

The page scroll down/up

## Other details

* Browser: Chrome Version 87.0.4280.66 (64 bit)
* OS: Tested on Ubunti 18.04 and Windows 10
* CKEditor version: v4.15.1
* Installed CKEditor plugins: Full package from the official website

**Comment by Dumluregn** [comment]
Hello, this issue is not reproducible on [our CDN page](http://cdn.ckeditor.com/4.15.1/full-all/samples/). I see you are using the custom integration. Is the bug present on any official CKEditor 4 demo?
