### ISSUE TITLE
How do i ignore the particular pattern on SCAYT

### ISSUE THREAD

**Issue by tbhaxor** [ckeditor/ckeditor4#4410]
## Type of report

Docs

## Provide a description of requested docs changes

I want to intentionally enable SCAYT and ignore spell checking for the following pattern `{{ ? (.+?) ?}}`

**Comment by f1ames** [comment]
Hi @tbhaxor, both SCAYT and WSC are third party plugins developed by the [WebSpellChecker](https://github.com/webspellchecker) organization.

Please report ticket directly in [SCAYT](https://github.com/WebSpellChecker/ckeditor-plugin-scayt) or [WSC](https://github.com/WebSpellChecker/ckeditor-plugin-wsc) repositories.
