### ISSUE TITLE
Drupal 8 CKeditor from stripping out INS code

### ISSUE THREAD

**Issue by raj190888** [ckeditor/ckeditor4#4415]
## Type of report

Prior in D7 this same problem was there but I solved it adding this lines --

config.protectedSource.push( /<ins[\s|\S]+?<\/ins>/g) in Config file

But in D8, i am not able to find config file. So how to stop D8 CKeditor from stripping out INS code which is very important in Adsense codes

**Comment by f1ames** [comment]
> But in D8, i am not able to find config file. So how to stop D8 CKeditor from stripping out INS code which is very important in Adsense codes

This looks like a Drupal 8 related question as in CKEditor 4 [`protectedSource` config](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-protectedSource) is still available in the latest versions and could be adjusted the same way you mentioned. Please refer to Drupal 8 docs or ask for help on Drupal 8 support channels.
