### ISSUE TITLE
Nesting block/inline widgets problems

### ISSUE THREAD

**Issue by voborl00** [ckeditor/ckeditor4#4426]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

I have defined two widgets which I could not successfully nest into each other using all possible combination of defining their "inline" widget property true/false and their "template" property using div/span.

nested widget:
template: `<div class="n_w">...</div>`,
inline: false

same definition for all 4 inline/block span/div combination
both widgets have also custom dialog definition (dialog: dialog.js)

 
Combination 1 
parent widget:
template: `<div class="p_w">{content}</div>,`
inline: false
generated code: `line1<br/><div ... class="cke_widget_wrapper ..."><div class="p_w cke_widget_element"><div class="n_w"> ...`
ckeditor.getData(): `line1<div class="p_w"><div class="n_w">`

block parent widget removes `<br/>` - could be somehow fixed without affecting some global CKE behaviour?

Combination 2
parent widget:
template: `<div class="p_w">{content}</div>`,
inline: true
generated code: `line1<br/><span class="cke_widget_wrapper ..."><div class="p_w cke_widget_element"><div class="n_w"> ...`
ckeditor.getData(): TypeError: Cannot read property 'attributes' of null at ckeditor.js:991 at CKEDITOR.htmlParser.element.forEach (ckeditor.js:321)

bug? while getting widget params ("1" != e.attributes["data-cke-widget-keep-attr"] && delete e.attributes["data-widget"]) on null object of desired cke widget element which exists but is span instead of div

Combination 3
parent widget:
template: `<span class="p_w">{content}</span>`,
inline: true
generated code: `line1<br/><span class="cke_widget_wrapper ..."><span class="p_w cke_widget_element"><div class="n_w"> ...`
ckeditor.getData(): ckeditor.js:991 Uncaught TypeError: Cannot read property 'attributes' of null at ckeditor.js:991 at CKEDITOR.htmlParser.element.forEach (ckeditor.js:321) at CKEDITOR.htmlParser.element.forEach (ckeditor.js:321)           

bug? while getting widget attrs ("1" != e.attributes["data-cke-widget-keep-attr"] && delete e.attributes["data-widget"]) on null object

Combination 4
parent widget:
template: `<span class="p_w">{content}</span>`,
inline: false
generated code: `line1<br/><div ... class="cke_widget_wrapper ..."><span class="p_w cke_widget_element"><div class="n_w"> ...`
ckeditor.getData(): `line1<span class="p_w"></span>`

even inline span widget removes `<br/>` (bug? because "dataFormat" input contains artificial `<div cke_widget_wrapper>` div which causes `<br/>` removal?)
and in addition content (=nested widget) is removed at whole

What I need, and could not anyhow achieve is to have parent widget defined as `<span>` (or maybe as `<div style="display: inline;"`) in order not to affect new lines/`<br/>` and be able to have more of them in one line, which can contain block/`<div>` widget inside.
My use case is building rich UI for defining IF-ELSE condition where parent widget is rich dialog containing two inputs (one for if value and other for else value) which can contain some other widgets like this:

`line1<br/><span/div class="widget_if">{if condition}<div class="widget_button">button</div>{else}condition not met{/if}</span>`

## Other details

* Browser: latest chrome
* OS: win10
* CKEditor version: 4.15

**Comment by jacekbogdanski** [comment]
Hey @voborl00, could you create some online demo sample with the issue? It's hard to understand the issue with some partial code listings and it would be much easier for us to find out what's going. As an example, you could use one of the online text editors listed in the ticket template:

* CodePen: https://codepen.io/Comandeer/pen/ExaMgpz?editors=1010
* JSFiddle: https://jsfiddle.net/Comandeer/d6ey8a2w
* JSBin: https://jsbin.com/keqekef/1/edit?html,js,output
* StackBlitz: https://stackblitz.com/edit/js-vcqfw3

**Comment by voborl00** [comment]
Case 1:

https://jsfiddle.net/b8ruvkt0/11/

Place cursor at the beginning of line2, insert widget (toolbar command without icon next to last icon 'about ck') and click getCKEData() button

getData before widget insertion:
```
line1<br />
line2
```

getData after widget insertion:
```
line1
<div class="widget_parent_1">
<h1>widget parent 1</h1>
{content}</div>
line2
```

![image](https://user-images.githubusercontent.com/3495229/102874206-723c0b00-4442-11eb-8ac9-a72ad3f7f706.png)

**Comment by voborl00** [comment]
Case 2:

https://jsfiddle.net/esr0df1g/8/

Insert widget (toolbar command without icon next to last icon 'about ck') and click Show source or click getCKEData() button

`ckeditor.js:formatted:27940 Uncaught TypeError: Cannot read property 'attributes' of null
    at ckeditor.js:formatted:27940
    at CKEDITOR.htmlParser.element.forEach (ckeditor.js:formatted:7370)
    at CKEDITOR.htmlParser.element.forEach (ckeditor.js:formatted:7375)
    at a.<anonymous> (ckeditor.js:formatted:27923)
    at a.d (ckeditor.js:formatted:135)
    at a.<anonymous> (ckeditor.js:formatted:199)
    at a.CKEDITOR.editor.CKEDITOR.editor.fire (ckeditor.js:formatted:243)
    at CKEDITOR.htmlDataProcessor.toDataFormat (ckeditor.js:formatted:7805)
    at $.getData (ckeditor.js:formatted:29590)
    at $.<anonymous> (ckeditor.js:formatted:8835)`

![image](https://user-images.githubusercontent.com/3495229/102875881-b4664c00-4444-11eb-9170-02490c5106db.png)

**Comment by voborl00** [comment]
Case 2/"no editables"

https://jsfiddle.net/kxhe9q48/16/

Insert widget (toolbar command without icon next to last icon 'about ck') and click Show source or click getCKEData() button

`ckeditor.js:1289 Uncaught TypeError: Cannot read property 'attributes' of null
    at ckeditor.js:1289
    at CKEDITOR.htmlParser.element.forEach (ckeditor.js:303)
    at CKEDITOR.htmlParser.element.forEach (ckeditor.js:303)
    at CKEDITOR.htmlParser.element.forEach (ckeditor.js:303)
    at CKEDITOR.htmlParser.element.forEach (ckeditor.js:303)
    at CKEDITOR.htmlParser.element.forEach (ckeditor.js:303)
    at a.<anonymous> (ckeditor.js:1288)
    at a.d (ckeditor.js:10)
    at a.<anonymous> (ckeditor.js:11)
    at a.CKEDITOR.editor.CKEDITOR.editor.fire (ckeditor.js:13)`

![image](https://user-images.githubusercontent.com/3495229/102877216-ae716a80-4446-11eb-8e94-be2bfda6118f.png)

**Comment by voborl00** [comment]
Case 4

https://jsfiddle.net/5hm6Lsuk/50/

click getCKEData() button and output strips `<br/>` from `line1<br/>`

cke.data line1
<p>parent content</p>

<div class="widget_nested_1">
<h1>widget nested 1</h1>
{content}</div>
<br />
line2

By the way, I cannot get inline span widgets to upcast, but the "br" behaviour persist even so

![image](https://user-images.githubusercontent.com/3495229/102881287-ed0a2380-444c-11eb-9a5c-75c6a940328f.png)

**Comment by f1ames** [comment]
Hi @voborl00, thank you for detailed description and code samples :+1: 

I see there are two issues:

1.  The `br` element is removed when widget is inserted (I see it happens with both `ENTER_P` and `ENTER_BR` mode). This can be observed in e.g. **Case 1** and **4**.
2.  You are not able to create inline widget (or the one which behaves as inline one), e.g. **Case 2** and **3**.

### Case 1

See [https://github.com/ckeditor/ckeditor4/issues/4426#issuecomment-749451682.](https://github.com/ckeditor/ckeditor4/issues/4426#issuecomment-749451682.)

Looks like an issue indeed, `br` is still in the DOM after widget is inserted but is removed from the editor output upon `getData()` call.

### Case 4

See [https://github.com/ckeditor/ckeditor4/issues/4426#issuecomment-749482052.](https://github.com/ckeditor/ckeditor4/issues/4426#issuecomment-749482052.)

The `br` is not there after editor initialization so it's removed during initialization. This means `getData()` is not the cause here. However, I suppose the cause may be the same as in **Case 1** (data filtering on input/output).

### Case 2 and 3

The `Uncaught TypeError: Cannot read property 'attributes' of null` is a known issue and it results from the fact that inline editable widgets are not supported (due to limitations in older browsers). For more details see original report #698 and #1091.

---

I guess we could extract `br` issue to a separate ticket and **Case 2** and **3** are already known. Unfortunately, we don't have any plans to work on #1091 in a nearest future.

**Comment by voborl00** [comment]
Ok, let's make it BR issue. Do you want me to interact somehow more, or just left this ticket as is and wait for progress? And by the way, can you guess some ETA for these BR cases? Thank you

**Comment by f1ames** [comment]
@voborl00 I have extracted `br` issue to #4466. As for the ETA, we have other priorities right now so it's really hard to say when we can work on this.

I'm closing this one as Cases 2 and 3 are already reported as mentioned before.
