### ISSUE TITLE
No color and Font size option show up after install new version, 4.15.1

### ISSUE THREAD

**Issue by susansongcs** [ckeditor/ckeditor4#4429]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. After install the new version of Color Button 4.15.1, it does not work. There is no color option show up.
2.  Also no font size option show up.

### Expected result

*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: Chrom
* OS: Mac
* CKEditor version: 4
* Installed CKEditor plugins:  Color button, Font Size and Family

**Comment by Dumluregn** [comment]
Hello, using the plugins in different version than the CKEditor 4 itself gives no guarantee it will work together since plugins often require specific editor core features. That means that if you want to use `Color Button` plugin in version `4.15.1`, please also use CKEditor `4.15.1`.

**Comment by susansongcs** [comment]
Hi Dumluregn,

Thank you for you reply. This does make sense. I use Drupal 9 and it has default CKeditor Version: 9.0.7, I do not know how to install Ckeditor 4 on Drupal 9. I did it on Drupal 7.

BTW, the error I got for setting color and font are javascript: void('Text Color').

Does any know how to install Ckeditor 4 on Drupal 9?

Thanks

**Comment by Dumluregn** [comment]
You should probably follow [this guide](https://www.drupal.org/docs/8/core/modules/ckeditor/managing-ckeditor-plugins-using-composer).

**Comment by susansongcs** [comment]
I updated drupal to lastest version then it fixed.

Thank you.
