### ISSUE TITLE
Multi number markers lists not pasted correctly

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor4#443]
## Are you reporting a feature or a bug?

Bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

http://dev.ckeditor.com/ticket/16872

## Provide detailed reproduction steps (if any)

1. Open attached `multi_list.docx` in Word and copy it's content.
2. Open CKEditor.
3. Paste into editable.

### Expected result

Pasted list has correct structure (ofc multiple digit markers do not need to be preserved).

### Actual result

Starting with "4.2.1.Aa" item, list structure is broken.

## Other details

I think it has something to do with this list item not having `nbsp` between marker and the list item content.

* Browser: Edge

**Comment by Dumluregn** [comment]
This issue is no longer reproducible in the latest Edge browser version.
