### ISSUE TITLE
page meta base href and config.baseHref ignored

### ISSUE THREAD

**Issue by jeandat** [ckeditor/ckeditor4#4432]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

It seems the page meta <base href="..."> and the config.baseHref parameter are totally ignored.
I can find issues about this on the internet and on this repo but there was never a response.

### Expected result

CKEditor should use that base href when computing urls for skin or plugins loading.

### Actual result

Base href never appear in any url loaded by ckeditor.

## Other details

* CKEditor version: 4.14.0

**Comment by jeandat** [comment]
Here is a workaround I found:

`CKEDITOR.basePath = '<base href from somewhere>' + CKEDITOR.basePath`;

**Comment by Dumluregn** [comment]
Hello, thank you for the report, however we need more information to understand this issue. Please, provide a demo or at least the reproduction steps where we could see and debug the problem. Also you mentioned this was reported previously - please link the corresponding issues.

**Comment by jeandat** [comment]
Kind of similar issue: https://github.com/ckeditor/ckeditor4/issues/896

My understanding is that if the page has a meta `<base href="/foo/">` it should be respected by ckeditor. Currently it is not.

Also configuring it in `config.js` with: `config.baseHref = '...'` doesn't work either.

**Comment by Dumluregn** [comment]
Hi, 
as far as I understand your issue, the problem has the same root as https://github.com/ckeditor/ckeditor4/issues/1856. That issue required intervention deep in the editor core, which could cause a number of new errors, so we decided it is not worth touching. For now I'm closing this issue as a duplicate - still, feel free to provide a demo if you find out that the problem you encountered is different than the one described in the mentioned ticket and we could reopen the issue then.
