### ISSUE TITLE
CKEditor 4 drop downs in ExtJs 6 Modern Dialog cause editor to loose content

### ISSUE THREAD

**Issue by rhoney** [ckeditor/ckeditor4#4434]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

Style / Font drop-downs of CKEditor cause the entire editor to fail and get stuck when editor is opened in an ExtJs 6 Modern window dialog.

Here's how we can reproduce this:

1. Goto following fiddle: https://fiddle.sencha.com/#view/editor&fiddle/3akp
2. Run the fiddle, and input any text in CKEditor
3. Now without selecting any text in the editor, click on the "Styles" drop-down on the toolbar.
4. Without doing anything, simply click the "Styles" drop-down again to close it.

You will notice the content is lost in the editor and the editor becomes "un-editable". In my troubleshooting, I noticed the editor's iframe is loosing its entire body when above steps are performed.

Any help would be greatly appreciated.

## Other details

* Browser: Google Chrome | 87.0.4280.88 (Official Build) (64-bit) (cohort: Stable)
* OS: Windows 7 Service Pack 1
* CKEditor version: 4.15.1
* Installed CKEditor plugins: Standard package

**Comment by Dumluregn** [comment]
The software you are referring to is a third-party one, and it is not maintained by CKSource. Since we cannot fix issues with the code that does not belong to us, we are unable to help solve your issue. Please redirect your question to the software’s author who should be able to review the problem and suggest a solution.

If, however, after contacting the software’s maintainer you find out the issue lies on the editor’s side, please provide a demo using only the CKEditor 4 itself, we will be happy to have a look at it.

**Comment by rhoney** [comment]
@Dumluregn I confirmed and the issue is certainly with CKEditor. We do not expect a tool to work independently without integration with other tools, or do we?

To the best of my knowledge, the third-party one isn't interfering with CKEditor's working. I have provided a fiddle to reproduce. Can you atleast check once and verify the issue is certainly with CKEditor 4?

**Comment by Dumluregn** [comment]
Hello again!

> We do not expect a tool to work independently without integration with other tools, or do we?

Of course we would like to see CKEditor 4 integrated with as many tools and frameworks as possible, but some of them are complex enough to require some specific adjustments to be working, like our [Angular integration](https://github.com/ckeditor/ckeditor4-angular). However we don't provide an official ExtJs 6 integration as we didn't ever try to make those two work together, and that would be the whole new feature request.

As for the issue itself, it seems that the reason may be automated reload of the iframe inside the editor - we are currently working on this as it's a wider problem. For the reference please see https://github.com/ckeditor/ckeditor4/issues/4390#issuecomment-751659731 and https://github.com/ckeditor/ckeditor4/issues/4462. After #4462 is resolved, this issue should also become invalid.
