### ISSUE TITLE
html5 video plugin and ckeditor4-react

### ISSUE THREAD

**Issue by hessaam** [ckeditor/ckeditor4#4435]
Is there any way to add [html5 video plugin](https://ckeditor.com/cke4/addon/html5video) to [ckeditor4-react](https://www.npmjs.com/package/ckeditor4-react)
?

**Comment by hessaam** [comment]
I asked a question about this on the Stackoverflow community.
[](https://stackoverflow.com/questions/65276219/ckeditor4-react-and-html5-video-plugin)

**Comment by Dumluregn** [comment]
Hello. At first use [`onNamespaceLoaded` property](https://github.com/ckeditor/ckeditor4-react/issues/129) with [`CKEDITOR.plugins.addExternal()` method](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_plugins.html#method-addExternal) to modify global `CKEDITOR` namespace. Then change the [component config](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_react.html#changing-the-editor-configuration).

Also, please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them, so I'm closing it now. If you have CKEditor license, please contact our support team.

**Comment by hessaam** [comment]
@Dumluregn  Would you please say whether is it possible to add html5video plugin to ckeditor4-react or not?

**Comment by Dumluregn** [comment]
Theoretically it should be possible like with any other CKEditor 4 plugin. However, as this is a 3rd party one (not maintained by CKSource), I can't guarantee this to you.

**Comment by hessaam** [comment]
@Dumluregn Thanks
