### ISSUE TITLE
Print and Preview don't work on Firefox when using editor from CDN

### ISSUE THREAD

**Issue by jswiderski** [ckeditor/ckeditor4#4444]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open https://ckeditor.com/docs/ckeditor4/latest/examples/fullpreset.html
2. Press Print or Preview button

### Expected result

*What is the expected result of the above steps?*

Preview should open in a window normally.

*What is the actual result of the above steps?*

Blank window opens. 
Error is thrown in the console: Permission denied to access property "_cke_htmlToLoad" on cross-origin object

## Other details

* Browser: Firefox
* OS: Any
* CKEditor version: 4.0+
* Installed CKEditor plugins: Preview, Print

I have tried setting ` Header set Access-Control-Allow-Origin "*"` but it didn't work. This could be Firefox issue:
https://bugzilla.mozilla.org/show_bug.cgi?id=911444
https://github.com/mozilla/pdf.js/issues/5397

**Comment by f1ames** [comment]
Fixed in https://github.com/ckeditor/ckeditor4/pull/4758.

**Comment by jacekbogdanski** [comment]
Unfortunately, we won't be able to provide the fix in `4.16.2` release. I'm sorry for the confusion, we will move this issue to the next release instead.
