### ISSUE TITLE
Accessibility: NVDA Reads whole content present inside the “Insert template” screen.

### ISSUE THREAD

**Issue by harshgangrade111** [ckeditor/ckeditor4#4446]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open a ckeditor 4 instance
2. Turn screen reader on (NVDA works)
3. Navigate into the Editor itself
4. Navigate to "Regarding" section.
6. Navigate to ""Regarding lookup" and search any result .
8. Select result.
10. Now navigate to top menu bar and select "Insert Template"
12. Insert Template" screen get open.
13. verify issue

### Expected result

It Should only announce selected content and heading “Insert template”.

### Actual result

NVDA Reads whole content present inside the “Insert template” screen.

## Other details

Browser Versions: Microsoft Edge Version 80.0.361.66 (Official build) (64-bit)

 

Windows Version: Windows10

 

Edge Version 87.0.664.66 (Official build) (64-bit)

 

FireFox: 74.0 (64-bit)

**Comment by Comandeer** [comment]
I can't reproduce the issue. NVDA announces only the selected item inside "Insert Template" dialog (the list with available templates).
