### ISSUE TITLE
Pasting with or without the plugin pastefromword

### ISSUE THREAD

**Issue by Brand3000** [ckeditor/ckeditor4#4447]
It would be great to have a possibility of pasting a text by pressing ctrl(cmd)+V without the plugin pastefromword. And on the other hand that would be great to have a button in the instruments to put a text from the buffer and apply the recognition of the text by this module.

**Comment by Comandeer** [comment]
It is possible to apply the filter from the plugin programatically. You can use [`CKEDITOR.plugins.pasteTools.loadFilters()`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_plugins_pastetools.html#method-loadFilters) function to load Paste from Word filter and then access it via `CKEDITOR.plugins.pasteTools.filters` namespace.

It is also possible to paste content without Paste from Word plugin, however the pasted content won't be checked for Word content.

I'll close the request as both things are already possible in CKEditor 4.
