### ISSUE TITLE
Embed Widget Code not Save 

### ISSUE THREAD

**Issue by asifashi1** [ckeditor/ckeditor4#4451]
I am using CK Editor V4.5.6 in the Codeigniter framework.
When I am trying to save one of the other website activity embedded code in my website with CK editor it's not saving. With the submit, button removes all widget code and other HTML code also. Simple text editing and HTML tags are working fine.

**Comment by f1ames** [comment]
Hi @asifashi1, this looks like an issue with Codeigniter CKEditor 4 integration. Since this integration is not developed by CKSource, please report an issue to integration authors.
