### ISSUE TITLE
More than two CKEditor in a Page hangs when user tries to change Font from Down down

### ISSUE THREAD

**Issue by sudhindrakrishnarao** [ckeditor/ckeditor4#4457]
## Type of report

Bug

At Oracle, we have a requirement of using more than 2 CKEditor components in a page with server side validation on the  CKEditor input components such that when the user TABS out of first CKEditor component, server side validation(through AJAX kind of request called as Partial page refresh in Oracle JDeveloper) should trigger. This is the requirement for one of Oracle customers.

Issue usecase :
---------------
In the first CKEditor, user enters some text and then without selecting the text
just click on Font selection dropdown, page hangs and the following exception is seen in the browser console
Uncaught TypeError: Cannot read property 'setState' of null
    at $.setState (rteck-llpnfd.js:1461)
    at $.e.onHide (rteck-llpnfd.js:1459)
    at $.hide (rteck-llpnfd.js:1372)
    at $.u (rteck-llpnfd.js:1366)
    at $.<anonymous> (rteck-llpnfd.js:1366)
    at CKEDITOR4.dom.window.p (rteck-llpnfd.js:606)
    at CKEDITOR4.dom.window.fire (rteck-llpnfd.js:608)
    at rteck-llpnfd.js:664
	
This issue is similar to the already logged ticket that is - https://dev.ckeditor.com/ticket/16898, which is still in pending [state](url)

Attaching here with the document containing screen shots with description for your reference
[CKEditorIssue.docx](https://github.com/ckeditor/ckeditor4/files/5750936/CKEditorIssue.docx)

1. …
2. …
3. …

### Expected result

*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: …All bowsers such as Chrome,IE & Firefox
* OS: …WIndows, Linux
* CKEditor version: …"4.14.0"
* Installed CKEditor plugins: …

**Comment by f1ames** [comment]
Hello @sudhindrakrishnarao, I tried to reproduce your issue based on your description via [this codepen demo](https://codepen.io/f1ames/pen/QWKaYPp?editors=1010), but was not able do so.

Could you provide more details on this issue (CKEditor 4 configuration, used plugins, any custom plugin used, etc) or a sample demo (e.g. using codepen) where the issue is easily reproducible?

**Comment by sudhindrakrishnarao** [comment]
please do not close this bug,  this is critical showstopper for our customer 
We are working on reproducing this issue in a simple test case.

**Comment by sudhindrakrishnarao** [comment]
Hello@f1ames,
This issue could not be reproducible in a simple html page, but happening using our ADF framework, which  internally using CKEditor.
We would like to have a joint debugging session with your CKEditor team, please let us know your available time 
and also let us know your mail id to communicate .

Thanking you,
Sudhindra

**Comment by Dumluregn** [comment]
Please note that our GitHub issue tracker serves for reporting bugs and new features only in CKEditor 4, so I'm closing the issue as it isn't reproducible without the external software.

If you have CKEditor license, please contact our support team for help in the implementation issues.

**Comment by sudhindrakrishnarao** [comment]
We are from Oracle, we have CKEditor license, by having CKEditor license, how do we approach support team?
Any contacts/mail id to contact?

Thanking you,
Sudhindra

**Comment by Dumluregn** [comment]
Please use the form on https://ckeditor.com/contact/ and choose `Technical support and security issues` as the type of inquiry.
