### ISSUE TITLE
Unable to create ckeditor4 on the official website

### ISSUE THREAD

**Issue by qidong364482611** [ckeditor/ckeditor4#4458]
<img width="1076" alt="截屏2020-12-30 上午11 00 50" src="https://user-images.githubusercontent.com/19990583/103327142-5cf05d80-4a8e-11eb-8de1-1742c97e3ff7.png">
Unable to create ckeditor4 on the official website

**Comment by f1ames** [comment]
Hello @qidong364482611, could you share your env information (OS, browser, browser extensions) and what exact steps led to this error?
