### ISSUE TITLE
[bug] paste from word becomes image 

### ISSUE THREAD

**Issue by lemueloodle** [ckeditor/ckeditor4#4459]
## Type of report

I'm getting a weird experience when I copy paste a doc file to the ckeditor. It became an image.
Using Safari browser.

![image](https://user-images.githubusercontent.com/6710404/103338243-b7061880-4ab8-11eb-9adf-275ed2e0c84d.png)

## Provide detailed reproduction steps (if any)

Using Safari and Mac
1. Copy a detailed text from Word
2. Command + V in ckeditor (The paste to Word is not working)

### Expected result

It should show the result in a proper format and not as image format.

### Actual result

Tested using Google Chrome
![image](https://user-images.githubusercontent.com/6710404/103339052-53311f00-4abb-11eb-9ac9-543b03b70c7d.png)

## Other details

* Browser: Safari
* OS: MacOS
* CKEditor version: CKEditor6
* Installed CKEditor plugins: …

**Comment by f1ames** [comment]
Hi @lemueloodle, could you share more details on your environment (OS and browser version, CKEditor configuration, active plugins and version)? If it's possible could you also share Word document which causes the issue so we may try to reproduce it on our end?

As for the latest CKEditor 4 version it seems to be working fine on [our official demo](https://ckeditor.com/docs/ckeditor4/latest/examples/pastefromword.html). OTOH we had similar issue with Firefox and Excel in the past (see #3585).

---

We have also recently covered improvements for images handling in Safari (see #1134) but it's not yet released and doesn't seem to be connected on the first sight.

Side note on:

> *   CKEditor version: CKEditor6

Looks like a typo TBH, you can check CKEditor 4 version by running `CKEDITOR.version` in browser dev console.

**Comment by nikolaykhodov** [comment]
We've encountered a similar issue: we solved it by disabling the EasyImage plugin
