### ISSUE TITLE
Improvements to accessibility checker

### ISSUE THREAD

**Issue by DwyerCMS** [ckeditor/ckeditor4#4479]
I would like to propose the following:

1.	Enable ability to skip or disable the alt text check. This is because our application currently appends image alt text to the HTML as part of the publishing workflow, and so it is not expected that the images in the WYSIWYG editor would have alt text at that point.
 
2.	The ambiguous link checker successfully notifies the user when they have a "click here" link, but not when the link says "this", "this article", "more" or "find out more". Would it be possible for the auditor to look for and flag links with this text (or any other text strings we identify in the future). i.e. can we create our own library of link text to flag?

**Comment by Comandeer** [comment]
The Accessibility Checker has [its own repository](https://github.com/cksource/ckeditor4-plugin-a11ychecker). Please report the feature request there.
