### ISSUE TITLE
Cutting and Pasting in Chrome produces non-breaking spaces

### ISSUE THREAD

**Issue by LiamDawe** [ckeditor/ckeditor4#4480]
## Type of report

Bug

In the current latest version, as tested using your [examples](https://ckeditor.com/docs/ckeditor4/latest/examples/standardpreset.html) with Chrome if you cut/paste and press spacebar you can get the editor to start adding in non-breaking spaces for no reason. It's highly frustrating, as it seems to only happen when cutting and pasting. Not even external pastes either, cut and paste from the example text and it still does it.

Video proof example: https://youtu.be/6xhSa89jW6A

Seems to happen as soon as you cut, it's so weird.

### Expected result

Don't start adding in non-breaking spaces.

### Actual result

See the video.

## Other details

* Browser: Chrome
* OS: Linux
* CKEditor version: latest
* Installed CKEditor plugins: whatever is on the linked example, so it's likely not plugin related?

**Comment by Comandeer** [comment]
It seems that this behavior is not connected with cutting and pasting but with the space at the end of paragraph. Chrome inserts `&nbsp;` in that case and it can be reproduced also in native `[contenteditable]` → jsfiddle.net/esh2xrjb. If you add a space at the end of the text and then click "Get HTML", you will see that there is `&nbsp;` at the end.

TBH this behavior allows to preserve information about whitespace at the end of paragraphs – Firefox does not do it and after switching to source mode and back to editing mode, the whitespace at the end of the paragraph is lost.
