### ISSUE TITLE
[Accessibility] - Keyboard focus is going onto non-interactive (disabled) controls in Editor text area toolbar.

### ISSUE THREAD

**Issue by sryarama** [ckeditor/ckeditor4#4483]
## Type of report

Bug

## Provide detailed reproduction steps (if any)
1) Open CKEDITOR demo site https://ckeditor.com/ckeditor-4/demo/
2) Tab till Editor text area and press 'Alt+F10' to navigate to toolbar.
3) Verify whether keyboard focus is going onto only interactive controls or not in toolbar.

### User Impact
Keyboard users may confuse why keyboard focus is going onto non-interactive and disabled control in toolbar section in Editor text area. Example on loading ckeditor demo site, you can observe undo/redo toolbar buttons are disabled but still keyboard focus will land on Alt+F10/TAB.

## Other details

* Browser: Google Chrome Version 87.0.4280.66 (Official Build) (64-bit)
* OS: Windows 10
* CKEditor version: 4

**Comment by Comandeer** [comment]
The information about buttons being disabled is conveyed in three ways:

*   buttons are dimmed,
*   focus indicator is different than the one for enabled buttons,
*   there is `[aria-disabled]` attribute.

The visual indicators should inform keyboard users about controls being disabled. On the other hand, the ability to focus disabled controls allows users of screen readers to easily discover functionality provided by the editor. Additionally, the state of the button itself often provides additional, contextual info, e.g. disabled "undo" button means that there are no changes to the editor's content and the disabled "cut" button – that there isn't anything to cut.

Additionally, [ARIA specification does not require to remove `[aria-disabled]` elements from tab order](https://w3c.github.io/aria/#aria-disabled) (bold's mine):

> Disabled elements **might not** receive focus from the tab order.

There is [some more info](https://w3c.github.io/aria-practices/#kbd_disabled_controls) inside ARIA Practices note, alongside [the example](https://w3c.github.io/aria-practices/examples/toolbar/toolbar.html).
