### ISSUE TITLE
Copy pasting from some libreoffice docs doesn't work

### ISSUE THREAD

**Issue by thiagotns** [ckeditor/ckeditor4#4486]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open pastefromlibreoffice demo -> https://ckeditor.com/docs/ckeditor4/latest/examples/pastefromlibreoffice.html
2. Open this odt file  -> https://drive.google.com/file/d/1sOCjrrQanKSnvzSFe4UbnC4HBM3NhcVi/view?usp=sharing
3. Copy the content of the file and paste at the demo editor

ps. Screenshot of the file ![image](https://user-images.githubusercontent.com/775638/104732583-35e78c00-571c-11eb-9e4c-e271ac1d46fc.png)

### Expected result

Properly paste

### Actual result

Nothing happens and the browser console shows a JS error.

![Captura de Tela (5)](https://user-images.githubusercontent.com/775638/104732117-801c3d80-571b-11eb-851b-f4c46a5c397e.png)

## Other details

* Browser: Google Chrome 87.0.4280.141 64 bits
* OS: Windows 10
* Libreoffice Version: 6.0.7.3 (x64)
* CKEditor version: 4
* Installed CKEditor plugins: pastefromlibreoffice (and others)

**Comment by Dumluregn** [comment]
Hello!

I was able to reproduce the issue with the file you provided - I'm getting the same error, which is probably caused by the double `<font>` tags in the HTML data in clipboard:
```html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8"/>
	<title></title>
	<meta name="generator" content="LibreOffice 7.0.4.2 (MacOSX)"/>
	<style type="text/css">
		@page { size: 21cm 29.7cm; margin: 2cm }
		p { margin-bottom: 0.21cm; direction: ltr; color: #000000; text-align: left; orphans: 2; widows: 2; background: transparent }
		p.western { font-family: "Times New Roman", serif; font-size: 12pt; so-language: pt-BR }
		p.cjk { font-family: "Times New Roman"; font-size: 12pt; so-language: pt-BR }
		p.ctl { font-family: "Times New Roman"; font-size: 12pt; so-language: ar-SA }
		a:link { color: #000080; text-decoration: underline }
	</style>
</head>
<body lang="pt-BR" text="#000000" link="#000080" vlink="#800000" dir="ltr"><p class="western" style="margin-bottom: 0cm; line-height: 150%">
<br/>

</p>
<p align="justify" style="text-indent: 2.52cm; margin-bottom: 0cm; line-height: 150%">
<br/>

</p>
<p align="justify" style="text-indent: 2.49cm; margin-bottom: 0cm; line-height: 150%">
<font size="4" style="font-size: 14pt"><font size="3" style="font-size: 12pt">Com
efeito, o Ato Regulamentar Conjunto nº. </font><font size="3" style="font-size: 12pt">XX</font><font size="3" style="font-size: 12pt">/</font><font size="3" style="font-size: 12pt">YYY</font><font size="3" style="font-size: 12pt">
– GPGJ/CGMP, com as alterações dadas pelo Ato Regulamentar
Conjunto nº </font><font size="3" style="font-size: 12pt">XX</font><font size="3" style="font-size: 12pt">/</font><font size="3" style="font-size: 12pt">YYYY</font><font size="3" style="font-size: 12pt">
– CPGP/CGMP, que trata sobre a regulamentação dos Plantões,
determina</font><font size="3" style="font-size: 12pt"><i> “a
compensação para todos”.</i></font></font></p>
</body>
</html>
```

However, I was unable to create such a file on my own. What is more, after I've opened this file and reset font size and family (to 12pt Times New Roman, as in already is), then the content is copied correctly - see attached file (I've used latest LibreOffice 7.0.4). Please, try to reproduce this with newer LibreOffice (since you used version 6.0.7 and when plugin was created there was already a newer one) and describe with as much details as possible how did you create this file.

**Comment by thiagotns** [comment]
Thanks @Dumluregn, after reset the font size and family, in the original file, worked properly.
