### ISSUE TITLE
Angular 9 ck editor remove html tag from html data and style and allowedContent =true is not working 

### ISSUE THREAD

**Issue by raoshahid799** [ckeditor/ckeditor4#4487]
i am using CK Editor 5 with online custom build,
passing the data with NgModel 
Ck edtior 5 remove html tag from data and plus style and other attribute 

i am using the following setting in config 

CkEditorConfig = {

    toolbar: {
      items: [...]
      , shouldNotGroupWhenFull: true,
      viewportTopOffset: 60
    },
  placeholder: 'Type some text',
    allowedContent: true,
    removeFormatAttributes : '',
 }
 i searched on internet but allowedContent =true is not working

**Comment by Dumluregn** [comment]
Hello, this is the repository for CKEditor 4.

Please report this issue in https://github.com/ckeditor/ckeditor5-angular repo issue tracker.
