### ISSUE TITLE
Table Border not showing

### ISSUE THREAD

**Issue by JohnCSMoodys** [ckeditor/ckeditor4#4488]
## Type of report

Bug

## Provide detailed reproduction steps (if any)
![image](https://user-images.githubusercontent.com/36516764/104756243-2fa7de80-5721-11eb-982c-ea339ceaa8d9.png)

1. …
2. …
3. …

### Expected result

*What is the expected result of the above steps?*

### Table Border must be visible

*What is the actual result of the above steps?*

## Other details

* Browser: Chrome
* OS: Win 10
* CKEditor version:4.14.0
* Installed CKEditor plugins: …

**Comment by Dumluregn** [comment]
It seems your CKEditor 4 implementation included custom styling (compare how the dialog looks like in the [pure CKEditor](http://cdn.ckeditor.com/4.15.1/full-all/samples/)), so you should check out the styling of the CMS or website where you encountered this issue.

**Comment by JohnCSMoodys** [comment]
Where can i check the styling (CKEditor CSS files)?

**Comment by Dumluregn** [comment]
It looks like you've pasted the same table into another CKEditor instance. Does this happen when you create a new table on the CDN page? If yes, please turn Source mode on and send the editor contents.

**Comment by K1tba** [comment]
It was probably about the fact that earlier, when I inserted the table component into the editor without styling, CKE4 automatically added borders not only to the table as now, but also to the cells of this table, as far as it was possible to find out earlier, this effect was achieved by assigning classes, but some time ago this mechanism was redesigned and now this is achieved by assigning certain table elements its own. Here is my solution (not too beautiful for me and I think maybe there is another way to achieve the same effect, but in a different way) to correct this behavior in the ckeditor file.js after the line h[e]=d?d:c[e]&&c[e][g]; add the following code: if (e==='width'){h[e]=h[e]||'1px';}else if(e==='style'){h[e]=h[e]==='none'?'dotted':h[e];}else if(e==='color'){h[e]=h[e]||'#d3d3d3';}
