### ISSUE TITLE
Bump react integration i documentation

### ISSUE THREAD

**Issue by sculpt0r** [ckeditor/ckeditor4#4492]
## Type of report

Docs

## Provide a description of requested docs changes

*What is the purpose and what should be changed?*
[React integration](https://github.com/ckeditor/ckeditor4-react ) is outdated in documentation.

Currently, newest version is `1.3.0` and docs use `1.2.0`.

**Comment by Dumluregn** [comment]
Angular and React deps are also outdated and need bumping. It's best to handle it after the new integration versions with CKEditor `4.16.0` are out.
