### ISSUE TITLE
XSS Vulnerability bug report

### ISSUE THREAD

**Issue by johto89** [ckeditor/ckeditor4#4496]
**Steps to reproduce**

Go to the Blog link https://download.cksource.com/CKEditor/CKEditor/CKEditor%204.15.1/ckeditor_4.15.1_full.zip . well you can choose any blog from your website.
Use "developer tools firefox or chro" insert payload: <script>alert(0)</script>. The next press button preview or button print.
Finally, popup showed.
This is so much risk which stored the malicious code over the website using this editor. Now whoever come to this page those people will become victim of XSS attack, May be attacker can steal User account details or other techniques he use. 

**Expected result**

**Actual result**
![Screenshot at 2021-01-20 11-31-56](https://user-images.githubusercontent.com/21223142/105128261-43828480-5b15-11eb-92eb-0a7c99c90f5d.png)

**Comment by johto89** [comment]
![Uploading imageedit_3_5162988917.png…]()

**Comment by shacojx** [comment]
this is the feature !!! :))

**Comment by sculpt0r** [comment]
Thank you for your report. We will investigate it thoroughly.

Meanwhile, I will close this issue as we normally ask for sending security reports through \[our contact form\](https://ckeditor.com/contact/).

For security reasons, I removed the original description, but the original issue you submitted is being handled in our security tracker.
