### ISSUE TITLE
The "ckeditor4-dev" NPM package size is not reasonable

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4#4511]
## Type of report

Task

## Provide description of the task

We have two CKEditor 4 NPM packages - `ckeditor4-dev` and `ckeditor4`. The dev package contains most of the files from this repo (also test files). This means its size stopped to be reasonable some time ago.

The `4.15.1` version is already 90 MB in size:

![image](https://user-images.githubusercontent.com/1061942/105826601-37893d80-5fc1-11eb-8aaa-4dc5c610ee47.png)

And the new `4.16.0` (thanks to some test fixtures related to Paste from Word and images) is around 240 MB :scream: Even with a reasonable internet connection (15 Mb/s upload), NPM gives network timeout error when trying to publish such package:

![image](https://user-images.githubusercontent.com/1061942/105827024-c26a3800-5fc1-11eb-8b96-8d685143eea8.png)

![image](https://user-images.githubusercontent.com/1061942/105827049-c9914600-5fc1-11eb-95a2-bb0ab5cae8a5.png)

## Other details

* Browser: Not related
* OS: Not related
* CKEditor version: Not related
* Installed CKEditor plugins: Not related

**Comment by f1ames** [comment]
## Ideas

1.  Split packages to `ckeditor4-dev` and `ckeditor4-dev-tests`. Still the tests folder has around 220 MB so it will not change match.
2.  ~Pre-pack tests folder before `npm publish` - it decreases the size for 220 MB to ~40 MB so it should be publishable~ It will not change anything since [npm packs files before publishing](https://docs.npmjs.com/cli/v6/using-npm/developers) (before sending them over to NPM). Untill we are able to find super efficent compression algorithm which will do much better job than [npm pack](https://docs.npmjs.com/cli/v6/commands/npm-pack). This would require extracting `tests` folder as npm `post install` step.
3.  Not including `tests` folder in package itself - extract all tests to separate repo and use as git submodule or NPM dependency (pointing to specific hash in git repo).
4.  Faster internet connection could do the job too maybe (to some extend until the package will be too big again) :thinking:

**Comment by Comandeer** [comment]
What's the point of `ckeditor4-dev` npm package? Can't the same be achieved by simply pointing to our git repository? npm should support such a thing.

**Comment by f1ames** [comment]
> What's the point of `ckeditor4-dev` npm package?

I'm not sure to be honest, since in fact, it is a copy of `ckeditor4` repository. So it's just another way to download `ckeditor4` development version :thinking: 

> Can't the same be achieved by simply pointing to our git repository? npm should support such a thing.

Do you mean npm can act as kind of a proxy? So you can still run `npm i ckeditor4-dev` but it will fetch from github directly? :thinking:

**Comment by Comandeer** [comment]
> Do you mean npm can act as kind of a proxy? So you can still run `npm i ckeditor4-dev` but it will fetch from github directly?

No, I mean that someone can insert dependency pointing to git repository inside `package.json`.

**Comment by f1ames** [comment]
> No, I mean that someone can insert dependency pointing to git repository inside `package.json`.

Yes, that's true :+1: Then we could simply deprecate `ckeditor4-dev` npm package and mention that for newer versions package.json should point to github repository directly :thinking:

**Comment by f1ames** [comment]
Ok, let's deprecate this package with a following message:

> This package is deprecated. Please use 'ckeditor/ckeditor4' GitHub repository directly as a 'ckeditor4-dev' npm dependency instead.

**Comment by f1ames** [comment]
Done:

![image](https://user-images.githubusercontent.com/1061942/118959500-ad475980-b962-11eb-972d-59db242dca16.png)
