### ISSUE TITLE
Unable to drag the width of a split header cell 

### ISSUE THREAD

**Issue by idabarbour** [ckeditor/ckeditor4#4522]
## Type of report

Bug

1. Create the below table in CKEditor
![image](https://user-images.githubusercontent.com/78554945/106927008-b4ae6400-66df-11eb-8cbc-8a9caaba914c.png)
2. Try to drag the left border of the 'cx' cell

### Expected result

The cell width can be modified.

### Actual result

Unable to drag the cell border.

## Other details
CKEditor v4.15
Browser - Edge, Chrome

* Installed CKEditor plugins: …

**Comment by Dumluregn** [comment]
Resizing the table is possible with the use of [Table Resize](https://ckeditor.com/cke4/addon/tableresize) plugin. Did you try to use it? I managed to resize the column as desired and didn't experience any issue.

**Comment by idabarbour** [comment]
Hello. Thanks so much for looking into this issue. Yes, the Table Resize plugin has been installed and I used it. I believe the issue may be related to the header cell being split.




[FIS-xSM]

4443 Brookfield Corp Dr. Suite 105
Chantilly, VA 20151

Ida Barbour, CSM, CSPO, ITIL
ida.barbour@fisconsulting.net<mailto:ida.barbour@fisconsulting.net>
Cell:  571-330-4147
Office: 703-378-5055
Fax: 703-378-5255

**Comment by Dumluregn** [comment]
Hi, I tried to reproduce this issue with the same code as you provided in https://github.com/ckeditor/ckeditor4/issues/4523#issuecomment-774137200:

```html
<table border="1" cellpadding="1" cellspacing="1" style="width:608px">
                <thead>
                                <tr>
                                                <th colspan="1" rowspan="2" scope="col" style="width: 157px; background-color: rgb(102, 204, 102);">Name</th>
                                                <th colspan="1" rowspan="2" scope="col" style="width: 70px; background-color: rgb(102, 204, 102);">Length</th>
                                                <th colspan="1" rowspan="2" scope="col" style="width: 48px; background-color: rgb(102, 204, 102);">Depth</th>
                                                <th colspan="3" rowspan="1" scope="col" style="width: 223px; background-color: rgb(102, 204, 102);">Maximum</th>
                                                <th colspan="1" rowspan="2" scope="col" style="width: 102px; background-color: rgb(102, 204, 102);">Remarks</th>
                                </tr>
                                <tr>
                                                <th scope="col" style="width: 76px; background-color: rgb(102, 204, 102);">LOA</th>
                                                <th scope="col" style="width: 68px; background-color: rgb(102, 204, 102);">Draft</th>
                                                <th scope="col" style="width: 76px; background-color: rgb(102, 204, 102);">Beam</th>
                                </tr>
                </thead>
                <tbody>
                                <tr>
                                                <td style="width:157px">&nbsp;</td>
                                                <td style="width:70px">&nbsp;</td>
                                                <td style="width:48px">&nbsp;</td>
                                                <td style="width:76px">&nbsp;</td>
                                                <td style="width:68px">&nbsp;</td>
                                                <td style="width:76px">&nbsp;</td>
                                                <td style="width:102px">&nbsp;</td>
                                </tr>
                                <tr>
                                                <td style="width:157px">&nbsp;</td>
                                                <td style="width:70px">&nbsp;</td>
                                                <td style="width:48px">&nbsp;</td>
                                                <td style="width:76px">&nbsp;</td>
                                                <td style="width:68px">&nbsp;</td>
                                                <td style="width:76px">&nbsp;</td>
                                                <td style="width:102px">&nbsp;</td>
                                </tr>
                </tbody>
</table>
```

and I didn't encounter the problem:
![column-resizer](https://user-images.githubusercontent.com/10883184/107205728-7924da00-69fe-11eb-8903-7c254e032db7.gif)

So just as in https://github.com/ckeditor/ckeditor4/issues/4523#issuecomment-775029837, I have to ask you for recording a demo (not just the issue, but all steps leading to it, so the process of creating a table) or very exact reproduction steps.

**Comment by idabarbour** [comment]
Unfortunately, I am unable to provide you with steps on creating the table from scratch for the issue was reported by a client. However, I have recorded a video on the issue I’m experiencing once the table has been created – I’m unable to drag the left border of the ‘LOA’ header cell. Please see attached.

https://user-images.githubusercontent.com/78554945/107251595-7fb55080-6a02-11eb-95cc-e705caa61836.mp4

**Comment by Dumluregn** [comment]
Could you please try to reproduce this error in our [official demo](https://ckeditor.com/docs/ckeditor4/latest/examples/table.html) for column resizing feature?

**Comment by idabarbour** [comment]
I could not reproduce the issue in CKEditor's official demo site. See attached screen recording.

https://user-images.githubusercontent.com/78554945/108888497-8a164380-75d9-11eb-983f-fcf7a86017ea.mp4

**Comment by Dumluregn** [comment]
Hello, we are unable to debug or work on the issues that are not reproducible in our official demos, therefore I'm closing this issue. However if you manage to find a way for us to reproduce it, feel free to provide additional feedback so that we could reopen this issue.
