### ISSUE TITLE
How to suppress warning: Error code: exportpdf-no-token-url.

### ISSUE THREAD

**Issue by kzimny** [ckeditor/ckeditor4#4527]
Is there any way to suppress `exportpdf-no-token-url` warning? I use the `https://cdn.ckeditor.com/4.16.0/full-all/ckeditor.js` version and want still use the **`full-all`** version. How to get rid of no token url warning? I don't suppose to use it. Passing an empty string to configuration `exportPdf_tokenUrl: '',` doesn't solve the issue. Is there an option to disable the exportpdf plugin? 

![image](https://user-images.githubusercontent.com/12007674/107055279-68435100-67d1-11eb-8e76-918957c8b506.png)

**Comment by Dumluregn** [comment]
Hello, just use the `removePlugins: 'exportpdf'` [config option](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-removePlugins).

**Comment by kzimny** [comment]
It works. Thanks!
