### ISSUE TITLE
Source plugin for inline Ckeditor remains non-editable in Firefox

### ISSUE THREAD

**Issue by surilsarvaiya** [ckeditor/ckeditor4#4531]
## Type of report

Bug

We're using Ckeditor extensively in our project.
At few instances we have also made use of the *inline* one.
For such inline ones, Source plugin area remains non-editable  in Firefox.
We have tested this on version 84.
This however works properly for Chrome, IE and Edge browsers.

We tried this but to no avail.
content editable=true

### Expected result

*Source area should be editable*

### Actual result

*Source plugin area remains non-editable*

## Other details

* Browser: … Firefox v84
* OS: … Windows and Linux
* CKEditor version: … 4.14.0
* Installed CKEditor plugins: …  Source-Dialog, Source-Area

**Comment by sculpt0r** [comment]
Hi @surilsarvaiya ,

Thank you for the report. I tried to reproduce your case and unfortunately, I wasn't able to receive such a result. Could you provide some example code that fails on FF 84? You can use one of these:  
- CodePen: https://codepen.io/Comandeer/pen/ExaMgpz?editors=1010  
- JSFiddle: https://jsfiddle.net/Comandeer/d6ey8a2w  
- JSBin: https://jsbin.com/keqekef/1/edit?html,js,output  
- StackBlitz: [https://stackblitz.com/edit/js-vcqfw3](https://stackblitz.com/edit/js-vcqfw3)  
  
Also, could you tell me that you are using CKEditor in a non-usual environment (frameworks etc.)? If so, please provide as many details as you are allowed to.

**Comment by surilsarvaiya** [comment]
Sure...let me try to reproduce it
