### ISSUE TITLE
Text being split across pages

### ISSUE THREAD

**Issue by BenWilliams1981** [ckeditor/ckeditor4#4533]
## Template

Bug

## Sentences that pulls into this report split across 2 pages. So the top of the text appears on one page and the bottom appears on the next. This makes the wording unreadable. Is there a way to prevent a sentence doing this? If there isn't enough room on the page to go onto the next?

<!--
![image](https://user-images.githubusercontent.com/78901108/107615171-9a2a3c80-6c43-11eb-8065-f4233cbf5cbf.png)

* Browser: …Edge/Chrome
* OS: …Wnidows
* CKEditor version: …CKEditor 4.7.2 (revision c9b79c9)
* Installed CKEditor plugins: …

**Comment by sculpt0r** [comment]
Hi @BenWilliams1981 ,

We would like to help solve your issue but it seems you have missed our [templates for feature requests and bug reports](https://github.com/ckeditor/ckeditor4/issues/new/choose). Their purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.
