### ISSUE TITLE
[Accessibility] Text color and background color toolbar buttons not available in high contrast mode

### ISSUE THREAD

**Issue by sryarama** [ckeditor/ckeditor4#4538]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Change the system visibility to high contrast mode.
2. Open an instance of the editor.
3. Access the toolbar by pressing ALT+F10.
4. Observe that text color and background color menus are not displayed.

### Expected result

Text color and back ground color toolbar items should be available in high contrast mode as well.

### Actual result

text color and background color menus are not available

### Normal mode
![image](https://user-images.githubusercontent.com/66038900/108434276-3e8c2000-71fc-11eb-8de0-b8d9770ab4a1.png)

### High Contrast mode
![image](https://user-images.githubusercontent.com/66038900/108434473-8e6ae700-71fc-11eb-8468-28286553645c.png)

## Other details

* Browser: Chromium EDGE
* OS: Windows 10
* CKEditor version: 4

**Comment by Dumluregn** [comment]
Hello, this is intended behaviour. In High Contrast mode user is not supposed to change color of text. If you need to allow that, just removing [this conditional check](https://github.com/ckeditor/ckeditor4/blob/major/plugins/colorbutton/plugin.js#L28) should be enough.
