### ISSUE TITLE
MathML not representing on CKedtior 4 on Chrom broswer

### ISSUE THREAD

**Issue by Nitinchopkar** [ckeditor/ckeditor4#4540]
WE have a MathML content which we tried to load on ckeditor 4 but its not representing there as expect[See Attachment]. 
- On Mozilla Math ML content working and expected result screen shot attached here(Mozilli_MathML_works.png
![Mozilli_MathML_works](https://user-images.githubusercontent.com/6725505/108714788-02302b00-7540-11eb-903e-802340e6b912.png)
)
- On Chome Math ML content not working screen short attached here(Chrom_MathML_NotWorking.png
![Chrom_MathML_NotWorking](https://user-images.githubusercontent.com/6725505/108714806-06f4df00-7540-11eb-9620-401edabdd8ec.png)
)
MathML content : {
<p>&lt;math xmlns=&quot;http://www.w3.org/1998/Math/MathML&quot;&gt;&lt;msup xmlns=&quot;http://www.w3.org/1998/Math/MathML&quot;&gt;&lt;mrow&gt;&lt;mfenced separators=&quot;|&quot;&gt;&lt;mrow&gt;&lt;mi&gt;x&lt;/mi&gt;&lt;mo&gt;+&lt;/mo&gt;&lt;mi&gt;a&lt;/mi&gt;&lt;/mrow&gt;&lt;/mfenced&gt;&lt;/mrow&gt;&lt;mrow&gt;&lt;mi&gt;n&lt;/mi&gt;&lt;/mrow&gt;&lt;/msup&gt;&lt;mo xmlns=&quot;http://www.w3.org/1998/Math/MathML&quot;&gt;=&lt;/mo&gt;&lt;mrow xmlns=&quot;http://www.w3.org/1998/Math/MathML&quot;&gt;&lt;msubsup&gt;&lt;mo stretchy=&quot;true&quot;&gt;&amp;sum;&lt;/mo&gt;&lt;mrow&gt;&lt;mi&gt;k&lt;/mi&gt;&lt;mo&gt;=&lt;/mo&gt;&lt;mn&gt;0&lt;/mn&gt;&lt;/mrow&gt;&lt;mrow&gt;&lt;mi&gt;n&lt;/mi&gt;&lt;/mrow&gt;&lt;/msubsup&gt;&lt;mrow&gt;&lt;mfenced separators=&quot;|&quot;&gt;&lt;mrow&gt;&lt;mfrac linethickness=&quot;0pt&quot;&gt;&lt;mrow&gt;&lt;mi&gt;n&lt;/mi&gt;&lt;/mrow&gt;&lt;mrow&gt;&lt;mi&gt;k&lt;/mi&gt;&lt;/mrow&gt;&lt;/mfrac&gt;&lt;/mrow&gt;&lt;/mfenced&gt;&lt;msup&gt;&lt;mrow&gt;&lt;mi&gt;x&lt;/mi&gt;&lt;/mrow&gt;&lt;mrow&gt;&lt;mi&gt;k&lt;/mi&gt;&lt;/mrow&gt;&lt;/msup&gt;&lt;msup&gt;&lt;mrow&gt;&lt;mi&gt;a&lt;/mi&gt;&lt;/mrow&gt;&lt;mrow&gt;&lt;mi&gt;n&lt;/mi&gt;&lt;mo&gt;-&lt;/mo&gt;&lt;mi&gt;k&lt;/mi&gt;&lt;/mrow&gt;&lt;/msup&gt;&lt;/mrow&gt;&lt;/mrow&gt;&lt;/math&gt;</p>

}

Please let us know if you want more information to reproduce issue in chrome browser. 
From
Nitin Chopkar

**Comment by sculpt0r** [comment]
hi @Nitinchopkar 

We would like to help solve your issue but it seems you have missed our [templates for feature requests and bug reports](https://github.com/ckeditor/ckeditor4/issues/new/choose). Their purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

I see that you are using CKEditor in some specific environment. Please add that information to the new issue report.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.
