### ISSUE TITLE
Paste Option OF CKEDITOR4 doesn't work in Chrome and Firefox browser, but it works in IE11

### ISSUE THREAD

**Issue by ThejashwiniAndroid** [ckeditor/ckeditor4#4541]
Not able to paste from the toolbar of CKEDITOR in Chrome and Firefox. It warns with message "Your browser doesn't allow you to paste this way. Press Ctrl+V to paste". Please help me to resolve this issue to make the paste Option to work.

**Comment by f1ames** [comment]
@ThejashwiniAndroid please see https://github.com/ckeditor/ckeditor4/issues/469#issuecomment-306279192.

**Comment by ThejashwiniAndroid** [comment]
Issue has been raised by people very long back, and its sad the fix is still not available either by Ckeditor or Browsers.
