### ISSUE TITLE
GHSL-2020-363: seeking security contact for your project

### ISSUE THREAD

**Issue by anticomputer** [ckeditor/ckeditor4#4542]
The GitHub Security Lab reported a potential security vulnerability (GHSL-2020-363) in your project (ckeditor/ckeditor4). We are approaching 90 days since our initial report and as per our [coordinated disclosure policy](https://securitylab.github.com/advisories#policy), we intend to publish a public advisory detailing this issue. If you wish to discuss or further coordinate a response to this issue with the GitHub Security Lab, please contact us at securitylab@github.com within the next 7 days in reference to GHSL-2020-363 and we would love to help you resolve these issues. If not, feel free to close this issue and we will proceed with advisory publication on expiration.

**Comment by f1ames** [comment]
Hello @anticomputer,

Thanks for the follow-up on this one. We have checked and proceeded the issue and send the response with all the details to the initial email address we had received the report from (which is yours from what I see - `anticomputer@***.com`), but didn't get any answer back.

Could you confirm you received this (it was sent on 5th of January) or would you like us the resend all the details to securitylab@github.com?

**Comment by anticomputer** [comment]
> Hello @anticomputer,
>
> Thanks for the follow-up on this one. We have checked and proceeded with the
> issue and send the response with all the details to the initial email address
> we had received the report from (which is yours from what I see -
> `anticomputer@***.com`), but didn't get any answer back.
>
> Could you confirm you have received this (it was sent on 5th of January) or
> would you like us to resend all the details to securitylab@github.com?
>

Yep, turns out my spam filter ate the ticketing system's response. I've noted your response and we'll update status accordingly on our end. Please feel free to close this issue. Thanks for following up!
