### ISSUE TITLE
Chinese word columns and rows incorrect in table plugin

### ISSUE THREAD

**Issue by kakawait** [ckeditor/ckeditor4#4547]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

Open table modal in chinese, and check wording

rows is 列
columns is 行   

### Expected result

rows is 行
columns is 列 

## Additional informations

rows is 行 https://translate.google.com/?sl=zh-CN&tl=en&text=%E8%A1%8C&op=translate and column is 列 https://translate.google.com/?sl=zh-CN&tl=en&text=%E5%88%97&op=translate

Can be confirm by other translation on other plugin that use the correct translation https://github.com/ckeditor/ckeditor4/blob/17a1555f7fbb0e83f737c9efe27650dca8dff36f/plugins/forms/lang/zh.js#L54

**Comment by Dumluregn** [comment]
Thank you very much for contribution! We're using [Transifex](https://www.transifex.com/ckeditor/ckeditor/) for managing language strings. Please send your contribution there, so that we can pull it into upcoming release.

Thanks!
