### ISSUE TITLE
Unable to set default text as bold text

### ISSUE THREAD

**Issue by rajesh-smartwebtech** [ckeditor/ckeditor4#4551]
Hello ck text editor 
Unable to set default text is Bold or unable to set Bold button as checked for bold text

can you know me what happened ?

**Comment by Dumluregn** [comment]
We would like to help solve your issue but it seems you have missed our [template for feature requests and bug reports](https://github.com/ckeditor/ckeditor-dev/blob/major/.github/ISSUE_TEMPLATE.md). Its purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.
