### ISSUE TITLE
Issue with Exporting Content edited in CKEditor (e.g. Special Characters): New Special Characters are added beyond what is typed/edited in CKEditor

### ISSUE THREAD

**Issue by davis-03** [ckeditor/ckeditor4#4552]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Special characters are typed into CKEditor plug-in used within SAP SuccessFactors Job Profile Builder (JPB)
2. For example: "Cette phrase est écrite en français" is typed into the CKEditor
3. Upon export from the CKEditor within JPB, the output reveals "**Cette phrase est &eacture;crite en fran&ccedil;ais**" instead of the expected "**Cette phrase est écrite en français**"

Note: upon further testing we have found the issue is not with new imports which are immediately exported, without edit.
Thus the issue appears to be after content is typed (net-new) or imported, then edited, with the CKEditor
We recognize this likely pinpoints the issue as being with CKEditor versus SAP SuccessFactors functionality and/or the file import process.

### Expected result

*What is the expected result of the above steps?*
The expected result is to see only the special characters imported and/or edited directly in CKEditor.
Here - the expected export results would be **"Cette phrase est écrite en français"**

### Actual result

*What is the actual result of the above steps?*
The actual result is to see additional the special characters beyond that which is imported/or edited directly in CKEditor.
Here - the actual export results are "**Cette phrase est &eacture;crite en f r a n & c c e d i l ; a i s**"

^we had to space out the actual results for handling the 'ç' special character as the Github editor was correcting the error!! 
Exactly the issue we want to solve!

## Other details

* Browser: Chrome
* OS: PC - Windows 10 Enteprise (v1909) ; Mac - Big Sur 11.2.1
* CKEditor version: 4.15
* Installed CKEditor plugins: None that we are aware of - may require further discussion

**Comment by davis-03** [comment]
Please see the below screenshots for the expected versus actual results - you will see the extra characters included

Davis

![Screen Shot 2021-03-01 at 1 14 35 PM](https://user-images.githubusercontent.com/79670508/109546621-13bd8980-7a90-11eb-81b4-e72116c9692f.png)

![Screen Shot 2021-03-01 at 1 13 51 PM](https://user-images.githubusercontent.com/79670508/109546546-f8eb1500-7a8f-11eb-833a-c20d202936f3.png)

**Comment by davis-03** [comment]
What we are finding after additional testing today (March 1, 2021):
The issue does appear to be with the edit function within CKEditor - we found multiple times that the clean import and immediate export (with no edits, typed characters, or changes) produces the correct or expected results. The only issues appear to arise when text is typed net-new or edited within the CKEditor

Davis

Davis

**Comment by Dumluregn** [comment]
Hello, CKEditor 4 by default replaces custom characters with HTML entities to avoid encoding issue during saving and loading data from database. This behaviour can be easily changed by [`config.entities`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-entities) option - set it to `false` and special characters should no longer be replaced.

**Comment by davis-03** [comment]
Hi @Dumluregn - thanks for the note! We will look to change this behavior through the option you provided and test the update this week. Appreciate your timely help!!

Davis
