### ISSUE TITLE
Add article describing the delayed editor initialisation feature 

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor4#4553]
## Type of report

Docs

## Provide a description of requested docs changes

In #4463 we introduce a bit complex mechanism for delayed editor initialisation on detached element. We should write an article or add a note to some existing one about how it works, when to use it and how to use it.

No obvious spot for this content for me, one proposal is `Features->Integration Features->API Usage` and the second one is `Guides->Integration`.

**Comment by jacekbogdanski** [comment]
Closed in https://github.com/ckeditor/ckeditor4-docs/pull/364
