### ISSUE TITLE
Unexpected html replace with base64 string

### ISSUE THREAD

**Issue by woody-li** [ckeditor/ckeditor4#4579]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

https://github.com/ckeditor/ckeditor4/blob/major/core/htmldataprocessor.js#L874
1. Set html data with a base64-encode img. The code contains some words that matched the regexp above.
2. Then the network list will contains a failed request because the base64 url has changed and invalid.

[Example of the url](https://github.com/ckeditor/ckeditor4/files/6169593/base64.txt)
Part of it below:
zNNk0gkQiDgx+8PEAwGUBQFu92Ow+HA4XCgaXIJVZw507SIxaJEIhEikQjxWAy7w4HX68Xr9eJyudH1T9wyS5ymE67p4wW0ox+zDrv2LYQQou8d2C8rinLwMdMwiEQiWJaFYRgoUgMnzoKe7SlONBrFNIzeo7/Su+0pB6cRfeO4Ae7YoGYd9RsOD24S5IQQon8cuGyloKBpGqqqEjfNgyHOiMePCHdCfFIWPScHccMAQFVVNE09eIneNE3Z1vrQx9Z1Hn1N++PCnBBCiL7Tc9AEVdOw2fSDl0x7at6Ugz9CnKkDW5FNVVEUBV3XsdvtaLqGqijSBq6PHRPgjhfWDv/7xL9BgpwQQvStnn2wgq5r2O

## Other details

* CKEditor version: 4.16.0

**Comment by sculpt0r** [comment]
Hi @woody-li ,
I try to reproduce this issue, but can't figure out what do you mean by `set html data`? Did you use https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#method-setData method? Did you set this base64 encoded data or the entire `img` element with `src` attribute set to provided encoded data?

Could you provide more detailed steps or even working sample using on of these:
* CodePen: https://codepen.io/Comandeer/pen/ExaMgpz?editors=1010
* JSFiddle: https://jsfiddle.net/Comandeer/d6ey8a2w
* JSBin: https://jsbin.com/keqekef/1/edit?html,js,output
* StackBlitz: https://stackblitz.com/edit/js-vcqfw3

**Comment by woody-li** [comment]
I found the cause of the problem that the original html in editor has added a attribute: data-cke-saved-src.
When i setData with the original html, it will be treated as insecure attr.
