### ISSUE TITLE
Chrome: The insertion point of a nested bullet list goes to the beginning of the line instead of the end when clicked on the white space after the line

### ISSUE THREAD

**Issue by pchuey** [ckeditor/ckeditor4#4594]
## Type of report

Bug

## Provide detailed reproduction steps (if any)
1. Create a bullet list with three lines of text.
2. Indent the second line to form a nested bullet list.
3. Click on the white space to the right of the first line.

### Expected result
The I beam cursor is at the end of the line.

### Actual result
The I beam cursor is in the beginning of the line.

## Other details
Easy to reproduce in the CKEditor 4 demo page (ckeditor.com/ckeditor-4/demo/).  There is a bullet list of three lines in the Article Editor tab of the demo page.

Issue is only with Chrome and Chromium Edge.  It is working fine in FF.

* Browser: Chrome & Chromium Edge
* OS: Windows
* CKEditor version: 4.7.2.2
* Installed CKEditor plugins: General

**Comment by Dumluregn** [comment]
Hello, this is a Chromium upstream - this behaviour is the same in any `contenteditable=true` element. We can't really do anything with it in the editor.
