### ISSUE TITLE
Open Dialog definition via one click on element.

### ISSUE THREAD

**Issue by armang98** [ckeditor/ckeditor4#4595]
## Type of report

Task

## Anyway or any property to open dialog definition via one click. In my case, I need to open the "Link Properties" dialog via one-click on the `<a>` element. For now, we can open the "Dialog Definition" dialog only via double-click on the element.

Image: 
![image](https://user-images.githubusercontent.com/37144283/112687374-d67ec880-8e90-11eb-8001-999623f092ae.png)

*For now I can open this dialog only via double click on the `<a>` element. I need any solution to open this via one click. If you have any code example to solve this or any idea please provide me.*

## Other details

* CKEditor version: 4,
* Angular version: 8,
* Stackoverflow link: https://stackoverflow.com/questions/66582217/is-there-any-way-to-open-ckeditor-dialog-manually

**Comment by Dumluregn** [comment]
You can try to add a click listener to the editable (remember that it has to be already created, hence everything is wrapped inside `instanceReady` event listener):
```js
var editor = CKEDITOR.replace( 'editor' ); // use your editor element id here

editor.on( 'instanceReady', function() {
	editor.editable().on( 'click', function( evt ) {
		var element = evt.data.getTarget().getAscendant( { a: 1, img: 1 }, true );

		if ( element && !element.isReadOnly() ) {
			if ( element.is( 'a' ) ) {
				evt.data.dialog = ( element.getAttribute( 'name' ) && ( !element.getAttribute( 'href' ) || !element.getChildCount() ) ) ? 'anchor' : 'link';

				// Pass the link to be selected along with event data.
				evt.data.link = element;
			} else if ( CKEDITOR.plugins.link.tryRestoreFakeAnchor( editor, element ) ) {
				evt.data.dialog = 'anchor';
			}
		}
		if ( evt.data.dialog ) {
			editor.openDialog( evt.data.dialog );
		}
	} );
} );
```

However please note that our GitHub issue tracker serves for reporting bugs and new features only. Unfortunately, your request is neither of them. If you have CKEditor license, please contact our support team.
