### ISSUE TITLE
ColorButton plugin: invalid init for contentTransformations

### ISSUE THREAD

**Issue by blindspeed90** [ckeditor/ckeditor4#4606]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

In addButton(), the line:
	contentTransformations = options.contentTransformations || {},
the {} should be [], as this is expected to be an array.  I hit this in my code downstream after setting colorButton_normalizeBackground=false in my config.

### Expected result

An array is expected.

### Actual result

An object is created.

## Other details

CKEditor v4.16.0, ColorButton plugin

**Comment by Comandeer** [comment]
Could you provide some more info, e.g. by providing the demo of the encountered bug? I can confirm that the object is created instead of an array, but I didn't notice that it causes any errors in the editor.
