### ISSUE TITLE
Bleeding tests – Uncaught TypeError: Cannot read property 'find' of null

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor4#4620]
## Type of report

Failing test

## Provide detailed reproduction steps (if any)

Our tests are [bleeding with error](https://travis-ci.com/github/ckeditor/ckeditor4/jobs/498000243#L454):

> Uncaught TypeError: Cannot read property 'find' of null

### Expected result

There is no error.

### Actual result

There is some uncaught error.

## Other details

* CKEditor version: `master`

**Comment by Dumluregn** [comment]
Similar to https://github.com/ckeditor/ckeditor4/issues/3772, but different error message 🤔

**Comment by sculpt0r** [comment]
Looks like each dot `.` in CI is one unit test. Based on that it could be easier to find which tests throws an error :)

**Comment by sculpt0r** [comment]
Currently, I cannot reproduce this error (especially we are using bender runner on CI). Even our full test runs don't show these errors. Can we close this one @jacekbogdanski ?

**Comment by jacekbogdanski** [comment]
Sure, I can also confirm that it looks stable https://app.travis-ci.com/github/ckeditor/ckeditor4/jobs/535717870 we can reopen the ticket if we will see it's bleeding again.
