### ISSUE TITLE
Failing 'colorinputvalidation' unit tests

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4#4629]
## Type of report

Failing tests

## Provide detailed reproduction steps (if any)

1. Run `tests/security/plugins/colordialog/colorinputvalidation` test suite.

### Expected result

All tests passing.

### Actual result

16 tests passing / 16 tests failing

## Other details

Tests started failing after merging `master` to `major` in https://github.com/ckeditor/ckeditor4/commit/62e3ae4c0dd1ddb37882ca0cfcf8078a23b986b1.

* Browser: Checked on Chrome but seems like generic issue
* OS: Linux
* CKEditor version: Latest `major`
* Installed CKEditor plugins: `colordialog`

**Comment by Dumluregn** [comment]
They can be failing because of the helpers refactor we did in https://github.com/ckeditor/ckeditor4/pull/4591. Tests in security repo should be updated accordingly.

**Comment by f1ames** [comment]
Fixed in security-tests repo already.
