### ISSUE TITLE
how can i fixed this error “ UnhandledPromiseRejectionWarning: Error: spawn UNKNOWN”

### ISSUE THREAD

**Issue by elaineKuo** [ckeditor/ckeditor4#4651]
## Type of report

Task
When I set up the documentation environment of CKEditor 4，used this url https://github.com/ckeditor/ckeditor4-docs；

with the Building Instructions ，when i excute “grunt build-serve --dev”，an error is reported。

Running "prepare-examples" task
Building CKEditor...
(node:36452) UnhandledPromiseRejectionWarning: Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:407:11)
    at spawn (child_process.js:553:9)
    at E:\ck-04-29\ckeditor4-docs\scripts\tools\buildckeditor.js:30:17
    at new Promise (<anonymous>)
    at buildCkeditor (E:\ck-04-29\ckeditor4-docs\scripts\tools\buildckeditor.js:29:9)
    at buildAndCopyCkeditor (E:\ck-04-29\ckeditor4-docs\scripts\tools\buildckeditor.js:24:9)
    at E:\ck-04-29\ckeditor4-docs\scripts\tools\buildckeditor.js:16:16
(node:36452) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:36452) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

how can i fixed it？

## Provide description of the task

*What steps should be taken to fulfil the task?*

## Other details

* Browser:
* OS: window 10
* CKEditor version: 4.16.0
* Installed CKEditor plugins: …

**Comment by f1ames** [comment]
Hi @elaineKuo,

From what I see (based on paths from provided log) you are using Windows and building docs is not really well tested there so it may give you some troubles. I would suggest trying with something like [Cygwin](https://www.cygwin.com/) or [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10) on Windows as it should be more straightforward :crossed_fingers: 

We are using mostly UNIX-like OSes (Linux and macOS) so we are not really able to assist you with this one.
