### ISSUE TITLE
    Request URL: /app/lib/ckeditor/vendor/promise.js?t=K24B&bust=2021-03-25T02:14:53.045Z 404 error

### ISSUE THREAD

**Issue by JohnCSMoodys** [ckeditor/ckeditor4#4655]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. …
2. …
3. …

### Expected result

*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: IE and Crome
* OS: Windows 10
* CKEditor version: 4.14.0
* Installed CKEditor plugins: …
![image](https://user-images.githubusercontent.com/36516764/116575782-974ef780-a8d4-11eb-9322-2c72faca4712.png)
![image](https://user-images.githubusercontent.com/36516764/116576044-d2e9c180-a8d4-11eb-85e6-3029357ac513.png)

**Comment by sculpt0r** [comment]
Hi @JohnCSMoodys ,

From the screens, I conclude:
- you are using `Edge`,
- you are hosting files from some directory, where `promise.js` is missing and you are expecting it, so there is `404` in network inspector

I can't tell anything more...

We would like to help solve your issue but it seems you have missed our [templates for feature requests and bug reports](https://github.com/ckeditor/ckeditor4/issues/new/choose). Their purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.

**Comment by f1ames** [comment]
The fact that `promise.js` file is missing may be caused by the past issue that `vendor` directory was not included in unoptimised builds - see #4059.

@JohnCSMoodys can you confirm which version you are using (optimised or unoptimised build)? Also it's fixed in the latest versions so upgrading to `4.16.0` should do the job.
