### ISSUE TITLE
ID with colon causes JavaScript runtime err in IE. 

### ISSUE THREAD

**Issue by limingli0707** [ckeditor/ckeditor4#4664]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

Almost the same bug as https://github.com/ckeditor/ckeditor4/issues/681. Just in our case the character needs to be escaped is colon.
### Expected result

*What is the expected result of the above steps?*
no javascript syntax err

### Actual result

*What is the actual result of the above steps?*
has javascript syntax err
## Other details

Almost the same bug as https://github.com/ckeditor/ckeditor4/issues/681
The problem is in the implementation of CKEDITOR.tools.escapeCss() which doesn’t return the expected result in IE11 because IE11 doesn't support CSS.escape(). So we need to escape characters in IE manually, in our case our id could have colons. so the fix is addressing the issue by escaping colon when CSS.escape is not available.

* Browser: FF, IE 11, Edge, Chrome (although only IE gives exception)
* OS: windos macOS
* CKEditor version: 4.14 (i think it happens in the latest version as well)
* Installed CKEditor plugins: …

**Comment by limingli0707** [comment]
FYI, I'm putting a fix here: https://github.com/ckeditor/ckeditor4/pull/4666. Thanks!

**Comment by sculpt0r** [comment]
Hi @limingli0707 ,
Thank you for the report. I have to mark it as a duplicate and close this issue.

Please track #681 for updates.
