### ISSUE TITLE
drag and drop image is not working in chrome and works in safari

### ISSUE THREAD

**Issue by victororlyk** [ckeditor/ckeditor4#4677]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. open ckeditor 
2. drag any image into ckeditor in different browser see diferent behavior

Safari

https://user-images.githubusercontent.com/33072590/117298644-4749d500-ae80-11eb-99c0-af84b92405f5.mov

Chrome

https://user-images.githubusercontent.com/33072590/117298689-53ce2d80-ae80-11eb-8085-79ddc727c2d9.mov

### Expected result

I am expecting that uploading images in chrome will work the same way as it works in safari

### Actual result
is safari I can drag and drop local image and in chrome it is just opnening new tab, without sending it to server.

I think the problem is with chrome or this plugin 

https://ckeditor.com/cke4/addon/uploadimage

## Other details

* BrowserChrome 90 /Safari
* OS: macOS Big Sur
* CKEditor version 4
* Installed CKEditor plugins:
- a11yhelp
- about
- ballonpanel
- baloontoolbar
- chopboard
- colordialog
- copyformatting
- dialog
- div
- easyimage
- embedbase
- find
- flash
- forms
- iframe
- image
- image2
- imagebase
- imageresize
- link
- liststyle
- magicline
- pagebreak
- pastefromgdocs
- pagefromlibreoffice
- pastefromword
- pastetools
- preview
- scayt
- shwoblocks
- smiley
- specialchar
- table
- tableselection
- tabletools
- templates
- uploadimage
- widget

mu config file

```
CKEDITOR.editorConfig = function (config) {
  config.embed_provider =
    '//ckeditor.iframe.ly/api/oembed?url={url}&callback={callback}';
  config.extraPlugins = 'uploadwidget, imageresize, uploadimage';

  config.toolbar = [
    {
      name: 'allStyles',
      items: [
        'Bold',
        'Italic',
        'Underline',
        'Strike',
        'BulletedList',
        'Blockquote',
        'JustifyLeft',
        'JustifyCenter',
        'JustifyRight',
        'BidiLtr',
        'BidiRtl',
        'Link',
        'Unlink',
        'Image',
      ],
    },
  ];
  // config.contentsLangDirection = 'rtl';
  config.removeButtons =
    'Source,Save,Templates,NewPage,ExportPdf,Preview,Print,Cut,Copy,Paste,PasteText,PasteFromWord,Undo,Redo,Find,Replace,SelectAll,Scayt,Form,Radio,TextField,Textarea,Select,Button,HiddenField,Checkbox,Subscript,Superscript,RemoveFormat,NumberedList,Outdent,Indent,CreateDiv,JustifyBlock,Anchor,Flash,Table,HorizontalRule,Smiley,SpecialChar,PageBreak,Iframe,Styles,TextColor,Maximize,ShowBlocks,BGColor,Format,Font,FontSize,Embed,EmbedSemantic,Language,Blockquote';
  config.removePlugins = 'elementspath';
  config.filebrowserUploadUrl = `http://api-...`;
  config.filebrowserBrowseUrl = `http://api-....`;
  config.imageResize = { maxWidth: 800, maxHeight: 800 };
};

```

**Comment by nedvadim** [comment]
@f1ames any help is highly appreciated! Experienced similar issue earlier

**Comment by sculpt0r** [comment]
Hi @victororlyk , @nedvadim 
I've check this on our documentation page: https://ckeditor.com/docs/ckeditor4/latest/examples/fileupload.html and it works fine.

However, I asked our team to verify it on their machines with the same result. I wasn't able to drag & drop anything on BrowserStack(multiple browsers test platform). So I think it maybe depends on some environment setup.

Could you provide any sample that reproduces your use case (e.g editor is in some iframe and so on) with one of those:
* CodePen: https://codepen.io/Comandeer/pen/ExaMgpz?editors=1010
* JSFiddle: https://jsfiddle.net/Comandeer/d6ey8a2w
* JSBin: https://jsbin.com/keqekef/1/edit?html,js,output
* StackBlitz: https://stackblitz.com/edit/js-vcqfw3

**Comment by victororlyk** [comment]
https://drive.google.com/drive/folders/1Xm3jfIlXhxbt_ltuhnhjDPNqRubFG3vh?usp=sharing
please download this example, go to samples/index.html and open it in browser

https://user-images.githubusercontent.com/33072590/117974384-2da00600-b336-11eb-8469-651ef9d99ef6.mov

**Comment by Comandeer** [comment]
Sorry for the delay in answering.

I've checked the sample you provided and it works correctly for me on Chrome (90.0.4430.212).
