### ISSUE TITLE
Upload Image while offline

### ISSUE THREAD

**Issue by tandvu** [ckeditor/ckeditor4#4678]
Provide detailed reproduction steps (if any)
Open Chrome Developer Tool. Application Tab. Click on Service Workers. Check Offline.
Click Image icon in CKEditor.
A Dialog popup 
Pick a local file.
Click Upload.

Expected result
The image should be displayed

Actual result
Nothing happens.

**Comment by Comandeer** [comment]
Duplicate of #4643.
