### ISSUE TITLE
Repo install manuall. Githooks problem 

### ISSUE THREAD

**Issue by KarolDawidziuk** [ckeditor/ckeditor4#4683]
## Type of report

Docs

## Provide a description of requested docs changes

There is some problems with installing githooks during setup cke4editor project according to the provided guidelines.

**Comment by KarolDawidziuk** [comment]
I think that I've found the problem. <br>
This is the order of executing command via guidelines. <br>
First we try to execute `ck4-githooks` command, but this [script](https://github.com/cksource/tools/blob/master/bin/ck4-githooks#L8) search a `post-checkout` and `post-merge` files which not exist yet. <br> 
One of the next step in guideline is invoke the `grunt githooks` command. This command create the above files and `hooks` catalog and put into `./git` folder. <br>

In notion i've already added a [new section](https://www.notion.so/Development-Setup-895803d61a9b42e79fd84ff0030e4431#e1175c5bba4a4090b4d997143703f03d) with this information. <br>

**Comment by f1ames** [comment]
Already fixed.
