### ISSUE TITLE
Justify formatting not displaying correctly with Preview. 

### ISSUE THREAD

**Issue by JohnCSMoodys** [ckeditor/ckeditor4#4684]
## Type of report

Bug

## Provide detailed reproduction steps (if any)
http://cdn.ckeditor.com/4.14.0/full-all/samples/
Formatting a text block with justify and use preview.
Let us know if there are any workaround suggestions.

### Expected result

*What is the expected result of the above steps?*
![image](https://user-images.githubusercontent.com/36516764/117468576-714fd580-af1a-11eb-9323-3cbea92a7b7e.png)

### Actual result

*What is the actual result of the above steps?*
![image](https://user-images.githubusercontent.com/36516764/117468606-7745b680-af1a-11eb-8fca-dc26427b0043.png)

## Other details

* Browser: Chrome and IE
* OS: Windows 10
* CKEditor version: 4.14.0
* Installed CKEditor plugins: …

**Comment by Dumluregn** [comment]
Hello, could you please provide the source code for the example you've showed on the screenshots?

**Comment by JohnCSMoodys** [comment]
This is reproducible on the demo site http://cdn.ckeditor.com/4.14.0/full-all/samples/

**Comment by Dumluregn** [comment]
I meant the source code of the editor's content 🙃
