### ISSUE TITLE
Failing test: /test/plugin/widget/widgetsintegration

### ISSUE THREAD

**Issue by KarolDawidziuk** [ckeditor/ckeditor4#4691]
## Type of report

Failing test

## Provide detailed reproduction steps (if any)

Name of failing test: [test content is removed after cutting (single widget)](tests/plugins/widget/widgetsintegration#tests%2Fplugins%2Fwidget%2Fwidgetsintegration%20test%20content%20is%20removed%20after%20cutting%20(single%20widget))

Error: 
![image](https://user-images.githubusercontent.com/18471998/117937917-c6b72880-b306-11eb-82a9-22386f6325ff.png)

### Expected result

* Test passed

### Actual result

* Test fails

## Other details

* Browser: Safari 14.1
* OS: macOs 11.3
* CKEditor version: 4.16.1 build presets: full

**Comment by Dumluregn** [comment]
Reproducible also in `4.16.0` and in dev version, not reproducible in Safari `14.0.1`.

**Comment by f1ames** [comment]
The exact same test with the same error fails on Safari Mobile on iOS (`14.5.1`).

**Comment by KarolDawidziuk** [comment]
Duplicate of [#4689](https://github.com/ckeditor/ckeditor4/issues/4689).
