### ISSUE TITLE
Failing test: tests/plugins/widget/manual/block

### ISSUE THREAD

**Issue by sculpt0r** [ckeditor/ckeditor4#4695]
## Type of report

Failing test

## Provide detailed reproduction steps (if any)

1. Put Lenna inside an empty widget
2. Try to drag outside widget into Lenna description text -> additional line appears abowe Lenna widget
3. Try to drag outside widget above Lenna -> additional line disappear

![DnD widget](https://user-images.githubusercontent.com/6498567/118054192-1ee13f80-b386-11eb-9230-ac3efa7687f7.gif)

### Expected result

Nothing happened after point 2 and 3

### Actual result

An additional line appears above Lena after step 2.
An additional line is gone after step 3.

## Other details

* Browser: IE11
* OS: Windows 10
* CKEditor version: 4.16.1
* Installed CKEditor plugins: -

**Comment by f1ames** [comment]
Hmmm, I recall similar issue but couldn't find anything reported, the only one is #997.

@sculpt0r could you check if it's a regression (e.g. does it happen in `4.14.0`)?

**Comment by sculpt0r** [comment]
There is no such issue in: `4.16.0`, `4.15.1`, `4.15.0`, `4.14.1`, `4.14.0`. So, I add a label.

**Comment by Dumluregn** [comment]
Potential suspect: https://github.com/ckeditor/ckeditor4/pull/4618.

**Comment by sculpt0r** [comment]
@Dumluregn - indeed :)
Reverting [merge](https://github.com/ckeditor/ckeditor4/commit/d5f63753f5df7a0e073f279810b3a4240476a777) from #4618 makes this work again. However, it also makes the old issue come back... ;(

**Comment by Comandeer** [comment]
I can't reproduce the issue.
