### ISSUE TITLE
Failing test: tests/plugins/toolbar/manual/hover/androidrichcombo

### ISSUE THREAD

**Issue by sculpt0r** [ckeditor/ckeditor4#4701]
## Type of report

Failing test

## Provide detailed reproduction steps (if any)

1. Run test and perform step 1

### Expected result

According to the test scenario, rich combos should have "darker background" 

### Actual result

The background is lighter (looks the same as in the toggle ON state). Looks like this for both: `iframe` and `div` based editor.

## Other details

* Browser: Chrome(mobile) 90.0.4430.91
* OS: Android 10
* CKEditor version: 4.16.1
* Installed CKEditor plugins: -

**Comment by Comandeer** [comment]
It seems like the description of the test is incorrect and it should, in fact, says about lighter background after long tap.
