### ISSUE TITLE
Failing tests / Impossible tests on mobile

### ISSUE THREAD

**Issue by sculpt0r** [ckeditor/ckeditor4#4705]
## Type of report

Failing tests

## Provide detailed reproduction steps (if any)
We have two tests that aren't ignored on mobile which requires `delete` key. Since there is no such key on the default mobile keyboard, those two are impossible to perform. 

For a workaround, we can use an external bluetooth keyboard, but that is not a good practice to have such tests available when they are impossible to perform:

- `tests/plugins/widget/manual/deleteparagraphbetween`
- `tests/plugins/widget/manual/deleteparagraph`

### Expected result

Impossible to perform tests on a specific platform are ignored on such a platform.

### Actual result

Tests are available.

## Other details

* Browser: Chrome mobile
* OS: Android
* CKEditor version: 4.16.1
* Installed CKEditor plugins: -

**Comment by f1ames** [comment]
> Impossible to perform tests on a specific platform are ignored on such a platform.

Agree we should just ignore those tests on mobiles.

**Comment by f1ames** [comment]
Fixed in #4723.
