### ISSUE TITLE
Tooltip for Hidden separator: says vertical and should be horizontal instead

### ISSUE THREAD

**Issue by marcm-ith** [ckeditor/ckeditor4#4713]
Hi,
Tooltip for Hidden separator: says **vertical** and should be **horizontal** instead

![image](https://user-images.githubusercontent.com/81153235/118267018-b4cab680-b4bb-11eb-96c4-1d9efdd29cc6.png)

**Comment by Dumluregn** [comment]
Hello, can you specify which plugin are you using? Looks like some 3rd party one, not maintained by CKEditor4 team.

**Comment by marcm-ith** [comment]
Hi Dariusz,
yes, right, this was a third party party plugin.
Sorry!
I close the issue.
