### ISSUE TITLE
Incorrect adding anchors 

### ISSUE THREAD

**Issue by KarolDawidziuk** [ckeditor/ckeditor4#4728]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Go to [link](https://ckeditor.com/latest/samples/index.html).
1. Add bold text style to `world!` and add the anchor.
1. Select whole line of `Hello world!` and try add another anchor.

### Expected result

The whole line should have one anchor

### Actual result

First word `Hello` have one anchor and `world!` have two anchors.

![image](https://user-images.githubusercontent.com/18471998/119488308-ace00180-bd5a-11eb-8bc9-9a619bec31b1.png)

## Other details

* Browser: IE/Safari/Firefox/Chrome/Opera
* OS: macOS 11.1
* CKEditor version: 4.16.1
* Installed CKEditor plugins: link

**Comment by jacekbogdanski** [comment]
Closed in #4733
