### ISSUE TITLE
Possible XSS issue

### ISSUE THREAD

**Issue by LiamDawe** [ckeditor/ckeditor4#4742]
Hi, this might be a XSS issue with the HTML filtering in the current version of CKEditor 4.

While it does correctly filter most, it seems something like this is not fully converted to entities as expected.

`'">><marquee><img src=x onerror=confirm(1)></marquee>"></plaintext\></|\><plaintext/onmouseover=prompt(1)>`

Which is converted to:

`<p>&#39;&quot;&gt;&gt;<img onerror="confirm(1)" src="x" />&quot;&gt;<!--|\--></p>`

As you can see, not _all_ of it is filtered. What it still allows though, can cause issues.

Testing by switching between WYSIWYG and Code/Source view to test and then showing normal output through a quick preview script, allows it to show an alert. Users would need to add in extra filtering before the output is shown.

Done correctly, this could end up as XSS hijacking?

**Comment by f1ames** [comment]
Hi @LiamDawe,

Thank for your report, however all security issues should be reported through [https://ckeditor.com/contact/.](https://ckeditor.com/contact/.)

We will be moving your report to our external tracker. Could you share your email address where we can reach you for more details regarding this issue?

**Comment by LiamDawe** [comment]
Feel free to reach me at liamdawe@protonmail.com
