### ISSUE TITLE
CKEditor 4 not loading text area on opera Version:76.0.4017.177

### ISSUE THREAD

**Issue by wakamd** [ckeditor/ckeditor4#4745]
## Type of report

I noticed that when I load a page with ckeditor 4 it does load the textarea/box on on chrome, firefox but not on opera.

* Browser: …
* OS: …Version:76.0.4017.177

* CKEditor version: 4
* Installed CKEditor plugins: …

**Comment by Dumluregn** [comment]
Hello, both our [demo](https://ckeditor.com/ckeditor-4/demo/) and [CDN sample](http://cdn.ckeditor.com/4.16.1/full-all/samples/) work fine for me on the mentioned Opera version. Can you share any webpage where it doesn't work for you?
