### ISSUE TITLE
How to arrange text side by side in Export to Word?

### ISSUE THREAD

**Issue by amoltupe** [ckeditor/ckeditor4#4751]
In Export to Word, I want to arrange content side by side, Just like float in CSS as seen in below image.
How can I achieve this functionality here?

![image](https://user-images.githubusercontent.com/13763588/121466187-9d0c2280-c9d4-11eb-8b7a-3d44da71b2f1.png)

**Comment by f1ames** [comment]
Hi @amoltupe, I guess you are using CKEditor 5 with Export to Word so this issue/feature should be reported in [CKEditor 5 repo](https://github.com/ckeditor/ckeditor5/issues/new/choose).

**Comment by amoltupe** [comment]
Thanks @f1ames , But can you plz try something so that I can get answer quick or if you can give any suggestion or tag related person. 
https://github.com/ckeditor/ckeditor5/issues/9845
