### ISSUE TITLE
[PasteFromWord]: When doc is pasted from word, incorrect (default) font-family and font-size displayed in dropdown

### ISSUE THREAD

**Issue by niagrawa** [ckeditor/ckeditor4#4752]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Copy document into ckeditor https://github.com/ckeditor/ckeditor4/files/5567048/1-8_9_LS.Lost.Procedure_101320.1.docx
2. Content is displayed in correct font-family "Tahoma", font-size "12"
3. However in dropdown we see "Seogoe UI" and "10"

### Expected result

Dropdown should show "Tahoma" and "12"

### Actual result

Dropdown should show "Seogoe UI" and "10"

## Other details

* Browser: Chrome
* OS: Windows 10
* CKEditor version: 4
* Installed CKEditor plugins: pastefromword

**Comment by Comandeer** [comment]
I can't reproduce the issue in the editor with default configuration. Can you provide more information about the configuration of the editor you used?

**Comment by niagrawa** [comment]
Hi @Comandeer. Actually we have set "Seogoe UI" and "10" as default font-family and font-size in our ckeditor instance. Now in your ckeditor I dont see anything selected by default. So for us when I am copying the content, it still shows "Seogoe UI" and "10" even though the text font is different. Only when i select the text the dropdown value is correct.

@Comandeer Can you suggest any alternative here.

**Comment by Comandeer** [comment]
Do you mean a behaviour [visible in this demo](https://jsfiddle.net/Comandeer/uxcdom3j/)? After pasting the content from the provided document the dropdown shows "Verdana" and it switches to "Tahoma" only after selecting some pasted text or putting caret inside this text.
