### ISSUE TITLE
Tests failing in Safari 14.1

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/ckeditor4#4759]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Run test `tests/plugins/widget/widgetsintegration#tests%2Fplugins%2Fwidget%2Fwidgetsintegration%20test%20content%20is%20removed%20after%20cutting%20(single%20widget)`
2. Run test `tests/plugins/clipboard/drop`

### Expected result

All the tests are passing.

### Actual result

They fail on Safari 14.1.

## Other details

* Browser: 14.1
* OS: macOS, BrowserStack
* CKEditor version: 4.16.1

**Comment by Dumluregn** [comment]
On Safari `14.1.1` also
```
/tests/plugins/pagebreak/pagebreak#tests%2Fplugins%2Fpagebreak%2Fpagebreak%20test%20paste
```
fails on `master` branch:
<img width="698" alt="Screenshot 2021-07-15 at 13 02 41" src="https://user-images.githubusercontent.com/10883184/125777875-6eee4ada-3817-475b-b7ee-27b30fd35ae4.png">

**Comment by f1ames** [comment]
Reported as separate issues in #4815, #4816 and #4818.
