### ISSUE TITLE
Broken Copy/Download buttons in documentation

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4#4764]
## Type of report

Docs

## Provide a description of requested docs changes

It worked on 4.16.0 just fine (https://ckeditor.com/docs/ckeditor4/4.16.0/examples/react.html#/):

![image](https://user-images.githubusercontent.com/1061942/122172704-51002880-ce81-11eb-949a-80c2e30d0891.png)

And starting from 4.16.1 it's broken (https://ckeditor.com/docs/ckeditor4/4.16.1/examples/react.html#/):

![image](https://user-images.githubusercontent.com/1061942/122172811-712fe780-ce81-11eb-918c-3756c1fdac96.png)

It seems like the cause may be changing highlighting library from highlight.js to prism.js in Umberto which changed structure/classes and caused invalid rendering :thinking:

**Comment by pomek** [comment]
Except for the invalid behavior, we also have two highlighter on the page – Highlight.js used by ckeditor4-docs and Prism.js from Umberto.

**Comment by pomek** [comment]
Disabling is not a thing (these snippets look bad). So, we need to adjust/fix SDK builder in Umberto.

**Comment by f1ames** [comment]
We will implement a solution for this issue in Umberto as mentioned in https://github.com/ckeditor/ckeditor4/issues/4764#issuecomment-862197734.

> Except for the invalid behavior, we also have two highlighter on the page – Highlight.js used by ckeditor4-docs and Prism.js from Umberto.

@pomek I'm thinking if any adjustments in `ckeditor4-docs` related to removing `Highlight.js` would be needed :thinking:

**Comment by Comandeer** [comment]
Buttons are working again :tada:
