### ISSUE TITLE
Insert Table Row and Column have wrong Translation for Chinese simplified

### ISSUE THREAD

**Issue by ksosine** [ckeditor/ckeditor4#4776]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

**Insert Table Row and Column have wrong Translation for Chinese simplified.** 
- Row Translated to Column
- Column Translated to Row

When inserting a table:
*incorrect translation: "Rows" - "列", "Columns" - "行",

When editing the table, right click the table to add rows or columns:
*incorrect translation:
"Insert Row Before" - "上方插入列", "Insert Row After" - "下方插入列",
"Insert Column Before" - "左方插入行", "Insert Column After" - “右方插入行”

### Expected result

*What is the expected result of the above steps?*
When inserting a table:
*correct translation: "Rows" - "行", "Columns" - "列",

When editing the table, right click the able to add rows or columns:
*correct translation:
"Insert Row Before" - "上方插入行", "Insert Row After" - "下方插入行",
"Insert Column Before" - "左方插入列", "Insert Column After" - “右方插入列”

### Actual result

*What is the actual result of the above steps?*
When inserting a table:
*incorrect translation: "Rows" - "列", "Columns" - "行",

When editing the table, right click the able to add rows or columns:
*incorrect translation:
"Insert Row Before" - "上方插入列", "Insert Row After" - "下方插入列",
"Insert Column Before" - "左方插入行", "Insert Column After" - “右方插入行”

## Other details

* Browser: …
* OS: …
* CKEditor version: … 4
* Installed CKEditor plugins: …
* This bug was reported by a Salesforce customer. Salesforce uses CKEditor 4 in a few of its products and features. This is a major translation bug (current translations mean the opposite of intended meaning) and should be fixed immediately.

**Comment by Comandeer** [comment]
Thank you very much for contribution! We're using [Transifex](https://www.transifex.com/ckeditor/ckeditor/) for managing language strings. You can send your proposed changes there, so that we can pull it into upcoming release.

Thanks!
