### ISSUE TITLE
(Higher Priority) CKeditor 4.16.1 Standard- Issue with Paste from word button not copying ms word content exactly with correct styling, formatting, identation and numbered bullet lists etc

### ISSUE THREAD

**Issue by sridharravva** [ckeditor/ckeditor4#4779]
Hi,
I am using the CKeditor 4.16.1 Standard version (Licensed version) and also using the PasteFromWord plugin along with its dependencies plugins as well such as "pastetools,clipboard,dialog" but whenever I use the "Paste from word" button, while copying the content from MS Word, then it is not copying ms word content exactly with correct styling, formatting, indentation and numbered bullet lists etc

config.extraPlugins = 'wordcount,htmlwriter,pastefromword,pastetools,clipboard,dialog';
config.allowedContent = true;

Example: I am trying to copy below content from MS Word:
4.1.1.2	Notes
    •	For Non-Construction programs - display SF424A, SF424C* - *SF424C will be optional
    •	For Construction programs - display SF424C only
    •	For Research, Training programs – Display SF424 R&R Fed, Non-Fed only
4.1.1.3	Assumptions - related to this epic
Existing Functionality works ‘As-is’ for the following Prior Approval Types:
    •	Approval to Draw-Down Funds
    •	Capital Update
    •	Other (e.g. Name Change, Deviation from Terms etc.)
Property Actions (e.g., Disposition, Encumbrance)

Output result after I use the "Paste from Word" button on CKEditor (4.16.1, Standard version), I am getting the below result for your reference. As you can see, it is losing the bulletted list numbers like 4.1.1.2 and also 4.1.1.3 along with some formatting, indentation and styling etc.
Could you please let me know how can we get the above exact copies over from MS Word into CKEditor using the "Paste from Word" button on CKEditor ? If there are any additional plugins or config settings that we need to use in order to fix the below issue, please let me know. Thanks in advance!

![image](https://user-images.githubusercontent.com/77024903/124070454-dcde8c80-da0b-11eb-89db-12ff4ad48880.png)

**Comment by Comandeer** [comment]
As you have CKEditor license, please contact our support team. Please note that our GitHub issue tracker serves for reporting bugs and new features only.

Additionally the issue with pasting multi-level lists is known: #1940.
