### ISSUE TITLE
uncaught TypeError - this.parent is null - remove (core/htmlparser/node.js:25)

### ISSUE THREAD

**Issue by keksa** [ckeditor/ckeditor4#4781]
[redacted]

**Comment by Comandeer** [comment]
Thank you for your report. We will investigate it thoroughly.

Meanwhile I will close this issue as we normally ask for sending issues connected with security through [our contact form](https://ckeditor.com/contact/).

For security reasons I removed the original description, but the original issue you submitted is being handled in our security tracker.

**Comment by keksa** [comment]
@Comandeer didn't think of it as a security issue as no javascript from the input was executed, the editor just crashed while trying to filter it

**Comment by keksa** [comment]
Hello @Comandeer, just wanted to ask if there is any development on this? I see a new version has been released, but the issue still exists.
