### ISSUE TITLE
Automatic button in widget bug?

### ISSUE THREAD

**Issue by andeersg** [ckeditor/ckeditor4#4784]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

I'm following the widget guide from CKEditor docs: https://ckeditor.com/docs/ckeditor4/latest/guide/widget_sdk_tutorial_2.html

I've copied the full example but the button does not show up in the toolbar. I've been debugging to find out whats wrong and come to the widget plugin.

In this function the plugins are added by name: https://github.com/ckeditor/ckeditor4/blob/major/core/ui.js#L52

Later in the widget plugin: https://github.com/ckeditor/ckeditor4/blob/major/plugins/widget/plugin.js#L2005 the names are capitalized when adding buttons to the toolbar. This capitalizing causes the names to mismatch and the button to be ignored.

1. Add plugin using the widget api. IDs are all lowercase like guide
2. Load editor

### Expected result

I expect the button to be visible in the toolbar.

### Actual result

Button is not added, but plugin is initialized.

## Other details

I'm not sure if this is a actual problem with CKEditor or the tutorial.

* Browser: Firefox
* OS: MacOS
* CKEditor version: 4.17.0

**Comment by Comandeer** [comment]
Can you provide some demo of the issue?

The plugin from the tutorial has to be included in the editor via [`extraPlugins` config variable](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-extraPlugins). Did you add it to the editor?
