### ISSUE TITLE
Incorrect fire Print on FF

### ISSUE THREAD

**Issue by KarolDawidziuk** [ckeditor/ckeditor4#4790]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

Open editor on FF and click on print button.

### Expected result

Preview and print tab should open correctly. No error in the console.

### Actual result

Preview are opened correctly but print preview is not available. No errors in the console.

## Other details

This happens because FF trying fire `print()` method before page was fully loaded. We need wait for that.
In the `preview` plugin we can create some kind of public API to allow adding callback that fired when the preview window is loaded.

* Browser:FF
* OS: macOS, Windows

**Comment by KarolDawidziuk** [comment]
Blocked by #4444.

**Comment by f1ames** [comment]
As #4444 is done we can proceed with this one.

**Comment by f1ames** [comment]
@KarolDawidziuk could you give more details on this one? Following the description (with CKEditor 4 `4.16.1` and Firefox `90.0.2`) it seems to be working fine. I see no content loss. Maybe some additional condition needs to be fulfilled? :thinking: 

Preview window:
![image](https://user-images.githubusercontent.com/1061942/128204457-ad679cec-05f7-406a-9493-9bf0f1e2badc.png)

Print window:
![image](https://user-images.githubusercontent.com/1061942/128204510-3aac6e8a-2bd1-46e5-ba98-0195c75ada68.png)

**Comment by KarolDawidziuk** [comment]
@f1ames It's strange because for me it's not working. There are no additional steps for reproducing it that were not mentioned in #4444. I tested it on macOS and Win7(vBox) and it fails. After [#4758](https://github.com/ckeditor/ckeditor4/pull/4758) fix `preview` works but `print` still not.

**Comment by f1ames** [comment]
@KarolDawidziuk so if you mentioned #4444 it means it is CDN related too? It's not mentioned anywhere in this ticket or issue description so if that's the case it would be good to update repo steps / description here.
