### ISSUE TITLE
CKEditor4 online builder not working

### ISSUE THREAD

**Issue by Saiprakash9** [ckeditor/ckeditor4#4792]
## Type of report

Bug

Link https://ckeditor.com/cke4/builder is not working. Giving 503 service unavailability error. Please do the needful.

<img width="1055" alt="CKEditorUnavailable" src="https://user-images.githubusercontent.com/7829196/125748051-b5c14664-ebce-4084-8894-b4d71a2e679f.png">

## Other details

* Browser: Chrome
* OS: MAC Catalina
* CKEditor version: 4.16.1
* Installed CKEditor plugins: 2019 version

**Comment by f1ames** [comment]
We did some backend systems migration yesterday so it might be related. The page you mentioned works for me, but maybe some CDN issue :thinking: 

@Saiprakash9 could you give some details from what region your are trying to access the page?

@vokiel can we check on our side if everything works fine?

**Comment by vokiel** [comment]
Indeed it was caused by the migration. It's alive again :tada:

**Comment by Saiprakash9** [comment]
@vokiel @f1ames thanks guys for resolving this. I was trying to access the page from India.
