### ISSUE TITLE
CKEditor 4.15.0 NPM package internally referring to https://cdn.ckeditor.com/4.15.0/standard-all/ckeditor.js file.

### ISSUE THREAD

**Issue by rohitmore-gep** [ckeditor/ckeditor4#4796]
### Bug

1. We are using **CKEditor NPM package - ckeditor4-angular: ^1.0.1**. In this package CKEditor internal code base referring to URL **https://cdn.ckeditor.com/4.15.0/standard-all/ckeditor.js** to load JS file.
2. Can't CKEditor make this JS file as part of NPM package itself? 
3. As JS file is getting referred through URL we are facing an issue where Client Users antivirus/VPN restricts this JS file URL.
4. Unless user white list this URL, it doesn't load. In browser >> Network tab shows clear error message while downloading this file.
5. We have seen this issue on Chrome browser only.

### Expected result
https://cdn.ckeditor.com/4.15.0/standard-all/ckeditor.js file should be loaded directly without any issues. This file can be made as a part of NPM package itself.

### Actual result
https://cdn.ckeditor.com/4.15.0/standard-all/ckeditor.js file is getting restricted at client end due to network restriction.

* Browser: Chrome, IE
* OS:  Windows
* CKEditor version:  ckeditor4-angular: ^1.0.1

**Comment by jswiderski** [comment]
This is how CKEditor works. It uses CDN URL by default but you can change that URL to e.g. local editor instance on your domain (you will need to [download](https://ckeditor.com/ckeditor-4/download/) it and add it to your project) - [https://ckeditor.com/docs/ckeditor4/latest/guide/dev_angular.html#customizing-ckeditor-preset-or-version](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_angular.html#customizing-ckeditor-preset-or-version).

**Comment by rohitmore-gep** [comment]
Hi @jswiderski,

Thanks for your response. 
We are using NPM package of **^1.0.1**, this always installs and loads latest version of CKeditor.
But if we have to change the CDN URL to our internal URL then we have to copy the whole code base in our project as an our internal component. Then later on if any update provided by CKEditor (using versioning) then we have to do all this activity manually. Is it correct?

Isn't there any alternative way, to handle this?
