### ISSUE TITLE
TypeError: b.getEditor is not a function

### ISSUE THREAD

**Issue by Egor-Lee** [ckeditor/ckeditor4#4803]
env: react 16.14.0/node 14.17.3
encountering console error as title through basic usage

import { CKEditor } from 'ckeditor4-react';
&lt;CKEditor initData={content} readOnly={true} debug={true} /&gt;

not working, any idea?

**Comment by sculpt0r** [comment]
Hi @Egor-Lee ,

thank you for your interest in CKEditor react integration. Please report any issue related to react integration at a separate repository: https://github.com/ckeditor/ckeditor4-react.

I'm closing this issue for now, but please, reopen a new in react repository. Please remember to provide every information you can. In this case, it is hard to tell what `not working` means. Is there any console error message? Without details, it is hard to tell what is happening.
