### ISSUE TITLE
Failing test: tests/plugins/pagebreak/pagebreak [SAFARI]

### ISSUE THREAD

**Issue by sculpt0r** [ckeditor/ckeditor4#4816]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

Failing test:  `test paste`

Full test path: `tests/plugins/pagebreak/pagebreak#tests%2Fplugins%2Fpagebreak%2Fpagebreak%20test%20paste`

### Expected result

*What is the expected result of the above steps?*

Test passed.

### Actual result

*What is the actual result of the above steps?*

Test failed.
```
Error
TypeError: undefined is not an object (evaluating 'range.checkReadOnly')
tests/plugins/pagebreak/pagebreak test paste

Unexpected error: undefined is not an object (evaluating 'range.checkReadOnly')
Expected: undefined (undefined)
Actual:   undefined (undefined)
```

## Other details

* Browser: Safari 14.1.2
* OS: MacOS 11.5.1
* CKEditor version: DEV (pre-released 4.16.2)
* Installed CKEditor plugins: -

**Comment by sculpt0r** [comment]
It is **not** failing on Safari 13.1 🤔 
Also, **not** failing on Chrome, FF.

Failing even back to `4.14.0` so it looks like safari problem here.

**Comment by f1ames** [comment]
DUP of https://github.com/ckeditor/ckeditor4/issues/4759.

**Comment by f1ames** [comment]
In fact https://github.com/ckeditor/ckeditor4/issues/4759 lists more than one failing test with not that much information so let's leave this open and close #4759.

We had already concluded that this is new Safari upstream not caused by changes in CKEditor 4 itself.

**Comment by f1ames** [comment]
It would be good to check if it's only the test which is failing or something is broken in the `pagebreak` plugin itself.

**Comment by sculpt0r** [comment]
Duplicate: https://github.com/ckeditor/ckeditor4/issues/4690
