### ISSUE TITLE
Failing test: tests/plugins/emoji/dropdown [Opera]

### ISSUE THREAD

**Issue by LukaszGudel** [ckeditor/ckeditor4#4817]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

Failing test: `test navigation highlights proper section when scrolls`

Full test path: `tests/plugins/emoji/dropdown#tests%2Fplugins%2Femoji%2Fdropdown%20test%20navigation%20highlights%20proper%20section%20when%20scrolls`

### Actual result

```
Travel item in navigation should be highlighted
Expected: true (boolean)
Actual:   false (boolean)
```

## Other details

* Browser: Opera 78.0.4093.112 (arm64)
* OS: BigSur 11.4
* CKEditor version: 4.16.2
* Dev unit tests

This test is failing only when running with other tests in `tests/plugins/emoji/dropdown`. If I open a single test `test navigation highlights proper section when scrolls` then it's passing.

Seems like an issue with arm64 (macbooks with M1)? This test is passing when I'm running it on Mac with Intel CPU.

**Comment by sculpt0r** [comment]
4.17.3 (pre-release) dev & presets passed. I'm closing this issue.
