### ISSUE TITLE
Failing tests: plugins/clipboard/drop [SAFARI]

### ISSUE THREAD

**Issue by sculpt0r** [ckeditor/ckeditor4#4818]
## Type of report

Bug

## Provide detailed reproduction steps (if any)
Failing tests: 
- `test internal drag and drop on editors margin (framed)` with full path: `tests/plugins/clipboard/drop#tests%2Fplugins%2Fclipboard%2Fdrop%20test%20internal%20drag%20and%20drop%20on%20editors%20margin%20(framed)`
- `test internal drag and drop on editors margin (inline)` with full path: `tests/plugins/clipboard/drop#tests%2Fplugins%2Fclipboard%2Fdrop%20test%20internal%20drag%20and%20drop%20on%20editors%20margin%20(inline)`
- `test internal drag and drop on editors margin (divarea)` with full path: `tests/plugins/clipboard/drop#tests%2Fplugins%2Fclipboard%2Fdrop%20test%20internal%20drag%20and%20drop%20on%20editors%20margin%20(divarea)`

### Expected result

*What is the expected result of the above steps?*
Tests passed.

### Actual result

*What is the actual result of the above steps?*

Tests failed.
All of them failed with: 
```
Error
TypeError: undefined is not an object (evaluating 'bookmark.is2')
tests/plugins/clipboard/drop test internal drag and drop on editors margin (framed)

Timeout: wait() called but resume() never called.
Expected: undefined (undefined)
Actual:   undefined (undefined)
```
With proper test case name of course
## Other details

* Browser: Safari 14.1.2
* OS: MacOS 11.5.1
* CKEditor version: DEV (pre-released 4.16.2)
* Installed CKEditor plugins: -

**Comment by sculpt0r** [comment]
It is **not** failing on Safari 13.1 🤔 
Also, **not** failing on Chrome, FF.

Failing even back to `4.14.0` so it looks like safari problem here.

**Comment by f1ames** [comment]
It would be good to check if it's only the test which is failing or something is broken with drag and drop handling. cc @sculpt0r

**Comment by sculpt0r** [comment]
This test was added as a response for https://github.com/ckeditor/ckeditor4/issues/2292. There is also a manual test for this issue: `droponmargin` which seems to be working.

**Comment by sculpt0r** [comment]
Duplicate: https://github.com/ckeditor/ckeditor4/issues/4689
