### ISSUE TITLE
Broken manual test: tests/plugins/uploadwidget/manual/escapecssuploadimage

### ISSUE THREAD

**Issue by LukaszGudel** [ckeditor/ckeditor4#4826]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

The editor is not loading when opening this manual test. Looking at the page HTML, there is a lot of `edito,r` strings is IDs, class names etc.
![image](https://user-images.githubusercontent.com/58658048/129019017-f633ad5f-ba56-4a31-8139-0f41eea94b76.png)

## Other details

* Browser: all browsers
* CKEditor version: 4.12.2

**Comment by jacekbogdanski** [comment]
The test looks to be working correctly, we didn't notice its inline editor.
