### ISSUE TITLE
Undo reverse entire table content instead of single cell

### ISSUE THREAD

**Issue by sculpt0r** [ckeditor/ckeditor4#4829]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Create a standard table
2. Write some text in a single cell
3. Jump to the next cell with the 'tab' key
4. Write text to each cell
5. Use undo button

### Expected result

*What is the expected result of the above steps?*
Text from the last cell is removed. All other cells contain text.
There is undo step for each cell.

### Actual result

*What is the actual result of the above steps?*
There is a single undo step that reverses the entire input from the table.

## Other details

* Browser: -
* OS: -
* CKEditor version: PROD (pre-released) 4.16.2
* Installed CKEditor plugins: table

**Comment by jacekbogdanski** [comment]
Could be probably fixed similarly like https://github.com/ckeditor/ckeditor4/blob/90e680e17d9d385077e47edd5dde60efa607e8c7/plugins/undo/plugin.js#L1125-L1131
