### ISSUE TITLE
Tag <abbr /> disappear after switching "Show source"

### ISSUE THREAD

**Issue by chrisooo3** [ckeditor/ckeditor4#4838]
I have created a plugin that wraps/unwraps selected text with `<abbr />` tag. 
After wrapping the selected text with `<abbr />` and clicking "Show source" button two times, `<abbr />` tag disappears.

Here we have [jsbin](https://jsbin.com/joxerikowo/1/edit?html,js,console,output).

## Provide detailed reproduction steps
1. Select text
![image](https://user-images.githubusercontent.com/70841270/129444100-73cdd256-cbfe-42c1-97c2-97d6582fad14.png)

2. Use my `abbr` plugin, it has no icon, so try to click here: 
![image](https://user-images.githubusercontent.com/70841270/129444130-d5b6a7a3-4190-4674-8cd0-045a45b8269b.png)
3. Click "Show source"(Źródło dokumentu in my case) two times.

### Expected result

The `<abbr />` tag should not disappear. 

### Actual result

The `<abbr />` tag disappears.

**Comment by Comandeer** [comment]
It's connected with the fact that you didn't alter [Advanced Content Filtering](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_acf.html) rules to allow a new element. You can allow this element by adding `allowedContent` property (which is, unfortunately, not documented right now) to the second argument of `editor.ui.addButton()` method:

```javascript
 editor.ui.addButton('greg', {
 	label: 'Add/Delete abbr',
 	command: 'wrapWithAbbr',
    toolbar: 'insert',
    allowedContent: 'abbr[title]'
 });
```
