### ISSUE TITLE
Pasting a link with & will is changed to &amp; which can breaks link

### ISSUE THREAD

**Issue by meghanking** [ckeditor/ckeditor4#4858]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Visit CKEditor 4 demo article 
2. Copy the following link: https://www.google.com/search?q=ckeditor+4+demo&sxsrf=AOaemvIOMlAFDqLmu7CedntFOZM__buC4Q%3A1629916057505&source=hp&ei=mYsmYYbvG5H70AST5RQ&iflsig=ALs-wAMAAAAAYSaZqel7dIi7ht5uNwnupRKhKbR7VdtE&oq=ckeditor+4+demo&gs_lcp=Cgdnd3Mtd2l6EAMyBAgjECcyBQgAEIAEMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeMgYIABAWEB46BwgjEOoCECc6BQgAEJECOgQIABBDOg4ILhCABBCxAxDHARCjAjoRCC4QgAQQsQMQgwEQxwEQ0QM6CwguEIAEELEDEIMBOgoIABCxAxCDARBDOggIABCABBCxAzoLCC4QgAQQxwEQowI6CAgAELEDEIMBOgsIABCABBCxAxCDAToICC4QsQMQgwE6CAguEIAEELEDOgsIABCABBCxAxDJAzoFCAAQkgM6BwguELEDEEM6DgguEIAEELEDEIMBEJMCOgUILhCABDoFCC4QsQM6DgguEIAEELEDEMcBEK8BOgoIABCABBCHAhAUOgsILhCABBDHARDRAzoHCAAQsQMQQ1CFFVirOWDYOmgCcAB4AIABe4gB9hCSAQQxNi44mAEAoAEBsAEK&sclient=gws-wiz&ved=0ahUKEwjGn_m85szyAhWRPZQKHZMyBQAQ4dUDCAo&uact=5
3. Paste into CKEditor

### Expected result

*What is the expected result of the above steps?*
Recognized as a link with no changes to URL

### Actual result
URL changes to the following, where "&" is replaced with "& a m p ;" (but with no spaces, but preview of this text not rendering as expected)
https://www.google.com/search?q=ckeditor+4+demo&amp;sxsrf=AOaemvIOMlAFDqLmu7CedntFOZM__buC4Q%3A1629916057505&amp;source=hp&amp;ei=mYsmYYbvG5H70AST5RQ&amp;iflsig=ALs-wAMAAAAAYSaZqel7dIi7ht5uNwnupRKhKbR7VdtE&amp;oq=ckeditor+4+demo&amp;gs_lcp=Cgdnd3Mtd2l6EAMyBAgjECcyBQgAEIAEMgYIABAWEB4yBggAEBYQHjIGCAAQFhAeMgYIABAWEB46BwgjEOoCECc6BQgAEJECOgQIABBDOg4ILhCABBCxAxDHARCjAjoRCC4QgAQQsQMQgwEQxwEQ0QM6CwguEIAEELEDEIMBOgoIABCxAxCDARBDOggIABCABBCxAzoLCC4QgAQQxwEQowI6CAgAELEDEIMBOgsIABCABBCxAxCDAToICC4QsQMQgwE6CAguEIAEELEDOgsIABCABBCxAxDJAzoFCAAQkgM6BwguELEDEEM6DgguEIAEELEDEIMBEJMCOgUILhCABDoFCC4QsQM6DgguEIAEELEDEMcBEK8BOgoIABCABBCHAhAUOgsILhCABBDHARDRAzoHCAAQsQMQQ1CFFVirOWDYOmgCcAB4AIABe4gB9hCSAQQxNi44mAEAoAEBsAEK&amp;sclient=gws-wiz&amp;ved=0ahUKEwjGn_m85szyAhWRPZQKHZMyBQAQ4dUDCAo&amp;uact=5
*What is the actual result of the above steps?*

## Other details

The above change to the URL does allow for it to be navigated to, but this is not the case for our customer scenario. In our case the URL will navigate to error page because the amp; being added is unexpected

* Browser: Chrome
* OS: Windows
* CKEditor version: CKEditor 4
* Installed CKEditor plugins: link

## EDIT

I have managed to reproduce this problem. When you copy actual link from the HTML page e.g. `https://www.google.com/search?q=google&client=firefox-b-d`  then it is pasted correctly -> You will have `&` in wysiwyg and `&amp;` in source mode.

If however you will paste the same link but you will copy it from e.g. Notepad, you will get `&amp;` in wysiwyg and `&amp;amp;` in source mode which in my opinion can break the link (the actual non-working link can be found in support issue no. 70206). 

![obraz](https://user-images.githubusercontent.com/5314687/133596638-91782344-8aaa-4678-b0c0-d761c65da535.png)

![obraz](https://user-images.githubusercontent.com/5314687/133596689-c3f1c2b2-11e4-4b45-9765-c749d8514223.png)

**Comment by Comandeer** [comment]
Can you provide the not working link? `&amp;` should be interpreted by browser the same way as `&` (as it's the same character, just written as an entity).

**Comment by meghanking** [comment]
I have provided examples of not working link within email thread to sla@cksource.com

I am hoping to understand if this is an issue with CKEditor 4 autolink with plans to fix, or if this is an issue with those websites not handling &amp; within their URLs as expected.
