### ISSUE TITLE
Bump version of the editor in bug templates

### ISSUE THREAD

**Issue by KarolDawidziuk** [ckeditor/ckeditor4#4902]
## Type of report

Task

## Provide description of the task

Our samples using an old version `4.13.1` of the editor. We should update it.
 
* CodePen: https://codepen.io/Comandeer/pen/ExaMgpz?editors=1010
* JSFiddle: https://jsfiddle.net/Comandeer/d6ey8a2w
* JSBin: https://jsbin.com/keqekef/1/edit?html,js,output
* StackBlitz: https://stackblitz.com/edit/js-vcqfw3

## Other details

...

**Comment by jacekbogdanski** [comment]
Let's do it after 4.17.0 release.

**Comment by sculpt0r** [comment]
Since https://github.com/ckeditor/ckeditor4/releases/tag/4.17.0 it is no longer blocked.
