### ISSUE TITLE
[Accessibility]Narrator said:"Press ALT 0 for help". Enter ALT+0 can't get any respond.

### ISSUE THREAD

**Issue by dayatu2019** [ckeditor/ckeditor4#4929]
In my webpart. "`<span id="cke_123" class="cke_voice_label">Press ALT 0 for help</span>`"
Narrator said:"Press ALT 0 for help". 
But don't have any respond.
So, how to disable this span?``

**Comment by KarolDawidziuk** [comment]
Hi, @dayatu2019 
Can you provide more details about this issue?
For me `ALT+0` is working correctly and showing accessibility instructions.

We would like to help solve your issue but it seems you have missed our [templates for feature requests and bug reports](https://github.com/ckeditor/ckeditor4/issues/new/choose). Their purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.
