### ISSUE TITLE
The text written in ckeditor becomes available on the DOM only after the form is submitted

### ISSUE THREAD

**Issue by ebdurrehm** [ckeditor/ckeditor4#4947]
## Type of report

Bug

Hi, ckeditor In version 4.16.2, the information written on the ckeditor falls on textarea only after the form is submitted. If we try to get the textarea information through the DOM before the form is submitted, then the empty value will return. This causes data to be sent blank when posting data to the server with axios and alternatives.

### Expected result

*after form is submitted *
![image](https://user-images.githubusercontent.com/42205442/140051594-f81bcdd1-2edc-482b-9f58-67668e95d901.png)

### Actual result
before form is submitted
![image](https://user-images.githubusercontent.com/42205442/140051273-4c163d73-8b5b-4da9-a17f-500975a109bb.png)

## Other details

* Browser:  Edge
* OS: Version 95.0.1020.40 (Official build) (64-bit)
* CKEditor version: …4.16.2
* Installed CKEditor plugins: … https://cdn.ckeditor.com/4.16.2/full/ckeditor.js

**Comment by Comandeer** [comment]
Do you have [`config.autoUpdateElement`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-autoUpdateElement) option set to `true`? Can you show the code that is used to submit the form?

You can also manually call [`editor#updateElement()`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#method-updateElement) method right before the form submission to update the value of the textarea.

**Comment by ebdurrehm** [comment]
> Do you have [`config.autoUpdateElement`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-autoUpdateElement) option set to `true`? Can you show the code that is used to submit the form?
> 
> You can also manually call [`editor#updateElement()`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#method-updateElement) method right before the form submission to update the value of the textarea.


My code
![image](https://user-images.githubusercontent.com/42205442/140085069-d079ab8c-47ea-4f70-9c23-1953e3fa538f.png)

![image](https://user-images.githubusercontent.com/42205442/140085069-d079ab8c-47ea-4f70-9c23-1953e3fa538f.png)

**Comment by ebdurrehm** [comment]
> Do you have [`config.autoUpdateElement`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-autoUpdateElement) option set to `true`? Can you show the code that is used to submit the form?
> 
> You can also manually call [`editor#updateElement()`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#method-updateElement) method right before the form submission to update the value of the textarea.


Thank you very much. The method you mentioned worked and the textarea was updated before the form was submitted. I close  the Issue.
