### ISSUE TITLE
Mention of how long CKE4 will be supported?

### ISSUE THREAD

**Issue by shabab477** [ckeditor/ckeditor4#4957]
## Type of report

Docs

## Provide a description of requested docs changes

We know that [CKEditor5](https://ckeditor.com/docs/ckeditor5/latest/index.html) has been released. Currently, we have legacy data that needs to be shown on CKE4 only because CKE5 has this new schema-model-view architecture which removes a few elements and also doesn't allow full page edit. Our team was wondering for how long CKE4 will be supported?  [CKE Support](https://support.ckeditor.com/hc/en-us/articles/115005281629-How-long-will-CKEditor-4-be-supported-#:~:text=The%20CKEditor%204.,support%20is%20guaranteed%20until%202023.) mentions that support will be given till 2023. Will this time be increased later on? 

*What is the purpose and what should be changed?*

Add support timeline for CKE4 and additional info about whether the timeline may change or not.

**Comment by lslowikowska** [comment]
Hi @shabab477, thank you for posting this question. I encourage you to [message us](https://ckeditor.com/contact/) so we could address the specific questions you have and answer your doubts directly.

**Comment by jacekbogdanski** [comment]
Since the question is not directly related to any bug or feature in CKEditor 4, I'm closing it. As @lslowikowska already wrote, please contact our support team regarding product questions.
