### ISSUE TITLE
Indenting Tables Does Not Work

### ISSUE THREAD

**Issue by jbalinski** [ckeditor/ckeditor4#4976]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

This issue has been around since CKEditor 3 and is documented here: https://dev.ckeditor.com/ticket/3140

There currently isn't a workflow available that will allow a user to indent a table.  

### Expected result
Be able to use the indent and outdent buttons on a table.

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: Chrome / Edge
* OS: Windows 10
* CKEditor version: 4.14.0
* Installed CKEditor plugins:
basicstyles, button, clipboard, colorbutton, colordialog, contextmenu, dialogadvtab, dialogui, divarea, enterkey, entities, fakeobjects, filetools, floatpanel, font, htmlwriter, image2, indent, indentblock, indentlist, link, list, listblock, liststyle, mentions, menu, menubutton, notification, notificationaggregator, panel, panelbutton, pastefromword, pastetext, pastetools, popup, removeformat, resize, richcombo, scayt, showborders, tab, table, tableresize, tabletools, toolbar, undo, uploadimage, widget

**Comment by Comandeer** [comment]
I can confirm the issue. However, I'll change the type of the ticket to feature request as it has never worked so it needs to be added to the editor.

Related issue: #3347.

**Comment by jacekbogdanski** [comment]
I would treat it as a dup of #3347 as both features require introducing the same logic which should also take into account PFW.
