### ISSUE TITLE
Issue resolved

### ISSUE THREAD

**Issue by paulovich10** [ckeditor/ckeditor4#4990]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. …
2. …
3. …

### Expected result

*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by sculpt0r** [comment]
Since the problem is solved - I'm closing this issue.
