### ISSUE TITLE
pastetext plugin notification not localized in italian

### ISSUE THREAD

**Issue by ezrapace1** [ckeditor/ckeditor4#4995]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

CkEditor 4 localized in italian.

1. over on pastetext, you'll get 'title' localized in italian;
2. click on pastetext, you'll get 'notification' not localized in italian;

### Expected result

I should see the notification of the pastetext plugin in italian.

### Actual result

I see the notification of the pastetext plugin in english.

## Other details

* Browser: Chrome 96.0.4664.45
* OS: Windows 10
* CKEditor version: 4
* Installed CKEditor plugins: clipboard, colorbutton, find, justify, link, pastefromword, pastetext, removeformat, selectall

All the other plugins installed are localized completely in italian.

![editor](https://user-images.githubusercontent.com/95416197/144413173-fb644556-c841-490a-9d40-924052dacf4d.png)

**Comment by sculpt0r** [comment]
Hi, @ezrapace1 

Definitely `4.17.1` is fully localized for Italian and looks it is working fine. Also, you can verify it on: https://www.transifex.com/ckeditor/ckeditor/

As you can see, we updated this notification 4 and 2 years ago in the `clipboard` and `pastetext` plugin:
- https://github.com/ckeditor/ckeditor4/blame/master/plugins/clipboard/lang/it.js
- https://github.com/ckeditor/ckeditor4/blame/master/plugins/pastetext/lang/it.js

I can encourage you to update the editor or just add those language keys to your current build. If you still encounter problems - feel free to open another issue with a detailed description of the bug.
