### ISSUE TITLE
Pasting bold text wrapped in <b> tags in ckeditor is not getting wrapped in <strong> tags even though we have config.coreStyles_bold = {element: 'strong'}

### ISSUE THREAD

**Issue by ananthula** [ckeditor/ckeditor4#5000]
## Type of report

Bug
1)In any editor(ex. jsfiddle) write <b>Make me strong</b> and copy the output, paste it in ck editor.
2)Inspect the text in ckeditor.
3)As we have config.coreStyles_bold = {element: 'strong'}, the text is still wrapped in <b> tags.

### Expected result
As we have config.coreStyles_bold = {element: 'strong'}, the text is expected to be wrapped in <strong> tags.

### Actual result
 The text is still wrapped in <b> tags.

**Comment by KarolDawidziuk** [comment]
Hi, @ananthula 

I cannot reproduce this issue. Tested on macOS and Windows.
But to be sure. You copied `<b>Make me strong</b>`, opened `sourcemode` in the editor, paste content, and back to `WYSIWYG` mode?  

https://user-images.githubusercontent.com/18471998/146517334-a5b6705e-c168-47a8-88aa-c4f46b9bd21d.mov
