### ISSUE TITLE
Copy from word is not working sometimes

### ISSUE THREAD

**Issue by margamvineel** [ckeditor/ckeditor4#5008]
## Type of report

Bug

## Provide detailed reproduction steps (if any)
Copy from word is not working sometimes, Styles are not getting applied, Bold font is missing.

1. …
2. …
3. …

### Expected result

*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by KarolDawidziuk** [comment]
Hi @margamvineel
Thank you for the report.

I understand that you've noticed the problem with pasting content from Word into the editor?

Can you provide more details about this issue? 
Browser, CKEditor version, OS, and cases when pasting not working.

Also, the best option would be to provide a working example. 

I encourage you to use one of our samples: 
* [CodePen](https://codepen.io/Comandeer/pen/ExaMgpz?editors=1010)
* [JSFiddle](https://jsfiddle.net/Comandeer/d6ey8a2w)
* [JSBin](https://jsbin.com/keqekef/1/edit?html,js,output)
* [StackBlitz](https://stackblitz.com/edit/js-vcqfw3)
