### ISSUE TITLE
website dosent work ckeditor

### ISSUE THREAD

**Issue by eurairapelli** [ckeditor/ckeditor4#5009]
link: https://ckeditor.com/cke4/builder

button upload build config dosent work

https://code.jquery.com/jquery-2.2.4.min.js is off

**Comment by KarolDawidziuk** [comment]
Hello, @eurairapelli 
Thank you for the report.

Everything seems to be working fine for me.
Tested on all modern browsers on Windows and macOS.

Maybe you have some browser extension that causing this issue? 
Please try again using the upload button in the private tab.

I'm closing this issue but if the problem persists feel free to reopen this issue or open another one  😉

**Comment by eurairapelli** [comment]
Close this ticket plz

Em qui., 30 de dez. de 2021 às 08:32, Kratek ***@***.***>
escreveu:
