### ISSUE TITLE
The line added after enter key is pressed does not have the styles of the line where enter was pressed if empty

### ISSUE THREAD

**Issue by gandhar-workik** [ckeditor/ckeditor4#5016]
Bug
Hi! The problem I'm facing is more of a question than a bug. 
When enter is pressed the next line is added as `<p>&nbsp</p>`. This line does not have the styles of the line where enter was pressed. So when 'Source' button is pressed or the code is saved the spacing isn't retained. 
How can those styles be added to the newly added line?

### Reproduction Steps
Go to the following page:
[https://ckeditor.com/latest/samples/index.html](https://ckeditor.com/latest/samples/index.html)
1. Add some text
2. Give this text some font-size (say 36)
3. Press enter (you'll see that the next line appears to be as big as the earlier
4. Click on "Source" button to view the source
5. Click again on "Source" button to view the editor view.

### Expected result
The newly created line should remain of the same height (i.e. the styles should be retained) after step 5.

### Actual result
The line takes the height equal to that of the `<p>` tag. 

https://user-images.githubusercontent.com/73214564/148192170-bee17b6e-a37c-45cf-bdf8-860b40eeec5f.mp4

**Comment by sculpt0r** [comment]
Possible related: https://github.com/ckeditor/ckeditor4/issues/4626

**Comment by sculpt0r** [comment]
Hi @gandhar-workik,
Thank you for the report. I can confirm the described situation. However, I must say it is a by-design behavior. When you press enter and start typing - the style is preserved. However, if you left it as it is - there is nothing to style, and when you switch to the source mode, the information about the styles is not preserved. To answer your question: just add any content to the new line before you switch modes.

I'm closing this issue for now.
