### ISSUE TITLE
Copied text from MS word becoming an image after pasting it in Editor

### ISSUE THREAD

**Issue by macray125** [ckeditor/ckeditor4#5025]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Create plain text in MS word and copy it.
2. Paste it in CKeditor
3. see image below for sample result

## Config

`var editor = CKEDITOR.replace( 'description', {
                extraPlugins: 'easyimage',
                removePlugins: 'image',
                height : 500,
                removeButtons: 'CopyFormatting,Subscript,Superscript,RemoveFormat,About,Anchor,Maximize,ShowBlocks,BidiLtr,BidiRtl,Language,Flash,Table,HorizontalRule,Smiley,SpecialChar,PageBreak,Iframe,Source,Save,NewPage,Preview,Print,Templates,Cut,Copy,Paste,PasteText,PasteFromWord,Undo,Redo,find,selection,spellchecker,Find,Replace,SelectAll,Scayt,Form,Checkbox,Radio,TextField,Textarea,Select,Button,ImageButton,HiddenField,CreateDiv',
                cloudServices_tokenUrl: 'tokenUrl here',
                cloudServices_uploadUrl: 'uploadUrl'
            } );`

### Expected result

the text should not change to an image

### Actual result

![image](https://user-images.githubusercontent.com/4024193/148856306-3c15129f-3b43-4afe-8842-3ce95f01e9de.png)

## Other details

* Browser: Chrome Version 96.0.4664.110 (Official Build) (arm64)
* OS: Mac OSX v 12.1
* CKEditor version: 4.9.2
* Installed CKEditor plugins: …

**Comment by Comandeer** [comment]
The issue is caused by Easy Image plugin, see #4994.
