### ISSUE TITLE
Failing test `/tests/plugins/find/find`

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor4#5055]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open http://localhost:1030/tests/plugins/find/find

### Expected result

All tests pass

### Actual result

There are failing tests:

<img width="598" alt="Failing tests for space separators – EN SPACE, EM SPACE and THIN SPACE" src="https://user-images.githubusercontent.com/1078728/151789403-271db841-f218-440f-ba4e-c212e682246f.png">

## Other details

* Browser: all
* OS: all
* CKEditor version: 4.17.2 (built)
* Installed CKEditor plugins: find

See similar #5054.

**Comment by Comandeer** [comment]
On IE 11 the issue is present also in tests for other separators.

**Comment by sculpt0r** [comment]
Some of the unicode characters are turned into entities (e.g. `\u2003` is turned into `&emsp;`). If you take a look at the source of the editor or when you `getData()`. However, tests are using `getData( true )` but as we see - it is not working in all cases.

**Comment by Comandeer** [comment]
Closed in #5066.
