### ISSUE TITLE
Unstable tests `/tests/core/creators/detachedinline`

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor4#5057]
## Type of report

Failing test

## Provide detailed reproduction steps (if any)

1. Open http://localhost:1030/tests/core/creators/detachedinline

### Expected result

All tests pass

### Actual result

Sometimes tests randomly fail, especially ones connected to immediate editor's creation.

## Other details

* Browser: IE11
* OS: Windows 7
* CKEditor version: 4.17.2 (built)
* Installed CKEditor plugins: N/A

**Comment by KarolDawidziuk** [comment]
Unfortunately, I cannot reproduce this issue. I made 15 attempts and the tests were passed each time.

**Comment by Comandeer** [comment]
I can't reproduce it anymore either.
