### ISSUE TITLE
User issue with CKeditor

### ISSUE THREAD

**Issue by LukeSingleton** [ckeditor/ckeditor4#5072]
Hi there
We are having an issue with a 3rd party application, Bullhorn.
One of our users is getting the below error:

Failed to load resource: net::ERR_NAME_NOT_RESOLVED
ckeditor.js:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
startup.js:97 app started, checking for valid session
startup.js:237 loaded required data: hierarchy
startup.js:237 loaded required data: groups
startup.js:139 begin load
startup.js:237 loaded required data: current-client
startup.js:237 loaded required data: rss-feeds
startup.js:237 loaded required data: currencies
startup.js:237 loaded required data: ratio-configs
startup.js:237 loaded required data: tag-categories
startup.js:237 loaded required data: timeframes
startup.js:237 loaded required data: dealmusic
startup.js:237 loaded required data: snd-report-configs
startup.js:237 loaded required data: tags
startup.js:237 loaded required data: users
startup.js:237 loaded required data: kpis
startup.js:242 loaded all required data
4index.js:199 Wrapper div has no height or width, try overriding style with `containerStyle` option
value @ index.js:199
ckeditor.js:1 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
log.js:118 [post-robot] fullpage :: app.bullhornstaffing.com/ 

	 #receive request :: register :: https://app.bullhornstaffing.com 

 Object
log.js:118 [post-robot] fullpage :: app.bullhornstaffing.com/ 

	 #send response :: register :: https://app.bullhornstaffing.com 

 Object
log.js:118 [post-robot] iframe :: app.bullhornstaffing.com/content/record/Candidate/40153/overview 

	 #receive response :: register :: https://app.bullhornstaffing.com 

 Object
main-es2015.7c6fbeb54754ccd09726.js:1 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://universal.bullhornstaffing.com') does not match the recipient window's origin ('https://app.bullhornstaffing.com').
send @ main-es2015.7c6fbeb54754ccd09726.js:1
vendor-es2015.48e352a9819fe3120e6d.js:1 ERROR ReferenceError: CKEDITOR is not defined
    at e.ngAfterViewInit (/vendor-es2015.48e352a9819fe3120e6d.js:1:1428035)
    at Dn (/vendor-es2015.48e352a9819fe3120e6d.js:1:2049149)
    at Tn (/vendor-es2015.48e352a9819fe3120e6d.js:1:2048990)
    at An (/vendor-es2015.48e352a9819fe3120e6d.js:1:2048716)
    at Xr (/vendor-es2015.48e352a9819fe3120e6d.js:1:2071281)
    at /vendor-es2015.48e352a9819fe3120e6d.js:1:2070631
    at Xr (/vendor-es2015.48e352a9819fe3120e6d.js:1:2070656)
    at /vendor-es2015.48e352a9819fe3120e6d.js:1:2070631
    at Xr (/vendor-es2015.48e352a9819fe3120e6d.js:1:2070656)
    at _o (/vendor-es2015.48e352a9819fe3120e6d.js:1:2077641)
ai @ vendor-es2015.48e352a9819fe3120e6d.js:1

When we log in to this user's account from a different location we don't get any errors.  

We have tried different networks, swapped out the user's laptop, done a dns flush, installed a new browser and no change.  When the user's laptop was used in a different location no errors.  

Any experts out there who could help with this issue?

Many thanks

Luke

**Comment by Comandeer** [comment]
The software you are referring to is a third-party one, and it is not maintained by CKSource. Since we cannot fix issues with the code that does not belong to us, we are unable to help solve your issue. Please redirect your question to the software’s author who should be able to review the problem and suggest a solution.

If, however, after contacting the software’s maintainer you find out the issue lies on the editor’s side, and you can provide a test case file showing the problem, we will be happy to have a look at it.
