### ISSUE TITLE
Export to pdf does not work with Smiley

### ISSUE THREAD

**Issue by abd800** [ckeditor/ckeditor4#5083]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. … Add one of the Smiley
2. … Press on Export to PDF
3. …

### Expected result

*What is the expected result of the above steps?*
**Pdf file with Smile**
### Actual result

*What is the actual result of the above steps?*
**Pdf without Smile** 
[ckeditor4-export-pdf.pdf](https://github.com/ckeditor/ckeditor4/files/8034763/ckeditor4-export-pdf.pdf)

## Other details

* Browser: … Firefox
* OS: … Windows
* CKEditor version: … 4.17.1
* Installed CKEditor plugins: …

**Comment by KarolDawidziuk** [comment]
Hi, @abd800 and thank you for the report.

For now, I cannot confirm that issue. It's looking like everything works well for me. Tested on Windows and macOS.
Could you provide more details about this issue? 

- Have you used some of 3rd party plugins?
- Could you check if there is an error in the console after you selecting the export to pdf option?
- Can you provide some working sample with your editor configuration? This will allow us to check if any particular editor configuration can cause such a problem.

I encourage you to use one of our samples to create the reproduction sample:

* [CodePen](https://codepen.io/karoldawidziuk/pen/LYzJvdx)
* [JSFiddle](https://jsfiddle.net/Kratek_95/nhwe5uLq)
* [JSBin](https://jsbin.com/gubepar/edit?html,js,output)
* [StackBlitz](https://stackblitz.com/edit/ckeditor4-bug-report)

**Comment by abd800** [comment]
We decide to not use this pdf plug in.

You can close this ticket.
Thanks
