### ISSUE TITLE
Characters appearing instead of the text that's typed in

### ISSUE THREAD

**Issue by hikingcycler** [ckeditor/ckeditor4#5086]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

We've gotten several reports from users who say that they typed a message into the editor using plain text, clicked "done" and then exited the program. Before they exited the message looked fine, still in plain text. However later when they went back in to take another look at the message, everything had been converted to characters. They deny using any paste features and/or source code,  and are only typing the text directly in the editor, then closing.

While we have been unable to recreate the issue on our end, the number of incidents of this happening and being reported to us have increased in frequency over the past few weeks. Examples are below:

[CK Editor Weird Characters Issue](https://user-images.githubusercontent.com/99500351/153646848-f548943c-7e58-4960-ab72-ce34a36dfc5a.png)

[CK Editor Weird Characters Issue example 2](https://user-images.githubusercontent.com/99500351/153646927-7de2e8e7-200a-49fc-ae28-a42b444ce42a.png)

>%3Cp%3EThank+you+for+registering+your+scouts+and+adults+as+participants+or+staff+for+our+Potawatomi+Klondike+Derby+this+weekend.+The+weather+should+be+perfect+for+the+Klondike+Derby.+Boots+are+a+necessity%2C+the+snow+is+deep%2C+2%2B+feet.%26nbsp%3B%3C%2Fp%3E%0A%0A%3Cp%3EEach+person+must+remember+to+bring+at+least+one+mask+with+them+to+this+event.%3C%2Fp%3E%0A%0A%3Cp%3EPlease+read+the+UPDATED+%3Ca+href%3D%22https%3A%2F%2Fscoutingevent.com%2Fattachment%2FBSA129%2Fdocument_16438405360_4182.pdf%22+target%3D%22_blank%22%3E%3Cstrong%3EPW+Klondike+Derby+Program+Guidebook%3C%2Fstrong%3E%3C%2Fa%3E+for+a+more+comprehensive+%26quot%3BWhat+to+Bring%26quot%3B+list+and+other+important+information.%3C%2Fp%3E%0A%0A%3Cp%3EBelow+is+a%26nbsp%3Blink+to+your+Registration+Summary.%26nbsp%3B+If+you+have+not+yet+added+the+names+of+your+participants%2C+use+it+to+add+them+now.%3C%2Fp%3E%0A%0A%3Cp%3ENOTE%3A%26nbsp%3B+This+email+will+be+sent+again+after+registration+closes+at+4+PM.%3C%2Fp%3E%0A%0A%3Cp%3E%3Cstrong%3E%7B%24registrationSummary%7D%3C%2Fstrong%3E%3C%2Fp%3E%0A

## Other details

* Browser: … Chrome
* OS: … Windows 10
* CKEditor version: … 4.4.5
* Installed CKEditor plugins: …

**Comment by hikingcycler** [comment]
This is still a recurring issue/bug.

**Comment by Comandeer** [comment]
Sorry for the delayed response.

Could you provide more information? From the screens you provided, it seems like the program, in which CKE4 is used, incorrectly handles form data and does not decode it before inserting it back to the editor. I assume that the editor is inside a `form`. [A similar sample](https://ckeditor.com/docs/ckeditor4/latest/examples/savetextarea.html) can be found in CKEditor 4's documentation, however, I can't reproduce the issue there.

**Comment by hikingcycler** [comment]
> Could you provide more information? From the screens you provided, it seems like the program, in which CKE4 is used, incorrectly handles form data and does not decode it before inserting it back to the editor. I assume that the editor is inside a `form`. 

Thank you for your reply. Yes, we use CKE4 in our program which we manage via DBeaver database administration tool and is hosted by AWS. The editor is inside of a mass email communication "form". In these incidents, the user created an email message within the editor, scheduled to be sent out at a later date - typing plain text directly into the editor. When they finished, they "closed" the editor and exited the "form" area of our program. They went to a different area of the program, came back later to take a final look at the email communication typed into the CKE4 editor, and it was no longer the plain text they had typed in - it had been "converted" to the code and characters shown in the screenshots provided.

**Comment by Comandeer** [comment]
It seems that the program you are using incorrectly handles form data and does not decode it after reinserting into the editor. As you pointed out, the issue is after reopening the editor – probably after the program inserted to the editor the data it saved earlier.

The issue you are describing seems to originate from third-party software, that is not maintained by CKSource. Since we cannot fix issues with the code that does not belong to us, we are unable to help solve your issue. Please redirect your question to the software’s author who should be able to review the problem and suggest a solution.

If, however, after contacting the software’s maintainer you find out the issue lies on the editor’s side, and you can provide a test case file showing the problem, we will be happy to have a look at it.
