### ISSUE TITLE
Insecure Randomness ckeditor4

### ISSUE THREAD

**Issue by eliakouruklis** [ckeditor/ckeditor4#5088]
For older versions like ckeditor4, I reported an "Insecure Randomness" vulnerability.
On line 10 of ckeditor.js, is it a real vulnerability? how can i support it?
Tanks

**Comment by jacekbogdanski** [comment]
@eliakouruklis security issues should be reported via [our contact form](https://ckeditor.com/contact/).

For security reasons, I removed the original description. Please, use the link above to contact our support team.
