### ISSUE TITLE
webspellchecker not working

### ISSUE THREAD

**Issue by vmasanas** [ckeditor/ckeditor4#5092]
I'm trying to use the scayt plugin for the translations and seems it stopped working recently.
I get this error when i try to do a spellcheck:

Subscription is disabled or doesn't exist. Contact support@webspellchecker.net for more details.

This was working until recently so not sure if something has changed on either side that might be causing this.
I've tried on a different installation and I also get the same error there.
I'm using the standard license that comes with the package, no custom license used here.
I'm running on CKeditor version 4.4.7 and 4.15.1 as a plugin on DNN platform.

**Comment by jacekbogdanski** [comment]
Hey @vmasanas, please see https://github.com/WebSpellChecker/ckeditor-plugin-wsc/issues/67
