### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by macray125** [ckeditor/ckeditor4#5104]
## Type of report

Bug

## Provide detailed reproduction steps (if any)
1. newly installed CKeditor 4.17.2

### Expected result

should not have a console error

### Actual result

![CKeditor 4 17 2 issue](https://user-images.githubusercontent.com/4024193/155659136-4714f4cf-655f-4ffb-a3e8-2fbb2ca746c6.jpg)

## Other details

* Browser: Chrome Version 98.0.4758.102 (Official Build) (64-bit)
* OS: Windows 10
* CKEditor version: 4.17.2
* Installed CKEditor plugins: all plugins in 4.17.2 standard build

**Comment by KarolDawidziuk** [comment]
Hello, @macray125 and thank you for the report.

For now, I cannot confirm this issue. 
Is `description` an ID attribute or a `name` of textarea element?

Could you provide a working sample showing your issue?
I encourage you to use one of samples:

* [CodePen](https://codepen.io/karoldawidziuk/pen/LYzJvdx)
* [JSFiddle](https://jsfiddle.net/Kratek_95/nhwe5uLq)
* [JSBin](https://jsbin.com/gubepar/edit?html,js,output)
* [StackBlit](https://stackblitz.com/edit/ckeditor4-bug-report)

**Comment by bounddeploy** [comment]
@macray125 This happened to me, when initialization was before load of ckeditor script.
