### ISSUE TITLE
Azure Application Gateway WAF blocking CKEDITOR data

### ISSUE THREAD

**Issue by deepakageeru** [ckeditor/ckeditor4#5105]
An Azure Application Gateway WAF (Web application firewall) policy in Prevention mode has been setup for our website

The data returned by CKEDITOR.getData() (sent in the body of a POST Http request) is rejected by the gateway with following error.

```
"ruleSetType": "OWASP_CRS",
"ruleSetVersion": "3.0.0",

"ruleId": "942450",
"message": "SQL Hex Encoding Identified",

"ruleId": "941130",
"message": "XSS Filter - Category 3: Attribute Vector",
```

Tried to post "CKEDITOR" data in base64 encoded format. Gateway threw a different error as below.

```
"ruleSetType": "OWASP_CRS",
"ruleSetVersion": "3.0.0",

"ruleId": "941120",
"message": "XSS Filter - Category 2: Event Handler Vector",


"ruleId": "942450",
"message": "SQL Hex Encoding Identified",
```

**Could anyone please suggest how CKEDITOR data can be posted to a server without gateway blocking it (may it be XSS issue or any of the OWASP_3.0 rules)**

WAF Rule set: OWASP_3.0
ckeditor.js version: 4.5.7
Backend Application: .NET based web application
Browser: Chrome and IE Edge

**Comment by jacekbogdanski** [comment]
@deepakageeru if you see any potential security vulnerability in the CKEditor 4, please contact us using our [support form](https://ckeditor.com/contact/) for security issues.

Regarding the OWASP alert in your endpoint service - it's really hard to say why it's complaining about the incoming HTML as it really depends if you are using 3rd party plugins or [custom editor ACF configuration](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_acf.html). We always encourage our users to never trust incoming HTML from the website and always incorporate content filtering on the server-side. It's basically the only safe way to ensure that HTML coming from your users is not somehow malformed either by intercepting HTTP requests or simply editor configuration. You can read about these best practices in our [Security guide](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_best_practices.html#filter-content-server-side).

Note that a valid security vulnerability should allow executing javascript code in the browser without using any additional tools like using browser dev console.

Please, contact our support if you see any potential XSS vector. For now, I'm closing this ticket to avoid public discussion about security vulnerabilities.

**Comment by hncvj** [comment]
I'm facing the same. @deepakageeru did you found any solution to this?
