### ISSUE TITLE
4.17.2 version is vulnerable to XSS

### ISSUE THREAD

**Issue by virajmota** [ckeditor/ckeditor4#5106]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. … Use ckeditor version 4.17.2 for an application.
2. … Ckeditor check for json response instead of string.
3..... Next, there is only client side validation for this library.
4. …Hence, replace &lt,&gt payload of request------------ to------ <any XSS payload script>

### Expected result

*What is the expected result of the above steps?*
client side script got encoded but however attacker could change that value in middle of way to server

### Actual result

*What is the actual result of the above steps?*
There must be encrypted value of script should be generate when request go to server.
so middle man cant find plain text so unable to replace with <XSS script>

## Other details

* Browser: …4.17.2
* OS: … Window
* CKEditor version: … 4.17.2
* Installed CKEditor plugins: …4.17.2

Thank you,
Viraj Mota

**Comment by jacekbogdanski** [comment]
Security issues should be reported by [our contact form](https://ckeditor.com/contact/).

For security reasons, I removed the original description.
