### ISSUE TITLE
Fill Empty Blocks function doesn't work as expected when allowing empty paragraphs

### ISSUE THREAD

**Issue by naxtell** [ckeditor/ckeditor4#5111]
I'm attempting to implement a function for `fillEmptyBlocks` as suggested in this old, closed ticket. [https://github.com/ckeditor/ckeditor4/issues/691](https://github.com/ckeditor/ckeditor4/issues/691)

I have the following to allow an empty `<div>` or `<p>` on their own.
`config.ignoreEmptyParagraph = false;`

I then have this function in an attempt to allow instances of `nbsp` manually added to stay, but prevent CKEditor from adding the value itself.
```
config.fillEmptyBlocks = function (element) {
    console.log('fillEmptyBlocks element');
    console.log(element);
    if (element.children.length == 0)
        return false;
};
```
If I enter `<div>&nbsp;</div>` in Source view and toggle Source view off and back on, I see that `element` has 0 children and the `nbsp` is stripped. 
If I enter at least two, `<div>&nbsp;&nbsp;</div>`, I see `element` reflects 2 children and the `nbsp` are not stripped.
Is there any other setting that would strip a single `nbsp` given that I am not ignoring empty blocks?
I have also tried including `CKEDITOR.dtd.$removeEmpty['div'] = false;` with no change in the above behavior.

**Comment by sculpt0r** [comment]
Hi @naxtell,
I'm not sure if this is a support question or bug report? In case of bug: please provide a sample project using one of those:
```
* CodePen: https://codepen.io/karoldawidziuk/pen/LYzJvdx
* JSFiddle: https://jsfiddle.net/Kratek_95/nhwe5uLq
* JSBin: https://jsbin.com/gubepar/edit?html,js,output
* StackBlitz: https://stackblitz.com/edit/ckeditor4-bug-report
```
with reproduction steps, also with expected and unexpected behaviors. Right now I'm not 100% sure what is the misbehavior. Also, please provide editor version, browser, and installed plugins - they might have significant meaning in such situations.

**Comment by naxtell** [comment]
Hi @sculpt0r,
I'm having a little trouble setting up the configuration in CodePen. I'm attempting to replicate how the CMS Kentico has implemented the tool but it isn't clear how to set that up in CodePen.
https://codepen.io/naxtell/pen/bGawmZv

**Comment by sculpt0r** [comment]
Hi @naxtell,
Unfortunately, I have no knowledge about CMS Kentico. Are you sure that the issue lies in CKEditor, not the CMS?
