### ISSUE TITLE
Failing test in `plugins/exportpdf/tests/exportpdf/` 

### ISSUE THREAD

**Issue by KarolDawidziuk** [ckeditor/ckeditor4#5114]
## Type of report

Failing test

## Provide detailed reproduction steps (if any)

1. Open `/plugins/exportpdf/tests/exportpdf/`

### Expected result

Test passed

### Actual result

Test failed
![Failing_test](https://user-images.githubusercontent.com/18471998/157227004-c206bf2a-b6df-4164-b931-8881555cad74.png)

## Other details

* Browser: IE11
* OS: Windows
* CKEditor version: 4.18.0(presets; full)

**Comment by sculpt0r** [comment]
Duplicate
