### ISSUE TITLE
Focus goes to editor when closing a dialog using "escape" key

### ISSUE THREAD

**Issue by kpasagada** [ckeditor/ckeditor4#5147]
## Type of report

Bug (accessibility issue)

## Provide detailed reproduction steps (if any)

1. Place cursor inside the editor 
2. Tab to the toolbar (using Alt+F10 on windows) and tab to the "link" button
3. Hit enter on "link" button for the link dialog to open
4. Press "escape" key to close the dialog
5. Notice that the focus goes to the editor instead of the link button

### Expected result

Focus should go back to the link button.
![image](https://user-images.githubusercontent.com/42693353/161655755-15a5e1ec-199b-4ef3-ae16-44962ff0eb76.png)

### Actual result

Focus goes back into the editor which is an accessibility issue for keyboard users. This can be observed on the CK Editor 4 demo page. https://ckeditor.com/ckeditor-4/demo/

## Other details

* Browser: Chrome 99.0.4844.84
* OS: Windows 11
* CKEditor version: 4.17.1
* Installed CKEditor plugins: Full preset

**Comment by Comandeer** [comment]
It's a similar case to the #4783 one. We decided then to [add appropriate info into our accessibility help dialog](https://github.com/ckeditor/ckeditor4/issues/4783#issuecomment-874611436). Probably the information about the focus change after closing dialogs should also be added to the dialog.
