### ISSUE TITLE
Cannot pase base64 if filebrowserUploadUrl is set

### ISSUE THREAD

**Issue by chrisooo3** [ckeditor/ckeditor4#5149]
If we set `filebrowserUploadUrl` in the config, there is no option to paste `base64` image, especially `MathType` formulas, which are base64 svg.

If we remove `filebrowserUploadUrl` from config, everything works fine, and we can easily copy-paste `MathType` formulas.

Reproduction sample: https://jsfiddle.net/xo5qpr1y/

Does anyone have any idea how to solve it?

I want to have the possibility to upload images to the server as well as the ability to paste base64 svg images from `MathType` plugin.

**Comment by jacekbogdanski** [comment]
@chrisooo3 sorry for the late response.

Could you describe what's expected outcome of using the MathType plugin with the `filebrowserUploadUrl` option? It seems rather like a feature request allowing you to decide whether you want to keep the image in content or upload it - but I would like to make sure I understand your use case. Could you confirm that:
* You want to be able to upload images using `filebrowserUploadUrl` option, but
* keep MathType images directly in HTML content?

**Comment by chrisooo3** [comment]
@jacekbogdanski I have made [fork](https://github.com/chrisooo3/ckeditor4/commit/3b39c7448216bb3d76feda22c8679e6e02a25170), which has fulfilled my needs.

Yes, I want to upload images normally, but MathType formulas save as base64 images in HTML content.

**Comment by jacekbogdanski** [comment]
Thanks for sharing that code 👍🏻
