### ISSUE TITLE
404 Error: ckeditor.com/4.4.7/standard/ckeditor.js 

### ISSUE THREAD

**Issue by astralis** [ckeditor/ckeditor4#5164]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

I'm unable to reach https://ckeditor.com/4.4.7/standard/ckeditor.js

Has it been removed?

**Comment by sculpt0r** [comment]
Hi @astralis,
Did you mean to use the URL with the `cdn` subdomain: https://cdn.ckeditor.com/4.4.7/standard/ckeditor.js ?

Was the provided URL works for you previously?

**Comment by jacekbogdanski** [comment]
CDN was down for some time yesterday redirecting to https://ckeditor.com/4.4.7/standard/ckeditor.js The issue has been already fixed so it should work as expected already, you can also read more about it here: https://github.com/ckeditor/ckeditor4/issues/475#issuecomment-1105362937

We apologize for the downtime @astralis, if you still have some issues with CDN please let us know, so we can reopen this ticket.
