### ISSUE TITLE
Breaking the link in the media embed results in an error thrown in the console

### ISSUE THREAD

**Issue by dufipl** [ckeditor/ckeditor4#5208]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Open manual test: http://localhost:1030/tests/plugins/autoembed/manual/autoembed
2. Insert embed media e.g. https://twitter.com/reinmarpl/status/573118615274315776
3. Edit the link of that embedded media to make it no sense

### Expected result

Error from UI that link is not working. No error in the console.

### Actual result

Error from UI that link is not working but also error 417 in the browser console:
`Failed to load resource: the server responded with a status of 417 (Unknown)`
![media embed issue](https://user-images.githubusercontent.com/32898551/168035439-3a0757f3-7d61-480e-b48f-525be128a72f.gif)

**Comment by Comandeer** [comment]
This is a feature of Chrome's devtools – it always logs errors about network failures in the console. It's not something we have any control over.

**Comment by dufipl** [comment]
@Comandeer I got a similar issue on Firefox, but it looks more like our fault: 
<img width="1438" alt="Zrzut ekranu 2022-07-14 o 12 05 09" src="https://user-images.githubusercontent.com/32898551/178957929-fee4601f-38a9-4aa5-99dc-89abcc3b86f5.png">
Also, the editor froze (constant loading circle) and there is no message to the user.
Is this a separate issue that I should report or maybe we would like to reopen this one?

**Comment by dufipl** [comment]
> @dufipl, I'd treat it as a separate issue.

Extracted to: https://github.com/ckeditor/ckeditor4/issues/5286
