### ISSUE TITLE
Unexpected behavior of image2 plugin wrapper after click to align center

### ISSUE THREAD

**Issue by celsowm** [ckeditor/ckeditor4#5213]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

* CodePen: https://codepen.io/celsowm/pen/PoQbpQW

1. Drag an image to ckeditor4 ([example](https://imgur.com/a/KnohQ0J))
2. Select the image
3. Click on align center button (cke_button__justifycenter)

### Expected result

*Align center only on image's "p" and not on its plugin's wrapper

### Actual result

![image](https://user-images.githubusercontent.com/369336/168405700-2c9214e9-f974-4b9f-a9e2-ea283b4ecfed.png)

*What is the actual result of the above steps?*

## Other details

* Browser: Chrome 101 and Firefox 100
* OS: Windows 10
* CKEditor version: https://cdn.ckeditor.com/4.18.0/full-all/ckeditor.js
* Installed CKEditor plugins: full-all

**Comment by Comandeer** [comment]
Could you explain a little more what is the expected result, e.g. show the desired output?

You can also check config options that allow customizing the behavior of the Justify plugin:

*   [`config.image2_alignClasses`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-image2_alignClasses),
*   [`config.justifyClasses`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-justifyClasses).

**Comment by celsowm** [comment]
> Could you explain a little more what is the expected result, e.g. show the desired output?
> 
> You can also check config options that allow customizing the behavior of the Justify plugin:
> 
>     * [`config.image2_alignClasses`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-image2_alignClasses),
> 
>     * [`config.justifyClasses`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-justifyClasses).

something like this:

![image](https://user-images.githubusercontent.com/369336/168632386-6108c89c-a118-4ca9-a546-34249819493e.png)

**Comment by celsowm** [comment]
A man... clicked in the wrong button, sorry

**Comment by celsowm** [comment]
@Comandeer : Is it possible to change image-center for an inline-css and not a class name? Reason: my webapp uses mpdf to generate pdf from ckeditor's html and css

**Comment by Comandeer** [comment]
@celsowm, unforunately there is no official way to do it. But you can manually transform classes to styles on [the `toDataFormat` event](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#event-toDataFormat) → https://jsfiddle.net/Comandeer/ta6xzvo9/ 

[The `toHtml` listener](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#event-toHtml) is needed for the editor to be able to correctly load the image with replaced classes.
