### ISSUE TITLE
SSL certificate error on CDN

### ISSUE THREAD

**Issue by sarankup** [ckeditor/ckeditor4#5223]
## Type of report

SSL security error on CDN url

Task

## Provide description of the task
https://cdn.ckeditor.com/4.16.0/full/ckeditor.js
The above given url has SSL issue.

*What steps should be taken to fulfil the task?*
None

## Other details
Please visit the given url and resolve the SSL issue.

* Browser:Chrome
* OS: Macintosh
* CKEditor version:4.16.0
* Installed CKEditor plugins:None

**Comment by chirayu25** [comment]
I am also facing the same issue.

**Comment by thinkgear** [comment]
I was facing the same issue. There is some issue with the cdn.ckeditor.com domain SSL certificate as https://cdn.ckeditor.com/ is also not working.

**Comment by jadhav-chetan** [comment]
facing same issue, for a workaround downloaded all JavaScripts and CSSs under static files.

**Comment by girish7221** [comment]
I am also facing the same issue. Because of this our main domain showing insecure connection.

**Comment by wwalc** [comment]
Apologies for the inconvenience. Could you please check if you still have issues on your end? According to CacheFly the issue has been resolved yesterday @ 10:00am UTC.

If the issue persists, can you visit [https://cdn.ckeditor.com/CacheFlyDebug](https://cdn.ckeditor.com/CacheFlyDebug) and send the result to [https://ckeditor.com/contact/](https://ckeditor.com/contact/) ?

**Comment by sarankup** [comment]
Issue has been resolved. Thank you. Enjoy deserving Sunday

**Comment by wwalc** [comment]
Thank you @sarankup for the confirmation! I'm happy the issue has been resolved.
