### ISSUE TITLE
[BUG] Skins not become applied after installing.

### ISSUE THREAD

**Issue by FuckingToasters** [ckeditor/ckeditor4#5226]
## Type of report

Bug

1. Downloading ckeditor files from generator website
2. Upload skins/moono-dark on the ftp server in jscript/rin/editor/skins
3. renaming the file to rin-moono-dark
4. refreshing the forum site

### Expected result
The Dark skin should've been applied.

### Actual result
It still shows me the standard white theme.

* Browser:  Firefox
* OS: Windows 10
* CKEditor version: / (rin editor)
* Installed CKEditor plugins: / (standard)

**Comment by sculpt0r** [comment]
Hi @FuckingToasters 

Did you use the [skin config option](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-skin) to change the skin? Also, I'm not sure about what is a `rin editor` that you mentioned in the `CKEditor version`? Is it some fork of CKE4?

**Comment by FuckingToasters** [comment]
> Hi @FuckingToasters
> 
> Did you use the [skin config option](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-skin) to change the skin? Without it - the editor will use the default skin. Also, I'm not sure about what is a `rin editor` that you mentioned in the `CKEditor version`? Is it some fork of CKE4?

Hi, i couldn't find a ckeditor plugin. the zip i've downloaded not included the mybb plugin filestructure while rin editor did. i thought it's from the same creator and the same thing just with a different name.

**Comment by sculpt0r** [comment]
Based on your last replay I conclude you are using some kind of third part modification of the CKE4? For final confirmation, could you provide sources of your editor and plugins?

As for the bbcode plugin - we have one here: https://ckeditor.com/cke4/addon/bbcode. You might want to follow the [docs](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_plugins.html#through-add-on-repository) to build your own original editor with required plugins.

Also there is [a bunch of themes](https://ckeditor.com/cke4/addons/skins/all?sort_by=field_custom_downloads_value&sort_order=DESC) available. Please note, that not all of them are created and supported by CKSource.

**Comment by sculpt0r** [comment]
Thank you @FuckingToasters for the confirmation.

The editor you are referring to is a third-party one, and it is not maintained by CKSource. Since we cannot fix issues with the code that does not belong to us, we are unable to help solve your issue. Please redirect your question to the editor’s author who should be able to review the problem and suggest a solution.

**Comment by FuckingToasters** [comment]
> Thank you @FuckingToasters for the confirmation.
> 
> The editor you are referring to is a third-party one, and it is not maintained by CKSource. Since we cannot fix issues with the code that does not belong to us, we are unable to help solve your issue. Please redirect your question to the editor’s author who should be able to review the problem and suggest a solution.

oh okay. could you explain me, how i can download the ckeditor mybb plugin with custom plugins i set on site? i tried it but it downloaded something, that i couldn't use in mybb
