### ISSUE TITLE
dropdownmenu does not open after first time

### ISSUE THREAD

**Issue by kertom** [ckeditor/ckeditor4#5243]
When i open a dropdown menu for the first time, it opens. However when i try to open another menu afterwards ,it does not open even though it is active .Then i have to touch it two more times in order to open it. 
This does not happen locally but only on the device/iPad.
Could you help me ,please?

**Comment by KarolDawidziuk** [comment]
Hello, @kertom 

We would like to help solve your issue but it seems you have missed our [templates for feature requests and bug reports](https://github.com/ckeditor/ckeditor4/issues/new/choose). Their purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.
