### ISSUE TITLE
how can i build multiple editors on a page with ckeditor-vue

### ISSUE THREAD

**Issue by elaineKuo** [ckeditor/ckeditor4#5249]
## Type of report

Bug

If there are multiple editors on the same page, only the last editor can trigger the bound event to take effect. The previous editor cannot trigger the bound event. Therefore, adding the key value is useless.

## Provide detailed reproduction steps (if any)

1. …
2. …
3. …

### Expected result

*What is the expected result of the above steps?*

### Actual result

*What is the actual result of the above steps?*

## Other details

* Browser: …
* OS: …
* CKEditor version: …
* Installed CKEditor plugins: …

**Comment by sculpt0r** [comment]
Hi @elaineKuo 
I see that you also create a report in the proper repo: https://github.com/ckeditor/ckeditor4-vue/issues/142.

Because of that - I'm closing this report. Please follow the topic in the above vue integration repo.
