### ISSUE TITLE
Failing `tests/plugins/templates/templates` test

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor4#5268]
## Type of report

Failing test

## Provide detailed reproduction steps (if any)

1. Open http://localhost:1030/tests/plugins/templates/templates

### Expected result

All tests pass

### Actual result

The "test insert template and replace content" test fails. The content of the editor is ok, but the selection is missing.

## Other details

The test fails only if run with other tests, alone it passes.

* Browser: Safari mobile
* OS: 15.5
* CKEditor version: 4.19.1
* Installed CKEditor plugins: templates

**Comment by KarolDawidziuk** [comment]
Unfortunately, I cannot reproduce this. All tests passed.
@Comandeer can you check if this test is still failing?

**Comment by Comandeer** [comment]
Seems to pass both on dev and built version. Closing it then.
