### ISSUE TITLE
colorButton_enableAutomatic cannot be set when In-Page configuration

### ISSUE THREAD

**Issue by cimenta** [ckeditor/ckeditor4#5293]
## Type of report

Bug

colorButton_enableAutomatic cannot be set when In-Page configuration. With below code the list of colors is set but the automatic

https://jsfiddle.net/radek/r6yv1m5p/7/
```

var ckeditor1 = CKEDITOR.inline('editor1', {
      removePlugins: 'exportpdf,sourcearea',
      fillEmptyBlocks : false,
      format_tags : "h1",
      colorButton_colors : 'CF5D4E,454545,FFF,DDD,CCEAEE,66AB16',
      colorButton_enableAutomatic : false,
      
//      language: 'fr',

    });
```

* Browser: latest firefox, latest Chrome
* CKEditor version: 4.19.1

**Comment by KarolDawidziuk** [comment]
Hello, @cimenta

I'm not sure if I understand your issue correctly. 
Do you mean that the colors of the color button should be like in your config `CF5D4E,454545,FFF,DDD,CCEAEE,66AB16` but it isn't?

As on the below screenshot it looks good.
![image](https://user-images.githubusercontent.com/18471998/180454165-24a27ff9-420b-47d5-958d-43e93e64d6fe.png)

However, if I misunderstood your report, could you please provide more details? Information about expected and actual result will be very helpful.

**Comment by cimenta** [comment]
Hi Karol

sorry for not being clear the first time. I thought it was actually clear from documentation https://ckeditor.com/docs/ckeditor4/latest/features/colorbutton.html

```
config.colorButton_enableAutomatic = false;
These settings will cause the color list to only contain the six colors listed above, with no “Automatic” option available:

```
https://ckeditor.com/docs/ckeditor4/latest/assets/img/colorbutton_04.png

But it my jsFiddle I do have the text "More Colors". 

So the expected result is to turn off the option "More Colors" via In-Page configuration

Thank you
Radek

**Comment by KarolDawidziuk** [comment]
Thank you @cimenta for more details.

To turn off `More Colors` option you can use another config option called [colorButton_enableMore](https://ckeditor.com/docs/ckeditor4/latest/features/colorbutton.html#more-colors-option-and-color-dialog)

Try to add it to your config:
```
colorButton_enableMore: false
```

Looks like this screenshot can be confusing and we should update it.

**Comment by cimenta** [comment]
I see now. Thank you for your help

**Comment by KarolDawidziuk** [comment]
I'll reopen this report because it's a thing that can be improved.
