### ISSUE TITLE
Text format was removed when you enter new line after inserting image.

### ISSUE THREAD

**Issue by lorenzo-viovicente** [ckeditor/ckeditor4#5295]
## Type of report

Bug

I am using Drupal 9.1 and ckeditor version 4.
I have noticed that when I have a selected text format and then insert an image, after entering new line the format is gone.

## Provide detailed reproduction steps (if any)

1. Add text with `Normal` format. This will turn the text format to p

<img width="542" alt="screenshot1-issue" src="https://user-images.githubusercontent.com/110001085/180901130-b7b1aeae-753e-4d1d-bbc7-d86d1157c103.png">

2. Add Image

3. Succeeding lines will return to the default which has no text formats

![screenshot2](https://user-images.githubusercontent.com/110001085/180901213-e51b3d50-2afb-406c-8ad6-9dc69e82b586.png)

### Expected result

*What is the expected result of the above steps?*

The text format should be retained and have a `<p>` tag on new line after inserting image

*What is the actual result of the above steps?*

The text format was removed on new line after inserting image

* Drupal: 9.1
* CKEditor version: 4
* Installed CKEditor plugins: CKEditor Description List, CKEditor Templates User Interface, CodeSnippet

**Comment by jacekbogdanski** [comment]
@lorenzo-viovicente I'm not able to reproduce the issue, and as far as I know, Drupal uses custom image implementation based on https://ckeditor.com/cke4/addon/image2, so the issue may originate in Drupal, not CKEditor 4 itself.

Are you able to reproduce the issue outside Drupal? Also, could you show the source HTML of that content once the issue occurs?
