### ISSUE TITLE
Pasting into chromium based browsers strips some styling

### ISSUE THREAD

**Issue by smaclagaibm** [ckeditor/ckeditor4#5297]
To reproduce
1. Rename the attached .txt file to .html
2. Open in a browser, select all, copy
3. Open in firefox:
https://ckeditor.com/ckeditor-4/demo/#document
4. Delete all the content in the default Document Editor and paste the previously copied content
Note that the pasted content looks the same as the copy source.
5. Repeat steps 3 and 4 with Chrome (or Safari, or Edge)
Note that the pasted content is NOT the same as the copy source.

Font/sizing, colors, horizontal rule, indention are all missing.

This worked on a previous version of CKEditor, 4.4.5. I don't know where between 4.4.5 and 4.19 it stopped working.

[index.txt](https://github.com/ckeditor/ckeditor4/files/9203825/index.txt)
![copySource](https://user-images.githubusercontent.com/103686632/181380421-6743d303-2241-4835-a65b-733631ac063d.png)

![chrome](https://user-images.githubusercontent.com/103686632/181380418-b1d19afd-63fa-49c3-b2ec-faa66b5f6529.png)
![safari](https://user-images.githubusercontent.com/103686632/181380426-e8bea5fc-4b42-49a1-9923-37b2f6280179.png)
![firefox](https://user-images.githubusercontent.com/103686632/181380424-8bd8b562-7364-4121-b3e3-f330aff15dd5.png)

**Comment by smaclagaibm** [comment]
And for anyone that's wondering, Red is better than blue because I'm an NCSU graduate and married to a UNC graduate.

**Comment by sculpt0r** [comment]
Hi @smaclagaibm - thank you for the report. I can confirm this issue.

Further issue details will be added soon...

**Comment by sculpt0r** [comment]
It's broken since [`4.5.0-beta`](https://github.com/ckeditor/ckeditor4/releases/tag/4.5.0-beta), and of course [`4.5.0`](https://github.com/ckeditor/ckeditor4/releases/tag/4.5.0).

**Comment by gillibrand** [comment]
Sounds right. This when found after upgrading from 4.4.5 to 4.19.

**Comment by jacekbogdanski** [comment]
Let's make a git bisect to understand what happened between these versions.

**Comment by gillibrand** [comment]
Anyway to get a rough estimate on when this might be prioritized? This is a frustrating regression after I upgraded. Thanks.

**Comment by Comandeer** [comment]
This change is connected with the introduction of the [paste filter](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-pasteFilter) in CKEditor 4.5.0. By default, this filter removes some of the styling in Safari and Chromium-based browsers as they tend to paste too much bloat from the clipboard.

The old behavior can be restored by setting the `pasteFilter` config variable to `null` → https://codepen.io/Comandeer/pen/OJZMPVg

**Comment by gillibrand** [comment]
@Comandeer Thanks for pointing that out. Yes, that was the problem, and restoring it to "null" goes back to the old behavior. 🙇‍♂️
