### ISSUE TITLE
Docs: What is the difference between major branch and master branch?

### ISSUE THREAD

**Issue by cclauss** [ckeditor/ckeditor4#5313]
## Type of report

Docs
The description at https://github.com/ckeditor/ckeditor4/tree/major#working-with-the-ckeditor4-repostiory confuses me.
https://github.com/ckeditor/ckeditor4/blob/major/CHANGES.md is v4.17.1
https://github.com/ckeditor/ckeditor4/blob/master/CHANGES.md is v4.19.1
https://github.com/ckeditor/ckeditor4/blob/stable/CHANGES.md is v4.19.1
Are they both **tested/supported** releases?  Which should I use?

## Provide a description of requested docs changes

*What is the purpose and what should be changed?*

**Comment by jacekbogdanski** [comment]
@cclauss these all branches are rather used for development. If you would like to use a source code of a specific editor version, see [CKEditor 4 Releases repository](https://github.com/ckeditor/ckeditor4-releases) - you will find a tag for each released version. You can also use our [CKEditor 4 Builder](https://ckeditor.com/cke4/builder) or [npm package](https://www.npmjs.com/package/ckeditor4).

Everything is explained in this guide - https://ckeditor.com/docs/ckeditor4/latest/guide/dev_installation.html

**Comment by Comandeer** [comment]
It seems that we still have info about the `major` branch in our `README.md` → [https://github.com/ckeditor/ckeditor4/tree/a7b0d54376a794f65bce64086bd5f6bb51cb02d9#working-with-the-ckeditor4-repository](https://github.com/ckeditor/ckeditor4/tree/a7b0d54376a794f65bce64086bd5f6bb51cb02d9#working-with-the-ckeditor4-repository) – probably we should update it.

**Comment by jacekbogdanski** [comment]
Good catch @Comandeer, corrected in https://github.com/ckeditor/ckeditor4/commit/fb2c8ef416069441fa073b48d53b2b8be72699ba

**Comment by cclauss** [comment]
Thanks!
