### ISSUE TITLE
CKEditor4 remove <div> and <span> tag

### ISSUE THREAD

**Issue by KIM-DONGWON** [ckeditor/ckeditor4#5314]
I am using CKEditor 4.19.1. If I drag and copy and paste the contents containing the and tag on another website, the and tag disappear.

When tested by version, 4.4.8 version is normally copied and paste, but and tags are deleted from Starting with 4.5.X version

The configuration below does not work.

```
config.allowedContent = true;
config.format_tags = 'p;h1;h2;h3;pre;div';
config.extraAllowedContent = 'div'; 
```

What should I do ?

**Comment by KarolDawidziuk** [comment]
Hi, @KIM-DONGWON 

We would like to help solve your issue but it seems you have missed our [templates for feature requests and bug reports](https://github.com/ckeditor/ckeditor4/issues/new/choose). Their purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem. 

In your case, it would be very useful to provide a working example that shows your problem.
You can use one of our samples to create the reproduction sample:

* CodePen: https://codepen.io/karoldawidziuk/pen/LYzJvdx
* JSFiddle: https://jsfiddle.net/Kratek_95/nhwe5uLq
* JSBin: https://jsbin.com/gubepar/edit?html,js,output
* StackBlitz: https://stackblitz.com/edit/ckeditor4-bug-report

**Comment by KIM-DONGWON** [comment]
@KarolDawidziuk 
I found the answer
The answer was the pasteFilter setting. 
config.pasteFilter = null;

Normal operation started after this setting

**Comment by KarolDawidziuk** [comment]
Thank you @KIM-DONGWON for the answer. I'm closing this issue.
