### ISSUE TITLE
Methods for disabling right-click context menu and reenable browser's in-built spell checking?

### ISSUE THREAD

**Issue by ylluminate** [ckeditor/ckeditor4#5315]
Scratching my head both as to where to ask this question and where to find a solution: I work with a webmail system routinely that is very burdensome insomuch that they use CKEditor and force both right-click contextual menus and do not allow the web browser's own spell checking to be used. This keeps spelling very much out of sync with other frequently used editing and creates an overly burdensome editing experience with CKE. 

Is there a method / script or some other option I can use or execute to disable right-click context and to re-enable the browser's builtin spell checking?

**Comment by KarolDawidziuk** [comment]
Hello @ylluminate 

> Is there a method / script or some other option I can use or execute to disable right-click context and to re-enable the browser's builtin spell checking?

Sure, you can enable a default browser spell checker(which is turned off by default) by using [disableNativeSpellChecker](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-disableNativeSpellChecker) config option. 
For more information please check also https://ckeditor.com/docs/ckeditor4/latest/features/spellcheck.html#native-browser-spell-checker

Or you can also open the browser's context menu by pressing `CTRL + Right Mouse Click` on Windows or `Command + Right Mouse Click` on MacOS.

**Comment by ylluminate** [comment]
Thanks so much for the cmd-right-click function. That does get me the menu, but it doesn't seem to facilitate any actual spelling options in this case. Hmmm.  Also, since I don't have the ability to modify the site's JS directly I suppose I'll need to figure out a way to inject the JS configuration option via Tampermonkey or such.
