### ISSUE TITLE
Data wiped out when ckeditor placed under cdkDropList 

### ISSUE THREAD

**Issue by chiragbytes** [ckeditor/ckeditor4#5322]
We are facing issue when ckeditor4 component placed under Angular material cdkDraggable component

Code Example:
`<div cdkDropList (cdkDropListDropped)="droppedData($event)">
                <div class="row"
                    *ngFor="let question of introQuestions;let indexResult=index; let first = first;let last = last;"
                    cdkDrag>
                    <div class="ml-3">
                        <label class="label">Sort</label>
                        <div class="mr-3 custom-swap-icon-space" cdkDragHandle>
                            <i class="fas fa-long-arrow-alt-up"></i>
                            <i class="fas fa-long-arrow-alt-down"></i>
                        </div>
                    </div>
                    <div class="form-group col-md-12">
                        <label class="label">Description: </label>
                            <ckeditor
                            name="questiondescription{{indexResult}}"
                            config=ckEditorConfig
                            skin="moono-lisa"
                            #questiondescription="ngModel"
                            [(ngModel)]="question.description"
                        ></ckeditor>
                    </div>
                </div>
            </div>`
### Expected result

When ckeditor4 used with angular material cdkdraggable component, it should work properly, data should not get wiped when dragged

### Actual result

At time of initialisation data shows up but whenever you select or drag item data under ckeditor wipes away however if you check with ngModel in textarea data is already there present in the list.

## Other details

* Browser: Chrome,Firefox,Safari
* OS: Linux
* CKEditor version: 4

**Comment by sculpt0r** [comment]
Hi @chiragbytes, could you report this issue once again at our angular integration repository: https://github.com/ckeditor/ckeditor4-angular? Also, please make sure you are using the official integration with angular.

I'm closing this issue due to maintenance reasons.
