### ISSUE TITLE
[CKEDITOR] Error code: editor-element-conflict when using 'CKEDITOR.inline( )'

### ISSUE THREAD

**Issue by simogeo** [ckeditor/ckeditor4#5324]
## Provide detailed reproduction steps (if any)

I'm using ckeditor v4.19.1 • 20-07-2022

And instantiate ckeditor to create inline edition. I'm for that using that piece of code : 

```js
if (typeof CKEDITOR !== 'undefined') {
    				CKEDITOR.disableAutoInline = true;
    				$("div[contenteditable='true']").each(function( index ) {
        		
                    var element_type = $(this).attr('data-comment-type');
    				var element_id = $(this).attr('id');
    				var comment_id = $(this).attr('data-comment-id');
    				// console.log(element_id);
    
    				CKEDITOR.inline( element_id, {
    					 customConfig: 'l21_light_confignoimgur.js', // because imgur make multi-instance bug
    				      on: {
    				        blur: function( event ) {
    				          var data = event.editor.getData();
    				          // alert('Sending: ' + data.length + ' to ' + comment_id );
    						  if(data.length < 15)  alertify.error('Le commentaire n\'est pas assez long. Les changements ne seront pas pris en compte. Rafraîchissez la page ou tapez \"Ctrl + Z\" pour voir le contenu initial.');
    						  else {
    							$.ajax({type:'POST', url: '../comment/_ajax_edit.php', data: { content: data, id: comment_id, type: element_type }, dataType: 'json', success: function(data) {
    								if(data.status==1) {
    									alertify.success(data.msg);
    								} else {
    									alertify.error(data.msg);
    								}
    							}});
    						   }
    				        }
    				      }
    					});
    				});
    			}
```

But switching from jQuery-1.11.3.min to  jQuery-3.6.1.min triggers the following error : **[CKEDITOR] Error code: editor-element-conflict**

I've seen the following issue and associated fix, but it seems it only works with inlineAll().  : https://github.com/ckeditor/ckeditor4/issues/4293

### Expected result

I expect inline editors to be instantiated on each element

### Actual result

It triggers `[CKEDITOR] Error code: editor-element-conflict` error

## Other details

* Browser: FF
* OS: ubuntu 22.04
* CKEditor version: ckeditor v4.19.1 • 20-07-2022
* jQuery version: jQuery-3.6.1.min
* Installed CKEditor plugins: full pack

**Comment by simogeo** [comment]
Hi @Comandeer, thanks for your test.

I've also tried a simplified sample and it works well as well ....
See here : https://jsfiddle.net/7anhfLm4/2/

I experience the issue inside a cms. I'll investigate and let you know

**Comment by simogeo** [comment]
By the way, I don't really understand because objects have different names / id. See following screenshot. Any clue ?

![image](https://user-images.githubusercontent.com/154323/190661829-0bcd2dd7-3cdc-4074-ab1c-214e40b49c3e.png)

**Comment by simogeo** [comment]
Investigating a bit more,  I can observe that my code works with jQuery 1.x and jQuery 2.x. 

I get the error with  jQuery 3.x versions only.

And according to [that page](
https://ckeditor.com/docs/ckeditor4/latest/guide/dev_jquery.html), I can read : 

> CKEditor 4 offers native jQuery integration through its jQuery Adapter (a jQuery plugin basically). It provides deep integration of CKEditor 4 and jQuery that lets you use the native features of jQuery when using CKEditor 4. The jQuery Adapter is compatible with jQuery versions 1.7+ and 2.0+.

Do you think, that could explain the problem ? I'm not that sure, but something unexpected is happening ...

**Comment by Comandeer** [comment]
The adapter should work correctly with jQuery 3+.

When do you run the code that invokes `CKEDITOR.inline`? The autoinlining of editors happens on `DOMContentLoaded` event (so basically on `jQuery.ready()`). Maybe you disable autoinlining after it happens.

**Comment by simogeo** [comment]
All the code above was located into `$( document ).ready(function() {  //...});` indeed.

But moving the `CKEDITOR.disableAutoInline = true;` instruction just after ckeditor initialization make it work again !

This means that something has changed in the way `document-ready` is executed. The explanation is probably there : https://jquery.com/upgrade-guide/3.0/#breaking-change-document-ready-handlers-are-now-asynchronous

Many thanks @Comandeer for pointing this out ! :+1:
