### ISSUE TITLE
At 400% zoom the "new windows(_blank)" selected item is not visible completely on screen when the dropdown is collapsed.

### ISSUE THREAD

**Issue by msftedad** [ckeditor/ckeditor4#5326]
**Test Environment:**
[https://codepen.io/kpasagada/pen/RwQPjvy](https://nam06.safelinks.protection.outlook.com/?url=https:%2f%2fcodepen.io%2fkpasagada%2fpen%2fRwQPjvy&data=05%7c01%7cv-roopesht%40microsoft.com%7c567f6963d11044e86a8308da351cdc7e%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637880695345710341%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c3000%7c%7c%7c&sdata=Vkw2uWYXGEtoOMp89DSV00VRRx1SgRs0L0PjqNoxcIQ%3D&reserved=0)
Chromium Edge:Version 101.0.1210.39
Windows Version: Windows 11 21H2

**Pre-Requisites (if any):**
Set Display resolution to 1280x1024.
Increase the screen zoom to 400%

**Repro Steps:**
1. Press enter in the link [https://codepen.io/kpasagada/pen/RwQPjvy](https://nam06.safelinks.protection.outlook.com/?url=https:%2f%2fcodepen.io%2fkpasagada%2fpen%2fRwQPjvy&data=05%7c01%7cv-roopesht%40microsoft.com%7c567f6963d11044e86a8308da351cdc7e%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c637880695345710341%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c3000%7c%7c%7c&sdata=Vkw2uWYXGEtoOMp89DSV00VRRx1SgRs0L0PjqNoxcIQ%3D&reserved=0)
2. Tab to "Open Panel”
3. Focus editor and press Alt+F10
4. Tab through keys until you reach Link button
5. Press Enter to open the dialog
6. Tab to “Target” tab item press enter
7. Tab to target dropdow press enter to expand and select “new windows(_blank)”

**Actual Result:**
When screen is in reflow resolution and in 400% zoom the "new windows(_blank)" selected item is not visible completely on screen when the dropdown is collapsed.

**Expected Result:**
When screen is in reflow resolution and in 400% zoom the "new windows(_blank)" selected item should be visible completely on screen when the dropdown is collapsed.

**Comment by Comandeer** [comment]
I've followed the steps on the Standard Preset sample of CKEditor 4: 

https://user-images.githubusercontent.com/1078728/191048968-1d9f0a50-740c-4bd7-8090-f8bda0596d7e.mov

However, testing the "Reflow" Success Criterion by setting the resolution to 1280×1024 can lead to false positive results as screen resolution is not the same as the [viewport](https://developer.mozilla.org/en-US/docs/Glossary/Visual_Viewport). For the maximized browser window the screen resolution of 1280×1024 translates to ~1263 px wide viewport, which translates to ~315 px wide one after the zoom – which is slightly less than the required 320px. The safer method seems to be using devtool's Responsive View tool which allows setting the viewport's width directly to 320px. In that particular case the results are very similar:
<img width="854" alt="CKEditor 4 sample inside the Responsive View tool with the viewport width set to 320px and the viewport height set to 256px" src="https://user-images.githubusercontent.com/1078728/191055678-504f3016-38e4-47cd-ba4d-43d8773b8f9d.png">

As can be seen, the combobox with available "Target" values is fully visible. Most of the option's name (enough to identify it) is also visible in the collapsed state. According to the [Understanding WCAG 2.1 note](https://www.w3.org/WAI/WCAG21/Understanding/reflow.html):

> How much of the content is visible may change at different scales.

In this case the content is slightly cut off but, as I mentioned earlier, the part that allows identifying the option is still clearly visible.

Furthermore:

> The Success Criterion is met as long as all content and functionality are still fully available - either directly, or revealed via accessible controls, or accessible via direct links.

The full option's name is still accessible after opening the combobox so the criterion is met.
