### ISSUE TITLE
Failing test: `/plugins/exportpdf/tests/exportpdf`

### ISSUE THREAD

**Issue by KarolDawidziuk** [ckeditor/ckeditor4#5329]
## Type of report

Failing test

## Provide detailed reproduction steps (if any)

1. Run tests: `/plugins/exportpdf/tests/exportpdf`

### Expected result

Test passing.

### Actual result

Test failing

![image](https://user-images.githubusercontent.com/18471998/191005455-27c222c3-45b0-43a5-88f2-515d4bf33369.png)

## Other details

* Browser: IE11
* OS: Windows(VBox)
* CKEditor version: 4.20(pre-relase)

**Comment by jacekbogdanski** [comment]
Duplicate
