### ISSUE TITLE
Link dialog prepends a valid notes link with "denied:"

### ISSUE THREAD

**Issue by rumpumpel1** [ckeditor/ckeditor4#5342]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. add a link to an answer by using the link-plugin
2. choose link-type = URL, protocol = other, URL = notes:///...........
3. OK -> Save Changes

### Expected result

Moving the mouse over the link should show in the browser that this link resolves to notes:///........

### Actual result

Moving the mouse over the link shows in the browser that this link resolves to denied:notes:///.....

## Other details

* Browser: Firefox, Edge, Chrome
* OS: Windows 10, Windows 11, debian 11
* CKEditor version: 4.20.0
* Installed CKEditor plugins: colordialog, dialog, image, link, liststyle, magicline, smiley, specialchar, table, tabletools

**Comment by KarolDawidziuk** [comment]
Hi @rumpumpel1 
Could you provide a reproduction sample? This will help us better understand your report.

You can use one of our samples to create it:
* CodePen: https://codepen.io/karoldawidziuk/pen/LYzJvdx
* JSFiddle: https://jsfiddle.net/Kratek_95/nhwe5uLq
* JSBin: https://jsbin.com/gubepar/edit?html,js,output
* StackBlitz: https://stackblitz.com/edit/ckeditor4-bug-report

**Comment by rumpumpel1** [comment]
In order to reproduce this bug, you need a client with a [notes installation](https://www.hcltechsw.com/notes/home).

From reading the code I understood, that ckeditor takes every link apart (for whatever reason) and will consequently fail with every link it doesn't know.

**Comment by rumpumpel1** [comment]
this is not an issue of ckeditor, but an issue of the program, which uses ckeditor.
