### ISSUE TITLE
Pagebreak plugin: pagebreak buttons doesn't exist in toolbar when using document editor

### ISSUE THREAD

**Issue by linhongyi** [ckeditor/ckeditor4#5344]
## Type of report

Bug

I use the config for [Document Editor](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_example_setups.html#document-editor)
as the following.

let editor = CKEDITOR.replace('editor1', {
...
extraPlugins: 'tableresize,uploadimage,uploadfile,pagebreak',
}

The pagebreak button is not showed in document editor, but it is showed in article editor.

I am also direct to set pagebreak html tag. It's not work

 let data = 
            "<p style=\"page-break-after: always;\">&nbsp;</p><p style=\"page-break-before: always;\">&nbsp;</p>"

editor.setData(data).

Thanks for you help.

**Comment by KarolDawidziuk** [comment]
Hi @linhongyi 

After adding an extra plugin that should be visible in the editor toolbar, be sure to add it to the toolbar as well. Based on the Document Editor example, you need to add "PageBreak" to the toolbar config. After it, the button should appear.

https://github.com/ckeditor/ckeditor4-docs-samples/blob/master/editors/document-editor/index.html#L69-L79

For example, if you want to add it after the `Blackquore` button, you need to just add:

```js
{ name: '...', 'Blockquote', 'PageBreak' ] },
```

Let me know if it helped and if not please provide a working sample with your configuration.
You can use one of our samples to create the reproduction sample:
* CodePen: https://codepen.io/karoldawidziuk/pen/LYzJvdx
* JSFiddle: https://jsfiddle.net/Kratek_95/nhwe5uLq
* JSBin: https://jsbin.com/gubepar/edit?html,js,output
* StackBlitz: https://stackblitz.com/edit/ckeditor4-bug-report
