### ISSUE TITLE
mathjax plugin doesn't support mathjax3

### ISSUE THREAD

**Issue by ExplorerSunil** [ckeditor/ckeditor4#5351]
I was trying to use mathjax widget plugin. But it doesn't support mathjax3 and was running into issues with symbols like \degree in currently supported mathjax 2 library version. Further more I couldn't find props to pass to mathjax library. Its very easy to do it in mathjax 3 through mathjax config object. Is there any plan for supporting mathjax 3 or if there is a workaround so that I could use mathjax 3. This is the link of plugin, I'm talking about:
https://ckeditor.com/docs/ckeditor4/latest/examples/mathjax.html

**Comment by KarolDawidziuk** [comment]
Hi @ExplorerSunil 

You can try to use a config option for this: https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-mathJaxLib, so you can provide your own URL here to version 3.0.

However, we can't guarantee that the newest version will be fully compatible with CKE4 for now.

In addition, we already have a feature request for updating this library so I'll close this issue.

**Comment by ExplorerSunil** [comment]
Hi @KarolDawidziuk 

   I already tried that mathjaxLib option. It was not working. It wasn't displaying any math at all with mathjax3. 

   So any plan on the other issue which is duplicate of this? it would be great if you could point me to it. So that I can track it, if team is planning to implement mathjax3 support in ckeditor4.

Thanks for your response.
