### ISSUE TITLE
removeFormat won't remove span if lang attribute is present

### ISSUE THREAD

**Issue by superedo73** [ckeditor/ckeditor4#5359]
removeFormat won't remove span tags if lang attribute is present.  Indeed, dir attribute is added too.

Pressing the removeFormat button won't either remove the span tag or the lang and dir attributes.

Without the lang attribute all is working as expected (span is removed)

Here my relevant conf:

removeFormatTags = 'cite,code,del,dfn,font,ins,kbd,q,samp,span,strike,tt,var',
removeFormatAttributes = 'class,style,lang,width,height,align,hspace,valign,dir',

## Other details

* Browser: Chrome
* OS: Windows 10
* CKEditor version: 4.19.1

**Comment by Comandeer** [comment]
This is an intended behavior as the language indication is not considered a formatting – it does not convey information about styling. See #779 for more details.

However, particular filters can be disabled to allow deleting language indication via the "Remove Format" plugin → [https://jsfiddle.net/Comandeer/ew46mx35/](https://jsfiddle.net/Comandeer/ew46mx35/) It's not a recommended and official solution (as the CKEditor 4 does not expose any public API for it) yet it's possible.

**Comment by superedo73** [comment]
Thank you very much.  Ok about preserving language indication.

Anyway, I think removeFormat it should at least remove the style attribute (carrying font, text, color and other formatting infos),  but when lang attribute is present,  either other attribute removal is skipped.

Thanks
