### ISSUE TITLE
media embed plugin error

### ISSUE THREAD

**Issue by sofiene2021** [ckeditor/ckeditor4#5361]
i installed ckeditor media embed plugin but when i put the video code i have this issue 

![Capture d’écran 27-10-2022 12 37 41](https://user-images.githubusercontent.com/95021861/198276399-498b589c-52f9-4e71-82f8-7468982fd570.png)
 
the java is enabled on the browser 
how can i solve this issue

**Comment by Comandeer** [comment]
This is a known issue, connected with how the embedded content is inserted into the editor (see #3264, #5341). However, this behavior is present only during editing, after saving the content it will work correctly.
