### ISSUE TITLE
removeFormat won't remove styling attributes in span with language attributes

### ISSUE THREAD

**Issue by superedo73** [ckeditor/ckeditor4#5363]
Even if it's clear that preserving span w/lang attribute is an intended behavior as the language indication is not considered a formatting – removeFormat seems to skip the check for other attributes in removeFormatAttributes to remove - even "style" ones conveying format info (font, size, etc.).

**Comment by KarolDawidziuk** [comment]
Hi @superedo73,

We would like to help solve your issue but it seems you have missed our [templates for feature requests and bug reports](https://github.com/ckeditor/ckeditor4/issues/new/choose). Their purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.
