### ISSUE TITLE
CSS Errors: Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped.

### ISSUE THREAD

**Issue by TheOldMan2000** [ckeditor/ckeditor4#5367]
## Type of report

Bug

Several CSS erros reported in browser console and also via W3C validator in file:
[https://cdn.ckeditor.com/4.20.0/standard/skins/moono-lisa/editor_gecko.css](https://cdn.ckeditor.com/4.20.0/standard/skins/moono-lisa/editor_gecko.css)

Console error reported:
Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped.

> Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. editor_gecko.css:5:13155
> Elements matching selector: .cke_menubutton_disabled .cke_menubutton_label
> 
> Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. editor_gecko.css:5:20991
> Elements matching selector: .cke_notification
> 
> Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. editor_gecko.css:5:22024
> Elements matching selector: .cke_notification_close
> 
> Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. editor_gecko.css:5:22091
> Elements matching selector: .cke_notification_close:hover
> 
> Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. editor_gecko.css:5:22223
> Elements matching selector: .cke_notification_warning a.cke_notification_close
> 
> Expected 'none', URL, or filter function but found 'alpha('.  Error in parsing value for 'filter'.  Declaration dropped. editor_gecko.css:5:22317
> Elements matching selector: .cke_notification_warning a.cke_notification_close:hover
> 

1. Open [https://ckeditor.com/docs/ckeditor4/latest/examples/standardpreset.html](url)
2. Check browser console or test via: [](https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fcdn.ckeditor.com%2F4.20.0%2Fstandard%2Fskins%2Fmoono-lisa%2Feditor_gecko.css&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en)

### Expected result

*What is the expected result of the above steps?*
Valid CSS used

### Actual result

*What is the actual result of the above steps?*
Console reports several CSS errors

W3C CSS Validator:
Sorry! We found the following errors (5)
                   URI : [](https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fcdn.ckeditor.com%2F4.20.0%2Fstandard%2Fskins%2Fmoono-lisa%2Feditor_gecko.css&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en)
                    
Parse Error                                                                       = 95)
Parse Error                                                                       = 60)
Parse Error                                                                       = 100)
Parse Error                                                                       = 80)
Parse Error                                                                       = 100)

## Other details

* Browser: …  Firefox 106.0.5 (64-bit)
* OS: … Win 10 
* CKEditor version: … 4.20.0, 4.19.x
* Installed CKEditor plugins: … N/A

**Comment by Comandeer** [comment]
CKEditor 4 is [compatible also with some old browsers](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_browsers.html), especially Internet Explorer 8+, which requires adding some legacy CSS intended for such browsers. This legacy CSS code, like `filter:alpha(opacity=30)`, is considered invalid by the validator but it does not affect the editor. As you can see in the browser console's messages, unknown or incorrect declarations are ignored ("Declaration dropped.").

If you, however, encounter any issues connected with these legacy CSS properties, feel free to report them.
