### ISSUE TITLE
CKEDITOR[(intermediate value)(intermediate value)(intermediate value)] is not a function

### ISSUE THREAD

**Issue by fedot199614** [ckeditor/ckeditor4#5370]
received next issue 
```
TypeError: CKEDITOR[(intermediate value)(intermediate value)(intermediate value)] is not a function
    at initEditor (index.cjs.js:264:71)
```
using CKeditor React implimentation 
`<CKEditor
                initData={value}
                onChange={handleUpdate}
                editorUrl={'http://localhost:3000/ckeditor/ckeditor.js'}
            />`

for http://localhost:3000/ckeditor/ckeditor.js package using this build https://ckeditor.com/cke4/builder
1) Full
2) Source (Big N’Slow)

**Comment by Comandeer** [comment]
Could you show a sample reproduction?
