### ISSUE TITLE
[Safari] Unable to add hyperlink in modal

### ISSUE THREAD

**Issue by sjoshi961** [ckeditor/ckeditor4#5371]
## Type of report

Bug
Open the hyperlink modal and add hyperlink URL in provided textbox. after clicking ok hyperlink is not generating and modal for hyperlink is not getting close.

### Expected result
1. after selection of text, hyperlink should generated and modal should be close for hyperlink.

### Actual result
On clicking OK button, modal is not getting closed and throwing error '**Undefined is not an object ('b.collapse ) in ckeditor**' also hyperlink is not appending to the text.

## Other details

* Browser: … Safari 
* OS: … 
* CKEditor version: … 
![link_issue](https://user-images.githubusercontent.com/118874996/203480698-271cac4e-ebff-432c-9743-911892d4ab6b.gif)

* Installed CKEditor plugins: …

**Comment by Comandeer** [comment]
Could you provide some more details? I'm not able to reproduce the issue, e.g. [in our docs](https://ckeditor.com/docs/ckeditor4/latest/examples/standardpreset.html).

**Comment by sjoshi961** [comment]
Thanks for your prompt response. We are getting this error on Ok with hyperlink 
![Screenshot 2022-11-24 114557](https://user-images.githubusercontent.com/118874996/203708354-8651b50e-2988-4234-ac2d-44bb643666a6.png)
erlink.

**Comment by Comandeer** [comment]
It seems that it's connected to the third-party software you use. Probably the selection is incorrectly cleared between selecting the word and clicking the "Link" button in the toolbar, resulting in this error. As the selection was cleared, the link can't be inserted into the editor.
