### ISSUE TITLE
CK Editor Image copy paste issue,

### ISSUE THREAD

**Issue by santoshsp16** [ckeditor/ckeditor4#5378]
## Type of report

Bug

## We are using CK editor 4.20 version facing issue in copy paste of image showing console error. 
Steps to reproduce the issue
1) Upload the image in CK editor window.
2)Copy uploaded image from CK editor window using Ctrl + C
3)Move to another CK editor window & paste the copied image by Ctrl + V
4) It will show console error as below 

![Console Error](https://user-images.githubusercontent.com/119281393/204207759-2597a113-5fae-4769-b133-99155e1cc57d.PNG)

### Expected result

Paste image without any console error.

### Actual result

Paste image gives console error 
data:image/png;base64,iVBORw0KGgoAAAAN/D/iNxmLEZAbyQAAAAASUVORK5CYII=.......  ...  net::ERR_INVALID_URL

## Other details

* Browser: … Chrome, Edge
* OS: … Windows 10
* CKEditor version: … 4.20

Note:- We have verified the same issue on CKEditor 4 official website & we are able to reproduce the same on that URL also.

**Comment by KarolDawidziuk** [comment]
Hi @santoshsp16

I cannot reproduce this issue. Can you provide the URL to the official CKEditor 4 website on which you facing the issue?
