### ISSUE TITLE
Embed plugin. Instagram link problem

### ISSUE THREAD

**Issue by elsive2** [ckeditor/ckeditor4#5389]
Hi, I'm having problems with the media embed plugin. The link to the instagram post on mobile phones does not work. Presumably the problem is in the id of the Instagram post, there is a dash (-) sign, which breaks the link for me. Tell me what should I do? (Good on desktop)

Post - https://www.instagram.com/p/Cjo2-DOIkAG/
Id with dash - Cjo2-DOIkAG

![image](https://user-images.githubusercontent.com/66211474/207300283-a1b00fcb-1a38-4fcf-918c-417c3abf71c7.png)

**Comment by KarolDawidziuk** [comment]
This is a known issue, connected with how the embedded content is inserted into the editor (see https://github.com/ckeditor/ckeditor4/issues/3264, https://github.com/ckeditor/ckeditor4/issues/5341). However, this behavior is present only during editing, after saving the content it will work correctly.

**Comment by KarolDawidziuk** [comment]
Hi @elsive2

For now, I cannot confirm this issue and pasting provided link works properly - tested on mobile Safari and Chrome.

To confirm this issue please provide more information, like:
* What mobile browser are you using? 
* Does this issue occur on all mobile browsers?
* Did your editor contain any 3rd party plugins?
* Did your editor contain some custom configuration? If yes, could you provide it?
