### ISSUE TITLE
getRandomValues can return undefined

### ISSUE THREAD

**Issue by z419** [ckeditor/ckeditor4#5395]
Getting error logs from older browers like ios 8 and chrome ~40 that crypto.getRandomValues returned undefined

Changed generateRandomNumber to make sure it returns a value
```
			var value = cryptoApi.getRandomValues( new Uint32Array( 1 ) );
			if ( value && value[0] ) {
				return value[0];
			}
```

**Comment by jacekbogdanski** [comment]
The crypto method already includes a simple polyfill for older browsers, like Internet Explorer: https://github.com/ckeditor/ckeditor4/blob/a41004afe2479972c7775d42d5d359a2d085dbf1/core/htmldataprocessor.js#L1113-L1121

Mentioned browsers (iOS 8, Chrome 40) [are not supported by the editor](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_browsers.html), and it's recommended to upgrade to versions that are currently supported by browser vendors.
