### ISSUE TITLE
window event listener not removed on destroy

### ISSUE THREAD

**Issue by z419** [ckeditor/ckeditor4#5396]
An event listener for popstate or hashchange is added to window by maximize plugin for each instance. It is not removed from window when calling editor.destroy()

**Comment by jacekbogdanski** [comment]
Yeah, it looks like `maximize` plugin is missing the proper `destroy` editor instance handler which may highly impact framework-based editor integrations:
https://github.com/ckeditor/ckeditor4/blob/a41004afe2479972c7775d42d5d359a2d085dbf1/plugins/maximize/plugin.js#L293-L305
