### ISSUE TITLE
Multiple bse64 image not loading with ckeditor 4 in chrome browser

### ISSUE THREAD

**Issue by sonamDwivedi24** [ckeditor/ckeditor4#5397]
Ckeditor version :- "4.18.0",revision:"5fe059002f3"

If I am adding single base64 image , it loading correctly in chrome.

If I am adding 10 image of base64 image in ckeditor, its lnot loading ckeditor.js in browser and browser not responding

**Comment by jacekbogdanski** [comment]
CKEditor 4 does not support inserting multiple images as base64 at once. We have a reported feature request for that improvement, so if you would like to see it implemented, please add 👍🏻 to the https://github.com/ckeditor/ckeditor4/issues/4682 ticket.

**Comment by sonamDwivedi24** [comment]
@jacekbogdanski If I am adding multiple image in ckedtior 4 same thing is working correctly in mozilla firefox. Only issue with chrome and edge.

**Comment by jacekbogdanski** [comment]
@sonamDwivedi24 every image saved in base64 includes a very long text with encoded binary data of that image. Depending on the specific browser and user machine, you may experience some slowdown or even freeze of the browser if there are too many images in the editor your OS/browser can handle. To overcome that upstream limitation you can use the [Easy Image](https://ckeditor.com/docs/ckeditor4/latest/features/easyimage.html) plugin that allows uploading images to [CKEditor Cloud Services](https://ckeditor.com/ckeditor-cloud-services/) with a customizable upload progress indication, or by integrating [File Manager](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_file_browse_upload.html).
