### ISSUE TITLE
Bump company name in license header

### ISSUE THREAD

**Issue by jacekbogdanski** [ckeditor/ckeditor4#5409]
## Type of report

Task

For example, see https://github.com/ckeditor/ckeditor5/blob/master/src/clipboard.ts#L1-L4 (make sure to compare with the CKE4 license to check if there are some significant differences except dates).

## Provide description of the task

* [x] https://github.com/ckeditor/ckeditor4
* [x] https://github.com/ckeditor/ckeditor4-presets
* [x] https://github.com/ckeditor/ckeditor4-docs
* [x] https://github.com/ckeditor/ckeditor4-docs-samples
* [x] https://github.com/ckeditor/ckeditor4-webpack-template
* [x] https://github.com/ckeditor/ckeditor4-integrations-common
* [x] https://github.com/ckeditor/ckeditor4-react
* [x] https://github.com/ckeditor/ckeditor4-angular/
* [x] https://github.com/ckeditor/ckeditor4-vue
* [x] https://github.com/ckeditor/ckeditor4-benderjs-runner
* [x] check if there are other repositories requiring update

**Comment by Comandeer** [comment]
Happy New 2023! :champagne:
