### ISSUE TITLE
Rename the "Normal" label/tag for block element formats to "Paragraph" instead.

### ISSUE THREAD

**Issue by klonos** [ckeditor/ckeditor4#5428]
This is the respective issue for https://dev.ckeditor.com/ticket/16824 (sorry I haven't followed up for so long).

## Steps to reproduce
- Basic installation; include the "Format" widget.
- While using the editor in the front end, click on the "Paragraph format" drop-down.
- While the label for selecting `<h2>`, `<h3>`, `<h4>` etc. is "Heading 2", "Heading 3", "Heading 4" respectively, the label for selecting a `<p>` is "Normal".

## Expected result
Having the label of the drop-down menu be "Paragraph" would make more sense to users.

## Actual result
The drop-down menu entry for paragraph tags is "Normal", which is too vague.

---

## Other details (browser, OS, CKEditor version, installed plugins)
Respective issue in the Backdrop CMS queue: https://github.com/backdrop/backdrop-issues/issues/2176

WordPress is also using "Paragraph" and we'd like to go with that in Backdrop CMS. We could change the `tag_p` option in the language files, but that would mean maintaining the change with any future upgrades of CKEditor versions, so we think that it would be best if this was fixed upstream. Hence this issue here.

Thank you beforehand for considering this.

**Comment by KarolDawidziuk** [comment]
Hi @klonos and thank you for the report.

Currently, we do not plan to rename this label to `Paragraph` as this name has been around for many years and we do not want to change the habits of current users.

If you want to change it yourself, there is a way you mentioned by you which is to change it in the language files. Another way is to use [setLang](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_plugins.html#method-setLang) method before the editor.
