### ISSUE TITLE
wrong version download

### ISSUE THREAD

**Issue by ophian** [ckeditor/ckeditor4#5433]
## Type of report

Download Task at website

## Provide description of the task

*What steps should be taken to fulfil the task?*

Download 4.20.2 on website. I did by custom build, which loads the old version 4.20.1.
But the website says "Download a ready-to-use CKEditor package" v4.20.2 • 15-02-2023

## Other details

* Browser: Chromium 110

The downloaded version is still at version:"4.20.1",revision:"b520aa2b40"

But loading an uncustomized basic version, the version is:"4.20.2",revision:"3a6ef162af".

**Comment by Comandeer** [comment]
Thanks for the report, I can confirm the issue. We will look into it.

**Comment by ophian** [comment]
Seems resolved, thanks!
