### ISSUE TITLE
missing translations of Bengali language

### ISSUE THREAD

**Issue by shakib04** [ckeditor/ckeditor4#5441]
## Type of report

Task

## Provide description of the task
There is some missing translation of bengali language. Need to add missing translation in bengali language.

*What steps should be taken to fulfil the task?*
Update some of the missing translation of bengali language.

**Comment by jacekbogdanski** [comment]
As mentioned in https://github.com/ckeditor/ckeditor4/pull/5442 already, that should be corrected using [Transifex](https://www.transifex.com/ckeditor/ckeditor/).
