### ISSUE TITLE
Title tag is removed but not the content resulting in unnecessary content in editor

### ISSUE THREAD

**Issue by arunragha89** [ckeditor/ckeditor4#5448]
## Type of report

Bug

## Provide detailed reproduction steps (if any)
When an html contains a title attribute `<html><head><title> My Title >/title></head></html>` and it inserted in CK Editor using the insertHTML method, the resulting content strips the title tag but not the content and the content is inserted in the body resulting in unnecessary content in editor

* JSFiddle: https://jsfiddle.net/u7bfwc94/2/

### Expected result

* I expect the title tag and its content to be removed completely instead of title tag alone

### Actual result

* Only the title tag is removed not the content

## Other details

* Browser: Chrome
* OS: Mac
* CKEditor version: 4.20.2
* Installed CKEditor plugins : n/A

**Comment by Comandeer** [comment]
This behavior is intended – as it's how [filtering content](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_advanced_content_filter.html) in CKEditor 4 works.

However, you can filter out the `title` element using the [`insertHtml` event](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#event-insertHtml).
