### ISSUE TITLE
Source map for ckeditor.js version 4.20.2 (3a6ef162af)

### ISSUE THREAD

**Issue by irandoct** [ckeditor/ckeditor4#5449]
Hi,
It seems the source map file for ckeditor.js does NOT includes in the package. May I ask you provide a link to the source map or update the package?

Thanks

**Comment by Comandeer** [comment]
Hi,

unfortunately, we do not provide a source map for CKEditor 4 and as CKEditor 4 is reaching its EoL this year, we do not intend to introduce it. You can use CKEditor 5 instead which provides it and many more features oriented to developer experience.

Alternatively, you could use the code from this repository for development – it contains an unminifiied version of CKEditor 4. It can be [used directly in npm](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#github-urls).
