### ISSUE TITLE
Remove italic style from TextPartLanguage feature. 

### ISSUE THREAD

**Issue by vladsolntsev** [ckeditor/ckeditor4#5455]
## Type of report

Task

## Provide description of the task

Remove the default CSS styling of the span[lang]

## Other details

This was just implemented in Ckeditor5 here - https://github.com/ckeditor/ckeditor5/pull/13804.

I think that this makes sense, as setting the italic font-style on the selected language is not intuitive at all, and makes it difficult for editors to know what part of the text is really in italic and what part is just a translated language.

**Comment by KarolDawidziuk** [comment]
Hi @vladsolntsev and sorry for the late reply.

As the CKEditor 4 allows you to modify styles placed inside the `contents.css` file in several different ways, there is no need to remove this.
To change it you can use one of the configuration options:
* [contentsCss](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-contentsCss)
* [addCss()](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR.html#method-addCss)
* [addContentsCss()](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_editor.html#method-addContentsCss)

I'm closing this report.
