### ISSUE TITLE
CDN Certificate is Expired !!

### ISSUE THREAD

**Issue by D40298008** [ckeditor/ckeditor4#5459]
The certificate for https://cdn.ckeditor.com/ is expired!

**Comment by chandlervt** [comment]
Can verify - certificate expired. Please update the certificate. 
Seems like a yearly thing .  There was a certificate issue in May 2022 as well.

**Comment by g-brodiei** [comment]
Confirm the certificate has expired.

<img width="590" alt="image" src="https://user-images.githubusercontent.com/10040350/232182686-60aaf85b-689c-4543-b929-cd2fd395d01c.png">

**Comment by wwalc** [comment]
We are checking it with the CDN provider, the new SSL certificate was uploaded there several days ago :/ Thank you for reporting it.

**Comment by wwalc** [comment]
Closing to track it in #13887.

**Comment by imadarif** [comment]
https://cdn.ckeditor.com/

Your connection is not private
Attackers might be trying to steal your information from cdn.ckeditor.com (for example, passwords, messages, or credit cards). [Learn more](chrome-error://chromewebdata/#)
NET::ERR_CERT_DATE_INVALID

**Comment by wwalc** [comment]
Yes, we are working on it. If we will not fix it in the next 30 mins, we will switch to a different vendor as we're having a hard time getting support, then it will be a matter of DNS propagation. We will reduce TTLs soon just in case.

**Comment by wwalc** [comment]
We are updating the DNS now. The DNS propagation may take a while (usually \<1h, but sometimes up to 24h) so if you need an instant fix, change the URL to start with [https://d3vxtqk803u6i6.cloudfront.net](https://d3vxtqk803u6i6.cloudfront.net/ckeditor5/37.0.1/multi-root/ckeditor.js). Remember to change it back to [https://cdn.ckeditor.com](https://cdn.ckeditor.com) after April, 20th 2023.

**Comment by wwalc** [comment]
We should be back live. Unfortunately, the DNS propagation may take a while as explained above. Restarting the browser, and flushing the DNS etc. may help to see the results immediately. Of course, it's very unlikely you will be able to instruct all your users to do so, so depending on the urgency you may change the URL as instructed above or just wait for max a couple of hours.

Apologies for the inconvenience. I guess I will not need any more ☕ today.

**Comment by chandlervt** [comment]
Thank you for resolving it! 
We were able to point to  a mirror and that solved the issue as well. It will be great if there are officially two mirrors on different domains for such situations.

**Comment by CiaranSmith** [comment]
Thanks for resolving this issue which impacted our customers. I fully apprecaite issues will occur, but what steps are being from  your side to ensure this does not happen again. Are there any suggestions for different approaches from the consumer side that would improve our resiliency to this type of issue?
