### ISSUE TITLE
copy pasting image with data and from mail content its not working

### ISSUE THREAD

**Issue by pushpanjali-patil** [ckeditor/ckeditor4#5465]
when im copy pasting content with images from outlook that time image is not getting paste in ckeditor attaching images for the same.

actual content:
![image](https://user-images.githubusercontent.com/56927198/233353049-34481b25-8b28-4e29-b765-c02d8eb20777.png)
![image](https://user-images.githubusercontent.com/56927198/233353138-8f2ded91-a5af-4fd2-a3c0-e3b6dff98822.png)

after pasting in ckeditor:
![image](https://user-images.githubusercontent.com/56927198/233353241-71fd22ed-c2ab-4610-9e85-1805274d99f2.png)

and getting below error in console:
[CKEDITOR] Error code: pastetools-failed-image-extraction

please help here

**Comment by Comandeer** [comment]
Pasting from Outlook is not officially supported. Please see #3106 for more details.

**Comment by pushpanjali-patil** [comment]
but from another mail diff contents are there with image that are working that im able to paste in ckeditor

see Ex:
![image](https://user-images.githubusercontent.com/56927198/233543080-b8a4388a-9730-4386-ae77-21c7e5c9e747.png)
