### ISSUE TITLE
while right click in ckeditor its showing paste icon which is not working

### ISSUE THREAD

**Issue by pushpanjali-patil** [ckeditor/ckeditor4#5466]
if i right click within ckeditor that time paste icon is showing and when clicking on that icon its showing your browser is not supporting to paste

see below attachment:
<img width="664" alt="Imagepasteicon" src="https://user-images.githubusercontent.com/56927198/233357183-5d91f917-3cac-41bd-8908-e618a97be0cd.png">

**Comment by Comandeer** [comment]
Please see [#469 (comment)](https://github.com/ckeditor/ckeditor4/issues/469#issuecomment-306279192) for an explanation of the current paste menu option behavior. Unfortunately, most browsers do not allow pasting via a context menu option, and due to that, we display that message.

**Comment by pushpanjali-patil** [comment]
so can we remove that icon which is showing after right click?

**Comment by pushpanjali-patil** [comment]
can we remove that right click paste icon from ckeditor4 in angular 12
