### ISSUE TITLE
CDN endpoint respond with 304 unexpected response

### ISSUE THREAD

**Issue by tianjianxia** [ckeditor/ckeditor4#5468]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

I am using CKEditor v4.11.1 in my application for a long time. Recently, it's started to fail to load the editor. After some deep dive I found that the scripts provided by cdn.ckeditor.com/4.11.1/standard-all endpoints start to return 301/304 response, which leads to the editor fail to load.

I upgrade the version from 4.11.1 to 4.21.0, the editor render properly after the upgrade, cdn start to return 200, the timestamp in the query parameter like **'t=N2M9'** is refreshed, but after about one week the issue happens again.

I am using the react component **'react-ckeditor-component'**, due to some reason I can not switch to other lib.

Is there any reason this CDN related issue happens? I see couple of CDN related issues in the repo, it looks like most of the requester choose to switch to local script at last. Is there a way to mitigate this problem without use local script?

### Expected result

scripts load from cdn endpoint with 200 response

### Actual result

3XX responses

![Sample network call](https://user-images.githubusercontent.com/59232054/233920033-fd704ded-3403-439e-9136-7456f2063cd3.png)

## Other details

* Browser: Chrome/Firefox
* OS: Mac/Win
* CKEditor version: 4.x.x
* Installed CKEditor plugins: N/A

**Comment by jacekbogdanski** [comment]
From what I see, CDN for both, 4.11.1 and 4.21 are available:

* https://cdn.ckeditor.com/4.11.1/standard-all/ckeditor.js
* https://cdn.ckeditor.com/4.21.0/standard-all/ckeditor.js

We had some issues with the CDN certificate that are explained in https://github.com/ckeditor/ckeditor4/issues/5459 but at the moment everything should be fine. @tianjianxia could you check the above links?
