### ISSUE TITLE
editor_gecko.css missing on file download

### ISSUE THREAD

**Issue by acroundtree** [ckeditor/ckeditor4#5470]
## Type of report

Bug

## Provide detailed reproduction steps (if any)
Download kama_4_21.0.zip and unzip file to skins folder. Make Kama the default skin. Open ckeditor in Firefox. Toolbar nor the textarea will not display. Inspect code in Firefox. Error will report that the editor_gecko.css file is missing. Open the kama folder and it will not be there. 

### Expected result

Ckeditor box should be displayed. 

### Actual result

Ckeditor does not display.

## Other details

* Browser: Firefox

**Comment by KarolDawidziuk** [comment]
Hi @acroundtree 

It's working properly for me(tested each type of editor) and the toolbar and textarea are displayed correctly, there is no error in the console, so I cannot confirm this and this report will be closed.

Please check the steps of [applying custom skin to the editor](https://ckeditor.com/docs/ckeditor4/latest/guide/skin_sdk_setup.html) and if you feel that there is still an issue with the editor or skin, please create an issue for it with your editor configuration.

**Comment by acroundtree** [comment]
I'm going to request to reopen as the issue may not be understood correctly. When you download a fresh new copy of the skin the file editor_gecko.css is missing on download. This may cause gecko based browsers, like Firefox (I'm running 102.10), not to work.
