### ISSUE TITLE
Ckeditor CDN is down

### ISSUE THREAD

**Issue by gergely-42droids** [ckeditor/ckeditor4#5471]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

Try to load the library from https://cdn-source.ckeditor.com/4.5.4/full-all/ or https://cdn.ckeditor.com/4.5.4/full-all/

### Expected result

The library loads.

### Actual result

Pending, the request never completes. This site can’t be reached error.

## Other details

Any browser, Mac/linux, 
Version: 4.5.4

**Comment by jacekbogdanski** [comment]
@gergely-42droids mentioned CDNs with [https://cdn-source.ckeditor.com](https://cdn-source.ckeditor.com/4.5.4/full-all/) domain are not supposed to be used by integrators.

You should use our public CDN listed in http://cdn.ckeditor.com/, so for example: https://cdn.ckeditor.com/4.5.4/standard-all/ckeditor.js

Additionally, https://cdn.ckeditor.com does not implement a directory listing, and you will need to request a specific file.

**Comment by wwalc** [comment]
@gergely-42droids Out of curiosity how did you find [https://cdn-source.ckeditor.com/](https://cdn-source.ckeditor.com/4.5.4/full-all/) ?

**Comment by gergely-42droids** [comment]
@jacekbogdanski Thank you, the URL you have suggested works. 
@wwalc I can't remember, but we have been using it on our Drupal 7 blog for the past 10+ years (just changed version numbers a few times). Worked until today.

**Comment by wwalc** [comment]
Ah, that clarifies it a bit, thank you. There is a chance that at the very early stage of a CDN, this incorrect URL was indexed by google quite well (oops). It is a much slower "origin" server than the real CDN, the target CDN only fetches files from there.

**Comment by gergely-42droids** [comment]
@wwalc Well, now, if someone finds this, they can use the replacement URL in Drupal 7: "//cdn.ckeditor.com/4.5.4/full-all"
:)
