### ISSUE TITLE
Target < Popup Window>

### ISSUE THREAD

**Issue by ashishmishra14** [ckeditor/ckeditor4#5473]
Hi, 
We are using ckeditor4.21.0 library in our app code and we are seeing a problem with the Target < Popup Window> properties applied to a link. 
Everytime we save the Target < Popup Window> properties applied to a link it doesn't get applied. Is this a known issue to Ckeditor?

![image](https://user-images.githubusercontent.com/115915455/235642221-52b65ffc-a9d1-48d8-afe1-e71f15bbdaa6.png)

Is this a known issue? if yes, Is this being worked on currently?

Thanks
Ashish

**Comment by Comandeer** [comment]
Could you prepare a sample reproduction? I've tested in the [official docs](https://ckeditor.com/docs/ckeditor4/latest/examples/standardpreset.html) and I wasn't able to reproduce the issue.

**Comment by ashishmishra14** [comment]
This can be resolved. The problem was this element was not configured in the ckeditor we were using as a result the element was automatically disallowed.
