### ISSUE TITLE
Facing Error while submitting the form on submit

### ISSUE THREAD

**Issue by T533-mark** [ckeditor/ckeditor4#5476]
I'm facing error while copy content from ms word to kceditor and then submit a form i'm getting 404 error its not getting route but when i'm giving simple format text its submitted successfully

**Comment by KarolDawidziuk** [comment]
We would like to help solve your issue but it seems you have missed our [templates for feature requests and bug reports](https://github.com/ckeditor/ckeditor4/issues/new/choose). Their purpose is to make sure you provide the most sufficient and clear description. Without this, we are unable to have a closer look at your problem.

Please refer to [our guide on how to report issues](https://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates) on the tracker, and open a new issue using the template as this one is being closed now.
