### ISSUE TITLE
Font name can't use non-English character.

### ISSUE THREAD

**Issue by regionbbs** [ckeditor/ckeditor4#5483]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

Configure editor with config.js to apply font name with non-english character.
e.g.
```
config.font_names = "新細明體;標楷體;微軟正黑體;" + config.font_names;
```

### Expected result

Display font name with non-english character correctly.

### Actual result

See figure:
![image](https://github.com/ckeditor/ckeditor4/assets/1799428/a4b1445f-f8a3-4f46-afb6-16a791a4c109)

## Other details

* Browser: Microsoft Edge 113.0.1774.42
* OS: Windows 10
* CKEditor version: 4.21
* Installed CKEditor plugins: Full package

**Comment by Comandeer** [comment]
I can't reproduce the issue: https://jsfiddle.net/q5fw6r8x/

Could you provide a demo?

**Comment by regionbbs** [comment]
I will check it and give a demo if it's still present.
Thank you.
