### ISSUE TITLE
Memory leak in Source Code Editing when having thousand of words

### ISSUE THREAD

**Issue by syhrimr** [ckeditor/ckeditor4#5492]
## Type of report

Bug

## Provide detailed reproduction steps (if any)

1. Go to https://ckeditor.com/docs/ckeditor4/latest/examples/sourcearea.html
2. In either source code area or dialog, input a long content. In here I input a around 5,9k words long content with images and computed style texts. You can put this code that I used to reproduce the issue https://codepen.io/syhrimr/pen/JjeGVgo

![image](https://github.com/ckeditor/ckeditor4/assets/24467085/d1e3c6ec-4a11-497a-9993-5e1757eda271)
3. Check the dev tools and there will be an error 
> Error: <svg> attribute viewBox: Expected number, "0 0 100% 4".

### Expected result

Fixed the error and memory leak.

### Actual result

In my case, since the content is long, the error occurs more than 20k times and causes memory leak.

![image](https://github.com/ckeditor/ckeditor4/assets/24467085/3efb471b-2585-4fb0-ad43-91a3f8717570)
![image](https://github.com/ckeditor/ckeditor4/assets/24467085/28b419a1-ff07-4a3d-a64e-f80b797f4c90)

## Other details

* Browser: Microsoft Edge version 114.0.1823.43 (Official build) (64-bit)
* OS: Windows 10 Pro 10.0.19044
* CKEditor version: 4.13.12 and 4.21.0
* Installed CKEditor plugins: Standard Plugins

**Comment by Comandeer** [comment]
Could you provide a content used for the reproduction?

**Comment by syhrimr** [comment]
@Comandeer here the content code that used for reproduction, I put it on Codepen https://codepen.io/syhrimr/pen/JjeGVgo

**Comment by Comandeer** [comment]
I'm not able to reproduce the error. I've tried pasting the content into the [CKEditor 4 sample](https://ckeditor.com/docs/ckeditor4/latest/examples/fullpreset.html) and the browser's console does not show any error connected to SVG.

**Comment by syhrimr** [comment]
Okay, so I found the root cause. The memory leak was coming from my browser extensions Microsoft Editor: Spelling and Grammar. Seems it got a bug with the error I reported above coming from it and aggressively check every text in the RTE.
