### ISSUE TITLE
CKeditor converting HEX Colours to rgba

### ISSUE THREAD

**Issue by ashishmishra14** [ckeditor/ckeditor4#5494]
Hi, 

is this a known issue that CKeditor converts hex code to rgba format once saved in the source?

We are using CKEditor 4.21.0 and uploaded a sample screenshot of the ckeditor. 

![image](https://github.com/ckeditor/ckeditor4/assets/115915455/082ad329-b5f8-4860-b654-8826588e7cf0)

the code that I'm trying to add is below

```
<p><b>Course Amendments Published!</b></p>
<p>Due to recent changes in the training dataset of the latest TEST ERP update, at least one lesson in the <a href="https://test/course/typyr54" style="color:#2e6ca2">F320 Contracts</a> course cannot be completed as described in the training guide.</p>
<p>Before you start completing the course, you should consult the course amendments, which you can find by clicking the link in the Training Materials module of the course.</p>
```

Screenshot of how the hex code was converted to the rgba

![image](https://github.com/ckeditor/ckeditor4/assets/115915455/6124d05a-512a-486c-a6af-fc3b1e82b890)

**Comment by ashishmishra14** [comment]
Any update on this?

**Comment by ashishmishra14** [comment]
"Please provide the requested feedback or the issue will be closed after next 7 days." - What do you need from me on this? I haven't heard from ckeditor yet? Can you review my questions above and clarify if that is a known bug

**Comment by jacekbogdanski** [comment]
@ashishmishra14 CKEditor 4 reached the end of life in June already. You can read more about available options in our readme, as unfortunately, we no longer provide code changes in the open-source version: https://github.com/ckeditor/ckeditor4#summary-of-options-after-the-ckeditor-4-end-of-life
