### ISSUE TITLE
Entire window tab is Freezing on doubleClicking the anchored link.

### ISSUE THREAD

**Issue by 123vignesh** [ckeditor/ckeditor4#5507]
## Type of report

Bug

## Issue Reproduction steps
1. For an example If I type '123' in the text instruction
2. Add link to another text by selecting '123'
3. And clicking the anchor tag and giving '123' for Anchor Name.
4. And double click on the anchored link '123' it opens a dialog In that select anchor name 123 and By Element Id '123' and press ok
5. If I double click again on the anchored link '123' the entire tab freezes.
 
The infinite loop it is entering is in ckEditor.js
 clear: function() {
                    for (var b = this.getInputElement().$; 0 < b.length; )
                        b.remove(0);
                    return this
                },
Here the 4th step is removing the dom element options and running properly
But in the 5th step the .remove(0) is calling a remove() function in different file 
remove: function() {
            var t = f.getParent.call(this);
            return t && t.removeChild(this),
            this
        }
Element.js

Please help me out how the same function is referencing the wrong function instead of removing the element at 0 position.

it was working fine in your editor. I was not able to reproce the issue in your sample editor

* Installed CKEditor plugins: …

**Comment by jacekbogdanski** [comment]
CKEditor 4 reached the end of life in June already. You can read more about available options in our readme, as unfortunately, we no longer provide code changes in the open-source version: https://github.com/ckeditor/ckeditor4#summary-of-options-after-the-ckeditor-4-end-of-life
