### ISSUE TITLE
[redacted]

### ISSUE THREAD

**Issue by Moyuchu** [ckeditor/ckeditor4#5508]
[redacted]

**Comment by Comandeer** [comment]
Thank you for your report. We will investigate it thoroughly.

Meanwhile I will close this issue as we normally ask for sending security reports through [our contact form](https://ckeditor.com/contact/).

For security reasons I removed the original description, but the original issue you submitted is being handled in our security tracker.

**Comment by Moyuchu** [comment]
Ok, thank you for your reply. How can I know if the problem is solved? Do I need to send the security report again using your contact form?

**Comment by Comandeer** [comment]
@Moyuchu, yes, the best way is to contact with us via our contact form.
