### ISSUE TITLE
Ckeditor 4 wordcount plugin is not working

### ISSUE THREAD

**Issue by pushpanjali-patil** [ckeditor/ckeditor4#5518]
we are trying to use ckedito4 wordconut plugin in angular 12 but its not supporting

**Comment by jacekbogdanski** [comment]
That's 3rd party plugin, not developed by CKEditor 4 team. Additionally, please note that CKEditor 4 reached EOL and is no longer supported outside the Extended Support Model. You can read more about ESM in https://ckeditor.com/docs/ckeditor4/latest/support/licensing/extended-support-model.html
