### ISSUE TITLE
i am unable to view drag and drop image if iam using uploadimage,image2 with ckeditor_wiris

### ISSUE THREAD

**Issue by praveenKumar9494** [ckeditor/ckeditor4#5523]

**Comment by crakage** [comment]
Not sure if it is the same issue but we can see on you demo page: 
https://ckeditor.com/ckeditor-4/demo/
if you try to upload an image you get an error: 'image source url missing'
![Screenshot 2024-07-31 at 07 26 48](https://github.com/user-attachments/assets/7c2112ac-a951-4576-aff4-46744a49c24c)
This seems to have started with Chrome last release 127.0.6533.72

Tested on mac os Sonoma 14.6
With Chrome 127.0.6533.72

**Comment by Comandeer** [comment]
I can't reproduce the issue in Chrome, Firefox, or Safari. Additionally,  [upload plugins are not officially supported alongside MathType plugin](https://ckeditor.com/docs/ckeditor4/latest/features/mathtype.html#configuration):

> At the moment the MathType plugin is not compatible with the [official file upload integration for CKEditor 4](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_file_upload.html). File upload capabilities must be disabled with the [`config.removePlugins`](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-removePlugins) configuration option to allow the use of MathType.

I can't also reproduce the issue on the demo page.

Please also note that CKEditor 4 was launched in 2012 and reached its End of Life (EOL) on June 30, 2023. A special edition, [CKEditor 4 LTS](https://ckeditor.com/ckeditor-4-support/) (“Long Term Support”), is available under commercial terms (["Extended Support Model"](https://ckeditor.com/ckeditor-4-support/)) for anyone looking to extend the coverage of security updates and critical bug fixes.

Please [contact us](https://ckeditor.com/contact/) if you would like to learn more about ESM.
