### ISSUE TITLE
Remove paste toolbar buttons

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor4#687]
## Are you reporting a feature or a bug?

Task

## Provide detailed reproduction steps (if any)

![Toolbar paste buttons](https://user-images.githubusercontent.com/5353898/28676392-d77b02b4-72ea-11e7-86a3-8064660640c2.png)

We still have this clipboard paste buttons, which give very little help.

It's important that the toolbar are still available, so that if any1 really needs it it can still be added with the toolbar configuration.

### Expected result

Toolbar buttons are not visible in the toolbar by default.

### Actual result

Toolbar buttons are included in standard, full preset.

**Comment by jacekbogdanski** [comment]
We use these buttons so long already, it would be confusing removing them right now.
