### ISSUE TITLE
Safari ignores nbsp in visual mode

### ISSUE THREAD

**Issue by biomancer** [ckeditor/ckeditor4#699]
## Are you reporting a feature or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Open latest demo ( http://nightly.ckeditor.com/17-07-28-06-04/standard/samples/ )
2. Use `&nbsp;` in source mode 
You can use source like that:
```
<p>Word and&nbsp;word and&nbsp;word and&nbsp;word and&nbsp;word and&nbsp;word and&nbsp;word and&nbsp;word and&nbsp;word and&nbsp;word</p>

<p>Word&nbsp;and word&nbsp;and word&nbsp;and word&nbsp;and word&nbsp;and word&nbsp;and word&nbsp;and word&nbsp;and word&nbsp;and word</p>
```
3. Switch to visual mode
4. Resize browser window so that lines begin to wrap

### Expected result

Browser should respect non-breaking spaces and word wrapping should work differently on first and second paragraph, like that: (chrome 60)

![image](https://user-images.githubusercontent.com/2938250/28724143-bd26b62e-73c1-11e7-8ae5-a81a6ebb7012.png)

### Actual result

Safari does not respect non-breaking spaces and result looks like that:

![image](https://user-images.githubusercontent.com/2938250/28724201-e94b6f60-73c1-11e7-87ed-eb417262ee06.png)

## Other details

* Browser: Safari 10.1.2 (10603.3.8)
* OS: OS X 10.10.5

and 

* Browser: Safari 9.0.2 (11601.3.9)
* OS: OS X 10.11.2 

* CKEditor version: 4.6.1, 4.7.1, current nightly demo (17-07-28-06-04)

**Comment by msamsel** [comment]
I was able to confirm it.
Here works fine on Safari: https://jsfiddle.net/e46x7of9/1/
Problem seems to be related to editor.

**Comment by hamusi** [comment]
For me https://jsfiddle.net/e46x7of9/1/
Or my more clearly visible https://jsfiddle.net/w0qcLprg/
Does not work in Safari version 14.0 (15610.1.28.1.9, 15610)

So I would say, it is browser's problem. At least now. But I don't know, how and where it can be reported.

**Comment by Dumluregn** [comment]
Hi @hamusi, thank you for reaching us and providing the demos - the fact that issue is reproducible in the basic `contenteditable` element shows that it's indeed a browser problem, not editor.

As for the further steps - there is [Safari issue tracker](https://bugs.webkit.org/). Could you report an issue there and post the link to it here so that we could track it?

**Comment by hamusi** [comment]
I'll try to.
Just want mention, that we found, that using style="-webkit-nbsp-mode: normal" helps in safari.

Thanks for pointing me to Bugzilla
And I see 2 reports about that already:
https://bugs.webkit.org/show_bug.cgi?id=38902
https://bugs.webkit.org/show_bug.cgi?id=12828
