### ISSUE TITLE
Broken selection after removing the whole content in Edge

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor4#709]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Open any editor where a widget is the first element in the editable tree, e.g. http://ckeditor.com/ demo.
2. Press <kbd>ctrl/cmd</kbd>+<kbd>a</kbd>.
1. Press the <kbd>delete</kbd> key.

### Expected result

All the content is removed, selection is put at the beginning of the editable area.

### Actual result

Selection is missing, elements path sows `body image`.

## Other details

It's a **regression in Edge** itself, was not preset in version 14.x.

After the removing there is still a widget wrapper hanging in the content. I'll speculate here: it looks to me as if the selection would be transformed by the browser to start inside of a widget wrapper.

Maybe we could utilize `widgetselection` plugin to work around that?

* Browser: Microsoft EdgeHTML 15.15063
* OS: Windwos 10
* CKEditor version: 4.7.1

**Comment by Dumluregn** [comment]
This issue is no longer reproducible in the latest Edge browser version.
