### ISSUE TITLE
Edge adds extra `<span>` to content

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor4#716]
## Are you reporting a feature request or a bug?

bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

*Put all reference links here…*

## Provide detailed reproduction steps (if any)

1. Open CKEditor sample: https://cdn.ckeditor.com/4.7.1/full-all/samples/ in Microsoft Edge 15 or 16.
1. Remove everything from editor (you can use `new page` option).
1. Type something.
1. <kbd>Ctrl</kbd>+<kbd>A</kbd> all text.
1. Use <kbd>Backspace</kbd> or <kbd>Delete</kbd>, to remove all content.
1. Start typing

### Expected result

regular text will appear like in Chrome or Firefox

### Actual result

Text is surrounded with `<span>` on Edge 15, text is surrounded with `<span style="background-color: #FFFFFF;">` on Edge 16

## Other details

* Browser: Edge 15, Edge 16
* OS: Win10 (Virtual Env)
* CKEditor version: 4.7.1
* Installed CKEditor plugins: full-all

Reported in Edge: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/13054850/

**Comment by Dumluregn** [comment]
This issue is no longer reproducible in the latest Edge browser version.
