### ISSUE TITLE
Unable to redo text styling after dismissing selection

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4#775]
## Are you reporting a feature request or a bug?

Bug

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

No

## Provide detailed reproduction steps (if any)

1. Go to http://cdn.ckeditor.com/4.7.1/full-all/samples/.
2. Select some text.
3. Change its color using color button.
    * **Text color changed**.
4. Undo.
    * **Text color changed back to default one**.
5. Click after text (IE9) or click on another element type (e.g. header - Chrome/FF) to dismiss non-collapsed selection or click on another element type.

### Expected result

Possible to redo text color change.

### Actual result

Undo/redo buttons becomes disabled (it is possible to redo only if selection is not dismissed).

## Other details

Looks like more broader issue with `undo` plugin, happens also with bold, etc.

* Browser: All
* OS: Windows 7 / OS X
* CKEditor version: 4.6.0
* Installed CKEditor plugins: `colorbutton`, `undo`

**Comment by f1ames** [comment]
Very similar to #627, only difference is how it behaves in Chrome/FF when selection is placed in the same element (redo is not disabled then).

**Comment by Dumluregn** [comment]
I'm closing this issue as it is no longer reproducible in [`4.13.0`](http://cdn.ckeditor.com/4.13.0/full-all/samples/).
