### ISSUE TITLE
CSP error on setData()

### ISSUE THREAD

**Issue by Synchro** [ckeditor/ckeditor4#829]
The `setData` method appears to be incompatible with content security policy headers that omit a `script-src` value of `unsafe-inline`

I know that many CSP issues were fixed in #8584 and the 4.7 release, but this is apparently still outstanding.

## Code to reproduce:

```javascript
var ckeditor_html = CKEDITOR.replace('html');
ckeditor_html.setData("<h1>Hello world</h1>");
```

### Expected result

The CKEditor content area is replaced with whatever is passed to setData.

### Actual result

Triggers this error:

```
ckeditor.js:formatted:2209 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval' ". Either the 'unsafe-inline' keyword, a hash ('sha256-7Q+Py4LXUy9/1pmd111REln5aqXrOU6rDkYppYSdEt8='), or a nonce ('nonce-...') is required to enable inline execution.

write @ ckeditor.js:formatted:2209
setData @ ckeditor.js:formatted:17223
(anonymous) @ ckeditor.js:formatted:8352
n @ ckeditor.js:formatted:136
(anonymous) @ ckeditor.js:formatted:200
CKEDITOR.editor.CKEDITOR.editor.fire @ ckeditor.js:formatted:244
setData @ ckeditor.js:formatted:6323
b @ ckeditor.js:formatted:17126
(anonymous) @ ckeditor.js:formatted:17159
CKEDITOR.editor.setMode @ ckeditor.js:formatted:7915
(anonymous) @ ckeditor.js:formatted:7808
n @ ckeditor.js:formatted:136
(anonymous) @ ckeditor.js:formatted:200
CKEDITOR.editor.CKEDITOR.editor.fire @ ckeditor.js:formatted:244
fireOnce @ ckeditor.js:formatted:213
CKEDITOR.editor.CKEDITOR.editor.fireOnce @ ckeditor.js:formatted:252
(anonymous) @ ckeditor.js:formatted:6173
f @ ckeditor.js:formatted:5753
D @ ckeditor.js:formatted:5761
w @ ckeditor.js:formatted:5768
(anonymous) @ ckeditor.js:formatted:5789
```

The code in question is:

```javascript
        write: function(a) {
            this.$.open("text/html", "replace");
            CKEDITOR.env.ie && (a = a.replace(/(?:^\s*<!DOCTYPE[^>]*?>)|^/i, '$\x26\n\x3cscript data-cke-temp\x3d"1"\x3e(' + CKEDITOR.tools.fixDomain + ")();\x3c/script\x3e"));
            this.$.write(a);
            this.$.close()
        },
```
The error is thrown on the `this.$.write(a);` line.

_Note: Direct reference in code below_
https://github.com/ckeditor/ckeditor-dev/blob/a3483c379f7df42e04ab2d03209b773c733baedf/core/dom/document.js#L264-L278

## Other details

* Browser: Chrome Canary
* OS: macOS 10.11
* CKEditor version: 4.7.2
* Installed CKEditor plugins: Defaults

**Comment by msamsel** [comment]
Hi,

I tried to reproduce your error but I wasn't able to do so. I've used this snippet: https://codepen.io/msamsel/pen/dzjQEq?editors=1010 and only see information about `[Violation] Avoid using document.write().`
I used Chrome Canary and MacOS 10.12.6.

Can you prepare some test environment where problem would be observable or give some additional info?

**Comment by Synchro** [comment]
Codepen does not set a CSP header at all, so it won't trigger the issue. I created a site using your codepen content plus the CSP settings I'm using and it reproduces the problem: https://ckeditor.synchromedia.co.uk/

**Comment by Synchro** [comment]
Ah, no, that's just because it was hosted externally and fails to match the `self` in the CSP; I fixed that by adding a local copy of creditor, but I still can't make it launch.

```
TypeError: Cannot read property 'getEditor' of undefined at a (https://ckeditor.synchromedia.co.uk/ckeditor/ckeditor.js:344:110) at Object.CKEDITOR.replace (https://ckeditor.synchromedia.co.uk/ckeditor/ckeditor.js:348:473) at https://ckeditor.synchromedia.co.uk/ckeditortest.js:1:23
```

The codepen would not show the problem anyway because the test script itself is inline, and so would never be run with the CSP in place, so I moved it to an external script. It's a bit odd - the codepen hardly adds anything, yet the test frame it loads has all kinds of additional resources that are not in the codepen.

**Comment by Synchro** [comment]
I made it launch - the script tags needed to be placed after the textarea. Now I'm seeing a CSP error just from instantiating the editor, and while the editor appears, most of the buttons are disabled.

**Comment by msamsel** [comment]
Thank you for this test page. If it's not a problem please don't remove it for some time.
I also correct your description to reference to proper code line in our repository instead of having pure code snippet.

**Comment by Comandeer** [comment]
The error on startup seems to be connected with inline script that it's added for every editor based on `wysiwygarea` plugin (so editor in `iframe`). Switching from `wysiwygarea` to `divarea` plugin allows editor to load correctly. However it's still unusable as every button in the toolbar uses `[onclick]` attribute to handle user's clicks. I'm afraid that at the moment it's just impossible to use CKEditor 4 without `unsafe-inline` in CSP.

Fixing this issue would involve a enormous amount of work as it would be basically rewriting the whole UI logic (to get rid of nasty `[on…]` attributes in favor of handling it on JS side) connected with improving our way of loading frames and, probably, loading plugins.

**Comment by Synchro** [comment]
I know there are issues as described in the #254 PR, however, that ticket gives the impression that most were solved or at least worked around. The 4.7 release notes mention "the editor can now be used with unsafe-eval Content Security Policy". In light of that, I've just changed the test site so that it allows `unsafe-inline` but not `unsafe-eval`, and now it's failing with a different error. It would be useful to have clear guidance on what CSP settings it *will* work with.

**Comment by Comandeer** [comment]
Now your demo is working for me on Chrome. Did you clear cache?

The minimum required CSP seems to be `default-src none ; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self'`. Note that you'd probably like to broaden `img-src` as it is also uses for every image inserted into CKE4.

As for #254: that issue had very narrow scope and was aimed only to get rid of `eval` usage in editor's templates.

**Comment by Synchro** [comment]
I was sure I had, and now I tried again it's working... Thanks for the clarification - at least being able to remove `unsafe-eval` is progress.

**Comment by mlewand** [comment]
This issue has been discussed in the past, here is a link to umbrella ticket reported on Trac: https://dev.ckeditor.com/ticket/8584

As you see we did some improvements whenever we could, although removing `onxyz` inline listeners is a tremendous amount of work.

Nonetheless it's a perfectly valid feature request, it's just we don't have enough hands to work on it. On the bright side, CKEditor 5 was developed with CSP conformance in mind from the very beginning so it will be fully supported there.

**Comment by jacekbogdanski** [comment]
Unfortunately, the issue scope is too wide to be covered.
