### ISSUE TITLE
Test /pastefromword/generated/excel fails on IE8 on master branch

### ISSUE THREAD

**Issue by msamsel** [ckeditor/ckeditor4#831]
## Are you reporting a feature request or a bug?

BUG

## [Check if the issue is already reported](http://docs.ckeditor.com/#!/guide/dev_issues_readme-section-avoid-duplicates)

*Put all reference links here…*

## Provide detailed reproduction steps (if any)

1. Run unit tests on IE8

### Expected result

Tests pass.

### Actual result

One test fails.

## Other details

* Browser: IE8
* OS: Win 7 ( Virtual env)
* CKEditor version: **master branch**
* Installed CKEditor plugins: full-all

**Comment by mlewand** [comment]
This issue is not crucial for 4.7.3, moving to backlog.

**Comment by f1ames** [comment]
Test passes (checked with `4.13.1`).
