### ISSUE TITLE
Pasting inside editor which contains a table after selecting all content is not working

### ISSUE THREAD

**Issue by Comandeer** [ckeditor/ckeditor4#875]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Open https://jsfiddle.net/9a6aenLg/2/
2. Select table via elements path and copy it.
3. Press <kbd>Ctrl</kbd> + <kbd>A</kbd>.
4. Paste table.

### Expected result

All content is replaced by pasted table.

### Actual result

Table inside editor's content becomes selected.

It seems like editor performs paste inside the table.

## Other details

* CKEditor version: 4.7.2
* Installed CKEditor plugins: tableselection

It's a regression from 4.7.1, probably due to the refactorization of paste algorithm.

**Comment by f1ames** [comment]
It happens for any elements/content, not only table - reported also in #1168, #2513.

**Comment by f1ames** [comment]
Fixed with https://github.com/ckeditor/ckeditor4/commit/a72568f451fe2fa963179a91c3edc82cfb084cdf.
