### ISSUE TITLE
Unable to drop content into table cell after its text

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4#949]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Go to http://tests.ckeditor.dev:1030/tests/plugins/clipboard/manual/draganddrop
2. Select some text and drag it into table cell dropping after cell contents

### Expected result

Text is dropped properly inside table cell.

### Actual result

Text is dropped somewhere after table.

![sep-21-2017 11-53-41](https://user-images.githubusercontent.com/1061942/30690167-8e78e770-9ec3-11e7-8352-7b820b22954f.gif)

Works fine when content is dropped on the cell text.

## Other details

* Browser: Edge 14, Edge 16 (preview)
* OS: Windows 10
* CKEditor version: 4.7.3
* Installed CKEditor plugins: `clipboard`, `table` (see http://tests.ckeditor.dev:1030/tests/plugins/clipboard/manual/draganddrop)

**Comment by Dumluregn** [comment]
This issue is no longer reproducible in the latest Edge browser version.
