### ISSUE TITLE
Unable to drop content on the beginning (before) of the blockquote

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4#950]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Go to http://tests.ckeditor.dev:1030/tests/plugins/clipboard/manual/draganddrop
2. Select some text, drag it and drop it on the whitespace before the blockquote.

### Expected result

Text is dropped and inserted on the beginning of the blockquote.

### Actual result

Text is inserted on the beginning of the editor.

![sep-21-2017 11-52-27](https://user-images.githubusercontent.com/1061942/30690354-3479818e-9ec4-11e7-92eb-e7ed2d71e5a6.gif)

## Other details

* Browser: Edge 14, Edge 16 (preview)
* OS: Windows 10
* CKEditor version: 4.7.3
* Installed CKEditor plugins: `clipboard`, `blockquote` (see http://tests.ckeditor.dev:1030/tests/plugins/clipboard/manual/draganddrop)

**Comment by mlewand** [comment]
@f1ames isn't it a native issue of Edge?

**Comment by f1ames** [comment]
@mlewand very possible, I will check it.

**Comment by f1ames** [comment]
@mlewand Works fine in the plain contenteditable https://codepen.io/f1ames/pen/OxXzKm.

**Comment by Dumluregn** [comment]
This issue is no longer reproducible in the latest Edge browser version.
