### ISSUE TITLE
Unable to type after select all with widget on the beginning

### ISSUE THREAD

**Issue by f1ames** [ckeditor/ckeditor4#999]
## Are you reporting a feature request or a bug?

Bug

## Provide detailed reproduction steps (if any)

1. Go to https://ckeditor.com.
2. Select all content in the **Article Editor**.
3. Type something.

### Expected result

It is possible to type, typed content replaces the selection.

### Actual result

Only first letter is typed and in a way that it is inserted inside widget content.

![oct-03-2017 17-33-03](https://user-images.githubusercontent.com/1061942/31133847-e542d8d0-a860-11e7-9e4a-98ddba232b32.gif)

## Other details

* Browser: **Edge 16+ (preview)**
* OS: Windows 10
* CKEditor version: 4.7.3
* Installed CKEditor plugins: `widget`

_There was a workaround implemented some time ago for similar issue, however it is Webkit/Blink specific - https://dev.ckeditor.com/ticket/11064._

**Comment by Dumluregn** [comment]
This issue is no longer reproducible in the latest Edge browser version.
